"""Hand-written SE322 chapter quiz questions.

Each MCQ is (question, correct option, [three distractors], explanation). The
builder shuffles options with a seed taken from the question text, so the
correct letter is stable between rebuilds but follows no position pattern.
Each short answer is (question, [keywords], model answer); two keyword hits
earn full credit.
"""

BANK = {
1: {"mcq": [
 ('IEEE defines software engineering as an approach that is systematic, disciplined, and quantifiable. What does “quantifiable” add to that definition?',
  'Results are measured against stated targets, not judged by taste',
  ['Every phase must follow a fixed waterfall lifecycle', 'Costs are fixed in advance through fixed-price contracts with the client', 'Developer output is tracked by counting lines of code'],
  'Quantifiable means outcomes are checked against measurable targets. Systematic means the work is repeatable and reviewable.'),
 ('A payment system stores money as a floating-point number. Why is it far cheaper to catch this in design review than after launch?',
  'Late, it becomes a data migration and repair instead of a type choice',
  ['Floating-point rounding only shows up during design review', 'Payment regulators audit designs but never running systems', 'Column types cannot be changed at all once a database is running in production'],
  'Cost of change grows roughly an order of magnitude per phase; the same defect costs a type choice early and a data-repair project late.'),
 ('A team frames a problem as: current portal deploys in 40 minutes; target is under 5; same Oracle database, no new servers. Which problem-solving element is “no new servers this year”?',
  'A constraint',
  ['The goal state', 'A candidate solution', 'The initial state'],
  'Constraints limit which candidate solutions are acceptable; the 40-minute deploy is the initial state and the 5-minute deploy is the goal state.'),
 ('Which decision is architectural rather than detailed design?',
  'Splitting the system into catalog, cart, and payment services',
  ["Using a HashMap keyed by SKU for the cart's line items", 'Adding a Strategy class for each discount rule in the cart', 'Renaming a private helper method inside the payment module'],
  'The service split fixes deployment boundaries, failure modes, and team ownership for years. The others are local and cheaply reversed.'),
 ('Which quick test best separates an architectural decision from a detailed-design one?',
  'Whether it is costly to reverse and affects many teams',
  ['Whether it appears on a UML class or package diagram', 'Whether a senior engineer or the team lead made it', 'Whether it touches the database or the network layer'],
  'Architectural decisions are high-impact and costly to undo; detailed-design decisions are local and cheap to replace.'),
 ('In architecture, which of these is an “externally visible property” of an element?',
  'The performance other elements can rely on',
  ['The names of its private fields', 'The sorting algorithm it uses internally', 'The data structures inside its methods'],
  'Externally visible properties are what other elements can depend on: provided services, performance, resource use. Internal implementation is hidden.'),
 ('What do architecture and detailed design have in common?',
  'Both use abstraction and decomposition to manage complexity',
  ['Both are completed before requirements are gathered', 'Both are expressed using only UML class diagrams', 'Both are owned, reviewed, and approved by the operations team before release'],
  'The two work at different scales but use the same complexity-management principles.'),
 ('Which stakeholder is most likely to put deployability and observability first?',
  'Operators',
  ['End users', 'Marketing staff', 'Maintainers of the test suite'],
  'Users emphasize usability and reliability, developers modifiability, and operators deployability and observability.'),
 ('The operations team is shown a diagram of two web nodes behind a load balancer with a replicated database. That diagram is a…',
  'View',
  ['Viewpoint', 'Architectural driver', 'Constraint'],
  'A viewpoint is the set of conventions and concerns ("show nodes and networks for operations"); the view is the actual representation that results.'),
 ("In a hospital system, the physician wants one-click chart access while compliance wants re-authentication every five minutes. What is the architect's job here?",
  'Make the trade-off explicit, e.g. short tokens plus a logged emergency path',
  ['Side with the most senior stakeholder and document the decision in the requirements', 'Leave the conflict for developers to settle while coding', 'Remove both requirements until the stakeholders agree'],
  'Conflicting concerns are normal; trade-offs must be explicit and justified, not left to chance.'),
 ('Why is identifying stakeholders treated as an architectural activity rather than a formality?',
  "Missed concerns return late as requirements the structure can't meet",
  ['Every diagram must list its stakeholders to be considered valid', 'Stakeholders must approve each module before it is coded', 'It lets the team skip writing quality attribute scenarios'],
  'Missing a stakeholder means missing their concerns, and those return late when changing the structure is costly.'),
 ('“Checkout must complete in under 2 seconds at 10,000 concurrent users.” Why is this an architectural driver while “the user can apply a coupon” usually is not?',
  'It forces structure: caching, replicas, async processing',
  ['It was the first requirement written in the document', 'It concerns the user interface, which is always architectural', 'Functional requirements are never architectural drivers'],
  'Drivers are the few requirements with major architectural influence. Most functional requirements do not change the structure.'),
 ('A university mandates its existing Oracle database and national data-residency rules. In driver terms these are…',
  'Constraints',
  ['Quality attribute scenarios', 'Design patterns', 'Business goals'],
  'Constraints restrict choice before design starts, for example mandated technology, regulation, budget, or legacy integration.'),
 ('According to the chapter, when is a driver worth recording?',
  'When you can name the structure it forces or rules out',
  ['When several stakeholders mention it in interviews', 'When it is a functional rather than a quality requirement', 'Whenever it is listed in the project charter'],
  'A driver that changes nothing about the structure is not architecturally significant.'),
 ('Which requirement is most likely to be architecturally significant?',
  'Customer data must stay behind a separate security boundary',
  ['Users can sort the course table by date, name, or instructor', 'The monthly report must show the title in bold at the top', 'The help page must list support office hours and email'],
  'Architecturally significant functional requirements usually involve scale, distribution, security boundaries, or integration.'),
 ('In Attribute-Driven Design, what happens right after choosing the element to decompose?',
  'Pick the driving requirement for it',
  ['Deploy the element to production', 'Write the user manual for it', 'Freeze all remaining requirements'],
  'ADD iterates: choose an element, pick its driver, select tactics and patterns, allocate responsibilities and interfaces, then verify.'),
 ('Tax rules change every fiscal year while the invoice layout is stable. What design move does the chapter recommend?',
  'Put tax calculation in its own module with a versioned rule table',
  ['Duplicate the tax logic in each invoice template', "Hard-code the current year's rates for speed", 'Merge tax and layout into one class so the two always change together in one release'],
  'Decompose around change boundaries so the volatile part changes in one place.'),
 ('Before committing to a message broker, a team runs a two-day spike pushing 50,000 events through it. This is an example of…',
  'Early validation with a prototype',
  ['Reverse engineering', 'Technical debt', 'Premature optimization of the messaging layer'],
  'Scenarios, prototypes, reviews, and risk analysis validate a design early; measured evidence beats vendor claims.'),
 ('Why is design described as iterative rather than a single top-down pass?',
  'Analysis and prototypes reveal new drivers',
  ['Iteration is required by the IEEE definition', 'Top-down designs cannot be documented', 'Each iteration must use a new technology'],
  'A single pass rarely survives the first prototype, because new knowledge changes the drivers.'),
 ('A six-person admin tool is given a plugin framework, a rules engine, and a message bus that are never used. This is mainly…',
  'Accidental complexity',
  ['Essential complexity', 'Information hiding', 'High cohesion'],
  'Essential complexity comes from the problem; accidental complexity comes from our chosen solution and can be designed away.'),
 ('Which statement about “simplicity” matches the chapter?',
  'Fewer things to hold in mind to change one behavior safely',
  ['Shipping the product with fewer features overall so there is less code to maintain', 'Using as few classes and files as possible', 'Avoiding design patterns and abstractions entirely'],
  'Simplicity is about the mental load of safe change, not about feature count.'),
 ('A layered monolith suits a 3-person startup but not a 200-engineer platform needing independent deploys. What principle does this show?',
  'No architecture is universally best; fit depends on context',
  ['Monoliths are always the wrong choice for any team', 'Microservices are always the better choice for small teams that need to ship quickly', 'Architecture matters only once a company is large'],
  'Design quality is judged against stakeholder scenarios and context, not by a universal ranking.'),
 ('How should design quality be demonstrated?',
  'Against stakeholder scenarios',
  ['By the number of diagrams produced', 'By aesthetic preference of the architect', 'By the age of the chosen technologies'],
  'Good design is shown by meeting stakeholder scenarios, not by looks alone.'),
 ('Encrypting every field in a medical database breaks indexed search and adds latency. What does this illustrate?',
  'Quality goals often conflict and need trade-offs',
  ['Security measures never affect performance if they are designed well', 'Sensitive fields should never be encrypted', 'Search speed is not a quality attribute'],
  'Confidentiality and performance pull in opposite directions; the team chooses what to encrypt and records the remaining risk.'),
 ('Three teams each own one layer of a monolith, so every feature needs three coordinated releases. Which idea explains this?',
  "Conway's law",
  ['Liskov substitution', "Moore's law", 'The open–closed principle'],
  'System structure mirrors team structure, so organizational boundaries should be designed alongside technical ones.'),
 ('An architect lacks the data to choose between two databases. Which response does the chapter treat as legitimate?',
  'Deferring the decision until evidence exists',
  ['Picking whichever vendor is cheapest today', 'Letting each team choose independently', 'Choosing both and deciding in production'],
  'Architects work with incomplete information; deliberately deferring a decision until evidence arrives is a valid design move.'),
 ('How does the chapter treat ethical and professional practices in design?',
  'As design constraints, not optional extras',
  ['As a concern only for legal teams', 'As optional work that can be skipped when the deadline is tight', 'As relevant only to AI systems'],
  'Professional obligations constrain design just like budget or regulation.'),
],
"short": [
 ('Explain why fixing a defect costs more the later it is found. Give one example.', ['order of magnitude', 'phase', 'migration', 'design review', 'production'], 'Cost of change grows roughly an order of magnitude per phase. A money-as-float bug is a one-line type decision in design review but a schema migration, data repair, and bank reconciliation after launch.'),
 ('Distinguish an architectural decision from a detailed-design decision and give one example of each.', ['expensive to reverse', 'many teams', 'local', 'service', 'class'], 'Architectural decisions are expensive to reverse and affect many teams or qualities (splitting into catalog, cart, and payment services). Detailed-design decisions are local and cheap to change (a HashMap for cart items).'),
 ('What is the difference between a viewpoint and a view?', ['conventions', 'concerns', 'representation', 'stakeholders', 'diagram'], 'A viewpoint defines the conventions, stakeholders, and concerns to address; a view is the actual representation produced by following it, such as the deployment diagram of a specific system.'),
 ('What makes a requirement an architectural driver? Give an example.', ['structure', 'quality', 'constraint', 'concurrent', 'significant'], 'A driver is one of the few requirements with major architectural influence: you can name the structure it forces. "Checkout under 2 s at 10,000 concurrent users" forces caching and replicas.'),
 ('Distinguish essential from accidental complexity.', ['problem', 'solution', 'design away', 'essential', 'accidental'], 'Essential complexity comes from the problem itself; accidental complexity comes from the solution we chose, such as unused frameworks, and can be designed away.'),
 ("Explain Conway's law and what it means for architects.", ['team', 'organization', 'structure', 'communication', 'boundaries'], 'System structure mirrors the communication structure of the teams that build it, so organizational boundaries should be designed together with technical boundaries.'),
]},

2: {"mcq": [
 ("Why can't an architecture be captured in one diagram?",
  "Module, runtime, and allocation structures can't be merged",
  ['Diagram tools limit how many boxes fit on a page', 'Standards forbid showing classes and servers together', 'Only the deployment diagram counts as architecture'],
  'One module can map to many runtime components and vice versa, so multiple complementary structures are needed.'),
 ('Which question does a component-and-connector (C&C) view answer?',
  'What is running and how does it communicate?',
  ['What can a developer change and what breaks?', 'Where does it live and who owns it?', 'Which requirements were rejected?'],
  'Module views cover change and dependencies; C&C views cover runtime interaction; allocation views cover placement and ownership.'),
 ('A PaymentValidator is deployed to two availability zones and owned by the Payments team. Which structure records this?',
  'Allocation structure',
  ['Module structure', 'Component-and-connector structure', 'Uses structure'],
  'Allocation structures map software to hardware, teams, files, or environments.'),
 ('The reporting module uses the ledger module but not the reverse. What does this one-way dependency allow?',
  'Reporting can be replaced without touching the ledger',
  ['The ledger can call reporting synchronously', 'Both modules must now always be built and deployed together as one unit', 'The ledger can no longer be unit tested'],
  'A uses structure shows dependency direction; a one-way dependency makes the dependent side replaceable.'),
 ('What does a viewpoint define?',
  'The conventions, concerns, and rules for a kind of view',
  ['The finished diagram produced for one specific system and its stakeholders', 'The schedule for deploying each component', 'The list of alternatives the team rejected'],
  'The viewpoint is the template; a view is what you produce with it.'),
 ('A regulator asks where personal data crosses a network boundary. Which view answers this?',
  'A deployment view with trust zones',
  ['A class diagram of the domain', 'A sequence diagram of the login flow', 'A package dependency diagram'],
  'Choose views by the stakeholder question they answer; only a deployment view with trust zones shows network boundaries.'),
 ('The process view shows an async event from Order to Shipping, but the module view shows Shipping calling Order directly. What is this?',
  'A real defect: the views contradict each other',
  ['A harmless difference in drawing style', 'Proof that the process view is optional', 'Normal, because each view is an independent model and may disagree with others'],
  'Views describe one system, so a contradiction between them means something is wrong.'),
 ('According to the chapter, a view without a key and defined element semantics is…',
  'Decoration: boxes and lines with no agreed meaning',
  ['Acceptable as long as the audience is technical', 'Preferable, because simpler diagrams read faster', 'Required for the scenario view in 4+1'],
  'Without a key, readers invent their own meaning for each symbol.'),
 ('Which activity belongs to requirements elicitation?',
  'Observing users and running facilitated meetings',
  ['Prioritizing, classifying, and negotiating the collected requirements', 'Tracing requirements to test evidence', 'Writing an ADR'],
  'Elicitation gathers requirements (interviews, meetings, observation, scenarios); analysis classifies, prioritizes, and negotiates them.'),
 ('“The system shall be fast.” What is the main problem?',
  'It is not verifiable, so it cannot be tested',
  ['It is too specific', 'It is a design constraint rather than a requirement, so it belongs elsewhere', 'It is a derived requirement'],
  'A verifiable version is "95% of searches return within 300 ms with 500 concurrent users".'),
 ('A data-protection law requires erasure on request; the team infers it needs a single deletion API. The law and the inferred API are, respectively…',
  'Imposed and derived requirements',
  ['Derived and imposed requirements', 'Process and product requirements', 'Functional and quality requirements'],
  'Imposed requirements come from outside (law, standards, policy); derived ones are consequences the team infers.'),
 ('What does traceability connect?',
  'Drivers to decisions and evidence',
  ['Developers to their managers', "Requirements to their authors' teams", 'Servers to their IP addresses'],
  'Example chain: expand to the EU → support GDPR erasure → isolate user data behind a deletion API → integration test proves deletion.'),
 ("Which property is NOT on the chapter's list of good requirement qualities?",
  "Written in the team's technical jargon",
  ['Verifiable by a test or measurement', 'Consistent with the other requirements', 'Attainable within the constraints'],
  'Good requirements are specific, consistent, correct, attainable, complete, and verifiable.'),
 ('How do quality attribute scenarios help nonfunctional requirements?',
  'They make them testable with a measure',
  ['They replace functional requirements', 'They remove the need for stakeholders', 'They are only written after deployment'],
  'A scenario gives a stimulus, context, and response measure that can pass or fail.'),
 ("In Kruchten's 4+1 model, which view primarily serves programmers and uses component or package diagrams?",
  'Development view',
  ['Logical view', 'Process view', 'Physical view'],
  'Logical serves end users, process serves integrators, development serves programmers, and physical serves system engineers.'),
 ('Why are scenarios the “+1” in 4+1?',
  'They validate the other four by tracing use cases',
  ['They are optional and only used in large systems', 'They replace the physical view for cloud systems', 'They describe how the system is built and packaged'],
  'A use case such as "student registers" must be traceable through the logical, process, development, and physical views.'),
 ('Which diagram types typically represent the logical view?',
  'Class, collaboration, and sequence diagrams',
  ['Deployment and network topology diagrams', 'Component and package dependency diagrams', 'Activity diagrams and Gantt charts'],
  'The logical view shows functionality in terms of classes and their interactions.'),
 ('A deployment diagram reveals that a reporting job and live registration share one database node. Which 4+1 view exposed this?',
  'Physical view',
  ['Logical view', 'Development view', 'Scenario view'],
  'The physical view maps software onto hardware nodes and exposes shared-resource problems.'),
 ('For “student registers for a course,” the seat-reservation transaction and its locking appear in which view?',
  'Process view',
  ['Logical view', 'Development view', 'Physical view'],
  'The process view covers concurrency, transactions, and runtime behavior.'),
 ('Which set of fields belongs in an Architecture Decision Record (ADR)?',
  'Context, decision, alternatives, consequences, and status',
  ['Author, reviewers, team size, deadline, budget, and approval signatures', 'Class names, method signatures, and test coverage', 'Server addresses, ports, and deployment credentials'],
  'An ADR preserves why a decision was made, what was rejected, and what it costs.'),
 ('Why record rejected alternatives in an ADR?',
  "So settled debates don't reopen when context is forgotten",
  ['Because auditors require a minimum number of options', 'To record who proposed each of the bad options', 'So the alternatives can be built later in parallel'],
  'Recorded rejections preserve the reasoning that settled a question.'),
 ('A team hard-codes a currency table to hit a launch date, records it with a review date, and replaces it next quarter. This is…',
  'Deliberate technical debt',
  ['Accidental technical debt', 'Architectural drift', 'A sensitivity point'],
  'Technical debt is a future obligation; here it was taken knowingly and tracked.'),
 ('Which sequence shows a valid ADR status lifecycle?',
  'Proposed → accepted → deprecated or superseded',
  ['Draft → deleted → accepted', 'Accepted → proposed → rejected', 'Open → in review → closed → reopened whenever someone disagrees'],
  'Status keeps the record honest as the system evolves.'),
 ('Two services exchange {"amount": 1050}; one means halalas, the other riyals. The schema validates. What kind of mismatch is this?',
  'Semantic',
  ['Syntactic', 'Protocol', 'Timing'],
  'Syntax agreed but meaning differed. Contracts must cover semantics, not just format.'),
 ("What does documenting only an element's provided interface hide?",
  'What the element requires from others',
  ['The names of its internal classes', 'How it performs under peak load', 'Its full version and release history'],
  'An interface has provided and required sides; both are dependencies.'),
 ('A payments API adds an optional field and postpones removing a deprecated one until a v2 endpoint. Which contract aspect is being managed?',
  'Versioning',
  ['Error handling', 'Timing', 'Security'],
  'Additive changes keep old clients working; breaking changes wait for a new version.'),
 ('What makes the semantic half of a contract checkable rather than conversational?',
  'Preconditions, postconditions, and invariants',
  ['Longer, more descriptive method names', 'Detailed comments above each method', 'A switch from XML payloads to JSON with a published schema file'],
  'Formal conditions state exactly what must hold before and after a call.'),
 ('Code violates the intended layering, while separately the documentation still shows one deployable after the team split off two services. These are, respectively…',
  'Erosion and drift',
  ['Drift and erosion', 'Debt and governance', 'Conformance and evaluation'],
  'Erosion is code violating the intended structure; drift is the design evolving without the documentation following.'),
 ('An ArchUnit test fails the build if any domain class imports infrastructure. What is this called?',
  'A fitness function enforcing conformance',
  ['A quality attribute scenario with a response measure', 'An ADR', 'A viewpoint'],
  'Fitness functions turn architectural rules into automated checks that CI can enforce.'),
 ('Which statement about architecture governance matches the chapter?',
  'Consistent decisions without needless bureaucracy',
  ['Manual approval of every commit by the architect', 'Nothing once the architecture document is signed', 'Only open-source or public projects'],
  'Architecture is not a one-time artifact; governance keeps it consistent over time with minimal overhead.'),
],
"short": [
 ('Name the three kinds of architectural structure and the question each answers.', ['module', 'component', 'connector', 'allocation', 'runtime'], 'Module structures: what can a developer change and what breaks. Component-and-connector: what runs and how it talks. Allocation: where it lives and who owns it.'),
 ('List the 4+1 views and explain why scenarios are the +1.', ['logical', 'process', 'development', 'physical', 'scenario'], 'Logical, process, development, and physical views, plus scenarios that validate them by tracing use cases through all four.'),
 ('Rewrite "the system shall be fast" as a verifiable requirement and explain why it is better.', ['ms', 'concurrent', 'percent', 'measur', 'verifiable'], '"95% of catalog searches return within 300 ms with 500 concurrent users." It can be measured and can fail, so it is verifiable.'),
 ('What goes into an ADR and why record rejected alternatives?', ['context', 'decision', 'alternatives', 'consequences', 'status'], 'Context, decision, alternatives, consequences, and status. Recording rejected alternatives stops the same debate reopening when context is forgotten.'),
 ('Give an example of a semantic interface mismatch.', ['semantic', 'meaning', 'unit', 'halalas', 'riyals'], 'Two services agree on {"amount": 1050}, but one means halalas and the other riyals. The syntax validates while the meaning is wrong.'),
 ('Distinguish architectural erosion from architectural drift.', ['erosion', 'drift', 'violate', 'documentation', 'intended'], 'Erosion is code violating the intended structure; drift is the design evolving without the documentation following.'),
]},

3: {"mcq": [
 ('Which list gives the six parts of a quality attribute scenario?',
  'Source, stimulus, environment, artifact, response, response measure',
  ['Actor, use case, precondition, postcondition, trigger, priority', 'Input, process, output, storage, feedback, control', 'Risk, threat, asset, control, owner, date'],
  'The six parts turn a quality wish into an analyzable requirement.'),
 ('In an availability scenario, “normal operation at peak hours” is the…',
  'Environment',
  ['Stimulus', 'Artifact', 'Response measure'],
  'The environment is the system state when the stimulus arrives; acceptable responses differ between normal and degraded conditions.'),
 ("“Service restored within 30 seconds with no committed order lost” is the scenario's…",
  'Response measure',
  ['Response to the stimulus', 'Source', 'Stimulus'],
  'The response is what the system does (promote the standby); the measure is how it is judged.'),
 ('What is the difference between general and concrete scenarios?',
  'General ones are reusable templates; concrete ones are system-specific',
  ['General ones have measures; concrete ones leave the measure out', 'Concrete ones omit the environment; general ones always include it', 'General ones cover security only; concrete ones cover all qualities'],
  'A general scenario is instantiated with system-specific values to make a concrete one.'),
 ("Why does the scenario's environment matter?",
  'Acceptable responses differ under normal load and overload',
  ['It names the programming language and framework', 'It records which analyst wrote the scenario', 'It replaces the need for a response measure by describing load conditions'],
  'The same stimulus can have different acceptable outcomes depending on system state.'),
 ('A discount rate moves from a compile-time constant to a config file to a runtime rules table. Which design decision category is this?',
  'Binding time',
  ['Coordination model', 'Allocation of responsibilities', 'Data model'],
  'Later binding buys flexibility (marketing can change it without a deploy) and adds failure modes.'),
 ('A thread pool capped at 200 with a bounded queue protects a service during a spike. This is a decision about…',
  'Resource management',
  ['Technology choice', 'Binding time', 'Mapping among elements'],
  'Bounded resources degrade gracefully; an unbounded pool briefly serves more, then dies from memory exhaustion.'),
 ('Which decision category decides what can scale, fail, or be released independently?',
  'Mapping elements to runtime and deployment units',
  ['Naming conventions for variables and classes', "The format of the project's data dictionary", 'The UI color scheme and layout grid'],
  'How elements map to processes and nodes sets the units of scaling, failure, and release.'),
 ('Why report p95 and p99 latency instead of the average?',
  'Averages hide the users who suffer during spikes',
  ['Averages are harder to compute', 'Percentiles always report lower, more flattering numbers than averages', 'Standards forbid averages'],
  'Tail latency is what customers experience when the system is busy.'),
 ('Why is spare capacity (headroom) a design parameter rather than waste?',
  'Latency climbs sharply as utilization nears capacity',
  ['Idle servers make the system more secure', 'Cloud providers charge less for machines that stay partly idle all month', 'Spare capacity is only needed for backups'],
  'Near full utilization, small load increases cause large latency jumps.'),
 ('An API rate-limits each key and drops low-priority analytics events first when the queue is 80% full. These tactics…',
  'Control resource demand',
  ['Increase resources', 'Detect faults', 'Resist attacks'],
  'Demand-side tactics include sampling, admission control, and prioritization, protecting the checkout path.'),
 ('Adding a Redis cache turns a 120 ms join into a 3 ms lookup for most reads. What new trade-off does it introduce?',
  'Staleness, controlled by the cache TTL',
  ['Lower security by default', 'Loss of all write capability', 'Higher latency for cached reads than for direct database queries'],
  'Caching improves performance but introduces data freshness as a new concern.'),
 ('Using Availability = MTBF / (MTBF + MTTR), which change improves availability as much as doubling MTBF?',
  'Halving MTTR',
  ['Doubling MTTR', 'Halving MTBF', 'Adding a second log file'],
  'Repair time matters as much as failure frequency.'),
 ('A pod receives a liveness probe every 5 seconds and is replaced after three misses. Which tactics are used?',
  'Heartbeat detection and spare recovery',
  ['Voting detection and rollback recovery', 'Encryption and audit logging', 'Sampling and request prioritization'],
  'Periodic probes detect the fault; a replacement pod recovers service.'),
 ('Roughly how much yearly downtime does 99.9% availability allow?',
  'About 8.8 hours',
  ['About 53 minutes', 'About 5 minutes', 'About 3.6 days'],
  '99.99% allows about 53 minutes; moving between those tiers often means going from one region to two.'),
 ('A repaired replica replays the write-ahead log, then serves shadow traffic before handling real users. Which tactic family is this?',
  'Reintroduction',
  ['Fault detection', 'Fault prevention', 'Demand control'],
  'Reintroduction includes resynchronization, shadow operation, and rollback.'),
 ('When does a fault become a failure?',
  'When it reaches the user',
  ['As soon as it is logged', 'When a developer notices it', 'Only when the whole system crashes'],
  'Masking a fault fast enough is a valid availability strategy.'),
 ('A stolen API key still fails because mTLS, IP-range checks, and per-key rate limits also apply. This demonstrates…',
  'Defense in depth',
  ['Least privilege', 'Non-repudiation', 'Single sign-on'],
  'Independent layered controls avoid any single control being a single point of failure.'),
 ('In STRIDE, an instructor denying they changed a grade is which threat?',
  'Repudiation',
  ['Spoofing', 'Tampering', 'Elevation of privilege'],
  'Repudiation is countered by an append-only audit log.'),
 ('Which four groups do security tactics fall into?',
  'Detect, resist, react to, and recover from attacks',
  ['Plan, build, test, deploy', 'Encrypt, compress, cache, log', 'Authenticate, authorize, audit, archive, and alert administrators'],
  'Tactics are grouped by what they do relative to an attack.'),
 ('What does least privilege mainly limit?',
  'The damage one compromised part can do',
  ['The number of registered users', 'The network bandwidth each service uses', 'The amount of duplicated code'],
  'A component with minimal rights can do minimal damage if taken over.'),
 ('Adding a payment provider touches one class implementing PaymentGateway plus one config entry. Which quality does this show?',
  'Modifiability through localized change',
  ['Availability through redundant payment providers', 'Performance through caching', 'Usability through undo'],
  'Callers depend on the interface, so the change stays in one place.'),
 ('A billing service takes a Clock dependency so tests can set the date to 29 February. Which testability property does this give?',
  'Controllability',
  ['Observability', 'Interoperability', 'Scalability'],
  'Controllability lets a test put the system into a chosen state; observability lets it see the result.'),
 ('How is modifiability measured?',
  'By the cost: modules touched, effort, and time',
  ['By the number of comments in the code', 'By the average response time of the system under representative load', 'By how many design patterns are used'],
  'Modifiability is about the cost of change.'),
 ('Which is a modifiability tactic?',
  'Defer binding time',
  ['Add a heartbeat', 'Encrypt data at rest', 'Increase thread pool size'],
  'Modifiability tactics reduce module size, increase cohesion, reduce coupling, and defer binding.'),
 ('A long export shows progress, can be cancelled, and leaves no partial file. Which usability tactic group does this belong to?',
  'Supporting user initiative',
  ['Supporting system initiative', 'Resisting attacks', 'Managing resources'],
  'User-initiative tactics include cancel, undo, pause, and aggregate; this also requires running outside the UI thread.'),
 ('Two hospitals both use HL7 FHIR, but one stores blood pressure as one string and the other as two values. What is missing?',
  'Semantic interoperability',
  ['Syntactic interoperability', 'Network connectivity', 'Authentication'],
  'Standards help but do not guarantee compatible meaning, so a translation layer is still needed.'),
 ('Which is an interoperability tactic?',
  'Tailoring the interface between mismatched parties',
  ['Adding CPU cores and memory to the shared integration server', 'Hashing passwords before they are stored', 'Supporting undo for user actions'],
  'Interoperability tactics include discovering services and orchestrating or tailoring interfaces.'),
 ('Why separate UI from domain logic for usability?',
  "So cancel, undo, and feedback don't tangle business rules",
  ['So the UI can be written in a different language', 'Because domain logic cannot run on the client, so it must live elsewhere', 'To remove the need for automated UI testing'],
  'Separation lets the UI provide feedback and recovery while domain logic stays independent.'),
],
"short": [
 ('Write a six-part performance scenario for a search feature.', ['source', 'stimulus', 'environment', 'artifact', 'response', 'measure'], 'Source: 5,000 concurrent users. Stimulus: submit searches. Environment: exam-week peak. Artifact: catalog search. Response: results returned. Measure: p95 under 500 ms, none over 2 s.'),
 ('Explain binding time with an example and its trade-off.', ['compile', 'config', 'run time', 'flexib', 'deploy'], 'A value can bind at compile time (fast, needs a release), at startup via config, or at run time via a rules table (changed without deploying). Later binding adds flexibility and new failure modes.'),
 ('Using the availability formula, explain why reducing repair time matters.', ['mtbf', 'mttr', 'repair', 'halving', 'formula'], 'Availability = MTBF / (MTBF + MTTR). Halving MTTR improves availability as much as doubling MTBF, so fast recovery is as valuable as fewer failures.'),
 ('What is defense in depth? Give an example.', ['layer', 'independent', 'single point', 'control', 'mtls'], 'Several independent controls so no single one is a point of failure; for example a stolen API key still fails mTLS, IP-range, and rate-limit checks.'),
 ('Explain controllability and observability in testability.', ['controllab', 'observab', 'state', 'clock', 'inject'], 'Controllability is putting the system into a chosen state (an injected Clock sets the date); observability is seeing the resulting behavior and output.'),
 ("Why don't shared standards guarantee interoperability?", ['semantic', 'meaning', 'syntax', 'translation', 'fhir'], 'Standards align syntax, but systems can still disagree on meaning, such as blood pressure as one string versus two values, so translation is still needed.'),
]},

4: {"mcq": [
 ('What distinguishes a documented pattern from a simple template?',
  'It states the consequences of applying it',
  ['It always includes working source code', 'It is drawn in standard UML notation', 'It is approved by an industry standards body'],
  'A pattern is a problem in context with a solution and consequences; the consequences make it a design tool.'),
 ('Who introduced the pattern form that software engineering adopted in the 1990s?',
  'Christopher Alexander',
  ['Edsger Dijkstra', 'Philippe Kruchten', 'David Parnas'],
  'Alexander described building patterns; Gamma and colleagues carried the form into software in 1994.'),
 ('Repository and blackboard belong to which style family?',
  'Data-centered',
  ['Data-flow', 'Hierarchical', 'Interactive'],
  'Pipes and filters is data-flow; layered is hierarchical; MVC is interactive; client-server and broker are distributed.'),
 ('What is an architectural style?',
  'Element and connector types plus rules for combining them',
  ['A feature provided by a specific programming language', "A company's coding guidelines and naming rules", 'A single diagram describing one particular system'],
  "The constraints are what deliver the style's benefits."),
 ('A system draws layers but lets any layer call any other. What does it lose?',
  "The benefits, since the layering rule isn't enforced",
  ["Nothing, since the diagram is what delivers the style's benefits anyway", 'Only the accuracy of its documentation', 'Its ability to connect to a database'],
  "The layered style's value comes from the rule that a layer only calls the layer below."),
 ('In a closed layered architecture, a layer may call…',
  'Only the layer directly below it',
  ['Any layer below it', 'Any layer above or below it, as long as the call is documented', 'Only the database'],
  'Open layers permit skipping; closed layers restrict calls to adjacent layers.'),
 ('A read-only lookup passes through a controller, a forwarding service, and a forwarding repository. What anti-pattern is this?',
  'Sinkhole',
  ['God object', 'Big ball of mud', 'Fat controller'],
  'Most requests pass through layers that add no logic; opening a layer for pure lookups avoids useless hops.'),
 ('Which is a known cost of layered architecture?',
  'Extra latency and duplicated transformations',
  ['The UI can no longer be changed', 'It removes separation of concerns between presentation and business logic', 'It cannot run on a single server'],
  'Benefits include portability and replaceability; costs include latency, duplicate transformations, and pressure to bypass layers.'),
 ('In MVC, what happens after the controller updates the model?',
  'The model notifies observing views of the change',
  ['The controller redraws every view directly with the new values', 'The view writes to the database', 'The model queries each view for its state'],
  'The model publishes change notifications without knowing specific views (Observer).'),
 ("A spreadsheet's grid, bar chart, and pie chart all update when one cell changes. Which MVC property is shown?",
  'Multiple views sharing one model',
  ['Views that update each other directly', 'A controller that stores the data', 'A pipeline of chained filters'],
  'Views observe the same model and do not know about each other.'),
 ('A CheckoutController computes tax, applies loyalty rules, and calls the payment gateway. What is the problem?',
  "It's a fat controller holding model logic",
  ['Controllers should never call other code', 'Tax logic should live in the view instead', 'Nothing; this is correct MVC design'],
  'Poor responsibility allocation creates fat controllers and anemic models.'),
 ('Which pattern works inside MVC to keep the model unaware of specific views?',
  'Observer',
  ['Singleton', 'Builder', 'Adapter'],
  'The model publishes changes and observers react.'),
 ('What motivated variants such as MVP and MVVM?',
  'Making presentation logic easier to test',
  ['Removing the model from the pattern', 'Supporting batch and offline processing', 'Replacing the database layer'],
  'They shift presentation logic into a testable presenter or view-model.'),
 ('What limits the throughput of a pipes-and-filters pipeline?',
  'The slowest filter',
  ['The fastest filter', 'The number of pipes', 'The length of the input file name'],
  'Data can only flow as fast as the bottleneck filter processes it.'),
 ('Which property keeps filters recombinable?',
  'A shared data format and no knowledge of neighbouring filters',
  ['Shared global state that every filter in the pipeline can read and update', 'Each filter calling the next directly', 'A central controller choosing the order at runtime'],
  'Independent, stateless filters with one format can be reordered and reused.'),
 ('Which workload fits pipes and filters poorly?',
  'A wizard where users go back to edit earlier steps',
  ["A compiler's lexer, parser, and optimizer chain", 'A CI pipeline of lint, build, and test stages', 'Filtering a log file with grep, cut, and sort'],
  'The style assumes a one-way stream; interactive back-and-forth breaks it.'),
 ('Which concern must a pipes-and-filters design define explicitly?',
  'Backpressure and error propagation',
  ['Which filter owns the shared global state', 'How each filter calls the next one directly', 'The order in which views are notified'],
  'Data formats, error propagation, backpressure, and termination all need defining.'),
 ('What does a broker do?',
  'Locates servers for clients and forwards requests',
  ['Stores all shared data centrally for clients', 'Renders the views that clients display', 'Compiles client code into server stubs'],
  'A broker provides location transparency and loose coupling.'),
 ('A mobile client calls api.shop.com/orders and a gateway picks one of twelve instances. Which pattern provides this?',
  'Broker',
  ['Blackboard', 'Layered', 'Pipes and filters'],
  'A service registry plus API gateway hides server location from the client.'),
 ('Why is order.getCustomer().getAddress().getCity() dangerous across a network?',
  'Each call is a network round-trip that can fail',
  ['Getters are not allowed in distributed systems', 'It violates the open–closed principle', 'Chained calls cannot be serialized to JSON'],
  'Remote calls add latency and partial failure; assuming they behave like local calls is a known fallacy.'),
 ('Why should operations that might be retried be idempotent?',
  "So a retry doesn't repeat the effect, like a double charge",
  ['So the operation runs faster on each attempt', 'So it no longer needs authentication', 'So it can keep running normally while the network connection is offline'],
  'Idempotency makes retries safe under partial failure.'),
 ('In the repository style, what drives control flow?',
  'The clients; the shared data is passive',
  ['Changes to the data trigger agents', 'A pipeline of filters', 'The view layer'],
  'In a blackboard, changes to the data drive which agent runs next.'),
 ('Which problem suits a blackboard architecture?',
  'Speech recognition, with no fixed solution order',
  ['Payroll calculation with fixed tax rules applied in a set order', 'Serving static pages for a website', 'A three-layer CRUD admin application'],
  'Specialist agents contribute partial solutions while a controller picks the next contributor.'),
 ('What is a known risk of the repository style?',
  'The shared store becomes a bottleneck',
  ['Clients cannot read the shared data', 'Data consistency becomes impossible', 'It requires a message broker'],
  'An IDE where all tools stall when the shared model locks illustrates this.'),
 ('OrderPlaced is consumed by inventory, email, and analytics. What must change to add a loyalty-points consumer?',
  'Nothing; the new consumer just subscribes',
  ['The order service must call the new consumer', 'Every existing consumer must be updated', 'The OrderPlaced schema must be replaced'],
  'Event-driven fan-out decouples producers from consumers.'),
 ('With at-least-once delivery, how should the email consumer avoid sending two receipts?',
  'Key sent mail on the event ID so a duplicate is a no-op',
  ['Assume duplicates never happen', 'Delete the event queue after each send', 'Send emails synchronously from the producer so no event is ever needed'],
  'Consumers must be idempotent because duplicate delivery is expected.'),
 ('What replaces the call stack when debugging an event-driven system?',
  'Correlation IDs and distributed tracing',
  ['Breakpoints in the broker', 'A single log file per server, read in time order across all machines', 'UML sequence diagrams'],
  'No single stack shows the whole transaction, so tracing links the steps.'),
 ('Which event-driven topology uses an orchestrator for multi-step workflows?',
  'Mediator topology',
  ['Broker topology', 'Pipes topology', 'Layered topology'],
  'The broker topology chains consumers directly for simpler flows.'),
],
"short": [
 ('What is the sinkhole anti-pattern and how can it be reduced?', ['layer', 'forward', 'no logic', 'open', 'sinkhole'], 'Most requests pass through layers that add no logic, paying the cost without benefit. Marking a layer open for pure lookups lets those requests skip useless hops.'),
 ('Explain how MVC keeps views in sync with the model.', ['controller', 'model', 'notif', 'observer', 'view'], 'The controller interprets input and updates the model; the model notifies observing views, which redraw. The model never knows specific views.'),
 ('Give two strengths and one weakness of pipes and filters.', ['reuse', 'concurren', 'reorder', 'interactive', 'slowest'], 'Filters can be reused, reordered, and run concurrently. It fits interactive or shared-state workflows poorly, and throughput is limited by the slowest filter.'),
 ('Contrast the repository and blackboard styles.', ['passive', 'client', 'agent', 'controller', 'partial'], 'In a repository, data is passive and clients drive control. In a blackboard, specialist agents contribute partial solutions and data changes plus a controller decide who acts next.'),
 ('Why must event consumers be idempotent?', ['duplicate', 'at-least-once', 'event id', 'idempot', 'retry'], 'At-least-once delivery means events can arrive twice; idempotent handling (for example keyed on the event ID) makes duplicates harmless.'),
]},

5: {"mcq": [
 ('Where does detailed design sit in the lifecycle?',
  'Between architecture and construction',
  ['Before requirements elicitation, as the first lifecycle phase', 'After deployment only', 'In place of testing'],
  'It refines architectural components into implementable structures and behavior.'),
 ('A component quietly opens its own database connection, bypassing the data-access layer. Why is this a detailed-design failure?',
  'It ignores architectural decisions from below',
  ['Nothing, since faster code is always acceptable', 'Database connections belong in the view layer', 'It violates the Liskov substitution principle'],
  'Detailed design must respect architectural decisions.'),
 ('“enrollment.status — enumeration {PENDING, CONFIRMED, WAITLISTED, DROPPED}; never null.” Which artifact is this?',
  'A data dictionary entry',
  ['An interface control document', 'A sequence diagram', 'An ADR'],
  "Data dictionaries define each data element's type, values, and rules."),
 ('A team generates class and sequence diagrams from an undocumented legacy module before changing it. This is…',
  'Reverse engineering',
  ['Refactoring', 'Forward engineering', 'Prototyping'],
  'Reverse engineering recovers design knowledge from existing code.'),
 ('How specific should detailed-design output be?',
  "Enough that developers don't re-decide structure",
  ['As vague as possible to leave room for coders', 'Just a list of the class names involved', 'Exactly the final source code, line by line'],
  'It settles structure so construction does not re-decide it.'),
 ('Generalization and realization model, respectively…',
  'Is-a, and implementing an interface',
  ['Ownership, and a usage dependency', 'Implementing an interface, and is-a', 'Composition, and aggregation'],
  'Generalization is inheritance; realization connects a classifier to an interface it implements.'),
 ('An Invoice owns InvoiceLines that are deleted with it; a Department references Professors who remain after it is deleted. These are…',
  'Composition and aggregation',
  ['Aggregation and composition', 'Realization and generalization', 'Association and dependency'],
  'Composition means the part dies with the whole; aggregation parts outlive it.'),
 ('A report sums shapes.map(Shape::area) with no type checks. Which mechanism makes this work?',
  'Polymorphism',
  ['Encapsulation', 'Aggregation', 'Reverse engineering'],
  'Each concrete shape supplies its own area(), chosen at run time.'),
 ('Which can be instantiated directly?',
  'A concrete class',
  ['An abstract class', 'An interface', 'An abstract method'],
  'Abstract classes and methods defer some implementation to subclasses.'),
 ("What is Parnas's criterion for modularization?",
  'Hide each likely-to-change decision in a module',
  ['Split code into modules by execution order', 'Give each developer their own module', 'Keep every module under 100 lines'],
  'Information hiding localizes likely change.'),
 ('cart.getItems() returns the internal List, so callers can clear it and bypass total recalculation. What is the fix?',
  'Return an unmodifiable copy so the invariant is preserved',
  ['Make the list public', 'Add a comment asking callers not to modify the returned list directly', 'Remove the totals field'],
  'Returning internal mutable state breaks encapsulation as surely as a public field.'),
 ('Session storage in Redis is hidden behind a SessionStore interface. What does this buy?',
  'A storage change touches one class, not forty',
  ['Redis queries become noticeably faster', 'Session data becomes encrypted automatically at rest and in transit', 'Session code no longer needs any tests'],
  'Hiding a volatile decision behind an abstraction localizes future change.'),
 ('Encapsulation protects more than private fields. What else does it include?',
  'Behavioral invariants',
  ['Network latency', 'Deployment topology', 'Team ownership'],
  'An object must keep its rules true, not only hide its data.'),
 ('A Utils class holds date formatting, password hashing, and CSV parsing. Its cohesion is…',
  'Coincidental',
  ['Functional', 'Sequential', 'Communicational'],
  'Coincidental cohesion is the weakest: parts are grouped for no real reason.'),
 ('Which is the strongest (best) form of cohesion?',
  'Functional',
  ['Temporal', 'Logical', 'Procedural'],
  'Cohesion runs from coincidental up to functional.'),
 ('generateReport(type, isPdf, includeCharts) lets the caller steer internal branching. This is…',
  'Control coupling',
  ['Data coupling', 'Content coupling', 'Functional cohesion'],
  'Separate PdfReport and CsvReport implementations remove the flags.'),
 ('Which coupling type is weakest and preferred?',
  'Data coupling',
  ['Common coupling', 'Content coupling', 'Control coupling'],
  'Coupling runs from content and common through control and stamp down to data.'),
 ('What does the Single Responsibility Principle really mean?',
  'A module answers to one actor or change source',
  ['Every method should be a single line', 'A class should expose only one method', 'Each file should contain exactly one class'],
  'SRP is about alignment with a change source, not doing one tiny task.'),
 ('Employee has calculatePay() for finance, reportHours() for operations, and save() for the DBA. What does SRP suggest?',
  "Split it so each actor's changes have one home",
  ['Merge the three into a single method', 'Make all three methods static', 'Add methods so other actors are served too'],
  'A class serving several actors will eventually break one while serving another.'),
 ('A growing switch over shipping carriers is replaced with a ShippingCarrier interface and one class per carrier. Which principle is applied?',
  'Open–closed',
  ['Interface segregation', 'Liskov substitution', 'Law of Demeter'],
  'A new carrier is a new class, not an edit to tested code.'),
 ('When does OCP become accidental complexity?',
  'When extension points have no real variation',
  ['Whenever an interface is introduced', 'When there are more than three subclasses', 'Whenever composition is used'],
  'Speculative flexibility costs complexity without payoff.'),
 ('Square extends Rectangle and forces height to equal width. Code setting width 5 and height 4 gets area 16. Which principle is violated?',
  'Liskov substitution',
  ['Single responsibility', 'Dependency inversion', 'Interface segregation'],
  'Signatures matched but behavior did not, so the subtype broke client expectations.'),
 ('According to LSP, a subtype may NOT…',
  'Strengthen preconditions or weaken postconditions',
  ["Add new public methods beyond the parent's", 'Override a method with its own implementation', 'Declare more fields than its parent class'],
  'Subtypes must accept at least what the parent accepts and guarantee at least what it guarantees.'),
 ('A basic printer must stub scan, fax, and staple from a Printer interface. Which principle fixes this?',
  'Interface segregation',
  ['Open–closed', 'Liskov substitution', 'Single responsibility'],
  'Split into Printer, Scanner, and FaxMachine so clients depend only on what they use.'),
 ('Under dependency inversion, who should own the abstraction?',
  'The high-level policy module',
  ['The low-level infrastructure module', 'A third-party library', 'The database'],
  'The detail conforms to policy, so compile-time dependencies point toward the domain.'),
 ('Which statement about dependency injection and dependency inversion is correct?',
  'Injection is a mechanism; inversion is a goal',
  ['They are two names for the same idea', 'Inversion can only be done with a DI container', 'Injecting a dependency always inverts it'],
  'You can inject a concrete class without inverting any dependency.'),
 ('A constructor takes a PaymentGateway, so a test passes a fake that returns DECLINED. What benefit does this show?',
  'Fast, isolated tests with no network',
  ['Better runtime performance in production', 'Stronger encryption', 'Fewer classes in production'],
  'Injecting collaborators makes behavior controllable in tests.'),
 ('Why is composition often preferred over inheritance?',
  'It can change at run time and avoids fragile base classes',
  ['It always executes faster than inherited code because calls are resolved statically', 'It removes the need to define any interfaces', 'Inheritance is deprecated in modern Java versions'],
  'Inheritance binds subclass to superclass implementation at compile time.'),
 ('A developer refactors a method and changes its output at the same time. Why is this risky?',
  'Refactoring must preserve behavior; mixing both invites outages',
  ['Refactoring is expected to change behavior anyway', 'Tests cannot run while code is being refactored', 'Compilers and CI tools reject commits that mix both kinds of change together'],
  'Separate structural changes from behavior changes, protected by automated tests.'),
 ('Which refactoring matches the “long parameter list” smell?',
  'Introduce parameter object',
  ['Replace conditional with polymorphism', 'Move method', 'Inline variable'],
  'Smells point at specific refactorings: long method → extract method, large class → extract class, feature envy → move method.'),
],
"short": [
 ('Distinguish aggregation from composition with an example.', ['lifetime', 'whole', 'part', 'composition', 'aggregation'], 'Composition: the part dies with the whole (Invoice and InvoiceLine). Aggregation: the part outlives it (Department and Professor).'),
 ("Explain Parnas's information hiding criterion with an example.", ['change', 'hide', 'decision', 'interface', 'module'], 'Modularize around the decisions most likely to change and hide each in a module; for example Redis session storage behind a SessionStore interface.'),
 ('Name the strongest cohesion and weakest coupling and explain why they are preferred.', ['functional', 'data coupling', 'cohesion', 'coupling', 'change'], 'Functional cohesion (one well-defined purpose) and data coupling (only needed data passed) keep changes local and modules understandable.'),
 ('Explain the Liskov Substitution Principle using the Square/Rectangle example.', ['subtype', 'behavior', 'area', 'precondition', 'substitut'], 'Subtypes must keep client expectations. A Square that forces height = width returns area 16 when the client set 5×4 and expected 20, so it cannot substitute for Rectangle.'),
 ('What is the difference between dependency injection and dependency inversion?', ['mechanism', 'goal', 'abstraction', 'high-level', 'inject'], 'Injection supplies collaborators from outside (a mechanism). Inversion makes high-level policy own the abstraction that details implement (a design goal). You can inject without inverting.'),
 ('Why prefer composition over inheritance?', ['run time', 'fragile base', 'decorator', 'compile time', 'reconfigur'], 'Composition can be reconfigured at run time and avoids the fragile base class problem; inheritance binds to the superclass implementation at compile time.'),
]},

6: {"mcq": [
 ('What do creational patterns separate clients from?',
  'Concrete construction decisions',
  ['Their user interface', 'The database schema that stores their objects', 'Their test suite'],
  'Clients ask for objects without hard-coding which concrete class is built.'),
 ('Which is the only class-scoped creational pattern?',
  'Factory Method',
  ['Abstract Factory', 'Builder', 'Prototype'],
  'Factory Method varies the product through subclassing; the other four creational patterns are object-scoped.'),
 ('Class-scoped and object-scoped patterns rely mainly on, respectively…',
  'Inheritance and composition',
  ['Composition and inheritance', 'Interfaces and enums', 'Threads and locks'],
  'Class patterns fix relationships at compile time through inheritance; object patterns vary them at run time through composition.'),
 ('Which part of a pattern entry most directly decides whether you should use it?',
  'Consequences',
  ['Intent', 'Participants', 'Sample code'],
  "Consequences state the trade-offs, such as a Singleton's global state and testing cost."),
 ('Which three purposes classify design patterns?',
  'Creational, structural, and behavioral',
  ['Class, object, and module-level design patterns', 'Local, remote, and cached', 'Abstract, concrete, and virtual'],
  'Scope (class or object) is the second, separate classification axis.'),
 ('In Factory Method, what does the creator class keep, and what does it delegate?',
  'Keeps the product-using logic; subclasses pick the product',
  ["Keeps the product's fields; delegates its methods", 'Keeps nothing itself; delegates all of the work to a global singleton', 'Keeps the concrete classes; delegates the interface'],
  'Application.openDocument() is written once; createDocument() is overridden.'),
 ('DrawingApplication.createDocument() returns a DrawingDocument and TextApplication returns a TextDocument. Which pattern is this?',
  'Factory Method',
  ['Abstract Factory', 'Prototype', 'Builder'],
  'Subclasses decide which product the shared framework logic receives.'),
 ('Why is Factory Method behind most framework hook points?',
  'The framework calls it; your subclass picks the product',
  ['Frameworks are not allowed to call constructors on application classes', 'It guarantees the framework has one instance', 'It lets the framework copy existing objects'],
  'Inversion of control: the framework owns the flow, the subclass supplies the product.'),
 ('What is a cost of Factory Method?',
  'Extra classes and indirection',
  ['Global state', 'Deep-copy hazards', 'Telescoping constructors'],
  'Each product variation may need a new creator subclass.'),
 ('What problem is Abstract Factory designed to prevent?',
  'Mixing products from different families',
  ['Creating more than one instance of a class', 'Copying objects shallowly by mistake', 'Constructors with too many parameters'],
  'It enforces compatibility within a product family.'),
 ('With Abstract Factory, which change is expensive?',
  'Adding a new product kind, such as Slider',
  ['Adding a new platform family, such as Linux', 'Adding a new client that uses the factory', 'Switching between factories at run time'],
  'A new family is one new class; a new product type edits the interface and all implementations.'),
 ('How is an Abstract Factory often implemented?',
  'One object whose methods are Factory Methods',
  ['A chain of decorators around a product', 'A registry of prototype instances cloned on demand', 'A pipeline of filters that build parts'],
  'Abstract Factory is also frequently a Singleton.'),
 ('What does client code depend on in Abstract Factory?',
  'Abstract factory and product interfaces',
  ['The concrete product classes it needs', 'The SDK of the platform it runs on', 'A global configuration singleton'],
  'The client never names a concrete class, so families can be swapped.'),
 ('A constructor with nine nullable parameters is replaced by .size(30).crust(THIN).topping("cheese").build(). Which pattern is this?',
  'Builder',
  ['Prototype', 'Abstract Factory', 'Facade'],
  'Builder avoids telescoping constructors for objects with many optional parts.'),
 ('Where does validation belong in a Builder?',
  'In build(), once the object is complete',
  ['In each setter, as each value arrives from the client', 'In the client, after construction', 'Nowhere; builders never validate'],
  'build() can reject a pizza with no size.'),
 ('One HouseDirector sequence drives a HouseBuilder and a HouseBlueprintBuilder to produce a house and a printable plan. What does this show?',
  'One process can build different representations',
  ['Directors create consistent product families', 'Builders must be implemented as singletons', 'Blueprints act as prototypes that get cloned'],
  'The director fixes the steps; each concrete builder decides what each step produces.'),
 ("What is Builder's main cost?",
  'Extra ceremony and classes',
  ['Global state', 'Shared mutable references', 'Inability to validate'],
  'It trades constructor simplicity for readability and control.'),
 ('When is Prototype a good choice?',
  'When setup is costly or the type is known only at run time',
  ['When exactly one instance must exist in the whole system', 'When related products must come in consistent families', 'When the object has many optional construction parameters'],
  'Cloning a configured instance skips costly setup.'),
 ("A shallow clone of an Order shares its List<OrderLine>. What happens when the copy's lines are edited?",
  "The original's lines change too",
  ['Nothing, since clones are independent', 'The copy throws an exception', 'The list is deep-copied automatically'],
  'Deep versus shallow copying must be decided deliberately.'),
 ("A diagram editor's toolbar clones a styled rectangle on each drop. What supports this lookup by key?",
  'A prototype registry',
  ['A director', 'A two-way adapter', 'An abstract product'],
  'Clients ask the registry for a copy without knowing any concrete class.'),
 ('Why is a naive lazy getInstance() unsafe?',
  'Two threads can each see null and create one',
  ['It always returns null on the first call', 'It cannot be called from static methods', 'It deep-copies the instance on each call'],
  'An eager static final field, double-checked locking, or an enum fixes it.'),
 ('Which is a reliable way to make a Java Singleton thread-safe?',
  'Use an enum or an eager static final field',
  ['Call getInstance() twice', 'Make the constructor public', 'Clone the instance separately for each calling thread'],
  'The JVM guarantees uniqueness during class initialization.'),
 ('Tests sharing a singleton cache pass alone but fail together. Why?',
  'State leaks between tests through the global instance',
  ['Singletons cannot be tested at all', 'The test framework creates a new singleton for every test class it loads', 'Caches are forbidden in tests'],
  'Injecting a single instance through a container gives single lifetime without global state.'),
 ('Why does the chapter say singletons hide dependencies?',
  'Callers use it without declaring it as a dependency',
  ['Singletons are always declared as private classes', 'Singletons are always lazily initialized', 'Singletons are loaded by a separate class loader'],
  'Hidden dependencies make code harder to test and reason about.'),
 ('When should Singleton be used?',
  'Only when one instance is a real invariant',
  ['Whenever an object is used in many places', 'For every service class in the application', 'To avoid passing parameters between classes'],
  'Dependency injection often gives single-instance lifetime more cleanly.'),
 ('Families of widgets that must stay consistent across a platform suggest which pattern?',
  'Abstract Factory',
  ['Factory Method', 'Builder', 'Prototype'],
  'Many kinds of one product → Factory Method; one product with many parts → Builder; costly setup → Prototype.'),
 ('What is the recommended starting point before adding a creational pattern?',
  'A plain constructor until construction starts varying',
  ['An Abstract Factory from the first version', 'A Singleton for every class that is created, to keep instances under control', 'A Builder for every object, however simple'],
  'Prefer the simplest mechanism that keeps the needed flexibility.'),
 ('Factories, Builder, and Prototype each primarily vary…',
  'What type, how it is assembled, and copying state',
  ['Speed, memory use, and security of creation', 'The view, controller, and model of creation', 'Compile time, link time, and run time binding'],
  'Choose by what varies: what, how, or when objects are created.'),
],
"short": [
 ('Compare Factory Method and Abstract Factory by scope and what they vary.', ['subclass', 'inheritance', 'family', 'composition', 'object'], 'Factory Method is class-scoped and varies the product through subclassing. Abstract Factory is object-scoped and swaps a factory object to produce a consistent family of products.'),
 ('What is the rigidity cost of Abstract Factory?', ['new product', 'every factory', 'interface', 'family', 'slider'], 'Adding a new family is one class, but adding a new product kind (such as Slider) changes the abstract factory interface and every implementation.'),
 ('Why does Builder put validation in build()?', ['build', 'complete', 'valid', 'optional', 'reject'], 'Only at build() is the object known to be complete, so it can reject invalid combinations such as a pizza with no size.'),
 ('Explain the shallow vs deep copy hazard in Prototype.', ['shallow', 'deep', 'reference', 'shared', 'clone'], "A shallow clone shares references, so editing the copy's list edits the original. A deep clone copies the referenced objects too."),
 ('Give two drawbacks of Singleton and one alternative.', ['global', 'test', 'hidden', 'thread', 'injection'], 'It creates global state that leaks between tests and hides dependencies (and naive lazy init is not thread-safe). Dependency injection can provide a single instance without the global.'),
]},

7: {"mcq": [
 ('The app expects PaymentGateway.charge(Money) but the SDK offers StripeClient.createCharge(long cents, String currency). Which pattern fits?',
  'Adapter',
  ['Bridge', 'Facade', 'Proxy'],
  'Adapter translates one interface into the one the client expects.'),
 ('Object adapters and class adapters use, respectively…',
  'Composition and inheritance',
  ['Inheritance and composition', 'Proxies and decorators', 'Events and callbacks'],
  'Class adapters need multiple inheritance or similar language support.'),
 ('What is the key timing difference between Adapter and Bridge?',
  'Adapter is retrofitted; Bridge is designed in up front',
  ['Bridge is retrofitted; Adapter is designed in up front', 'Both are only applied at run time', 'Neither is used when writing new code'],
  'Adapter reconciles existing unrelated code; Bridge plans for two independent dimensions.'),
 ('What does an Adapter change?',
  'The interface, not the core responsibility',
  ['The core responsibility, not the interface', 'Both interface and responsibility', 'Only performance'],
  'The adaptee still does the work; the adapter only translates.'),
 ('What is a two-way adapter?',
  'One implementing both interfaces for either side',
  ['One that wraps two separate adaptee objects', 'One shared by exactly two client classes', "One that also caches the adaptee's results"],
  'It lets both old and new code treat the object as their own type.'),
 ('Three shapes and three renderers would need nine subclasses. How many classes does Bridge need?',
  'Six',
  ['Nine', 'Three', 'Twelve'],
  'Bridge turns m × n into m + n; adding a fourth renderer adds one class.'),
 ('Before applying Bridge, what must you identify?',
  'Two independent axes of change',
  ['A single legacy interface', 'A part–whole hierarchy', 'An expensive object to load lazily'],
  'Bridge separates an abstraction dimension from an implementation dimension.'),
 ('JDBC code written against Connection and Statement while vendors supply drivers is an example of…',
  'Bridge',
  ['Composite', 'Decorator', 'Facade'],
  'The abstraction side (JDBC API) and implementation side (drivers) vary independently.'),
 ('In Bridge, what is a refined abstraction?',
  'An extension of the abstraction side only',
  ['A concrete implementor of the bridge', 'An adapter wrapping legacy code', 'A proxy that caches implementor calls'],
  'Each side can grow on its own.'),
 ('A backup tool calls getSize() on the root folder without checking whether each node is a file or folder. Which pattern enables this?',
  'Composite',
  ['Decorator', 'Proxy', 'Bridge'],
  'Leaves and composites share one interface; folders sum their children recursively.'),
 ('In the transparent Composite variant, where do child-management methods such as add() live?',
  'On the component, so add() on a leaf fails at run time',
  ['Only on the composite class, never on the leaf, so leaves cannot misuse them', 'Only on the leaf class, never the composite', 'In a separate visitor that walks the tree'],
  'The safe variant puts them only on the composite, trading uniformity for type safety.'),
 ('What is the main power of Composite?',
  'Clients never check leaf versus branch',
  ['It prevents cycles in the tree automatically', 'It removes the need for any recursion', 'It makes tree traversal much faster'],
  'Uniform treatment of parts and wholes simplifies client code.'),
 ('Which concerns need care when using Composite?',
  'Ownership, cycles, and traversal policy',
  ['Thread-safe lazy initialization of each leaf', 'Telescoping constructors', 'Broker registration'],
  'Trees can accidentally become graphs or share children.'),
 ('new BufferedReader(new InputStreamReader(new FileInputStream(f))) is an example of…',
  'Decorator',
  ['Adapter only', 'Composite', 'Abstract Factory'],
  'Buffering and decoding are added by wrapping, not by a BufferedDecodingFileReader subclass.'),
 ('Compress-then-encrypt produces a small file; encrypt-then-compress barely compresses. What does this show about decorators?',
  'Their order affects behavior',
  ['They must be applied in alphabetical order', 'Only one decorator can be applied', "They change the component's interface"],
  'Same wrappers, different order, different results.'),
 ("Why can't a client tell a decorated object from a plain one?",
  'It shares the interface and forwards calls',
  ['It is a subclass of the client class', 'It replaces and deletes the original object', 'The client never calls the wrapped object'],
  'Transparency is what lets decorators stack.'),
 ('What is a known cost of many small decorators?',
  'Harder debugging and unclear object identity',
  ['Class explosion from deep subclassing', "Loss of the component's original interface", 'Shared global mutable state'],
  'Deep wrapper stacks can be hard to trace.'),
 ('TripFacade.bookTrip() calls flight, hotel, car, payment, and email subsystems and rolls back on failure. Which pattern is this?',
  'Facade',
  ['Proxy', 'Adapter', 'Bridge'],
  'Facade gives a simpler entry point to a complex subsystem.'),
 ('Does a Facade forbid direct use of the subsystem?',
  'No; advanced users can still call it directly',
  ['Yes; every call must pass through the facade', 'Only for read operations, not writes', 'Only when used in a layered architecture'],
  'The facade covers the common cases without locking out the rest.'),
 ('What separates Facade from Adapter and Mediator?',
  'It simplifies an interface without adding features',
  ['It translates one interface into another', 'It coordinates peer objects that would otherwise talk to each other directly', 'It controls access to a single object'],
  'Adapter translates; Mediator coordinates colleagues; Facade simplifies.'),
 ('What risk does the chapter warn about for Facade?',
  'Growing into an all-knowing god object',
  ['Class explosion from subclassing', 'Shallow copies of subsystem state', 'Unbounded recursion between subsystems'],
  'A facade should stay a thin entry point.'),
 ('A document shows placeholders and loads each 8 MP image only when it scrolls into view. Which proxy type is this?',
  'Virtual proxy',
  ['Protection proxy', 'Remote proxy', 'Caching proxy'],
  'Virtual proxies defer expensive creation until needed.'),
 ("AdminServiceProxy checks the caller's role before forwarding. Which proxy type is this?",
  'Protection proxy',
  ['Virtual proxy', 'Remote proxy', 'Smart reference'],
  'Authorization lives in one wrapper instead of at the top of every method.'),
 ('Proxy and Decorator share a structure. What distinguishes them?',
  'Intent: access control versus added behavior',
  ['Proxy changes the interface; Decorator does not', 'Decorator is only used for I/O streams', 'A proxy must always be remote'],
  'Both wrap an object with the same interface; their purpose differs.'),
 ('Why must a remote proxy not hide latency and failure misleadingly?',
  'Callers must still handle delays and partial failure',
  ['Remote proxies are always faster than local calls', 'The compiler hides latency automatically', 'Remote calls through a proxy never fail'],
  'Preserving the interface should not pretend a remote call is local.'),
 ('Which is a smart-reference proxy responsibility?',
  'Reference counting or locking around the subject',
  ['Translating a legacy interface into the one clients expect', 'Summing the sizes of child nodes', 'Building an object step by step'],
  'Smart references add bookkeeping around access.'),
],
"short": [
 ('Explain how Bridge avoids class explosion with numbers.', ['m', 'n', 'abstraction', 'implementation', 'six'], 'Without Bridge, m abstractions × n implementations need m×n classes (3 shapes × 3 renderers = 9). With Bridge it is m + n (6), and a new renderer adds one class.'),
 ('Compare the transparent and safe Composite variants.', ['transparent', 'safe', 'add', 'leaf', 'type'], 'Transparent puts child methods on the component, so leaves must reject add() at run time. Safe puts them only on the composite, gaining type safety but requiring client type checks.'),
 ('Why does decorator order matter? Give an example.', ['order', 'compress', 'encrypt', 'wrap', 'different'], 'Each wrapper transforms what the next sees. Compress-then-encrypt gives a small ciphertext; encrypt-then-compress gives near-random bytes that barely compress.'),
 ('Distinguish Proxy from Decorator.', ['intent', 'access', 'responsibil', 'same interface', 'control'], 'Both wrap an object with the same interface. Proxy controls access (lazy loading, protection, remote); Decorator adds responsibilities.'),
 ('Distinguish Adapter from Facade.', ['translate', 'simplif', 'interface', 'subsystem', 'existing'], 'Adapter translates one interface into another that a client expects. Facade provides a simpler interface to a complex subsystem without changing what it can do.'),
]},

8: {"mcq": [
 ('What is the main goal of architecture evaluation?',
  'Informed decisions about risks and trade-offs',
  ['A pass/fail grade for the architect and the design team', 'Replacing testing', 'Approving the project budget'],
  'Evaluation is not a beauty contest; it exposes risks, sensitivity points, and trade-offs.'),
 ('When is the cheapest time to fix an architectural mistake?',
  'While the architecture is still a document',
  ['During user acceptance testing', 'After the first production incident shows the real weakness', 'During the annual audit'],
  'A shared database found in review is a design change; after launch it is a migration and a maintenance window.'),
 ('Which is a common side benefit of the first evaluation session?',
  'The documented architecture differs from real intent',
  ['The project budget is usually increased', 'All architectural risks are eliminated', 'Documentation is no longer needed once the evaluation has finished'],
  'Evaluation forces clarity and alignment.'),
 ('When should evaluation be repeated?',
  'When drivers or the architecture change',
  ['Never; once is enough', 'Only after production failures reveal a problem', 'Every day'],
  'Evaluate early and again when the basis for decisions changes.'),
 ('A question is only about how costly three planned changes will be. Which method fits best?',
  'SAAM',
  ['ATAM', 'ARID', 'STRIDE'],
  'SAAM focuses on scenario-based modifiability analysis.'),
 ('A half-designed shared component must be usable by other teams. Which method fits?',
  'ARID',
  ['ATAM', 'SAAM', 'A post-mortem'],
  'ARID reviews an intermediate design with its future users.'),
 ('A finished architecture has competing performance and security goals. Which method fits?',
  'ATAM',
  ['SAAM', 'ARID', 'Code review'],
  'ATAM analyzes trade-offs among multiple quality attributes.'),
 ('How does ATAM relate to SAAM?',
  'ATAM extended SAAM to all qualities and trade-offs',
  ['SAAM was created later to replace ATAM', 'They are two names for the same method', 'ATAM evaluates code while SAAM evaluates designs'],
  'SAAM came first; ATAM added trade-off analysis across qualities.'),
 ('In an ARID session, what do reviewers do that surfaces usability gaps quickly?',
  'Write pseudocode using the draft interface',
  ["Vote on the diagram's notation and colors", 'Load-test the component in production', 'Rewrite the component from scratch themselves'],
  'Active design review makes reviewers use the design, not just read it.'),
 ('The number of web-server replicas strongly affects availability and nothing else. It is a…',
  'Sensitivity point',
  ['Trade-off point', 'Non-risk', 'Risk theme'],
  'A sensitivity point affects one quality attribute.'),
 ('Raising message-bus encryption improves confidentiality but worsens latency. This is a…',
  'Trade-off point',
  ['Sensitivity point', 'Non-risk', 'Utility tree leaf'],
  'A trade-off point affects multiple qualities and needs an explicit decision.'),
 ('“The failover procedure has never been tested under load” is recorded as a…',
  'Risk',
  ['Non-risk', 'Sensitivity point', 'Business driver'],
  'Risks are potentially problematic decisions or gaps.'),
 ('Why record non-risks?',
  'They show which decisions were checked and sound',
  ['They pad the report to a required length', 'They list decisions that will become risks', 'They replace the utility tree in the report'],
  'A non-risk shows what was analyzed and why it is acceptable.'),
 ('Which ATAM phase widens participation to the broader stakeholder group?',
  'Phase 2',
  ['Phase 0', 'Phase 1', 'Phase 3'],
  'Phase 1 works with the core team; phase 2 involves the broader stakeholders; phase 3 delivers the report and follow-up.'),
 ('Which is an ATAM output?',
  'Risks, non-risks, sensitivity and trade-off points',
  ['The production source code, build scripts, and release notes', 'A signed contract with the vendor', 'A deployment script for each environment'],
  'Outputs also include analyzed approaches and prioritized scenarios.'),
 ('What does a lightweight ATAM keep?',
  'Scenario and trade-off reasoning, less ceremony',
  ['Only the final report, without any of the analysis behind it', 'Only the list of stakeholders', 'Nothing but the ATAM name'],
  'It trims process while retaining the core analysis.'),
 ('What is the structure of a utility tree?',
  'Utility → attribute → refinement → scenario',
  ['Goal → task → subtask → acceptance test', 'Module → class → method → line of code', 'Risk → owner → due date → status'],
  'Each leaf is a concrete scenario rated by importance and difficulty.'),
 ('Which utility tree leaves are analyzed first?',
  '(H,H): high importance, high difficulty',
  ['(L,L): low importance, low difficulty', '(H,L): high importance, low difficulty', '(L,H): low importance, high difficulty'],
  'They carry the most business value and the most architectural uncertainty.'),
 ('In a utility tree rating such as (H, M), what do the two letters represent?',
  'Business importance and technical difficulty',
  ['Implementation hours and maintenance cost', 'Cache hit rate and mean response time', 'Hazard severity and likelihood of attack'],
  'Ratings guide which scenarios get detailed analysis.'),
 ('Twelve scenarios are brainstormed but there is time to analyze four. How are they chosen?',
  'Stakeholders vote; top scenarios are analyzed',
  ['The architect picks the ones they prefer', 'They are taken in alphabetical order', 'The four easiest ones are chosen first'],
  'Prioritization focuses limited evaluation time.'),
 ('A failover is traced: detect 5 s, drain 3 s, promote 10 s, total 18 s against a 30 s target, with promotion untested. What should the report make visible?',
  'That the promotion step is an untested assumption',
  ['That the requirement is met, so nothing else matters', 'That the target should be raised', 'That heartbeats are unnecessary'],
  'Tracing a scenario through structures must show where evidence is weak.'),
 ('A team claims a 90% cache hit rate with no measurement. How should evaluators record it?',
  'As an assumption, with a measurement advised',
  ['As verified evidence of performance', 'As a non-risk, since caches are standard', 'As a trade-off point for the cache'],
  '"We believe" is an assumption; a load test result is evidence.'),
 ('What is a risk theme?',
  'Related risks grouped by the driver they threaten',
  ["A single untested component that threatens the system's availability", 'The visual style used in the final report', 'The list of stakeholders who attended'],
  'Themes such as "operational readiness is unaddressed" make findings actionable for management.'),
 ('What should each evaluation finding leave the review with?',
  'An owner and a follow-up date',
  ['A new architect assigned to the project', 'A deleted requirement', 'An automatic pass'],
  'Re-evaluation then checks whether mitigation changed the risk profile.'),
],
"short": [
 ('Distinguish a sensitivity point from a trade-off point with examples.', ['one quality', 'multiple', 'replica', 'encrypt', 'latency'], 'A sensitivity point affects one quality (replica count → availability). A trade-off point affects several (encryption level → confidentiality up, latency worse).'),
 ('When would you choose ATAM, SAAM, or ARID?', ['atam', 'saam', 'arid', 'modifiab', 'partial'], 'ATAM for finished architectures with competing qualities; SAAM for modifiability questions about planned changes; ARID for reviewing an intermediate design with its future users.'),
 ('Describe a utility tree and how its leaves are prioritized.', ['utility', 'quality attribute', 'refinement', 'scenario', 'importance'], 'Utility → quality attribute → refinement → concrete scenario. Each leaf is rated by business importance and architectural difficulty; (H,H) leaves are analyzed first.'),
 ('Why must evaluators separate assumptions from evidence?', ['assumption', 'evidence', 'measure', 'load test', 'believe'], '"We believe it is fast enough" is an assumption; a load-test result is evidence. Blurring them hides risk, so assumptions are flagged with recommended measurements.'),
 ('What is a risk theme and why is it useful?', ['group', 'related', 'business driver', 'theme', 'management'], 'A risk theme groups related risks and maps them to the business driver they endanger, which makes findings actionable for management.'),
]},

9: {"mcq": [
 ('Why is one 90-page document for both new developers and operations a poor choice?',
  'Each audience needs different content, so neither is served',
  ['Long documents cannot be kept in version control alongside the source code', 'Operations teams do not read design documents', 'Developers only need the source code to work'],
  'Developers need module views and build steps; operations needs deployment, monitoring, and failure modes.'),
 ('The retry policy is written once in a cross-cutting section and referenced from each view. What principle does this apply?',
  'A single source of truth, no repetition',
  ['Recording the rationale for decisions', 'Giving each view a primary presentation', 'Adding a variability guide per view'],
  'A change cannot then leave three views disagreeing.'),
 ('When is documentation ready to be declared done?',
  'Once its intended readers find it fit to use',
  ['When every UML diagram type is included', 'When it reaches the target page count', 'When the lead architect has signed it'],
  'Documentation nobody can act on is not documentation.'),
 ('Which set lists the parts of a view document?',
  'Presentation, catalog, context, variability, rationale',
  ['Title, author, date, reviewers, and signature', 'Classes, methods, fields, code comments, and the unit tests for each', 'Risks, owners, dates, priorities, and status'],
  'Each part answers a different reader question about the view.'),
 ('“NotificationService provides send(Notification), requires TemplateStore, may not be called synchronously from checkout.” This belongs in the…',
  'Element catalog',
  ['Primary presentation', 'Glossary', 'Documentation roadmap'],
  'The catalog defines responsibilities, interfaces, and relationships of each element.'),
 ('“Identity provider is a build-time choice among LDAP, Azure AD, or Okta.” This belongs in the…',
  'Variability guide',
  ['Context diagram', 'Element catalog', 'ADR log only'],
  'Variability guides record permitted options and when they are bound.'),
 ("What does a view's context section show?",
  "The view's boundary and external dependencies",
  ['The history of the project so far', "The team's schedule, availability, and on-call rotation for the view", 'Every class in the system in detail'],
  'Context places the view within its surroundings.'),
 ('Which approach separates conceptual, module, execution, and code views?',
  'Siemens Four-Views',
  ['Kruchten 4+1', 'C4', 'Software Cost Reduction'],
  '4+1 uses logical, process, development, physical, and scenarios.'),
 ('The C4 model nests which levels?',
  'Context, container, component, and code',
  ['Class, collaboration, component, cloud', 'Concept, control, cache, commit', 'Client, connector, core, controller'],
  'C4 is a widely used modern variant, often a fast fit for microservices teams.'),
 ('A table maps the billing module to the billing-api container on two nodes. Why does this matter?',
  'It keeps module and deployment views consistent',
  ['It replaces the need for a deployment view', 'It is required only when using RUP', 'It serves as the project glossary'],
  'Consistency and mappings prevent contradictory documentation.'),
 ('How should views be chosen?',
  'From stakeholder concerns, not every possible model',
  ['By producing every UML diagram type available', 'By copying the set used in another project', "By using the modeling tool's default templates"],
  'Each selected view should answer a real stakeholder question.'),
 ('“All service errors return RFC 7807 problem details and retries use exponential backoff with jitter.” Where does this belong?',
  'In a cross-cutting concepts section',
  ["In one component's element catalog", 'Only in the code comments', 'In the variability guide'],
  'It belongs to no single view but constrains all of them.'),
 ('“Student” meant applicant, enrolled learner, and debtor to three offices. Which artifact solves this?',
  'A glossary',
  ['A deployment view', 'A variability guide', 'A sequence diagram'],
  'A glossary prevents one word meaning different things to different teams.'),
 ('What is the role of the documentation roadmap?',
  'Telling readers where to look for each question',
  ['Listing release dates for each version', 'Showing the network topology of the system', 'Recording alternatives that were rejected'],
  'It is the entry point that makes a large package usable.'),
 ('Which documentation element preserves decision context and consequences?',
  'ADRs',
  ['The acronym list', 'The element catalog', 'The primary presentation'],
  'ADRs capture context, decision, alternatives, consequences, and status.'),
 ('An arrow from A to B could mean “calls”, “data flows to”, “depends on”, or “sends a message to”. What fixes this?',
  'A key that defines each line style',
  ['Adding more arrows between boxes', 'Using brighter, distinct colors', 'Removing all labels from arrows'],
  'Without a key, four readers form four architectures.'),
 ('Instead of one diagram with 60 services, a team ships a 6-box context diagram and six focused container diagrams. What principle is applied?',
  'One diagram per question, at a readable scope',
  ['Automated diagrams are always the better choice', 'A diagram should show everything at once', 'Diagrams should be replaced by prose only'],
  'A diagram that answers five questions answers none well.'),
 ('What is the limit of automatically generated diagrams?',
  "They stay fresh but can't capture intent",
  ['They are always inaccurate and misleading', 'They cannot be stored in version control', 'They replace all hand-written rationale'],
  'Generated dependency graphs show facts; why payments must not call reporting is written by hand.'),
 ('Why does documentation outside the definition of done go stale?',
  'Nothing forces it to change when code changes',
  ['Documentation files expire automatically', 'Reviewers delete old documents each release', 'Version control cannot store documentation'],
  'Making documentation part of done keeps it current.'),
 ('Architecture docs and PlantUML sources live in the repo and are reviewed in the same pull request as the code. This is…',
  'Docs as code',
  ['A glossary', 'Reverse engineering', 'A variability guide'],
  'An undocumented structural change then fails review.'),
 ('Which facts should generated artifacts carry?',
  'The fast-changing ones, like dependency graphs',
  ['The rationale behind key design decisions', 'The glossary definitions of domain terms', "The stakeholders' priorities and concerns"],
  'Generated facts stay fresh for free; rationale must be written by people.'),
 ('Which describes useful documentation?',
  'Concise to maintain, detailed enough to act on',
  ['As long and exhaustive as possible so nothing is ever missed', 'Diagrams only, with no written text', 'Written once and then never changed'],
  'Balance maintainability with actionability.'),
],
"short": [
 ('List the parts of a view document and what each provides.', ['primary presentation', 'element catalog', 'context', 'variability', 'rationale'], 'Primary presentation (diagram plus key), element catalog (responsibilities and interfaces), context (boundary and external dependencies), variability guide (permitted options), and rationale (why, and rejected alternatives).'),
 ('Why does every diagram need a key? Give an example.', ['key', 'arrow', 'meaning', 'notation', 'ambiguous'], 'Boxes and lines are ambiguous; an arrow could mean calls, data flow, dependency, or messaging. A key fixes one meaning so readers share one architecture.'),
 ('What is a cross-cutting concept? Give an example.', ['cross-cutting', 'all views', 'retry', 'error', 'backoff'], 'A rule that belongs to no single view but constrains all of them, such as all service errors using RFC 7807 and retries using exponential backoff with jitter.'),
 ('Explain how to keep architecture documentation living.', ['docs as code', 'pull request', 'definition of done', 'generated', 'version'], 'Version docs with code, review them in the same pull request, make them part of the definition of done, and generate the fast-changing facts while writing rationale by hand.'),
 ('Compare 4+1, Siemens Four-Views, and C4.', ['logical', 'conceptual', 'container', 'context', 'execution'], '4+1: logical, process, development, physical plus scenarios. Siemens: conceptual, module, execution, code. C4: context, container, component, code.'),
]},
}
