"""CYS403 Chapter 1 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, flow, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 1
TITLE = "Security Risk Management, Governance and Control"
SLUG = "security-risk-management-governance-and-control"
SUMMARY = "why cyber risk is a business issue, Val IT, Risk IT and COBIT, the CIA triad, business-driven security, cybersecurity governance, security policy, and the three levels of security planning."
HOOK = "Security Is a Business Decision:"
GRADIENT = "Risk, Governance and Policy"
SUB = "Why every organization must treat cyber risk as a business priority, how governance frameworks connect IT value and IT risk, and how policy turns management intent into enforceable action."
CHIPS = ["Cyber Risk", "Val IT · Risk IT · COBIT", "CIA Triad", "Governance", "Policy Infrastructure", "Security Planning"]

SECTIONS = [
    ("Why Care", "Why Care About Cyber Risk?", [
        p("Modern enterprises are <strong>dependent on automation and integration</strong>. Because systems are so connected, cyber risk cannot be managed inside a single IT silo: it has to <strong>cross IT silos</strong> and be <strong>integrated with the organization's existing levels of risk management</strong>."),
        p("The problem is a knowledge gap. According to a Nasdaq report, <strong>91% of board members at the most vulnerable companies cannot interpret a cybersecurity report</strong>. That gap between executives and IT must be bridged:"),
        ul("First, identify <strong>why cyber risk should be a business priority</strong> for any executive.",
           "The goal is <em>not</em> to turn CEOs and CFOs into technologists, but to help the business <strong>adapt to the digital landscape</strong> it operates in.",
           "It requires effort from <strong>both management and IT</strong> to find middle ground in a relationship that has often been difficult."),
        h3("Risk and value are two sides of the same coin", "b"),
        p("Risk is <strong>inherent to all enterprises</strong>. Enterprises earn their return <em>by taking risks</em>, so trying to eliminate every risk can remove the very risks that drive profit. Organizations must make sure that <strong>opportunities for value creation are not missed</strong> by trying to eliminate all risk. This is why guidance was needed on how to <strong>manage and capitalize on risk</strong> effectively."),
        tip("warn", "Common misconception", "The aim of risk management is not zero risk. A business that avoids all risk also avoids its opportunities. The aim is to take the <em>right</em> risks and manage them to an acceptable level."),
    ]),
    ("Frameworks", "IT Value, IT Risk and COBIT", [
        p("Three ISACA frameworks work together to connect IT investment, IT risk, and IT governance:"),
        defs(("Val IT", "A <strong>governance framework</strong> used to <strong>create business value from IT investments</strong>."),
             ("Risk IT", "Provides an <strong>end-to-end, comprehensive view of all risks</strong> related to the use of information technology."),
             ("COBIT", "Gives management and business process owners an <strong>IT governance model</strong> that helps deliver value from IT <em>and</em> understand and manage the risks associated with IT.")),
        p("<strong>Risk IT complements and extends COBIT and Val IT</strong>, making a more complete IT governance guidance resource."),
        h3("Where IT risk fits in", "c"),
        p("Before Risk IT, available standards and frameworks were either too <strong>generic enterprise-risk-management-oriented</strong> or too <strong>IT-security-oriented</strong>. There was no comprehensive framework connecting the two, and Risk IT filled that gap."),
        mnemonic("Which framework does what?", f"{key('V-R-C')}: <strong>V</strong>al IT = <em>Value</em> from IT investments; <strong>R</strong>isk IT = <em>Risk</em> of using IT; <strong>C</strong>OBIT = the overall <em>Control/governance</em> model that covers both value and risk."),
    ]),
    ("Principles", "The Cybersecurity Triad and Business-Driven Security", [
        p("Everything cybersecurity protects can be described by the three properties of the <strong>cybersecurity (CIA) triad</strong>:"),
        defs(("Confidentiality", "Information is disclosed only to those who are authorized to see it."),
             ("Integrity", "Information and systems are accurate, complete, and protected from unauthorized modification."),
             ("Availability", "Information and systems are accessible to authorized users when they are needed.")),
        h3("Business-driven security", "d"),
        p("Business-driven security means <strong>creating a security strategy that aligns with the business's needs</strong>. Security exists to support the organization, not the other way round."),
        h3("Organizational and business requirements", "a"),
        ul("<strong>Focus on the mission</strong> of the organization.",
           "<strong>Each type of organization has differing security requirements</strong>: a hospital, a bank, and a university protect different things.",
           "<strong>Security must make sense and be cost effective</strong>."),
        h3("Complete security solutions", "b"),
        vs(("Functional requirements", "Define the <strong>security behavior</strong> of the control measure. They are <strong>selected based on the risk management process</strong>.", "a"),
           ("Assurance requirements", "Provide <strong>confidence that the security function is performing as expected</strong>. Assurance is a <strong>critical part</strong> of the security program.", "c")),
        tip("exam", "Functional vs assurance", "Functional = <em>what the control does</em>. Assurance = <em>proof that it actually does it</em>. A firewall rule is functional; an audit showing the rule works is assurance."),
    ]),
    ("Management", "Cybersecurity Management and Governance", [
        p("<strong>Cybersecurity management</strong> is everything an organization does to protect its information systems and computer networks from cyber attacks, intrusions, malware, and various types of data breaches."),
        flow("Cybersecurity Management", "Governance", "Risk Management"),
        p("Cybersecurity management includes two parts: <strong>governance</strong> and <strong>risk management</strong>."),
        h3("Cybersecurity governance", "c"),
        ul("Cybersecurity governance is an <strong>integral part of overall corporate governance</strong>.",
           "It must be <strong>fully integrated into overall risk analysis and management</strong>.",
           "It ensures that the IT infrastructure <strong>meets all requirements</strong>, <strong>supports the strategies and objectives of the company</strong>, and <strong>includes service level agreements (SLAs) if outsourced</strong>."),
        vs(("Governance", "Sets <strong>direction and oversight</strong>: what the organization should achieve, and holds management accountable for it.", "a"),
           ("Management", "Plans and <strong>executes the activities</strong> that achieve that direction day to day.", "d")),
        h3("Security blueprints", "e"),
        p("Security blueprints <strong>provide a structure for organizing requirements and solutions</strong>, ensure that <strong>security is considered holistically</strong>, and are used <strong>to identify and design security requirements</strong>."),
    ]),
    ("Policy", "The Policy Environment and Policy Infrastructure", [
        p("At the top of the policy hierarchy is the <strong>overarching organizational policy</strong>, also called <strong>management's security statement</strong>. It does not exist in a vacuum: it is shaped by the environment around it."),
        table(["Environmental influence", "Why it shapes policy"],
              ["Laws", "Legal obligations the organization must obey."],
              ["Regulations", "Industry or government rules (e.g. data protection)."],
              ["Organizational goals", "Long-term aims the policy must support."],
              ["Organizational objectives", "Specific, measurable targets."],
              ["Shareholders' interests", "Owners expect assets and reputation to be protected."]),
        h3("Policy infrastructure", "b"),
        steps(("High-level policies are interpreted into functional policies", "The overarching statement is too broad to act on, so it is broken down into topic-specific functional policies."),
              ("Functional policies create the foundation", "Derived from the overarching policy, they are the foundation for procedures, standards, and baselines that accomplish the objectives."),
              ("Policies gain credibility through top management buy-in", "Without visible executive support, policies are ignored.")),
        h3("Examples of functional policies", "c"),
        table(["#", "Functional policy"], ["1", "Data classification"], ["2", "Certification and accreditation"], ["3", "Access control"],
              ["4", "Outsourcing"], ["5", "Remote access"], ["6", "Acceptable mail and Internet usage"], ["7", "Privacy"],
              ["8", "Dissemination control"], ["9", "Sharing control"]),
        tip("info", "Example", "An <strong>Internet usage policy</strong> is a functional policy: it applies the security statement to one topic (how employees may use the Internet) and is then enforced through standards and procedures."),
    ]),
    ("Implementation", "Standards, Procedures, Guidelines and Baselines", [
        p("<strong>Standards, procedures, baselines, and guidelines turn management objectives and goals (functional policies) into enforceable actions for employees.</strong>"),
        flow("Security statement", "Functional policies", "Standards · Procedures · Baselines · Guidelines"),
        table(["Element", "Definition", "Examples"],
              ["<strong>Standards</strong> (local)", "Adoption of <strong>common hardware and software mechanisms and products</strong> throughout the enterprise.", "Desktop, anti-virus, firewall"],
              ["<strong>Procedures</strong>", "<strong>Step-by-step actions</strong> that must be followed to accomplish a task.", "How to create a user account"],
              ["<strong>Guidelines</strong>", "<strong>Recommendations</strong> for product implementations, procurement, and planning.", "ISO 17799, Common Criteria, ITIL"],
              ["<strong>Baselines</strong>", "<strong>Benchmarks</strong> that ensure a <strong>minimum level of security configuration</strong> across implementations and systems; establish consistent implementation; <strong>platform unique</strong>.", "VPN setup, IDS configuration, password rules"]),
        mnemonic("Tell them apart", f"{key('Standards = WHAT product')}, {key('Procedures = HOW, step by step')}, {key('Guidelines = SHOULD (recommended)')}, {key('Baselines = MINIMUM configuration')}. Only guidelines are optional recommendations."),
        tip("warn", "Classic trap", "ISO 17799, Common Criteria, and ITIL are listed on the slides as examples of <strong>guidelines</strong>, not standards. Password rules and IDS configuration are <strong>baselines</strong>."),
    ]),
    ("Planning", "Three Levels of Security Planning", [
        table(["Level", "Time frame", "Focus", "Example"],
              ["<strong>Strategic</strong>", "Long term", "High-level, long-range organizational requirements", "Overall security policy"],
              ["<strong>Tactical</strong>", "Medium term", "Events that affect the whole organization", "Functional plans"],
              ["<strong>Operational</strong>", "Short term", "Very specific actions reacting to an incident (fighting fires at the keyboard level); directly affects how objectives are accomplished", "Responding to a specific incident"]),
        flow("Strategic (long)", "Tactical (medium)", "Operational (short)"),
        mnemonic("S-T-O", f"{key('Strategy → Tactics → Operations')}: from the boardroom's long view, to organization-wide plans, down to the keyboard-level response."),
    ]),
    ("Big Idea", "Security Transcends Technology", [
        p("The chapter closes with its key message: <strong>security transcends technology</strong>. Firewalls and anti-virus are not enough on their own; security depends on business alignment, governance, policy, people, and above all <strong>risk management</strong>, which the rest of the course builds on."),
        tip("good", "Link to the next chapters", "Chapter 2 defines risk precisely, Chapter 3 studies threats and vulnerabilities, and Chapters 4–6 turn them into a full risk assessment."),
    ]),
]

TIPS = [
    ("91% statistic", "91% of board members at the most vulnerable companies cannot interpret a cybersecurity report (Nasdaq). It shows the executive–IT knowledge gap."),
    ("Risk and value", "Risk and value are two sides of the same coin. Don't eliminate all risk: you would also eliminate value creation."),
    ("V-R-C frameworks", "Val IT = value from IT investments; Risk IT = end-to-end view of IT risk; COBIT = IT governance model. Risk IT complements and extends COBIT and Val IT."),
    ("Management = governance + RM", "Cybersecurity management includes governance and risk management. Governance is an integral part of corporate governance."),
    ("Functional vs assurance", "Functional requirements define security behavior (chosen by risk management); assurance requirements give confidence it works."),
    ("Policy order", "Security statement → functional policies → standards, procedures, baselines, guidelines. Policies gain credibility through top management buy-in."),
    ("Guidelines vs baselines", "Guidelines are recommendations (ISO 17799, Common Criteria, ITIL). Baselines are minimum configurations (VPN setup, IDS config, password rules)."),
    ("Planning levels", "Strategic = long term (security policy); tactical = medium term (functional plans); operational = short term, keyboard-level incident response."),
]

QUICK = [
    ["Why care about cyber risk", "Enterprises depend on automation/integration; risk must cross IT silos and integrate with existing risk management."],
    ["Board knowledge gap", "91% of board members at the most vulnerable companies can't interpret a cybersecurity report."],
    ["Risk vs value", "Two sides of the same coin; enterprises achieve return by taking risks."],
    ["Val IT", "Governance framework to create business value from IT investments."],
    ["Risk IT", "End-to-end, comprehensive view of all IT-related risks; extends COBIT and Val IT."],
    ["COBIT", "IT governance model for delivering value from IT and managing IT risks."],
    ["CIA triad", "Confidentiality, integrity, availability."],
    ["Business-driven security", "Security strategy aligned with business needs; mission-focused and cost effective."],
    ["Functional requirements", "Define security behavior of a control; selected by risk management."],
    ["Assurance requirements", "Confidence that the security function performs as expected."],
    ["Cybersecurity management", "Protecting systems and networks from attacks, intrusions, malware, breaches; includes governance + risk management."],
    ["Cybersecurity governance", "Part of corporate governance; IT meets requirements, supports strategy, includes SLAs if outsourced."],
    ["Security blueprints", "Structure for organizing requirements and solutions; holistic security design."],
    ["Overarching policy", "Management's security statement; shaped by laws, regulations, goals, objectives, shareholders."],
    ["Functional policies", "Data classification, C&amp;A, access control, outsourcing, remote access, mail/Internet use, privacy, dissemination, sharing."],
    ["Standards / procedures", "Common mechanisms and products / step-by-step actions."],
    ["Guidelines / baselines", "Recommendations (ISO 17799, CC, ITIL) / minimum security configuration (VPN, IDS, passwords)."],
    ["Planning levels", "Strategic (long), tactical (medium), operational (short)."],
]

BRANCHES = [
    ("Why Cyber Risk Matters", "Cyber risk is a business priority, not just an IT problem.", [
        ("Dependence on Automation", "Key Idea", "Enterprises depend on automation and integration, so cyber risk must cross IT silos and integrate with existing risk management practices."),
        ("The Board Knowledge Gap", "Key Fact", "91% of board members at the most vulnerable companies can't interpret a cybersecurity report (Nasdaq).", "The goal is not to make executives technologists, but to help the business adapt; it takes effort from both management and IT."),
        ("Risk and Value", "Key Idea", "Risk and value are two sides of the same coin. Risk is inherent in every enterprise.", "Trying to eliminate all risk can remove the very risks that drive profit and miss value-creation opportunities."),
    ]),
    ("Governance Frameworks", "Val IT, Risk IT and COBIT work together.", [
        ("Val IT", "Framework", "A governance framework for creating business value from IT investments."),
        ("Risk IT", "Framework", "An end-to-end, comprehensive view of all risks related to IT use. It complements and extends COBIT and Val IT."),
        ("COBIT", "Framework", "An IT governance model helping management deliver value from IT and understand and manage IT risks."),
        ("Where IT Risk Fits", "Key Idea", "Earlier standards were either generic ERM-oriented or IT-security-oriented; Risk IT bridges the two."),
    ]),
    ("Security Principles", "", [
        ("CIA Triad", "Principle", "<strong>Confidentiality</strong>, <strong>integrity</strong>, and <strong>availability</strong>: the three properties cybersecurity protects."),
        ("Business-Driven Security", "Principle", "A security strategy aligned with business needs: focused on the mission, different per organization, cost effective."),
        ("Functional Requirements", "Solution", "Define the security behavior of a control measure; selected through the risk management process."),
        ("Assurance Requirements", "Solution", "Provide confidence that the security function performs as expected; a critical part of the program."),
    ]),
    ("Management and Governance", "Cybersecurity management = governance + risk management.", [
        ("Cybersecurity Management", "Definition", "Everything an organization does to protect systems and networks from attacks, intrusions, malware, and data breaches."),
        ("Cybersecurity Governance", "Definition", "An integral part of corporate governance, fully integrated into risk management.", "Ensures IT meets requirements, supports company strategy, and includes SLAs if outsourced."),
        ("Governance vs Management", "Comparison", "Governance sets direction and oversight; management plans and executes the work."),
        ("Security Blueprints", "Tool", "Structure for organizing requirements and solutions so security is considered holistically."),
    ]),
    ("Security Policy", "From management's statement to enforceable action.", [
        ("Overarching Policy", "Policy", "Management's security statement, shaped by laws, regulations, organizational goals and objectives, and shareholders' interests."),
        ("Policy Infrastructure", "Policy", "High-level policies become functional policies, which found procedures, standards, and baselines. Policies gain credibility through top management buy-in."),
        ("Functional Policy Examples", "Policy", "Data classification, certification and accreditation, access control, outsourcing, remote access, acceptable mail/Internet use, privacy, dissemination control, sharing control."),
        ("Standards and Procedures", "Implementation", "<strong>Standards</strong>: common hardware/software mechanisms (desktop, anti-virus, firewall). <strong>Procedures</strong>: step-by-step actions for a task."),
        ("Guidelines and Baselines", "Implementation", "<strong>Guidelines</strong>: recommendations (ISO 17799, Common Criteria, ITIL). <strong>Baselines</strong>: minimum, platform-unique security configuration (VPN, IDS, password rules)."),
    ]),
    ("Security Planning Levels", "", [
        ("Strategic", "Level", "Long term; high-level, long-range requirements. Example: overall security policy."),
        ("Tactical", "Level", "Medium term; events affecting the whole organization. Example: functional plans."),
        ("Operational", "Level", "Short term; specific reaction to an incident, fighting fires at the keyboard level."),
        ("Security Transcends Technology", "Big Idea", "Security depends on business alignment, governance, policy, and risk management, not technology alone."),
    ]),
]

QUIZ = {
    "mcq": [
        ("According to the Nasdaq report cited in the slides, what percentage of board members at the most vulnerable companies cannot interpret a cybersecurity report?",
         ["51%", "71%", "91%", "99%"], 2, "91% of board members at the most vulnerable companies cannot interpret a cybersecurity report, which shows the executive–IT knowledge gap.", "Why care"),
        ("Which framework is described as a governance framework used to create business value from IT investments?",
         ["Risk IT", "Val IT", "COBIT", "ITIL"], 1, "Val IT focuses on value creation from IT investments; Risk IT covers IT risk; COBIT is the overall IT governance model.", "Frameworks"),
        ("Which framework provides an end-to-end, comprehensive view of all risks related to the use of IT?",
         ["Risk IT", "Val IT", "ISO 17799", "Common Criteria"], 0, "Risk IT gives the end-to-end view of IT-related risk and complements and extends COBIT and Val IT.", "Frameworks"),
        ("What is the relationship between Risk IT, COBIT and Val IT?",
         ["Risk IT replaces COBIT and Val IT", "COBIT is a subset of Risk IT", "Risk IT complements and extends COBIT and Val IT", "The three frameworks are unrelated"], 2,
         "The slides state that Risk IT complements and extends COBIT and Val IT to make a more complete IT governance resource.", "Frameworks"),
        ("Why is it a mistake for an enterprise to try to eliminate all risk?",
         ["Risk elimination is illegal", "It may eliminate the very risks that drive profit and value creation", "Risk cannot be measured", "Insurance always covers every loss"], 1,
         "Enterprises achieve return by taking risks. Eliminating all risk means missing opportunities for value creation.", "Risk and value"),
        ("Cybersecurity management includes which two components?",
         ["Auditing and encryption", "Governance and risk management", "Firewalls and anti-virus", "Planning and procurement"], 1,
         "The slides define cybersecurity management as including governance and risk management.", "Management"),
        ("Which requirement type provides confidence that a security function is performing as expected?",
         ["Functional requirements", "Business requirements", "Assurance requirements", "Baseline requirements"], 2,
         "Assurance requirements provide confidence that the security function works as expected; functional requirements define its behavior.", "Security solutions"),
        ("A company requires every server to use the same approved anti-virus product. This is an example of a:",
         ["Standard", "Procedure", "Guideline", "Strategic plan"], 0,
         "Standards mean adopting common hardware and software mechanisms and products throughout the enterprise, such as anti-virus and firewalls.", "Implementation"),
        ("ISO 17799, Common Criteria and ITIL are given in the slides as examples of:",
         ["Standards", "Baselines", "Procedures", "Guidelines"], 3,
         "Guidelines are recommendations for implementation, procurement, and planning. The slides list ISO 17799, Common Criteria, and ITIL as examples.", "Implementation"),
        ("Password rules, VPN setup and IDS configuration that set a minimum level of security configuration are examples of:",
         ["Baselines", "Guidelines", "Functional policies", "Security statements"], 0,
         "Baselines are benchmarks that ensure a minimum, platform-unique security configuration across systems.", "Implementation"),
        ("Which planning level focuses on very specific actions to react to an incident, fighting fires at the keyboard level?",
         ["Strategic", "Tactical", "Operational", "Governance"], 2,
         "Operational planning is short term and deals with specific reactions to incidents.", "Planning levels"),
        ("Which of the following is NOT listed in the slides as an example of a functional policy?",
         ["Remote access", "Data classification", "Firewall rule base configuration", "Privacy"], 2,
         "Functional policies include data classification, C&A, access control, outsourcing, remote access, mail/Internet use, privacy, dissemination, and sharing control. A firewall rule base is a technical configuration, not a functional policy.", "Policy"),
        ("According to the slides, how do policies gain credibility?",
         ["Through strong encryption", "Through top management buy-in", "Through employee voting", "Through vendor certification"], 1,
         "Policies gain credibility when top management visibly supports them.", "Policy"),
    ],
    "tf": [
        ("Cybersecurity governance is an integral part of overall corporate governance.", True, "The slides state that cybersecurity governance is an integral part of corporate governance.", "Governance"),
        ("The goal of bridging the executive–IT gap is to turn CEOs and CFOs into technologists.", False, "The goal is not to turn business leaders into technologists, but for businesses to adapt to the digital landscape.", "Why care"),
        ("Procedures are step-by-step actions that must be followed to accomplish a task.", True, "That is the slide definition of procedures.", "Implementation"),
        ("Guidelines are mandatory rules that every employee must follow exactly.", False, "Guidelines are recommendations. Standards, procedures, and baselines are the enforceable elements.", "Implementation"),
        ("Functional requirements of a security solution are selected based on the risk management process.", True, "Functional requirements define the control's security behavior and are selected through risk management.", "Security solutions"),
        ("Every type of organization has the same security requirements.", False, "Each type of organization has differing security requirements, so security must fit its mission.", "Business requirements"),
        ("Tactical security planning is long term and focuses on the overall security policy.", False, "That describes strategic planning. Tactical planning is medium term (functional plans).", "Planning levels"),
        ("Governance should ensure that outsourced IT infrastructure includes service level agreements.", True, "Governance ensures IT meets requirements, supports strategy, and includes SLAs if outsourced.", "Governance"),
    ],
    "fill": [
        ("The overarching organizational policy is also called management's security ________.", "statement", ["statement"], "The overarching policy is management's security statement.", "Policy"),
        ("Security ________ provide a structure for organizing requirements and solutions so security is considered holistically.", "blueprints", ["blueprint"], "Security blueprints organize requirements and solutions.", "Governance"),
        ("________ planning is medium term and focuses on events that affect the whole organization.", "Tactical", ["tactical"], "Tactical planning covers functional plans.", "Planning levels"),
        ("The three properties of the cybersecurity triad are confidentiality, integrity and ________.", "availability", ["availability"], "CIA = confidentiality, integrity, availability.", "CIA triad"),
        ("Risk and ________ are two sides of the same coin.", "value", ["value"], "The slides pair risk with value creation.", "Risk and value"),
    ],
    "match": [
        ("Match each policy implementation element to its description.", "Implementation", [
            ("Standards", "Common hardware and software products adopted enterprise-wide"),
            ("Procedures", "Step-by-step actions to accomplish a task"),
            ("Guidelines", "Recommendations such as ISO 17799 or ITIL"),
            ("Baselines", "Minimum security configuration across systems"),
            ("Functional policies", "Topic-specific policies derived from the security statement"),
        ]),
        ("Match each framework or planning level to its role.", "Frameworks and planning", [
            ("Val IT", "Create business value from IT investments"),
            ("Risk IT", "End-to-end view of all IT-related risks"),
            ("COBIT", "IT governance model covering value and risk"),
            ("Strategic plan", "Long-term, high-level organizational requirements"),
            ("Operational plan", "Short-term reaction to a specific incident"),
        ]),
    ],
    "short": [
        ("Explain why cyber risk should be treated as a business priority rather than only an IT issue.",
         ["automation", "integration", "silos", "board", "value", "business"],
         "Enterprises depend on automation and integration, so cyber risk affects the whole business and must cross IT silos and integrate with existing risk management. Board members often cannot interpret cybersecurity reports (91% at the most vulnerable companies), so the gap between executives and IT must be bridged. Risk and value are linked: managing risk well protects value without missing opportunities.",
         "Why care"),
        ("Describe the policy infrastructure, from management's security statement down to enforceable actions.",
         ["statement", "functional", "standards", "procedures", "baselines", "management"],
         "The overarching policy (management's security statement) is shaped by laws, regulations, goals, objectives, and shareholders' interests. It is interpreted into functional policies such as access control or remote access. Functional policies form the foundation for standards, procedures, baselines, and guidelines, which turn objectives into enforceable actions. Policies gain credibility through top management buy-in.",
         "Policy"),
        ("Scenario: A hospital adopts the same firewall security settings as a retail shop because it is cheap. Using business-driven security, explain the problem.",
         ["mission", "requirements", "differ", "cost", "align", "business"],
         "Business-driven security aligns the security strategy with the organization's own business needs. Each type of organization has differing security requirements: a hospital protects patient data and life-critical availability, unlike a shop. Security must focus on the organization's mission and be cost effective for that mission, not merely cheap.",
         "Business-driven security"),
    ],
}
