"""CYS403 Chapter 2 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, flow, formula, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 2
TITLE = "Risk Management Fundamentals"
SLUG = "risk-management-fundamentals"
SUMMARY = "the definition of risk, assets, threats, vulnerabilities and residual risk, the five risk management steps and risk register, quantitative (SLE, ARO, ALE) and qualitative analysis, risk mitigation options, countermeasure selection, and the five types of security controls."
HOOK = "Measuring the Unknown:"
GRADIENT = "Risk Management Fundamentals"
SUB = "What risk really is, how to identify and rank it, how to put a price on it with SLE and ALE, and how to choose the right response and controls."
CHIPS = ["Risk Terms", "Risk Register", "SLE · ARO · ALE", "Qualitative Matrix", "Mitigation Options", "Control Types"]

SECTIONS = [
    ("Definition", "What Is Risk?", [
        p("<strong>Risk is the possibility of losing something of value.</strong> Put another way, <strong>risk is the probability that a threat will turn into a disaster</strong>."),
        p("A <strong>vulnerability (weakness)</strong> and a <strong>hazard</strong> are not dangerous when taken separately. But when they <strong>come together</strong>, they become a risk: the probability that a disaster will happen."),
        h3("The NIST SP 800-30 definition", "b"),
        tip("exam", "Memorize this definition", "Risk is <strong>a function of the likelihood</strong> of a given <strong>threat-source's exercising a particular potential vulnerability</strong>, and the resulting <strong>impact</strong> of that adverse event on the organization's assets. (NIST SP 800-30)"),
        formula("Risk = Probability (threat, vulnerability, impact)"),
    ]),
    ("Terminology", "Key Terms and Concepts", [
        defs(("Asset", "Something that is <strong>valued by the organization</strong> to accomplish its goals and objectives."),
             ("Threat", "<strong>Any potential danger</strong> to information or an information system."),
             ("Attack", "<strong>Any actual danger</strong> to information or an information system."),
             ("Threat agent", "Anything that has the <strong>potential</strong> of causing a threat."),
             ("Attacker", "Anything that is the <strong>actual cause</strong> of an attack."),
             ("Vulnerability", "Any <strong>weakness that could be exploited</strong>. Vulnerabilities exist in every IT system, product, and application.")),
        defs(("Exposure", "An <strong>opportunity</strong> for a threat to cause loss."),
             ("Countermeasures and safeguards", "Measures and actions <strong>taken to protect systems</strong>."),
             ("Residual risk", "The amount of risk <strong>remaining after</strong> countermeasures and safeguards are applied.")),
        mnemonic("Potential vs actual", f"{key('Threat → Attack')} and {key('Threat agent → Attacker')}: the first word in each pair is <em>potential</em>, the second is <em>actual</em>."),
        h3("Examples of threats", "c"),
        table(["", ""], ["Unauthorized access", "Human errors"], ["Hardware failure", "Neighboring hazards"],
              ["Utility failure", "Tampering"], ["Loss of key personnel", "Dissatisfied employees"]),
    ]),
    ("Risk Factors", "Risk Factors and Residual Risk", [
        p("Risk exists where three factors overlap: <strong>threats</strong>, <strong>assets</strong>, and <strong>vulnerabilities</strong>. Remove any one of them and there is no risk."),
        flow("Threats", "exploit Vulnerabilities", "in Assets = RISK"),
        p("Once safeguards are applied, the overlap shrinks but rarely disappears. What is left is the <strong>residual risk</strong>, which should be reduced to an <strong>acceptable level</strong>."),
        tip("warn", "Residual risk is never zero", "Controls reduce risk; they do not eliminate it. Management must decide what level of residual risk is acceptable."),
    ]),
    ("Overview", "Risk Management: Identify, Assess, Control", [
        p("Organizations must design and create <strong>safe environments</strong> in which business processes and procedures can function. <strong>Risk management is the process of identifying and controlling the risks facing an organization.</strong>"),
        defs(("Risk identification", "Examining an organization's <strong>current information technology security situation</strong>."),
             ("Risk assessment", "<strong>Evaluating the risks</strong> to find a suitable control."),
             ("Risk control", "<strong>Applying controls to reduce risks</strong> to the organization's data and information systems.")),
        vs(("Know yourself", "Identify, examine, and understand the <strong>information and systems currently in place</strong>.", "a"),
           ("Know the enemy", "Identify, examine, and understand the <strong>threats facing the organization</strong>.", "b")),
        p("Managing risk is the <strong>responsibility of each community of interest</strong> within the organization."),
        h3("Purpose of risk management", "d"),
        ul("Identify potential cyber risks <strong>before they occur</strong>,",
           "<strong>across the life of the product or project</strong>,",
           "so that <strong>risk-handling activities may be planned and invoked as needed</strong>."),
        p("Risk management identifies and reduces risks (threats, vulnerabilities, and impact on asset value). <strong>Mitigating controls</strong> (safeguards and countermeasures) reduce risk, and <strong>residual risk should be set to an acceptable level</strong>."),
    ]),
    ("Components", "The Three Components of Risk Management", [
        table(["Risk assessment", "Risk mitigation", "Evaluation and assurance"],
              ["Identification of risks", "Risk avoidance", "Ongoing risk assessment"],
              ["Evaluation of risks", "Risk mitigation", "Periodic evaluation"],
              ["Risk impact", "Risk acceptance", "Regulatory compliance"],
              ["Recommendation of risk-reducing measures", "Risk transference", ""],
              ["", "Evaluation of risks", ""]),
        tip("info", "Read the table top-down", "Assessment finds and rates risks; mitigation decides what to do about them; evaluation and assurance keep checking that the decisions still hold."),
    ]),
    ("Process", "The Five Risk Management Steps", [
        steps(("Identify the risk", "Uncover, recognize, and describe risks that might affect the system or its outcomes. Several techniques exist. <strong>You start to prepare your Risk Register.</strong>"),
              ("Analyze the risk", "Determine the <strong>likelihood and impact</strong> of each risk and understand its potential to affect business objectives. This is also input to the Risk Register."),
              ("Evaluate and rank the risk", "Determine the <strong>risk score = combination of likelihood and impact</strong>. Decide whether the risk is acceptable or serious enough to treat. Rankings go into the Risk Register."),
              ("Risk control (risk response planning)", "Plan to treat the highest-ranked risks to reach acceptable levels: mitigation strategies, preventive plans, and <strong>contingency plans (DRP, BCP, IRP)</strong>. Treatment measures are added to the Risk Register."),
              ("Monitor and review the risk", "Use the Risk Register to <strong>monitor, track, and review</strong> risks.")),
        mnemonic("I-A-E-C-M", f"{key('I Always Evaluate Carefully, Monthly')} = <strong>I</strong>dentify, <strong>A</strong>nalyze, <strong>E</strong>valuate/rank, <strong>C</strong>ontrol, <strong>M</strong>onitor."),
        tip("exam", "The risk register", "The Risk Register is started in step 1 and updated in every later step. Step 5 is where you use it to monitor and review."),
        h3("Automated tools for risk management", "e"),
        ul("Aim to <strong>minimize manual effort</strong>.", "Can be <strong>time consuming to set up</strong>.", "<strong>Perform calculations quickly</strong>."),
    ]),
    ("Quantitative", "Quantitative Risk Analysis", [
        p("There are two types of risk analysis: <strong>quantitative</strong> and <strong>qualitative</strong>. Both provide unique capabilities, and <strong>both are often required to get a full picture</strong>."),
        ul("<strong>Assigns independently objective numeric monetary values</strong> (RISK = MONEY).",
           "Is <strong>fully quantitative</strong> only if <strong>all</strong> elements of the analysis are quantified.",
           "Is sometimes <strong>difficult to achieve</strong>.",
           "<strong>Requires substantial time and personnel resources.</strong>"),
        h3("Quantitative analysis steps", "b"),
        steps(("Determine asset value (AV)", "What the asset is worth to the organization."),
              ("Estimate potential losses", "The exposure factor (EF): the percentage of value lost in one incident."),
              ("Conduct a threat analysis", "Probability and impact: how often the threat happens (ARO)."),
              ("Determine annual loss expectancy (ALE)", "The expected yearly loss.")),
        formula("SLE = Asset Value × Exposure Factor<br>ALE = SLE × ARO<br>Value of control = ALE(before) − ALE(after) − ACS"),
        h3("Worked example from the slides", "c"),
        p("A server is worth <strong>USD 10,000</strong>. If attacked by threat X, EF = <strong>70%</strong>. The threat is expected <strong>20 times a year</strong> (ARO, a subjective expert estimate)."),
        table(["Quantity", "Calculation", "Result"],
              ["SLE", "10,000 × 70%", "<strong>7,000</strong>"],
              ["ALE", "7,000 × 20", "<strong>140,000</strong>"],
              ["Value of control", "140,000 (ALE before) − 50,000 (ALE after) − 30,000 (annual cost of control)", "<strong>60,000</strong>"]),
        tip("good", "Decision rule", "If the value of the control is <strong>positive</strong>, the control saves more than it costs, so it is worth buying."),
    ]),
    ("Qualitative", "Qualitative Risk Analysis", [
        ul("<strong>Scenario oriented.</strong>", "<strong>Does not attempt to assign absolute numeric values</strong> to risk components.", "<strong>Purely qualitative</strong> risk analysis is possible."),
        h3("Critical factors", "b"),
        ul("<strong>Rank the seriousness of threats and the sensitivity of assets.</strong>", "Perform a <strong>carefully reasoned</strong> risk assessment."),
        h3("Risk levels: the AS/NZS 4360 matrix", "c"),
        table(["Likelihood ↓ / Consequence →", "1 Insignificant", "2 Minor", "3 Moderate", "4 Major", "5 Catastrophic"],
              ["A (almost certain)", "H", "H", "E", "E", "E"],
              ["B (likely)", "M", "H", "H", "E", "E"],
              ["C (possible)", "L", "M", "H", "E", "E"],
              ["D (unlikely)", "L", "L", "M", "H", "E"],
              ["E (rare)", "L", "L", "M", "H", "H"]),
        table(["Level", "Meaning"],
              ["<strong>E</strong> Extreme", "Immediate action required to mitigate the risk, or decide not to proceed."],
              ["<strong>H</strong> High", "Action should be taken to compensate for the risk."],
              ["<strong>M</strong> Moderate", "Action should be taken to monitor the risk."],
              ["<strong>L</strong> Low", "Routine acceptance of the risk."]),
        h3("Five top qualitative RA techniques", "d"),
        ul("<strong>Delphi technique</strong>", "<strong>SWIFT analysis</strong> (Structured What-If)", "<strong>Decision tree analysis</strong>", "<strong>Bow-tie analysis</strong>", "<strong>Probability/consequence matrix</strong>"),
        vs(("Quantitative", "Objective, uses money values and formulas, needs lots of data and time, results are verifiable.", "a"),
           ("Qualitative", "Subjective, uses ranks/words from expert judgment, scenario-based, faster, easier to perform.", "b")),
    ]),
    ("Response", "Risk Mitigation Options", [
        defs(("Risk acceptance", "Accept the risk <strong>if the cost of the control is higher than the expected loss</strong>."),
             ("Risk reduction", "<strong>Implement a countermeasure</strong> to reduce the risk impact."),
             ("Risk transference", "<strong>Outsource or transfer to a third party</strong> (e.g. insurance)."),
             ("Risk avoidance", "<strong>Stop the activities</strong> that are causing the risk.")),
        mnemonic("A-R-T-A", f"{key('Accept · Reduce · Transfer · Avoid')}. Ask: is it cheaper to live with it, fix it, pass it on, or stop doing it?"),
        h3("The right amount of security", "c"),
        p("Use <strong>cost/benefit analysis (CBA)</strong>: balance the <strong>cost to protect</strong> against the <strong>asset value</strong>. Security is a balancing act. Before a CBA you must understand:"),
        ul("The <strong>adversary</strong>: means, motives, and opportunity", "<strong>Asset value</strong> (more than just cost)", "<strong>Threat analysis</strong>",
           "<strong>Vulnerability analysis</strong>", "The <strong>resulting risk</strong>", "<strong>Countermeasures</strong>", "<strong>Risk tolerance</strong> and <strong>risk appetite</strong>"),
    ]),
    ("Selection", "Countermeasure Selection Principles", [
        table(["Principle", "Meaning"],
              ["Cost/benefit analysis", "Cost must be justified by the potential loss."],
              ["Accountability", "Someone is clearly responsible for the safeguard."],
              ["Absence of design secrecy", "Security does not rely on a secret design: safeguards are changeable, interoperable, and trusted (Common Criteria evaluation)."],
              ["Audit capability", "The safeguard can be tested and audited."],
              ["Vendor trustworthiness", "The supplier is reliable."],
              ["Independence of control and subject", "Segregation of duties: those controlled don't control the safeguard."],
              ["Universal application", "Applies to everyone equally."],
              ["Compartmentalization and defense in depth", "Layered protection limits damage."],
              ["Isolation, economy, least common mechanism", "Isolate critical parts, keep it simple, minimize shared mechanisms."],
              ["Acceptance and tolerance by personnel", "Users must accept it or they will bypass it."],
              ["Minimum human intervention", "Less manual effort, fewer errors."],
              ["Sustainability", "Can be maintained over time."],
              ["Reaction and recovery", "Supports responding to and recovering from incidents."],
              ["Override and fail-safe defaults", "Fails into a secure state; overrides are controlled."],
              ["Residuals and reset", "Clears residual data and returns to a known state."]),
    ]),
    ("Controls", "Types of Security Controls", [
        table(["Control type", "Purpose", "Example"],
              ["<strong>Directive</strong> (administrative)", "Advise employees of the <strong>behavior expected</strong> of them when using information systems.", "Acceptable use policy"],
              ["<strong>Preventive</strong>", "Physical, administrative, and technical measures to <strong>prevent actions violating policy</strong> or increasing risk.", "Locks, firewalls, access control"],
              ["<strong>Detective</strong>", "Practices, processes, and tools that <strong>identify and possibly react to security violations</strong>.", "IDS, audit logs, CCTV"],
              ["<strong>Corrective</strong>", "React to a detected incident to <strong>reduce or eliminate the chance of the unwanted event recurring</strong>.", "Patching, removing malware"],
              ["<strong>Recovery</strong>", "<strong>Restore the system or operation to a normal state</strong> after integrity or availability is compromised.", "Restoring backups, DRP"]),
        flow("Directive", "Preventive", "Detective", "Corrective", "Recovery"),
        mnemonic("Before, during, after", f"{key('Do Please Detect, Correct, Recover')}: tell people (Directive), stop it (Preventive), find it (Detective), fix it (Corrective), get back to normal (Recovery)."),
    ]),
]

TIPS = [
    ("NIST SP 800-30 risk", "Risk is a function of the likelihood of a threat-source exercising a vulnerability and the resulting impact on assets."),
    ("Threat vs attack", "Threat = potential danger; attack = actual danger. Threat agent = potential cause; attacker = actual cause."),
    ("Residual risk", "The risk remaining after safeguards are applied. Set it to an acceptable level; it is never zero."),
    ("Five steps", "Identify → Analyze → Evaluate and rank → Control (DRP, BCP, IRP) → Monitor and review. The Risk Register starts at step 1."),
    ("Formulas", "SLE = AV × EF. ALE = SLE × ARO. Control value = ALE before − ALE after − annual cost of control."),
    ("Slide example", "Server USD 10,000, EF 70% → SLE 7,000; ARO 20 → ALE 140,000; control value = 140,000 − 50,000 − 30,000 = 60,000."),
    ("Matrix levels", "E = immediate action or don't proceed; H = compensate; M = monitor; L = routine acceptance."),
    ("A-R-T-A", "Accept (control costs more than loss), Reduce (countermeasure), Transfer (third party), Avoid (stop the activity)."),
]

QUICK = [
    ["Risk", "Possibility of losing something of value; probability a threat becomes a disaster."],
    ["Risk (NIST SP 800-30)", "Likelihood of a threat-source exercising a vulnerability × resulting impact on assets."],
    ["Asset", "Something valued by the organization to accomplish its goals."],
    ["Threat / attack", "Potential danger / actual danger."],
    ["Threat agent / attacker", "Potential cause of a threat / actual cause of an attack."],
    ["Vulnerability", "Any weakness that could be exploited."],
    ["Exposure", "An opportunity for a threat to cause loss."],
    ["Residual risk", "Risk remaining after countermeasures are applied."],
    ["Risk identification / assessment / control", "Examine current security / evaluate risks to find controls / apply controls."],
    ["Risk management steps", "Identify, analyze, evaluate and rank, control, monitor and review."],
    ["Risk score", "Combination of likelihood and impact."],
    ["Quantitative analysis", "Objective monetary values; fully quantitative only if all elements quantified; costly."],
    ["SLE / ALE", "AV × EF / SLE × ARO."],
    ["Qualitative analysis", "Scenario oriented; no absolute numbers; ranks seriousness of threats and asset sensitivity."],
    ["AS/NZS 4360", "Likelihood (A–E) × consequence (1–5) → Extreme, High, Moderate, Low."],
    ["Qualitative techniques", "Delphi, SWIFT, decision tree, bow-tie, probability/consequence matrix."],
    ["Mitigation options", "Acceptance, reduction, transference, avoidance."],
    ["Control types", "Directive, preventive, detective, corrective, recovery."],
]

BRANCHES = [
    ("Defining Risk", "Risk = Probability(threat, vulnerability, impact).", [
        ("What Risk Is", "Definition", "The possibility of losing something of value; the probability that a threat turns into a disaster.", "A vulnerability and a hazard are not dangerous separately, only together."),
        ("NIST SP 800-30", "Definition", "Risk is a function of the likelihood of a threat-source exercising a vulnerability and the resulting impact on organizational assets."),
        ("Risk Factors", "Key Idea", "Risk lives where threats, assets, and vulnerabilities overlap. After controls, what remains is residual risk."),
    ]),
    ("Key Terms", "", [
        ("Asset", "Term", "Something valued by the organization to accomplish its goals and objectives."),
        ("Threat vs Attack", "Comparison", "<strong>Threat</strong>: any potential danger. <strong>Attack</strong>: any actual danger."),
        ("Threat Agent vs Attacker", "Comparison", "<strong>Threat agent</strong>: potential cause of a threat. <strong>Attacker</strong>: actual cause of an attack."),
        ("Vulnerability and Exposure", "Term", "<strong>Vulnerability</strong>: any exploitable weakness. <strong>Exposure</strong>: an opportunity for a threat to cause loss."),
        ("Safeguards and Residual Risk", "Term", "<strong>Countermeasures/safeguards</strong> protect systems. <strong>Residual risk</strong> is what remains after they are applied."),
    ]),
    ("Risk Management Process", "Identify and control risks.", [
        ("Identify, Assess, Control", "Definition", "Identification examines current IT security; assessment evaluates risks to find controls; control applies controls to reduce risk."),
        ("Know Yourself, Know the Enemy", "Key Idea", "Understand your own systems and information, and understand the threats you face."),
        ("Step 1–2: Identify, Analyze", "Process", "Uncover and describe risks and start the Risk Register; then determine likelihood and impact."),
        ("Step 3: Evaluate and Rank", "Process", "Risk score = likelihood combined with impact; decide whether to accept or treat."),
        ("Step 4–5: Control, Monitor", "Process", "Plan treatment for top risks (mitigation, DRP, BCP, IRP), then monitor and review with the Risk Register."),
        ("Three Components", "Structure", "Risk assessment, risk mitigation, and evaluation and assurance (ongoing assessment, periodic evaluation, regulatory compliance)."),
    ]),
    ("Quantitative Analysis", "RISK = MONEY.", [
        ("Characteristics", "Definition", "Objective monetary values; fully quantitative only if everything is quantified; difficult, time and staff intensive."),
        ("SLE", "Formula", "Single loss expectancy = asset value × exposure factor."),
        ("ALE", "Formula", "Annual loss expectancy = SLE × ARO (annual rate of occurrence)."),
        ("Value of a Control", "Formula", "ALE(before) − ALE(after) − annual cost of control. Positive means worth buying."),
        ("Server Example", "Example", "AV 10,000, EF 70% → SLE 7,000. ARO 20 → ALE 140,000. Control value = 140,000 − 50,000 − 30,000 = 60,000."),
    ]),
    ("Qualitative Analysis", "Scenario-based ranking.", [
        ("Characteristics", "Definition", "Scenario oriented; no absolute numeric values; ranks threat seriousness and asset sensitivity through reasoned assessment."),
        ("AS/NZS 4360 Matrix", "Tool", "Likelihood A (almost certain) to E (rare) against consequence 1 (insignificant) to 5 (catastrophic)."),
        ("Risk Levels", "Tool", "Extreme: immediate action or don't proceed. High: compensate. Moderate: monitor. Low: routine acceptance."),
        ("Five Techniques", "Technique", "Delphi, SWIFT (structured what-if), decision tree, bow-tie, probability/consequence matrix."),
    ]),
    ("Responding to Risk", "", [
        ("Mitigation Options", "Option", "<strong>Accept</strong> if control costs more than the loss; <strong>reduce</strong> with a countermeasure; <strong>transfer</strong> to a third party; <strong>avoid</strong> by stopping the activity."),
        ("Cost/Benefit Analysis", "Key Idea", "Balance cost to protect against asset value. Understand adversary, asset value, threats, vulnerabilities, resulting risk, countermeasures, and risk tolerance/appetite."),
        ("Selection Principles", "Principle", "Cost justified by loss, accountability, no design secrecy, auditable, vendor trust, segregation of duties, defense in depth, personnel acceptance, fail-safe defaults, and more."),
    ]),
    ("Security Controls", "Five control types.", [
        ("Directive", "Control", "Administrative controls advising employees of expected behavior."),
        ("Preventive", "Control", "Physical, administrative, and technical measures that prevent policy violations."),
        ("Detective", "Control", "Practices and tools that identify and possibly react to violations."),
        ("Corrective", "Control", "React to detected incidents to reduce or eliminate recurrence."),
        ("Recovery", "Control", "Restore systems to normal operation after integrity or availability is compromised."),
    ]),
]

QUIZ = {
    "mcq": [
        ("According to NIST SP 800-30, risk is a function of:",
         ["Asset cost and insurance premium", "The likelihood of a threat-source exercising a vulnerability and the resulting impact", "The number of vulnerabilities in a system", "The number of attackers in a region"], 1,
         "NIST SP 800-30 defines risk as a function of likelihood of a threat-source exercising a vulnerability and the resulting impact on organizational assets.", "Definition"),
        ("What is the difference between a threat and an attack?",
         ["A threat is actual danger; an attack is potential danger", "A threat is potential danger; an attack is actual danger", "They are identical", "A threat affects hardware; an attack affects software"], 1,
         "A threat is any potential danger; an attack is any actual danger to information or systems.", "Terms"),
        ("The amount of risk remaining after countermeasures and safeguards are applied is called:",
         ["Exposure", "Inherent risk", "Residual risk", "Threat agent"], 2, "Residual risk is what remains after safeguards are applied.", "Terms"),
        ("In which risk management step do you start preparing the Risk Register?",
         ["Step 1: Identify the risk", "Step 3: Evaluate and rank", "Step 4: Risk control", "Step 5: Monitor and review"], 0,
         "The Risk Register is started during Step 1 and updated in later steps.", "Five steps"),
        ("Creating DRP, BCP and IRP contingency plans belongs to which risk management step?",
         ["Identify the risk", "Analyze the risk", "Risk control (risk response planning)", "Monitor and review"], 2,
         "Step 4, risk control, creates mitigation strategies, preventive plans, and contingency plans such as DRP, BCP, and IRP.", "Five steps"),
        ("The risk score used to evaluate and rank risks is the combination of:",
         ["Cost and benefit", "Likelihood and impact", "Threat and attacker", "Asset value and ARO"], 1, "Step 3 ranks risks using the risk score: likelihood combined with impact.", "Five steps"),
        ("Which statement about quantitative risk analysis is TRUE?",
         ["It never assigns monetary values", "It is fully quantitative only if all elements are quantified", "It requires few resources", "It is purely scenario oriented"], 1,
         "Quantitative analysis assigns objective monetary values and is fully quantitative only when every element is quantified. It requires substantial time and staff.", "Quantitative"),
        ("Which analysis is scenario oriented and does not assign absolute numeric values to risk components?",
         ["Quantitative risk analysis", "Qualitative risk analysis", "Cost/benefit analysis", "Annual loss expectancy"], 1, "Qualitative analysis is scenario oriented and uses ranks rather than absolute numbers.", "Qualitative"),
        ("In the AS/NZS 4360 matrix, a risk that is 'likely' (B) with a 'major' (4) consequence is rated:",
         ["Low", "Moderate", "High", "Extreme"], 3, "Row B, column 4 is E: Extreme risk, requiring immediate action or a decision not to proceed.", "Qualitative"),
        ("A company buys cyber insurance to cover losses from a data breach. Which mitigation option is this?",
         ["Risk acceptance", "Risk reduction", "Risk transference", "Risk avoidance"], 2, "Transferring the financial impact to a third party such as an insurer is risk transference.", "Mitigation"),
        ("According to the slides, risk acceptance is appropriate when:",
         ["The cost of the control is higher than the expected loss", "The risk is rated Extreme", "The asset is critical", "A third party is available"], 0,
         "The slides define risk acceptance as appropriate if the cost is higher than the expected loss.", "Mitigation"),
        ("Intrusion detection systems and audit logs that identify security violations are examples of which control type?",
         ["Directive", "Preventive", "Detective", "Recovery"], 2, "Detective controls identify and possibly react to security violations.", "Controls"),
        ("Which countermeasure selection principle corresponds to segregation of duties?",
         ["Universal application", "Independence of control and subject", "Audit capability", "Sustainability"], 1,
         "Independence of control and subject means the people controlled by a safeguard do not control it, which is segregation of duties.", "Selection principles"),
        ("Which of the following is listed as one of the five top qualitative RA techniques?",
         ["Annual loss expectancy", "Bow-tie analysis", "Exposure factor", "Safeguard value"], 1,
         "The five techniques are Delphi, SWIFT, decision tree, bow-tie, and probability/consequence matrix.", "Qualitative"),
    ],
    "tf": [
        ("A vulnerability and a hazard are dangerous even when taken separately.", False, "The slides say they are not dangerous separately; only when they come together do they become a risk.", "Definition"),
        ("Vulnerabilities exist in every IT system, product and application.", True, "The slide definition of vulnerability states this.", "Terms"),
        ("Both quantitative and qualitative analysis are often required to get a full picture of risk.", True, "Each provides unique capabilities, and both are often needed.", "Analysis types"),
        ("Automated risk management tools are always quick to set up.", False, "They minimize manual effort and calculate quickly but can be time consuming to set up.", "Tools"),
        ("Recovery controls restore a system to a normal operating state after integrity or availability is compromised.", True, "That is the definition of recovery controls.", "Controls"),
        ("In the AS/NZS 4360 scale, a Low risk calls for immediate action.", False, "Low risk means routine acceptance. Extreme calls for immediate action.", "Qualitative"),
        ("Risk avoidance means implementing a countermeasure to reduce the risk impact.", False, "That is risk reduction. Avoidance means stopping the activity that creates the risk.", "Mitigation"),
        ("Asset value in a cost/benefit analysis should be considered as more than just the cost of the asset.", True, "The slides stress that asset value is more than just cost.", "Cost/benefit"),
    ],
    "fill": [
        ("Any potential danger to information or an information system is a ________.", "threat", ["threat"], "A threat is potential danger; an attack is actual danger.", "Terms"),
        ("An opportunity for a threat to cause loss is called an ________.", "exposure", ["exposure"], "Exposure = opportunity for loss.", "Terms"),
        ("The document used across all five steps to record, rank and track risks is the risk ________.", "register", ["register"], "The Risk Register is started in step 1 and used for monitoring in step 5.", "Five steps"),
        ("________ controls advise employees of the behavior expected of them.", "Directive", ["directive"], "Directive (administrative) controls communicate expected behavior.", "Controls"),
        ("SWIFT analysis stands for Structured ________-If.", "What", ["what"], "SWIFT is a Structured What-If technique.", "Qualitative"),
    ],
    "calc": [
        ("A server is worth $10,000 and the exposure factor is 70%. What is the SLE (in dollars)?", "7,000", ["7000", "7,000"], "SLE = AV × EF = 10,000 × 0.70 = 7,000.", "Quantitative"),
        ("Using SLE = $7,000 and ARO = 20, what is the ALE (in dollars)?", "140,000", ["140000", "140,000"], "ALE = SLE × ARO = 7,000 × 20 = 140,000.", "Quantitative"),
        ("ALE before a control is $140,000, ALE after is $50,000 and the annual cost of the control is $30,000. What is the value of the control?", "60,000", ["60000", "60,000"], "Value = 140,000 − 50,000 − 30,000 = 60,000.", "Quantitative"),
        ("A database worth $50,000 loses 40% of its value per breach, and breaches happen twice a year. What is the ALE?", "40,000", ["40000", "40,000"], "SLE = 50,000 × 0.40 = 20,000; ALE = 20,000 × 2 = 40,000.", "Quantitative"),
    ],
    "match": [
        ("Match each term to its definition.", "Terms", [
            ("Asset", "Something valued by the organization to achieve its goals"),
            ("Vulnerability", "Any weakness that could be exploited"),
            ("Threat agent", "Anything with the potential of causing a threat"),
            ("Exposure", "An opportunity for a threat to cause loss"),
            ("Residual risk", "Risk remaining after safeguards are applied"),
        ]),
        ("Match each control or mitigation option to its description.", "Controls and options", [
            ("Preventive control", "Stops actions that violate policy"),
            ("Corrective control", "Reduces the chance of an incident recurring"),
            ("Risk transference", "Outsourcing or passing risk to a third party"),
            ("Risk avoidance", "Stopping the activity that causes the risk"),
            ("Risk acceptance", "Living with the risk when control costs exceed the loss"),
        ]),
    ],
    "short": [
        ("List and briefly explain the five risk management steps.",
         ["identify", "analyze", "evaluate", "control", "monitor", "register"],
         "1) Identify the risk: find and describe risks and start the Risk Register. 2) Analyze: determine likelihood and impact. 3) Evaluate and rank: compute the risk score and decide whether to accept or treat. 4) Risk control (response planning): plan treatment for top risks, including DRP, BCP, and IRP. 5) Monitor and review: track risks using the Risk Register.",
         "Five steps"),
        ("Compare quantitative and qualitative risk analysis, including one strength and one weakness of each.",
         ["monetary", "objective", "scenario", "subjective", "time", "numeric"],
         "Quantitative analysis assigns objective monetary values (SLE, ALE); it gives verifiable, numeric results but is hard to achieve and needs substantial time, data, and people. Qualitative analysis is scenario oriented and ranks threat seriousness and asset sensitivity without absolute numbers; it is quicker but more subjective. Both are often needed for a full picture.",
         "Analysis types"),
        ("Scenario: Laptops are frequently stolen from a branch office. Give one example of each of the four risk mitigation options for this risk.",
         ["accept", "reduce", "transfer", "avoid", "insurance", "lock"],
         "Accept: keep operating without new controls if protection costs more than expected losses. Reduce: install cable locks and full-disk encryption. Transfer: buy insurance or lease laptops from a provider responsible for theft. Avoid: stop issuing laptops at that branch and use fixed desktops instead.",
         "Mitigation"),
    ],
}
