"""CYS403 Chapter 3 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, flow, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 3
TITLE = "Threat and Vulnerability Management"
SLUG = "threat-and-vulnerability-management"
SUMMARY = "threats against the network, host and application, threat components and agents, database and web threats, vulnerability types, CVE and CVSS, the twelve threat modeling methods (STRIDE, PASTA, LINDDUN, attack trees, OCTAVE and more), DREAD scoring, and threat/vulnerability pairs."
HOOK = "Know the Source:"
GRADIENT = "Threats, Vulnerabilities and Threat Models"
SUB = "Before you can manage a risk you must understand where it comes from: who attacks, what they target, which weaknesses they exploit, and how structured threat models expose all of it."
CHIPS = ["Threat Types", "Threat Agents", "Vulnerabilities", "CVE · CVSS", "STRIDE · PASTA · OCTAVE", "DREAD"]

SECTIONS = [
    ("Introduction", "Managing the Source of Risk", [
        p("A key step in managing risk is to <strong>first understand and manage its source</strong>: <strong>threats and vulnerabilities</strong>, and especially <strong>threat/vulnerability pairs</strong>. Once you understand these elements, it is much easier to identify mitigation techniques."),
        p("A <strong>threat</strong> is <strong>any activity that represents a possible danger</strong>. This includes any circumstances or events with the potential to <strong>adversely impact the confidentiality, integrity, or availability</strong> of a business's assets."),
        h3("Common types of attack", "b"),
        ul("Organizational attacks", "Hackers", "Automated attacks", "Attacks on restricted data", "Accidental breaches in security", "Viruses, Trojan horses, and worms", "Denial of service (DoS), where connections fail"),
        h3("Possible threat sources: the seven IT infrastructure domains", "c"),
        p("Threats can originate in any of the seven domains of a typical IT infrastructure: the <strong>User</strong>, <strong>Workstation</strong>, <strong>LAN</strong>, <strong>LAN-to-WAN</strong>, <strong>WAN</strong>, <strong>Remote Access</strong>, and <strong>System/Application</strong> domains."),
    ]),
    ("Targets", "Threats Against the Network, Host and Application", [
        table(["Target", "Threat", "Examples"],
              ["<strong>Network</strong>", "Information gathering", "Port scanning; trace routing to detect topology; broadcast requests to enumerate subnet hosts"],
              ["Network", "Eavesdropping", "Packet sniffers stealing passwords"],
              ["Network", "Denial of service", "SYN floods, ICMP echo request floods, malformed packets"],
              ["Network", "Spoofing", "Packets with spoofed source addresses"],
              ["<strong>Host</strong>", "Arbitrary code execution", "Buffer overflows in ISAPI DLLs; directory traversal"],
              ["Host", "File disclosure", "Malformed HTR requests; virtualized UNC share vulnerability"],
              ["Host", "Denial of service", "Malformed SMTP, WebDAV requests and URLs; brute-force file uploads"],
              ["Host", "Unauthorized access", "Insufficiently restrictive ACLs; spoofing with stolen credentials"],
              ["Host", "Exploiting open ports and protocols", "NetBIOS/SMB host enumeration; connecting remotely to SQL Server"],
              ["<strong>Application</strong>", "SQL injection", "DROP TABLE typed into an input field"],
              ["Application", "Cross-site scripting (XSS)", "Malicious client-side script stealing cookies"],
              ["Application", "Hidden-field tampering", "Changing the value of a hidden form field"],
              ["Application", "Session hijacking / identity spoofing", "Stolen session ID or forms-authentication cookie"],
              ["Application", "Information disclosure", "Client sees a stack trace on an unhandled exception"]),
        mnemonic("Which layer?", f"{key('Network = packets')}, {key('Host = the server OS and services')}, {key('Application = inputs, cookies, sessions')}. SQL injection and XSS are always application threats."),
    ]),
    ("Components", "Components of a Threat and Threat Agents", [
        table(["Component", "Meaning and examples"],
              ["<strong>Threat agents</strong>", "Criminals, terrorists, subversive/secret groups, state sponsored, disgruntled employees, hackers, pressure groups, commercial groups"],
              ["<strong>Motivators</strong>", "Political, secular, personal gain, religion, power, terrorism, curiosity"],
              ["<strong>Capability</strong>", "Software, technology, facilities, education and training, methods, books and manuals"],
              ["<strong>Catalysts</strong>", "Events, technology changes, personal circumstances"],
              ["<strong>Amplifiers</strong>", "Peer pressure, fame, access to information, changing technology, deskilling through scripting, skills, law enforcement activity, target profile"],
              ["<strong>Inhibitors</strong>", "Fear of capture or failure, technical difficulty, cost of participation, sensitivity to public perception, law enforcement activity"]),
        mnemonic("A-M-C-C-A-I", f"{key('Agents Must Carry Capability, Amplified or Inhibited')}: who, why, with what, what triggers it, what boosts it, what holds it back. Catalysts <em>trigger</em>; amplifiers <em>increase</em>; inhibitors <em>discourage</em>."),
        h3("Types of threat agents", "b"),
        defs(("Natural", "Fire, floods, power failure, earthquakes."),
             ("Unintentional", "Insiders or outsiders who are <strong>primarily non-hostile</strong> (mistakes)."),
             ("Intentional", "Insiders or outsiders who are hostile or non-hostile (curious): foreign agents, industrial espionage, terrorists, organized crime, hackers, insiders, political dissidents, vendors and suppliers.")),
    ]),
    ("Catalogs", "Database, Web and Information System Threats", [
        h3("Top ten database security threats", "a"),
        table(["#", "Threat", "Key idea"],
              ["1", "Excessive privilege abuse", "Privileges exceed the job (an administrator who can change contact info also changes grades)"],
              ["2", "Legitimate privilege abuse", "Legitimate access misused (health worker selling patient records)"],
              ["3", "Privilege elevation", "Platform vulnerabilities turn user rights into administrator rights"],
              ["4", "Database platform vulnerabilities", "Flaws in the underlying OS and services"],
              ["5", "SQL injection", "Unauthorized statements injected into a SQL data channel"],
              ["6", "Weak audit trail", "Regulatory risk, less deterrence, poor detection and recovery"],
              ["7", "Denial of service", "Access denied to intended users"],
              ["8", "Communication protocol vulnerabilities", "Many vendor patches fix protocol flaws"],
              ["9", "Weak authentication", "Attackers assume legitimate identities with stolen credentials"],
              ["10", "Backup data exposure", "Unprotected backup tapes and disks are stolen"]),
        h3("Ten web threats", "b"),
        ul("Bigger, subtler DDoS attacks", "Old browsers and vulnerable plug-ins (Java, Flash, Reader)", "Good sites hosting bad content (watering hole attacks)",
           "Mobile apps and BYOD on the unsecured web", "Failing to clean up bad input (SQL injection)", "Hazards of digital certificates (fraudulent SSL certificates)",
           "Cross-site scripting", "The insecure Internet of Things", "Getting in the front door (web bots scraping business intelligence)", "New technology, same problems (people click links)"),
        h3("Major security threats on information systems", "c"),
        table(["Threat", "Description"],
              ["Intrusion / hacking", "Gaining access without the owner's knowledge (poor shopping carts, hidden fields, client-side validation, direct SQL, session hijacking, buffer overflow, port scan)"],
              ["Viruses and worms", "Programs that make systems not work properly (polymorphic, stealth, tunneling, droppers, cavity viruses)"],
              ["Trojan horse", "Two components, a server and a client; steal data, log keystrokes, send files"],
              ["Spoofing", "Fooling users into trusting a fake source (IP, DNS, ARP spoofing)"],
              ["Sniffing", "Capturing login IDs and passwords over the wire (TCPDump, Snoop)"],
              ["Denial of service", "Bringing down the network for legitimate users; can be done with a simple ping"]),
    ]),
    ("Vulnerabilities", "Vulnerabilities: Types and How They Manifest", [
        p("A vulnerability is <strong>some weakness of a system that could allow security to be violated</strong>."),
        h3("Types of vulnerabilities", "a"),
        ul("Physical", "Natural", "Hardware/software", "Media (stolen or damaged disks and tapes)", "Emanation (due to radiation)", "Communication", "Human"),
        h3("How vulnerabilities manifest (misuse)", "b"),
        table(["Misuse", "Examples"],
              ["External misuse", "Visual spying, misrepresenting, physical scavenging"],
              ["Hardware misuse", "Logical scavenging, eavesdropping, interference, physical attack or removal"],
              ["Masquerading", "Impersonation, piggybacking, spoofing, network weaving"],
              ["Pest programs", "Trojan horses, logic bombs, worms, viruses"],
              ["Bypasses", "Trapdoor attacks, authorization attacks such as password cracking"],
              ["Active misuse", "Basic active attack, incremental attack, denial of service"],
              ["Passive misuse", "Browsing, interference, aggregation, covert channels"]),
        h3("Where vulnerabilities come from", "c"),
        table(["Source", "Examples"],
              ["Employees", "Discussing work in public, taking data out of the office, installing unauthorized software, tailgating, opening spam, writing down passwords, lack of awareness"],
              ["Former employees", "Working for competitors, retaining company data, discussing company matters"],
              ["Technology", "Social networking, file sharing, rapid change, legacy systems, data on mobile devices"],
              ["Hardware", "Dust, heat and humidity, design flaws, out-of-date or misconfigured hardware"],
              ["Software", "Insufficient testing, no audit trail, bugs, unchecked input, bloatware, SaaS loss of control, vendors going out of business"],
              ["Network", "Unprotected communications, open connections/ports, insecure architecture, unused user IDs, excessive privileges, WiFi"],
              ["IT management", "Missed patches, weak incident and change management, no audits, improper waste disposal, lack of risk analysis, inadequate continuity planning"],
              ["Partners and suppliers", "Telecom and utility disruption, supply disruption, sharing confidential data"]),
    ]),
    ("CVE", "Common Vulnerabilities and Exposures (CVE)", [
        p("CVE defines a vulnerability as <strong>a weakness in the computational logic (e.g. code) found in software and hardware components that, when exploited, results in a negative impact to confidentiality, integrity, or availability</strong>. Mitigation typically involves coding changes, but could include specification changes or even removing affected protocols or functionality entirely."),
        p("All vulnerabilities in the <strong>NVD</strong> (National Vulnerability Database) have been assigned a CVE identifier. A CVE entry contains:"),
        defs(("CVE ID", "A unique identifier, e.g. CVE-2016-7280."), ("Description", "What the weakness is and its effect."), ("References", "Links to advisories and reports.")),
        h3("Examples", "d"),
        table(["CVE", "Description"],
              ["CVE-2016-7280", "XSS vulnerability in Microsoft Edge lets remote attackers inject arbitrary web script or HTML (Microsoft Edge Information Disclosure Vulnerability)."],
              ["CVE-2016-3273", "The XSS Filter in Internet Explorer 9–11 and Edge does not properly restrict JavaScript, letting attackers obtain sensitive information via a crafted site."]),
    ]),
    ("Threat Modeling", "Threat Modeling and STRIDE", [
        p("Threat modeling is a <strong>structured approach to identifying, quantifying, and addressing threats</strong>. Threat-modeling methods create an <strong>abstraction of the system</strong>, <strong>profiles of potential attackers</strong> (goals and methods), and a <strong>catalog of potential threats</strong>."),
        h3("The twelve threat models", "a"),
        table(["", "", ""], ["STRIDE", "PASTA", "LINDDUN"], ["CVSS", "Attack Trees", "Persona non Grata"],
              ["Security Cards", "hTMM", "Quantitative TMM"], ["Trike", "VAST", "OCTAVE"]),
        h3("STRIDE", "b"),
        ul("Evaluates the <strong>system detail design</strong>; it models the <strong>in-place system</strong>.", "Built on <strong>data-flow diagrams (DFDs)</strong>.",
           "Identifies system entities, events, and system boundaries.", "Microsoft no longer maintains STRIDE separately; it is part of the <strong>Microsoft SDL</strong> through the <strong>Threat Modeling Tool</strong>."),
        table(["Letter", "Threat", "Question it asks", "Property violated"],
              ["S", "Spoofing", "Can an attacker gain access using a false identity?", "Authentication"],
              ["T", "Tampering", "Can an attacker modify data as it flows through the application?", "Integrity"],
              ["R", "Repudiation", "If an attacker denies doing something, can we prove they did it?", "Non-repudiation"],
              ["I", "Information disclosure", "Can an attacker gain access to private or potentially injurious data?", "Confidentiality"],
              ["D", "Denial of service", "Can an attacker crash or reduce the availability of the system?", "Availability"],
              ["E", "Elevation of privilege", "Can an attacker assume the identity of a privileged user?", "Authorization"]),
        tip("exam", "STRIDE vs DREAD", "<strong>STRIDE classifies</strong> threats (what kind). <strong>DREAD scores</strong> them (how bad) so they can be prioritized."),
    ]),
    ("Frameworks", "PASTA, LINDDUN, CVSS and Attack Trees", [
        defs(("PASTA", "Process for Attack Simulation and Threat Analysis. A <strong>risk-centric</strong> framework (2012) with <strong>seven stages</strong>. Brings business objectives and technical requirements together and elevates threat modeling to a <strong>strategic level</strong> involving key decision makers."),
             ("LINDDUN", "Focuses on <strong>privacy</strong> concerns. Starts with a DFD (data flows, stores, processes, external entities) and has <strong>six steps</strong>."),
             ("CVSS", "Common Vulnerability Scoring System. Captures a vulnerability's principal characteristics and produces a <strong>numerical severity score</strong>, computed from analyst-assigned metric values with an online calculator.")),
        h3("LINDDUN privacy threats", "b"),
        table(["Letter", "Threat", "Meaning"],
              ["L", "Linkability", "Distinguishing whether two items of interest are linked (visits by the same user)"],
              ["I", "Identifiability", "Identifying the subject within a set (the sender of an email)"],
              ["N", "Non-repudiation", "Being unable to deny an action where deniability is needed (anonymous voting, whistleblowing)"],
              ["D", "Detectability", "Distinguishing whether an item of interest exists"],
              ["D", "Disclosure of information", "Data privacy leakage (STRIDE is used here)"],
              ["U", "Unawareness", "Being unaware of the consequences of sharing information"],
              ["N", "Non-compliance", "Not complying with legislation, regulations, and corporate policy"]),
        h3("Attack trees", "c"),
        ul("A <strong>hierarchical decomposition of a threat</strong> into individual, testable conditions.", "The <strong>root is the adversary's goal</strong>.",
           "Each level below decomposes the attack into finer approaches.", "Child nodes are <strong>ORed together by default</strong>; special notation marks <strong>AND</strong> nodes."),
        vs(("Graph notation", "Goal: read a file from a password-protected PC → get password (search desk, social engineer), network access, or physical access (boot with CD, remove hard disk).", "a"),
           ("Text notation", "Goal: read a message sent between PCs → 1. convince sender (blackmail, bribe); 2. read on sender's PC; 3. read on receiver's PC; 4. read in transit (sniff, usurp mail server).", "d")),
    ]),
    ("Hybrid Methods", "PnG, Security Cards, hTMM, Quantitative TMM, Trike, VAST and OCTAVE", [
        table(["Method", "Key characteristics"],
              ["<strong>Persona non Grata (PnG)</strong>", "Focuses on the motivations and skills of human attackers; views the system from an unintended-use point of view; helpful early in threat modeling."],
              ["<strong>Security Cards</strong>", "A brainstorming technique with a deck of cards to find unusual and complex attacks: who might attack, why, which assets, and how."],
              ["<strong>hTMM</strong>", "Hybrid Threat Modeling Method (SEI, 2018): SQUARE + Security Cards + PnG. Goals: no false positives, no overlooked threats, consistent results, cost effective."],
              ["<strong>Quantitative TMM</strong>", "Attack trees + STRIDE + CVSS applied together for cyber-physical systems with complex interdependencies. Build attack trees for the STRIDE categories, then score components with CVSS."],
              ["<strong>Trike</strong>", "A security audit framework using threat modeling from a risk-management, defensive perspective. Uses an actor-asset-action matrix with CRUD cells, a DFD, attack trees, and a five-point probability scale; threats are elevation of privilege or denial of service."],
              ["<strong>VAST</strong>", "Visual, Agile, and Simple Threat modeling: scales across infrastructure and DevOps, fits Agile. Application threat models (developers, DFD and process flow) and operational threat models (infrastructure, attacker view)."],
              ["<strong>OCTAVE</strong>", "Operationally Critical Threat, Asset, and Vulnerability Evaluation: a risk-based strategic method focused on <strong>organizational</strong> risk, not technological risk."]),
        h3("OCTAVE's three phases", "b"),
        steps(("Build asset-based threat profiles", "An organizational evaluation."),
              ("Identify infrastructure vulnerabilities", "An evaluation of the information infrastructure."),
              ("Develop a security strategy and plans", "Identify risks to critical assets and make decisions.")),
        h3("hTMM main steps", "c"),
        steps(("Identify the system to be threat-modeled", ""), ("Apply Security Cards based on developer suggestions", ""),
              ("Remove unlikely PnGs", "Those with no realistic attack vectors."), ("Summarize results with tool support", ""),
              ("Continue with a formal risk-assessment method", "")),
        tip("warn", "Easy to confuse", "<strong>hTMM</strong> = SQUARE + Security Cards + PnG. <strong>Quantitative TMM</strong> = attack trees + STRIDE + CVSS."),
    ]),
    ("Prioritizing", "DREAD, Threat/Vulnerability Pairs and the Threat Matrix", [
        table(["Letter", "Factor", "Question"],
              ["D", "Damage potential", "What are the consequences of a successful exploit?"],
              ["R", "Reproducibility", "Would an exploit work every time or only under certain circumstances?"],
              ["E", "Exploitability", "How skilled must an attacker be to exploit the vulnerability?"],
              ["A", "Affected users", "How many users would be affected by a successful exploit?"],
              ["D", "Discoverability", "How likely is it that an attacker will know the vulnerability exists?"]),
        h3("DREAD example from the slides", "b"),
        table(["Threat", "D", "R", "E", "A", "D", "Sum"],
              ["Auth cookie theft (eavesdropping)", "3", "2", "3", "2", "3", "<strong>13</strong>"],
              ["Auth cookie theft (XSS)", "3", "2", "2", "2", "3", "<strong>12</strong>"]),
        p("Damage potential is high (spoofed identities); a cookie can be stolen any time but is useful only until it expires; anyone can run a sniffer while XSS needs moderate skill; all users could be affected but most won't click malicious links; the flaw is easy to discover. The higher sum means <strong>eavesdropping is prioritized</strong>."),
        h3("Threat/vulnerability pairs", "c"),
        ul("A threat/vulnerability pair occurs <strong>when a threat exploits a vulnerability</strong>.", "The vulnerability provides a <strong>path for the threat</strong> that results in harm or loss.",
           "<strong>Both must come together</strong> to result in a loss.", "Vulnerabilities depend on your organization: with no public-facing servers, there are no vulnerabilities in that area, so <strong>the risk is zero</strong>."),
        p("A <strong>threat matrix</strong> plots the <strong>capabilities of a threat against the types of vulnerability</strong>, similar to a risk assessment matrix."),
    ]),
]

TIPS = [
    ("Threat definition", "Any activity representing a possible danger: circumstances or events that could adversely impact CIA of assets."),
    ("Target layers", "Network: sniffing, SYN floods, spoofed packets. Host: buffer overflows, ACLs, open ports. Application: SQL injection, XSS, hidden fields, session hijacking."),
    ("Catalyst vs amplifier vs inhibitor", "Catalysts trigger (events, tech change); amplifiers increase (fame, peer pressure); inhibitors discourage (fear of capture, cost)."),
    ("CVE entry", "CVE ID + description + references. All NVD vulnerabilities have a CVE ID."),
    ("STRIDE", "Spoofing, Tampering, Repudiation, Information disclosure, DoS, Elevation of privilege. DFD-based; part of Microsoft SDL."),
    ("Privacy = LINDDUN", "Linkability, Identifiability, Non-repudiation, Detectability, Disclosure, Unawareness, Non-compliance. Six steps, starts from a DFD."),
    ("Attack trees", "Root = attacker's goal; children ORed by default; AND needs special notation."),
    ("OCTAVE vs hTMM", "OCTAVE: organizational (not technological) risk, 3 phases. hTMM: SQUARE + Security Cards + PnG. Quantitative TMM: attack trees + STRIDE + CVSS."),
    ("DREAD", "Damage, Reproducibility, Exploitability, Affected users, Discoverability. Slide example: eavesdropping 13 beats XSS 12."),
    ("Pairs", "Loss needs a threat AND a vulnerability. No vulnerability in an area = zero risk there."),
]

QUICK = [
    ["Threat", "Activity representing possible danger to CIA of assets."],
    ["Network threats", "Information gathering, eavesdropping, DoS, spoofing."],
    ["Host threats", "Arbitrary code execution, file disclosure, DoS, unauthorized access, open ports."],
    ["Application threats", "SQL injection, XSS, hidden-field tampering, session hijacking, identity spoofing, information disclosure."],
    ["Threat components", "Agents, motivators, capability, catalysts, amplifiers, inhibitors."],
    ["Threat agent types", "Natural, unintentional, intentional."],
    ["Database threat #1", "Excessive privilege abuse."],
    ["Vulnerability types", "Physical, natural, hardware/software, media, emanation, communication, human."],
    ["Misuse categories", "External, hardware, masquerading, pest programs, bypasses, active, passive."],
    ["CVE", "Weakness in computational logic that impacts CIA when exploited; entry = ID, description, references."],
    ["CVSS", "Numerical severity score from analyst metric values."],
    ["STRIDE", "Classifies threats on DFDs; Microsoft SDL Threat Modeling Tool."],
    ["PASTA", "Risk-centric, 7 stages, aligns business objectives and technical requirements."],
    ["LINDDUN", "Privacy threat modeling, 6 steps, DFD based."],
    ["Attack tree", "Hierarchical decomposition; root = goal; OR by default."],
    ["PnG / Security Cards", "Attacker motivations and skills / brainstorming deck of cards."],
    ["Trike", "Security audit framework; actor-asset-action CRUD matrix; 5-point scale."],
    ["VAST", "Agile, scalable; application and operational threat models."],
    ["OCTAVE", "Organizational risk; 3 phases: threat profiles, infrastructure vulnerabilities, strategy."],
    ["DREAD", "Damage, reproducibility, exploitability, affected users, discoverability; sum to prioritize."],
    ["Threat/vulnerability pair", "A threat exploiting a vulnerability; both needed for a loss."],
]

BRANCHES = [
    ("Threats", "Possible dangers to CIA.", [
        ("Definition", "Definition", "Any activity representing a possible danger: circumstances or events that could adversely impact confidentiality, integrity, or availability."),
        ("Network Threats", "Target", "Information gathering (port scanning), eavesdropping (sniffers), DoS (SYN and ICMP floods), spoofing."),
        ("Host Threats", "Target", "Arbitrary code execution (buffer overflows), file disclosure, DoS, unauthorized access (weak ACLs), exploiting open ports."),
        ("Application Threats", "Target", "SQL injection, XSS, hidden-field tampering, session hijacking, identity spoofing, information disclosure."),
        ("Seven IT Domains", "Source", "User, Workstation, LAN, LAN-to-WAN, WAN, Remote Access, System/Application."),
    ]),
    ("Threat Anatomy", "", [
        ("Agents and Motivators", "Component", "Agents: criminals, terrorists, states, disgruntled employees, hackers. Motivators: political, personal gain, religion, power, curiosity."),
        ("Capability and Catalysts", "Component", "Capability: software, facilities, training, methods. Catalysts: events, technology changes, personal circumstances."),
        ("Amplifiers and Inhibitors", "Component", "Amplifiers: peer pressure, fame, scripting. Inhibitors: fear of capture, difficulty, cost, law enforcement."),
        ("Agent Types", "Classification", "Natural (fire, flood), unintentional (non-hostile mistakes), intentional (espionage, organized crime, insiders)."),
    ]),
    ("Threat Catalogs", "", [
        ("Top Database Threats", "Catalog", "Excessive and legitimate privilege abuse, privilege elevation, platform flaws, SQL injection, weak audit trail, DoS, protocol flaws, weak authentication, backup exposure."),
        ("Ten Web Threats", "Catalog", "DDoS, old browsers/plug-ins, watering holes, mobile/BYOD, bad input, certificate hacks, XSS, insecure IoT, web bots, people clicking links."),
        ("Information System Threats", "Catalog", "Intrusion/hacking, viruses and worms, Trojan horses (client + server), spoofing (IP, DNS, ARP), sniffing, denial of service."),
    ]),
    ("Vulnerabilities", "Weaknesses that allow security to be violated.", [
        ("Types", "Classification", "Physical, natural, hardware/software, media, emanation, communication, human."),
        ("Misuse", "Classification", "External, hardware, masquerading, pest programs, bypasses (trapdoors, password cracking), active, passive (browsing, covert channels)."),
        ("Sources", "Classification", "Employees, former employees, technology, hardware, software, network, IT management, partners and suppliers."),
        ("CVE", "Standard", "A weakness in computational logic that impacts CIA when exploited. Entry = CVE ID, description, references; all NVD entries have one."),
    ]),
    ("Threat Modeling Methods", "Twelve structured approaches.", [
        ("STRIDE", "Method", "Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege. DFD based; part of Microsoft SDL."),
        ("PASTA", "Method", "Risk-centric, seven stages; brings business objectives and technical requirements to a strategic level."),
        ("LINDDUN", "Method", "Privacy: Linkability, Identifiability, Non-repudiation, Detectability, Disclosure, Unawareness, Non-compliance."),
        ("CVSS", "Method", "Produces a numerical severity score from analyst-assigned metric values."),
        ("Attack Trees", "Method", "Hierarchical decomposition; root = adversary goal; children ORed by default, AND by special notation."),
        ("Hybrid Methods", [
            ("PnG and Security Cards", "Method", "PnG studies attacker motivations and skills; Security Cards brainstorm who, why, what, and how."),
            ("hTMM", "Method", "SEI 2018: SQUARE + Security Cards + PnG; no false positives or overlooked threats, consistent, cost effective."),
            ("Quantitative TMM", "Method", "Attack trees + STRIDE + CVSS for cyber-physical systems."),
            ("Trike and VAST", "Method", "Trike: audit framework with actor-asset-action CRUD matrix. VAST: agile, scalable application and operational models."),
            ("OCTAVE", "Method", "Organizational risk; three phases: asset-based threat profiles, infrastructure vulnerabilities, security strategy."),
        ]),
    ]),
    ("Prioritizing Threats", "", [
        ("DREAD", "Scoring", "Damage potential, Reproducibility, Exploitability, Affected users, Discoverability."),
        ("DREAD Example", "Example", "Cookie theft by eavesdropping scores 13; by XSS scores 12, so eavesdropping is prioritized."),
        ("Threat/Vulnerability Pairs", "Key Idea", "A loss needs a threat exploiting a vulnerability. No public servers means no vulnerabilities there, so risk is zero."),
        ("Threat Matrix", "Tool", "Threat capabilities plotted against vulnerability types, like a risk matrix."),
    ]),
]

QUIZ = {
    "mcq": [
        ("An attacker types a DROP TABLE command into a web form input field. This threat is against the:",
         ["Network", "Host", "Application", "Physical facility"], 2, "SQL injection is listed under threats against the application.", "Threat targets"),
        ("SYN floods and ICMP echo request floods are examples of which network threat?",
         ["Eavesdropping", "Denial of service", "Spoofing", "Information gathering"], 1, "They are denial-of-service threats against the network.", "Threat targets"),
        ("Which threat component includes fear of capture, cost of participation and level of technical difficulty?",
         ["Threat amplifiers", "Threat catalysts", "Threat inhibitors", "Threat motivators"], 2, "Inhibitors discourage an attack; amplifiers increase it; catalysts trigger it.", "Threat components"),
        ("A university administrator who only needs to change student contact details uses excess update rights to change grades. Which database threat is this?",
         ["Legitimate privilege abuse", "Excessive privilege abuse", "Privilege elevation", "Weak authentication"], 1,
         "This is the slide example of excessive privilege abuse: privileges exceed job requirements.", "Database threats"),
        ("A CVE entry contains which three items?",
         ["CVE ID, description, references", "Score, vendor, patch", "Asset, threat, vulnerability", "Likelihood, impact, control"], 0, "A CVE entry contains the CVE ID, description, and references.", "CVE"),
        ("Which threat modeling method focuses on privacy concerns?",
         ["STRIDE", "PASTA", "LINDDUN", "Trike"], 2, "LINDDUN is the privacy-focused method.", "Threat modeling"),
        ("In STRIDE, the question 'If an attacker denies doing something, can we prove he did it?' refers to:",
         ["Spoofing", "Tampering", "Repudiation", "Elevation of privilege"], 2, "Repudiation concerns proving that an action was performed.", "STRIDE"),
        ("Which method is described as a risk-centric framework with seven stages that brings business objectives and technical requirements together?",
         ["PASTA", "OCTAVE", "VAST", "hTMM"], 0, "PASTA (2012) is risk-centric with seven stages and a strategic focus.", "Threat modeling"),
        ("In an attack tree, child nodes are combined by default using:",
         ["AND", "OR", "XOR", "NOT"], 1, "Child nodes are ORed together by default; special notation indicates AND.", "Attack trees"),
        ("The Hybrid Threat Modeling Method (hTMM) combines:",
         ["Attack trees, STRIDE and CVSS", "SQUARE, Security Cards and PnG", "OCTAVE, PASTA and VAST", "DREAD, CVE and NVD"], 1,
         "hTMM combines SQUARE, Security Cards, and Persona non Grata. Quantitative TMM combines attack trees, STRIDE, and CVSS.", "Hybrid methods"),
        ("OCTAVE focuses on assessing:",
         ["Only technological risks", "Organizational risks rather than technological risks", "Privacy risks in DFDs", "Numeric severity of CVEs"], 1,
         "OCTAVE is a risk-based strategic method that focuses on organizational risk and does not address technological risk.", "OCTAVE"),
        ("Which Trike element has four parts (CRUD) in each cell?",
         ["The DFD", "The actor-asset-action matrix", "The attack tree", "The five-point scale"], 1, "Trike's actor-asset-action matrix has CRUD parts per cell with associated rules.", "Trike"),
        ("In the slides' DREAD example, why is cookie theft by eavesdropping prioritized over cookie theft by XSS?",
         ["It has higher damage potential", "Its total score is 13 versus 12, because it needs less skill to exploit", "It affects fewer users", "It is harder to discover"], 1,
         "Exploitability is 3 for eavesdropping (anyone can run a sniffer) versus 2 for XSS, giving totals of 13 and 12.", "DREAD"),
        ("An organization has no public-facing servers. According to the threat/vulnerability pair concept, the risk from attacks on public-facing servers is:",
         ["High", "Moderate", "Zero", "Unknown until a CVSS score is calculated"], 2, "Without the vulnerability, the threat has no path, so the risk in that area is zero.", "Pairs"),
    ],
    "tf": [
        ("A Trojan horse has two components: one that runs as a server and one that runs as a client.", True, "That is how the slides describe Trojan horses.", "IS threats"),
        ("Microsoft still maintains STRIDE as a separate, standalone product.", False, "Microsoft no longer maintains STRIDE separately; it is implemented in the SDL Threat Modeling Tool.", "STRIDE"),
        ("Emanation vulnerabilities arise from radiation.", True, "The slides list emanation vulnerabilities as due to radiation.", "Vulnerability types"),
        ("STRIDE models the in-place system using data-flow diagrams.", True, "STRIDE evaluates the system detail design using DFDs.", "STRIDE"),
        ("A CVSS score can only be calculated manually and never with an online calculator.", False, "A CVSS score can be computed with a calculator available online.", "CVSS"),
        ("Persona non Grata focuses on the motivations and skills of human attackers.", True, "PnG examines attacker skills, motivations, and goals.", "Hybrid methods"),
        ("A threat alone, without a vulnerability, is enough to result in a loss.", False, "Both the threat and the vulnerability must come together to result in a loss.", "Pairs"),
        ("In Trike, identified threats fall into either elevation of privilege or denial of service.", True, "Trike categorizes threats as elevations of privilege or denials of service.", "Trike"),
    ],
    "fill": [
        ("________ spoofing, DNS spoofing and ARP spoofing are forms of spoofing listed in the slides.", "IP", ["ip"], "The slides list IP, DNS, and ARP spoofing.", "IS threats"),
        ("The E in DREAD stands for ________.", "Exploitability", ["exploitability"], "DREAD = Damage, Reproducibility, Exploitability, Affected users, Discoverability.", "DREAD"),
        ("All vulnerabilities in the ________ have been assigned a CVE identifier.", "NVD (National Vulnerability Database)", ["nvd", "national vulnerability database"], "The NVD assigns CVE identifiers to all its vulnerabilities.", "CVE"),
        ("In an attack tree, the root of the tree is the adversary's ________.", "goal", ["goal"], "The root represents the attacker's goal.", "Attack trees"),
        ("OCTAVE stands for Operationally Critical Threat, Asset, and ________ Evaluation.", "Vulnerability", ["vulnerability"], "OCTAVE = Operationally Critical Threat, Asset, and Vulnerability Evaluation.", "OCTAVE"),
    ],
    "calc": [
        ("Using DREAD, a threat scores D=3, R=3, E=2, A=1, D=2. What is its total score?", "11", ["11"], "3 + 3 + 2 + 1 + 2 = 11.", "DREAD"),
        ("Cookie theft by eavesdropping scores D=3, R=2, E=3, A=2, D=3. What is its DREAD total?", "13", ["13"], "3 + 2 + 3 + 2 + 3 = 13, matching the slide example.", "DREAD"),
    ],
    "match": [
        ("Match each STRIDE threat to the question it asks.", "STRIDE", [
            ("Spoofing", "Can an attacker gain access using a false identity?"),
            ("Tampering", "Can an attacker modify data in transit?"),
            ("Information disclosure", "Can an attacker access private data?"),
            ("Denial of service", "Can an attacker reduce system availability?"),
            ("Elevation of privilege", "Can an attacker assume a privileged identity?"),
        ]),
        ("Match each threat modeling method to its focus.", "Threat modeling", [
            ("LINDDUN", "Privacy threats starting from a DFD"),
            ("CVSS", "Numerical vulnerability severity score"),
            ("Security Cards", "Brainstorming unusual attacks with a deck of cards"),
            ("VAST", "Agile, scalable application and operational models"),
            ("OCTAVE", "Organizational risk in three phases"),
        ]),
    ],
    "short": [
        ("Explain the six components of a threat and give one example of each.",
         ["agent", "motivator", "capability", "catalyst", "amplifier", "inhibitor"],
         "Threat agents are who attacks (criminals, disgruntled employees). Motivators are why (personal gain, politics). Capability is the means (software, training). Catalysts trigger the attack (events, technology changes). Amplifiers increase the likelihood (fame, peer pressure, scripting tools). Inhibitors discourage it (fear of capture, cost, law enforcement).",
         "Threat components"),
        ("Compare STRIDE and DREAD. How would you use them together?",
         ["classify", "score", "spoofing", "damage", "prioritize", "dfd"],
         "STRIDE classifies threats into Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, and Elevation of privilege, usually by walking a data-flow diagram of the system. DREAD scores each threat on Damage, Reproducibility, Exploitability, Affected users, and Discoverability. Use STRIDE to find and categorize threats, then DREAD to rank them so the highest totals are handled first.",
         "STRIDE and DREAD"),
        ("Scenario: An attacker wants to read a confidential file on a password-protected PC. Sketch an attack tree in text notation.",
         ["goal", "password", "physical", "network", "or", "social"],
         "Goal: Read file from password-protected PC. 1. Get the password: 1.1 search the desk, 1.2 social-engineer the owner. 2. Gain network access. 3. Gain physical access: 3.1 boot with a CD, 3.2 remove the hard disk. Child nodes are ORed by default: any one path achieves the goal.",
         "Attack trees"),
    ],
}
