"""CYS403 Chapter 4 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, flow, formula, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 4
TITLE = "Risk Management Lifecycle"
SLUG = "risk-management-lifecycle"
SUMMARY = "the risk management lifecycle, accountability of the communities of interest, asset identification and inventory attributes, asset classification, weighted asset valuation and ranking, threat and vulnerability identification, and the TVA worksheet."
HOOK = "Know What You Protect:"
GRADIENT = "The Risk Management Lifecycle"
SUB = "Every risk assessment starts with the assets. Learn who is accountable, how to build an asset inventory, how to classify and value assets, and how the TVA worksheet ties assets to threats and vulnerabilities."
CHIPS = ["Communities of Interest", "Asset Inventory", "Classification", "Weighted Valuation", "Asset Ranking", "TVA Worksheet"]

SECTIONS = [
    ("Overview", "What Risk Management Involves", [
        p("<strong>Risk management is the identification, assessment, and prioritization of risks.</strong> Managing risk is <strong>one of the key responsibilities of every manager</strong> within the organization."),
        p("In any well-developed risk management program, <strong>two formal processes</strong> are at work:"),
        vs(("Risk identification and assessment", "Find the assets, threats, and vulnerabilities, then measure and prioritize the risks.", "a"),
           ("Risk control", "Choose and apply cost-effective controls to reduce the risks.", "d")),
        h3("The risk management cycle", "b"),
        table(["Phase", "Activities"],
              ["<strong>Risk identification</strong>", "Identify · Measure · Prioritize"],
              ["<strong>Control measures</strong>", "Cost/benefit analysis"]),
        p("Risk identification works on three elements: <strong>threat, vulnerability, and asset</strong>."),
    ]),
    ("Accountability", "Accountability: The Communities of Interest", [
        p("<strong>Communities of interest must work together</strong> to manage risk. Each has a distinct role:"),
        defs(("Cyber security", "Takes the <strong>leadership role</strong> in addressing risk."),
             ("Information technology", "<strong>Builds and maintains secure systems</strong>."),
             ("Management", "<strong>Allocates resources</strong> and <strong>prioritizes security concerns</strong>."),
             ("Users", "Play a <strong>crucial role in early detection</strong> and proper response to threats.")),
        tip("exam", "Who does what?", "Security leads, IT builds, management funds and prioritizes, users detect. A question about budget points to management; a question about noticing a phishing email points to users."),
    ]),
    ("Steps", "Steps in Risk Management", [
        steps(("Identify risks", "Using the threat–vulnerability matrix and asset impact."),
              ("Assess risks", "Quantitative or qualitative."),
              ("Evaluate the risk controls (CBA model)", "Determine which control options are cost-effective."),
              ("Acquire or install the appropriate controls", ""),
              ("Oversee processes", "Ensure the controls remain effective."),
              ("Summarize the findings", "")),
        flow("Asset identification", "Classification", "Valuation and ranking", "Threat identification", "Vulnerability identification", "TVA worksheet"),
    ]),
    ("Inventory", "Asset Identification and Inventory", [
        p("Risk identification begins with an <strong>asset inventory</strong>:"),
        ul("<strong>Identify information assets</strong>, including <strong>people, procedures, data and information, software, hardware, and networking elements</strong>.",
           "Do this <strong>without pre-judging the value of each asset</strong>: values are assigned later in the process.",
           "<strong>Determine which attributes of each asset should be tracked.</strong>"),
        h3("Potential attributes by asset type", "b"),
        table(["Physical devices", "People", "Procedures", "Data"],
              ["Name", "Position name/number/ID", "Description", "Classification (sensitive, confidential, private, public)"],
              ["Asset tag", "Supervisor name/number/ID", "Intended purpose", "Owner / creator / manager"],
              ["IP address", "Security clearance level", "Software/hardware/networking elements it is tied to", "Size of data structure"],
              ["MAC address", "Special skills", "Where it is stored for reference", "Data structure used"],
              ["Asset type; serial number", "", "Where it is stored for update purposes", "Online or offline"],
              ["Manufacturer name; model or part number", "", "", "Location"],
              ["Software version, update revision, or FCO number", "", "", "Backup procedures"],
              ["Physical / logical location; controlling entity", "", "", ""]),
        tip("info", "Tools", "Asset inventories can be supported by tools such as a <strong>network asset tracker</strong> and <strong>asset management</strong> software."),
        tip("warn", "Don't value too early", "Identification must be done without pre-judging each asset's value. Valuation comes after the inventory is complete."),
    ]),
    ("Classification", "Classifying and Categorizing Assets", [
        ul("<strong>Determine or refine an asset classification scheme.</strong>",
           "A classification scheme <strong>categorizes information assets based on their sensitivity and security needs</strong>.",
           "Each category <strong>designates the level of protection needed</strong> for a particular asset.",
           "Some asset types, such as <strong>personnel</strong>, may require an <strong>alternative classification scheme</strong>.",
           "Classification categories must be <strong>comprehensive and mutually exclusive</strong>."),
        mnemonic("Good categories", f"{key('Comprehensive + Mutually exclusive')}: every asset fits somewhere, and no asset fits in two places."),
        table(["Data classification", "Typical meaning"],
              ["Sensitive", "Highest protection; serious harm if disclosed"],
              ["Confidential", "Internal use by authorized staff only"],
              ["Private", "Personal information about individuals"],
              ["Public", "Can be freely released"]),
    ]),
    ("Valuation", "Asset Valuation and Ranking", [
        p("<strong>Determine the values of assets</strong> by assigning a <strong>relative value</strong>: comparative judgments made so that <strong>the most valuable information assets are given the highest priority</strong>."),
        h3("Factors to consider", "b"),
        defs(("Asset cost", "What it costs to acquire or replace."), ("Impact on profitability", "How much profit depends on it."),
             ("Impact on revenue", "How much income it generates."), ("Impact on public image", "Reputational damage if it is lost.")),
        h3("Questions for assessing asset value", "c"),
        steps(("Which asset is the most critical to the success of the organization?", ""), ("Which asset generates the most revenue?", ""),
              ("Which asset generates the highest profitability?", ""), ("Which asset is the most expensive to replace?", ""),
              ("Which asset is the most expensive to protect?", ""), ("Whose loss or compromise would be most embarrassing or cause the greatest liability?", "")),
        h3("Weighted factor analysis", "d"),
        p("A <strong>weighted factor analysis worksheet</strong> turns these questions into numbers: each criterion gets a <strong>weight</strong> (weights total 100), each asset gets a <strong>score per criterion</strong> (e.g. 0.1–1.0), and the asset's <strong>weighted score</strong> is the sum of score × weight."),
        formula("Weighted score = Σ (criterion score × criterion weight)"),
        table(["Asset (illustration)", "Revenue (30)", "Profitability (40)", "Public image (30)", "Weighted score"],
              ["Customer order database", "1.0", "0.9", "0.5", "30 + 36 + 15 = <strong>81</strong>"],
              ["Public website", "0.8", "0.6", "1.0", "24 + 24 + 30 = <strong>78</strong>"],
              ["Internal wiki", "0.2", "0.3", "0.2", "6 + 12 + 6 = <strong>24</strong>"]),
        p("<strong>Asset ranking</strong> then <strong>prioritizes the assets according to value</strong>: the highest weighted score is protected first."),
    ]),
    ("Threats", "Threat and Vulnerability Identification", [
        p("After ranking the assets, the <strong>threats and vulnerabilities are assessed</strong> as in Chapter 3. The outcome is a <strong>threat–vulnerability matrix</strong>, and threats are <strong>prioritized based on their score for each asset</strong>."),
        h3("Vulnerability assessment examples", "b"),
        table(["Asset", "Vulnerability", "Threat"],
              ["Email servers", "Anti-virus software not updated", "Virus attack"],
              ["Router", "Incorrect router configuration", "Network susceptible to reduction or loss of connectivity"]),
        tip("good", "Read the pattern", "Each row is one <strong>threat/vulnerability pair on one asset</strong>. That is exactly the unit the TVA worksheet records."),
    ]),
    ("TVA", "The TVA Worksheet", [
        p("At the end of the risk identification process you have two lists:"),
        vs(("List 1", "A list of <strong>assets and their vulnerabilities</strong>, prioritized by asset value.", "a"),
           ("List 2", "A list that <strong>prioritizes the threats</strong> facing the organization, based on the weighted table.", "c")),
        p("These lists are combined into a single worksheet: the <strong>Threat–Vulnerability–Asset (TVA) worksheet</strong>. Assets are listed along one axis in order of priority, threats along the other in order of priority, and each intersection records the vulnerabilities (T#V#A#) where that threat meets that asset."),
        table(["", "Asset 1 (most valuable)", "Asset 2", "Asset 3"],
              ["Threat 1 (most dangerous)", "T1V1A1, T1V2A1", "T1V1A2", "—"],
              ["Threat 2", "T2V1A1", "T2V1A2, T2V2A2", "T2V1A3"],
              ["Threat 3", "—", "T3V1A2", "T3V1A3"]),
        tip("exam", "Where to start", "The top-left of the TVA worksheet (most valuable asset × most dangerous threat) holds the highest-priority vulnerabilities."),
        p("<strong>What is next?</strong> Risk assessment, either <strong>quantitative or qualitative</strong>, which Chapter 5 covers."),
    ]),
]

TIPS = [
    ("Two formal processes", "Risk identification and assessment, and risk control."),
    ("Communities of interest", "Cyber security leads; IT builds and maintains secure systems; management allocates resources and prioritizes; users detect and respond early."),
    ("Six steps", "Identify, assess, evaluate controls (CBA), acquire/install controls, oversee effectiveness, summarize findings."),
    ("Inventory rule", "Identify people, procedures, data, software, hardware, networking without pre-judging value."),
    ("Classification rule", "Categories based on sensitivity and security needs; comprehensive and mutually exclusive."),
    ("Valuation factors", "Cost, impact on profitability, revenue, and public image. Assign relative values."),
    ("Weighted analysis", "Weighted score = Σ score × weight; rank assets by the result."),
    ("TVA worksheet", "Combines prioritized assets/vulnerabilities with prioritized threats; next step is risk assessment."),
]

QUICK = [
    ["Risk management", "Identification, assessment, and prioritization of risks."],
    ["Formal processes", "Risk identification and assessment; risk control."],
    ["Risk management cycle", "Risk identification (identify, measure, prioritize) and control measures (CBA)."],
    ["Cyber security role", "Leadership in addressing risk."],
    ["IT role", "Build and maintain secure systems."],
    ["Management role", "Resource allocation and prioritization."],
    ["Users role", "Early detection and proper response to threats."],
    ["Asset categories", "People, procedures, data/information, software, hardware, networking."],
    ["Device attributes", "Name, asset tag, IP, MAC, type, serial number, manufacturer, model, version, location, controlling entity."],
    ["People attributes", "Position, supervisor, security clearance, special skills."],
    ["Data attributes", "Classification, owner, size, structure, online/offline, location, backup procedures."],
    ["Classification scheme", "Based on sensitivity/security needs; comprehensive and mutually exclusive."],
    ["Valuation factors", "Cost, profitability, revenue, public image."],
    ["Weighted factor analysis", "Criteria weights × asset scores, summed and ranked."],
    ["Threat–vulnerability matrix", "Output of threat identification; prioritizes threats per asset."],
    ["TVA worksheet", "Threat–Vulnerability–Asset worksheet combining both prioritized lists."],
]

BRANCHES = [
    ("Risk Management Overview", "Identification, assessment, and prioritization of risks.", [
        ("Definition", "Definition", "Risk management identifies, assesses, and prioritizes risks. It is a key responsibility of every manager."),
        ("Two Formal Processes", "Key Idea", "Risk identification and assessment, and risk control."),
        ("Risk Management Cycle", "Process", "Risk identification (identify, measure, prioritize) followed by control measures chosen by cost/benefit analysis."),
        ("Six Steps", "Process", "Identify, assess (quantitative or qualitative), evaluate controls with CBA, install controls, oversee effectiveness, summarize findings."),
    ]),
    ("Communities of Interest", "Everyone shares accountability.", [
        ("Cyber Security", "Role", "Leadership role in addressing risk."),
        ("Information Technology", "Role", "Builds and maintains secure systems."),
        ("Management", "Role", "Allocates resources and prioritizes security concerns."),
        ("Users", "Role", "Crucial role in early detection and proper response to threats."),
    ]),
    ("Asset Identification", "Build the inventory first.", [
        ("What to Inventory", "Step", "People, procedures, data and information, software, hardware, and networking elements, without pre-judging value."),
        ("Device Attributes", "Attributes", "Name, asset tag, IP and MAC address, type, serial number, manufacturer, model, software version, location, controlling entity."),
        ("People and Procedure Attributes", "Attributes", "People: position, supervisor, clearance, skills. Procedures: description, purpose, related elements, storage locations."),
        ("Data Attributes", "Attributes", "Classification, owner, size, structure, online/offline, location, backup procedures."),
    ]),
    ("Classification", "", [
        ("Classification Scheme", "Rule", "Categorizes assets by sensitivity and security needs; each category sets the protection level."),
        ("Category Rules", "Rule", "Categories must be comprehensive and mutually exclusive; personnel may need an alternative scheme."),
        ("Data Levels", "Example", "Sensitive, confidential, private, public."),
    ]),
    ("Valuation and Ranking", "Most valuable assets get the highest priority.", [
        ("Valuation Factors", "Factor", "Asset cost and impact on profitability, revenue, and public image."),
        ("Six Valuation Questions", "Checklist", "Most critical? Most revenue? Most profit? Most expensive to replace? Most expensive to protect? Most embarrassing or liable if lost?"),
        ("Weighted Factor Analysis", "Technique", "Weight each criterion, score each asset, sum score × weight, and rank assets by the result."),
        ("Asset Ranking", "Step", "Prioritize assets according to value before identifying threats."),
    ]),
    ("Threats and the TVA Worksheet", "", [
        ("Threat–Vulnerability Matrix", "Output", "After ranking assets, assess threats and vulnerabilities and prioritize threats by score per asset."),
        ("Vulnerability Examples", "Example", "Email servers + outdated anti-virus + virus attack; router + incorrect configuration + loss of connectivity."),
        ("TVA Worksheet", "Tool", "Combines the prioritized asset/vulnerability list with the prioritized threat list; cells record T#V#A# pairs."),
        ("What Comes Next", "Key Idea", "Risk assessment: quantitative or qualitative."),
    ]),
]

QUIZ = {
    "mcq": [
        ("In a well-developed risk management program, which two formal processes are at work?",
         ["Auditing and patching", "Risk identification and assessment, and risk control", "Encryption and access control", "Procurement and training"], 1,
         "The slides name risk identification and assessment, and risk control.", "Overview"),
        ("Which community of interest is responsible for resource allocation and prioritization of security concerns?",
         ["Cyber security", "Information technology", "Management", "Users"], 2, "Management allocates resources and prioritizes security concerns.", "Accountability"),
        ("Which community of interest plays a crucial role in early detection of threats?",
         ["Users", "Management", "Auditors", "Vendors"], 0, "Users play a crucial role in early detection and proper response to threats.", "Accountability"),
        ("When creating the asset inventory, assets should be identified:",
         ["Only after assigning dollar values", "Without pre-judging the value of each asset", "Only for hardware", "By the external auditor"], 1,
         "Identification is done without pre-judging value; values are assigned later.", "Inventory"),
        ("Which of the following is a sample attribute for PEOPLE assets?",
         ["MAC address", "Security clearance level", "Backup procedures", "Serial number"], 1, "People attributes include position, supervisor, security clearance, and special skills.", "Inventory"),
        ("Which attribute belongs to DATA assets?",
         ["Asset tag", "Supervisor ID", "Classification (sensitive, confidential, private, public)", "Manufacturer's model number"], 2,
         "Data attributes include classification, owner, size, structure, online/offline, location, and backup procedures.", "Inventory"),
        ("Asset classification categories must be:",
         ["Overlapping and flexible", "Comprehensive and mutually exclusive", "Based only on purchase price", "Identical for people and data"], 1,
         "Categories must be comprehensive and mutually exclusive.", "Classification"),
        ("Which is NOT listed as a factor in asset valuation?",
         ["Asset cost", "Impact on revenue", "Impact on public image", "Number of vendors"], 3, "The factors are cost and impact on profitability, revenue, and public image.", "Valuation"),
        ("In a weighted factor analysis, an asset's weighted score is calculated by:",
         ["Adding all weights", "Multiplying each criterion score by its weight and summing", "Dividing asset cost by ARO", "Counting its vulnerabilities"], 1,
         "Weighted score = Σ (criterion score × weight).", "Valuation"),
        ("After assets are ranked, what is the outcome of threat identification?",
         ["A risk register", "A threat–vulnerability matrix", "A POAM", "A CVSS score"], 1, "The outcome is a threat–vulnerability matrix, with threats prioritized per asset.", "Threats"),
        ("An email server with anti-virus software that is not updated faces a virus attack. The vulnerability here is:",
         ["The email server", "The virus attack", "The out-of-date anti-virus software", "The network"], 2, "Asset = email server; vulnerability = anti-virus not updated; threat = virus attack.", "Threats"),
        ("The TVA worksheet combines:",
         ["Budget and schedule", "The prioritized list of assets and vulnerabilities with the prioritized list of threats", "Controls and costs", "CVE IDs and CVSS scores"], 1,
         "It combines the asset/vulnerability list and the threat list into one Threat–Vulnerability–Asset worksheet.", "TVA"),
    ],
    "tf": [
        ("Managing risk is one of the key responsibilities of every manager in the organization.", True, "The slides state this directly.", "Overview"),
        ("The IT community of interest takes the leadership role in addressing risk.", False, "Cyber security takes the leadership role; IT builds and maintains secure systems.", "Accountability"),
        ("People and procedures are considered information assets in the inventory.", True, "Assets include people, procedures, data, software, hardware, and networking elements.", "Inventory"),
        ("Personnel may require an alternative classification scheme.", True, "Some asset types, such as personnel, may require an alternative scheme.", "Classification"),
        ("Asset valuation assigns relative values so that the most valuable assets get the highest priority.", True, "Comparative judgments ensure the most valuable assets are prioritized.", "Valuation"),
        ("Risk assessment happens before asset identification in the lifecycle.", False, "Assets are identified, classified, valued, and ranked first; risk assessment comes after the TVA worksheet.", "Lifecycle"),
        ("An incorrect router configuration that could cause loss of connectivity is an example of a vulnerability.", True, "The slides give incorrect router configuration as the vulnerability for the router asset.", "Threats"),
        ("A network asset tracker is a tool that can support asset inventory.", True, "Network asset tracker and asset management tools are listed.", "Inventory"),
    ],
    "fill": [
        ("TVA stands for Threat, Vulnerability, ________.", "Asset", ["asset"], "TVA = Threat–Vulnerability–Asset.", "TVA"),
        ("The ________ community of interest builds and maintains secure systems.", "Information Technology (IT)", ["information technology", "it"], "IT builds and maintains secure systems.", "Accountability"),
        ("Evaluating risk controls uses the ________ model to decide which options are cost-effective.", "CBA (cost/benefit analysis)", ["cba", "cost benefit", "cost/benefit", "cost-benefit"], "The CBA model determines cost-effective controls.", "Steps"),
        ("A classification scheme categorizes assets based on their sensitivity and security ________.", "needs", ["needs", "need"], "Classification is based on sensitivity and security needs.", "Classification"),
        ("After identifying and valuing assets, the next step is asset ________: prioritizing according to value.", "ranking", ["ranking", "rank"], "Asset ranking prioritizes by value.", "Valuation"),
    ],
    "calc": [
        ("Weights: revenue 40, profitability 35, public image 25. An asset scores 0.5, 0.8 and 1.0. What is its weighted score?", "73", ["73"], "0.5×40 + 0.8×35 + 1.0×25 = 20 + 28 + 25 = 73.", "Weighted analysis"),
        ("Weights: revenue 30, profitability 40, public image 30. Asset A scores 0.9, 0.7, 0.4; Asset B scores 0.6, 0.9, 0.8. Which asset ranks higher, A or B?", "B (78 vs 67)", ["b"], "A = 27 + 28 + 12 = 67. B = 18 + 36 + 24 = 78, so B ranks higher.", "Asset ranking"),
    ],
    "match": [
        ("Match each community of interest to its role.", "Accountability", [
            ("Cyber security", "Leadership role in addressing risk"),
            ("Information technology", "Build and maintain secure systems"),
            ("Management", "Resource allocation and prioritization"),
            ("Users", "Early detection and response to threats"),
        ]),
        ("Match each attribute to the asset type it describes.", "Inventory", [
            ("MAC address", "Physical device"),
            ("Security clearance level", "People"),
            ("Intended purpose", "Procedures"),
            ("Backup procedures", "Data"),
        ]),
    ],
    "short": [
        ("Describe the steps from asset identification to the TVA worksheet.",
         ["inventory", "classify", "value", "rank", "threat", "vulnerability", "tva"],
         "First build an asset inventory of people, procedures, data, software, hardware, and networking, tracking relevant attributes without pre-judging value. Classify assets by sensitivity with comprehensive, mutually exclusive categories. Value assets using factors such as cost, revenue, profitability, and public image (weighted factor analysis), then rank them. Identify threats and vulnerabilities per asset to form a threat–vulnerability matrix. Combine the prioritized lists into the TVA worksheet, which feeds risk assessment.",
         "Lifecycle"),
        ("Explain why different communities of interest must work together in risk management.",
         ["security", "it", "management", "users", "resources", "detection"],
         "No single group can manage risk alone. Cyber security leads the effort and sets direction; IT builds and maintains secure systems; management provides resources and decides priorities; users are often first to notice threats and must respond properly. Without cooperation, controls are underfunded, poorly implemented, or bypassed.",
         "Accountability"),
        ("Scenario: A company lists its assets as 'servers', 'laptops', 'computers' and 'customer data'. Critique this classification.",
         ["mutually exclusive", "comprehensive", "overlap", "people", "procedures", "sensitivity"],
         "The categories are not mutually exclusive: laptops and servers are also computers, so an asset could fall into two categories. They are not comprehensive either: people, procedures, software, and networking elements are missing. A better scheme classifies by sensitivity and security needs (e.g. sensitive, confidential, private, public for data) with every asset fitting exactly one category.",
         "Classification"),
    ],
}
