"""CYS403 Chapter 5 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, formula, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 5
TITLE = "Risk Assessment Approaches"
SLUG = "risk-assessment-approaches"
SUMMARY = "why and when risk assessments are performed, scope, critical areas and team, quantitative assessment with SLE, ARO, ALE and safeguard value, the laptop class activity, qualitative probability and impact, the risk determination formula with worked examples, and the ranked risk worksheet."
HOOK = "Putting Numbers on Danger:"
GRADIENT = "Risk Assessment Approaches"
SUB = "How to find the most serious risks, when to assess them, how to calculate losses and savings with SLE, ARO and ALE, and how to rank vulnerabilities with the risk determination formula."
CHIPS = ["Scope · Areas · Team", "SLE · ARO · ALE", "Safeguard Value", "Probability × Impact", "Risk Determination", "Ranked Worksheet"]

SECTIONS = [
    ("Purpose", "What Risk Assessment Is and Why It Matters", [
        p("<strong>Risk assessment (RA) is performed to identify the most serious risks.</strong> There are two primary methods:"),
        vs(("Quantitative", "Calculates <strong>monetary values</strong> with <strong>predefined formulas</strong>.", "a"),
           ("Qualitative", "Uses <strong>values or words</strong> assigned to the <strong>probability</strong> of a risk occurring and its <strong>impact</strong> if it occurs.", "b")),
        h3("Importance of risk assessment", "c"),
        ul("RAs are an <strong>important part of the risk management process</strong>.",
           "Without an RA, it is <strong>difficult to determine which systems should be protected</strong>, and unclear <strong>how to protect them</strong>.",
           "An RA identifies <strong>the most important systems to protect</strong>.",
           "It gives insight into <strong>which controls will provide the most value</strong>."),
        p("After identifying threats, vulnerabilities, and asset value, you need the <strong>likelihood and impact of each threat on the assets</strong>, then <strong>prioritize the risks</strong> to know which must be treated first."),
    ]),
    ("Timing", "When to Conduct a Risk Assessment", [
        p("<strong>Risk assessment is a continuous process.</strong> It should be conducted:"),
        steps(("When evaluating risk in the SDLC", "At project initiation, company startup, and similar starting points."),
              ("When evaluating a security control", "During periodic monitoring."),
              ("After a control is implemented", "To ensure its suitability and functionality.")),
        tip("warn", "Not a one-time event", "An RA done once and filed away quickly becomes outdated. Assets, threats, and controls change, so the assessment must be repeated."),
    ]),
    ("Components", "Critical Components: Scope, Critical Areas, Team", [
        defs(("[1] Scope", "Identifies the <strong>boundary of the RA</strong>: what is included and what is not. It helps <strong>keep the RA on track</strong>."),
             ("[2] Critical areas", "Identifies the <strong>critical areas that should be included</strong>, helping the RA team <strong>focus only on what's important</strong>."),
             ("[3] Team", "RA team personnel <strong>should not be the same people responsible for correcting deficiencies</strong>, to <strong>avoid a conflict of interest</strong>. But input from the responsible people is very important.")),
        h3("Critical areas example", "b"),
        table(["In-scope system", "Critical area to focus on"],
              ["Web server", "Single point of failure (SPOF); OS update/patch status"],
              ["Database server", "Only the data exchanged with the web server"],
              ["Firewall", "Inspection of all traffic"]),
        mnemonic("S-C-T", f"{key('Scope, Critical areas, Team')}: where the boundary is, what matters inside it, and who is independent enough to judge it."),
    ]),
    ("Quantitative", "Quantitative Risk Assessment", [
        p("<strong>Quantitative assessment is an objective method.</strong> It uses numbers such as actual dollar values, requires <strong>a significant amount of data that takes a long time to gather</strong>, and is essentially <strong>a simple math problem using formulas</strong>."),
        table(["Term", "Meaning", "Example from the slides"],
              ["<strong>SLE</strong> Single loss expectancy", "Total loss expected from a <strong>single incident</strong> (when a threat exploits a vulnerability); includes hardware, software, and data.", "$5,000"],
              ["<strong>ARO</strong> Annual rate of occurrence", "Number of times an incident is <strong>expected per year</strong>.", "Once a month → ARO = 12"],
              ["<strong>ALE</strong> Annual loss expectancy", "Expected loss for a year = <strong>SLE × ARO</strong> (a dollar value).", "$5,000 × 12 = $60,000"],
              ["<strong>Safeguard value</strong>", "The <strong>cost of a control</strong> used to mitigate risk.", "$50 anti-virus × 100 computers = $5,000"]),
        formula("ALE = SLE × ARO<br>Savings with control = ALE(before) − ALE(after) − Control cost"),
        h3("Benefits and limitations", "b"),
        vs(("Benefits", "Mathematical calculation with <strong>accurate, objective results</strong>; <strong>verifiable facts</strong> without debate; <strong>can be automated</strong> (e.g. Excel).", "d"),
           ("Limitations", "<strong>Accurate data isn't always available</strong>; <strong>hard to ensure people use the control as expected</strong>.", "e")),
    ]),
    ("Class Activity", "Worked Example: Stolen Laptops", [
        p("A company issues laptops worth <strong>$2,000</strong> each (hardware, software, and data). About <strong>100 laptops</strong> are in use. Over the past two years the company lost <strong>one laptop per quarter</strong>, stolen when left unattended."),
        table(["Question", "Answer", "Why"],
              ["SLE?", "<strong>$2,000</strong>", "One stolen laptop loses its full value."],
              ["ARO?", "<strong>4</strong>", "One per quarter = 4 per year."],
              ["ALE?", "<strong>$8,000</strong>", "$2,000 × 4."]),
        h3("Should the company buy hardware locks?", "b"),
        p("Locks cost <strong>$10 each</strong>, so the safeguard value is $10 × 100 = <strong>$1,000</strong>. With locks, the ARO is expected to drop from <strong>4 to 1</strong>."),
        steps(("Current ALE (before the control)", "$2,000 × 4 = <strong>$8,000</strong>"),
              ("ARO with the control", "<strong>1</strong>"),
              ("ALE with the control (after)", "$2,000 × 1 = <strong>$2,000</strong>"),
              ("Savings with the control", "$8,000 − $2,000 − $1,000 = <strong>$5,000</strong>")),
        tip("good", "Decision", "Savings are positive ($5,000), so <strong>yes, buy the locks</strong>: they cost $1,000 a year but cut expected losses by $6,000."),
    ]),
    ("Qualitative", "Qualitative Risk Assessment", [
        p("<strong>Qualitative assessment is a subjective method.</strong> It uses <strong>relative values based on expert opinion</strong>. Experts give their input on the probability and impact of a risk, so a qualitative RA can be <strong>completed rather quickly</strong>."),
        defs(("Probability", "The <strong>likelihood that a threat will exploit a vulnerability</strong>. Rated with word values (Low, Medium, High) or percentages (e.g. 10% = low, 100% = high)."),
             ("Impact", "The <strong>negative result if a risk occurs</strong>; identifies the <strong>magnitude of a risk (amount of loss)</strong>. Rated with the same kind of word or percentage scale.")),
        formula("Risk level = Probability × Impact"),
        tip("info", "Putting it together", "Each risk is plotted on a probability × impact matrix, and the results are written up in a <strong>risk assessment report</strong> listing risks from highest to lowest level."),
    ]),
    ("Formula", "Risk Determination Formula", [
        p("For relative risk assessment, risk <strong>equals</strong> the likelihood of vulnerability occurrence <strong>times</strong> value (or impact), <strong>minus</strong> the percentage of risk already controlled, <strong>plus</strong> an element of uncertainty."),
        formula("Risk = (Likelihood × Value) − (% controlled × Likelihood × Value) + (% uncertainty × Likelihood × Value)"),
        h3("Likelihood", "b"),
        ul("The <strong>probability that a specific vulnerability will be the object of a successful attack</strong>.",
           "Assign a number between <strong>0.1 (low) and 1.0 (high)</strong>, or between <strong>1 and 100 (%)</strong>.",
           "<strong>Zero is not used</strong>: vulnerabilities with zero likelihood are removed from the asset/vulnerability list."),
        tip("exam", "Uncertainty", "If data is <strong>90% accurate</strong>, uncertainty = 1 − 0.9 = <strong>10%</strong>. If 80% accurate, uncertainty = <strong>20%</strong>."),
        h3("Worked examples from the slides", "c"),
        table(["Case", "Inputs", "Calculation", "Risk"],
              ["Asset A, vulnerability 1", "Value 50, likelihood 1.0, 0% controlled, 90% accurate (10% uncertainty)", "(50×1.0) − 0 + 10%(50) = 50 − 0 + 5", "<strong>55</strong>"],
              ["Asset B, vulnerability 2", "Value 100, likelihood 0.5, 50% controlled, 80% accurate (20% uncertainty)", "(100×0.5) − 50%(50) + 20%(50) = 50 − 25 + 10", "<strong>35</strong>"],
              ["Asset B, vulnerability 3", "Value 100, likelihood 0.1, 0% controlled, 80% accurate (20% uncertainty)", "(100×0.1) − 0 + 20%(10) = 10 − 0 + 2", "<strong>12</strong>"]),
        mnemonic("Compute the base first", f"{key('Base = Likelihood × Value')}. Then subtract controlled% of the base and add uncertainty% of the <em>same base</em>."),
    ]),
    ("Results", "Documenting the Results", [
        ul("The final summary is comprised in a <strong>ranked (vulnerability) risk worksheet</strong>.",
           "The ranked risk worksheet is the <strong>initial working document for the next step</strong> in the risk management process: <strong>assessing and controlling risk</strong>."),
        table(["Deliverable", "Purpose"],
              ["<strong>Information asset classification worksheet</strong>", "Assembles information about information assets and their impact."],
              ["<strong>Weighted criteria analysis worksheet</strong>", "Assigns a ranked value or impact weight to each information asset."],
              ["<strong>Ranked vulnerability risk worksheet</strong>", "Assigns a ranked risk rating for each uncontrolled asset–vulnerability pair."]),
        tip("good", "Using the examples", "Ranking the three worked examples gives A/V1 (55) first, B/V2 (35) second, and B/V3 (12) third."),
    ]),
]

TIPS = [
    ("Two methods", "Quantitative = monetary values with formulas (objective). Qualitative = words/values for probability and impact from experts (subjective, quick)."),
    ("When to assess", "Continuously: SDLC/project start, periodic control monitoring, and after a control is implemented."),
    ("S-C-T", "Scope = boundary; critical areas = focus; team ≠ people who fix deficiencies (conflict of interest)."),
    ("Core formulas", "ALE = SLE × ARO. Savings = ALE before − ALE after − control cost."),
    ("Laptop activity", "SLE $2,000, ARO 4, ALE $8,000; locks $1,000, ARO → 1, ALE after $2,000; savings $5,000 → buy."),
    ("Likelihood scale", "0.1–1.0 or 1–100%. Zero is never used; such vulnerabilities are removed."),
    ("Risk determination", "Risk = L×V − controlled%(L×V) + uncertainty%(L×V). Examples: 55, 35, 12."),
    ("Three deliverables", "Asset classification worksheet, weighted criteria analysis worksheet, ranked vulnerability risk worksheet."),
]

QUICK = [
    ["Risk assessment", "Performed to identify the most serious risks."],
    ["Quantitative RA", "Objective; dollar values; lots of data and time; formulas."],
    ["Qualitative RA", "Subjective; expert opinion on probability and impact; quick."],
    ["When to conduct RA", "SDLC/project initiation, periodic control monitoring, after control implementation."],
    ["Scope", "Boundary of the RA: what is and isn't included."],
    ["Critical areas", "Important parts to focus on (web server SPOF, exchanged data, firewall inspection)."],
    ["Team", "Not the people responsible for fixing deficiencies; avoids conflict of interest."],
    ["SLE", "Total loss from a single incident."],
    ["ARO", "Incidents expected per year."],
    ["ALE", "SLE × ARO."],
    ["Safeguard value", "Cost of a control (e.g. $50 × 100 computers = $5,000)."],
    ["Savings with control", "ALE before − ALE after − control cost."],
    ["Quantitative benefits / limits", "Objective, verifiable, automatable / data not always available, control use not guaranteed."],
    ["Probability / impact", "Likelihood a threat exploits a vulnerability / magnitude of loss."],
    ["Risk determination", "L × V − % controlled + % uncertainty."],
    ["Likelihood values", "0.1 to 1.0 or 1 to 100; zero not used."],
    ["Ranked risk worksheet", "Final summary; starting point for assessing and controlling risk."],
]

BRANCHES = [
    ("Risk Assessment Basics", "Identify the most serious risks.", [
        ("Purpose", "Definition", "Risk assessment identifies the most serious risks, which systems to protect, how, and which controls give the most value."),
        ("Two Methods", "Comparison", "Quantitative: monetary values with formulas. Qualitative: words or values for probability and impact."),
        ("When to Assess", "Timing", "Continuously: in the SDLC and project initiation, during periodic control monitoring, and after a control is implemented."),
    ]),
    ("Critical Components", "", [
        ("Scope", "Component", "The boundary of the RA: what is included and excluded. Keeps the RA on track."),
        ("Critical Areas", "Component", "The important parts to include, e.g. web server SPOF and patching, database data exchanged with the web server, firewall traffic inspection."),
        ("Team", "Component", "Not the people responsible for correcting deficiencies (conflict of interest), though their input is important."),
    ]),
    ("Quantitative Assessment", "Objective, dollar-based.", [
        ("SLE", "Term", "Total loss expected from a single incident, including hardware, software, and data."),
        ("ARO", "Term", "Times an incident is expected per year. Once a month means ARO = 12."),
        ("ALE", "Formula", "ALE = SLE × ARO. $5,000 × 12 = $60,000."),
        ("Safeguard Value", "Term", "Cost of a control. $50 anti-virus × 100 computers = $5,000."),
        ("Benefits and Limitations", "Comparison", "Objective, verifiable, automatable; but accurate data isn't always available and control use isn't guaranteed."),
        ("Laptop Activity", [
            ("Before Locks", "Example", "SLE $2,000; ARO 4 (one per quarter); ALE $8,000."),
            ("After Locks", "Example", "Locks $10 × 100 = $1,000; ARO drops to 1; ALE $2,000."),
            ("Decision", "Example", "Savings = $8,000 − $2,000 − $1,000 = $5,000, so buy the locks."),
        ]),
    ]),
    ("Qualitative Assessment", "Subjective, expert-based.", [
        ("Characteristics", "Definition", "Relative values from expert opinion on probability and impact; completed quickly."),
        ("Probability", "Term", "Likelihood that a threat exploits a vulnerability; Low/Medium/High or percentages."),
        ("Impact", "Term", "Negative result if the risk occurs; magnitude of loss."),
        ("Risk Level", "Formula", "Risk level = probability × impact."),
    ]),
    ("Risk Determination", "L × V − controlled + uncertainty.", [
        ("Formula", "Formula", "Risk = likelihood × value − % risk already controlled + element of uncertainty."),
        ("Likelihood Scale", "Rule", "0.1 (low) to 1.0 (high), or 1–100%. Zero isn't used; zero-likelihood vulnerabilities are removed."),
        ("Asset A Example", "Example", "Value 50, likelihood 1.0, no controls, 10% uncertainty: 50 − 0 + 5 = 55."),
        ("Asset B Examples", "Example", "V2: 100 × 0.5 = 50; −50% (25) + 20% (10) = 35. V3: 100 × 0.1 = 10; − 0 + 20% (2) = 12."),
    ]),
    ("Documenting Results", "", [
        ("Ranked Risk Worksheet", "Deliverable", "Final summary of the RA and the starting point for assessing and controlling risk."),
        ("Asset Classification Worksheet", "Deliverable", "Assembles information about assets and their impact."),
        ("Weighted Criteria Worksheet", "Deliverable", "Assigns a ranked value or impact weight to each asset."),
        ("Ranked Vulnerability Worksheet", "Deliverable", "Assigns a ranked risk rating to each uncontrolled asset–vulnerability pair."),
    ]),
]

QUIZ = {
    "mcq": [
        ("Risk assessment is performed primarily to:",
         ["Purchase security products", "Identify the most serious risks", "Replace risk management", "Train users"], 1, "RA is performed to identify the most serious risks.", "Purpose"),
        ("Which statement describes quantitative risk assessment?",
         ["Subjective, based on expert opinion, completed quickly", "Objective, uses dollar values, requires a lot of data", "Uses only Low/Medium/High words", "Needs no formulas"], 1,
         "Quantitative RA is objective, uses actual dollar values and formulas, and requires a significant amount of data.", "Methods"),
        ("Why should the RA team not be the same people responsible for correcting deficiencies?",
         ["They lack technical skill", "To avoid a conflict of interest", "They are too expensive", "Because scope forbids it"], 1,
         "Separating the RA team from those who fix deficiencies avoids a conflict of interest, though their input is still important.", "Components"),
        ("Which RA component identifies the boundary of what is and is not included?",
         ["Team", "Critical areas", "Scope", "ALE"], 2, "Scope identifies the RA boundary and keeps the RA on track.", "Components"),
        ("An incident happened once a month last year. Assuming nothing changes, what is the ARO?",
         ["1", "4", "12", "30"], 2, "Monthly = 12 times per year.", "Quantitative"),
        ("Which term refers to the cost of a control?",
         ["SLE", "Safeguard value", "ARO", "Exposure factor"], 1, "Safeguard value is the cost of a control, e.g. $50 × 100 computers = $5,000.", "Quantitative"),
        ("Which is a LIMITATION of quantitative risk assessment?",
         ["Results cannot be verified", "Accurate data isn't always available", "It cannot be automated", "It relies only on expert opinion"], 1,
         "Limitations: accurate data isn't always available, and it's hard to ensure controls are used as expected.", "Quantitative"),
        ("In qualitative RA, impact is defined as:",
         ["The likelihood a threat exploits a vulnerability", "The negative result if a risk occurs", "The annual rate of occurrence", "The cost of the safeguard"], 1,
         "Impact is the negative result if a risk occurs; probability is the likelihood.", "Qualitative"),
        ("In the risk determination formula, why is a likelihood of zero never used?",
         ["Zero breaks the multiplication", "Vulnerabilities with zero likelihood are removed from the asset/vulnerability list", "Zero means maximum risk", "The formula requires negative numbers"], 1,
         "Vulnerabilities with zero likelihood are removed from the list, so zero is not used.", "Risk determination"),
        ("If assumptions and data are 80% accurate, the element of uncertainty is:",
         ["80%", "8%", "20%", "0%"], 2, "Uncertainty = 1 − 0.8 = 20%.", "Risk determination"),
        ("Which deliverable assigns a ranked risk rating for each uncontrolled asset–vulnerability pair?",
         ["Information asset classification worksheet", "Weighted criteria analysis worksheet", "Ranked vulnerability risk worksheet", "POAM"], 2,
         "The ranked vulnerability risk worksheet rates each uncontrolled asset–vulnerability pair.", "Results"),
        ("When should an RA be conducted after a control is implemented?",
         ["Never", "To ensure the control's suitability and functionality", "Only if the control failed", "Only during the SDLC"], 1,
         "After implementation, an RA ensures the control's suitability and functionality.", "Timing"),
    ],
    "tf": [
        ("Risk assessment is a one-time activity performed only at project initiation.", False, "RA is a continuous process conducted at several points.", "Timing"),
        ("A qualitative risk assessment can be completed rather quickly.", True, "Because it relies on expert opinion, it can be completed quickly.", "Qualitative"),
        ("SLE includes the value of hardware, software and data.", True, "The slides say SLE includes hardware, software, and data.", "Quantitative"),
        ("Quantitative risk assessment can be automated, for example with an Excel sheet.", True, "Automation is listed as a benefit.", "Quantitative"),
        ("Likelihood can be expressed as a number between 0.1 and 1.0 or between 1 and 100.", True, "Both scales are given in the slides.", "Risk determination"),
        ("In the risk determination formula, the percentage of risk already controlled is added to the risk.", False, "It is subtracted; the element of uncertainty is added.", "Risk determination"),
        ("The ranked risk worksheet is the initial working document for assessing and controlling risk.", True, "It feeds the next step in the risk management process.", "Results"),
        ("Critical areas help the RA team focus only on what is important.", True, "Identifying critical areas keeps the team focused.", "Components"),
    ],
    "fill": [
        ("ALE is calculated by multiplying SLE by ________.", "ARO", ["aro", "annual rate of occurrence"], "ALE = SLE × ARO.", "Quantitative"),
        ("________ is the likelihood that a threat will exploit a vulnerability.", "Probability", ["probability", "likelihood"], "Probability (likelihood) is one of the two qualitative dimensions.", "Qualitative"),
        ("The three critical components of a risk assessment are scope, critical areas and ________.", "team", ["team"], "Scope, critical areas, and team.", "Components"),
        ("Risk level in qualitative assessment = Probability × ________.", "Impact", ["impact"], "Risk level = probability × impact.", "Qualitative"),
        ("The ________ criteria analysis worksheet assigns a ranked value or impact weight to each information asset.", "weighted", ["weighted"], "The weighted criteria analysis worksheet ranks asset values.", "Results"),
    ],
    "calc": [
        ("SLE is $5,000 and ARO is 12. What is the ALE (in dollars)?", "60,000", ["60000", "60,000"], "5,000 × 12 = 60,000.", "Quantitative"),
        ("Laptops are worth $2,000 and one is stolen each quarter. What is the ALE?", "8,000", ["8000", "8,000"], "SLE 2,000 × ARO 4 = 8,000.", "Class activity"),
        ("ALE before = $8,000, ALE after = $2,000, control cost = $1,000. What are the savings with the control?", "5,000", ["5000", "5,000"], "8,000 − 2,000 − 1,000 = 5,000.", "Class activity"),
        ("Asset value 50, likelihood 1.0, no controls, data 90% accurate. Using the risk determination formula, what is the risk?", "55", ["55"], "50×1.0 = 50; −0 + 10%(50) = 5; risk = 55.", "Risk determination"),
        ("Asset value 100, likelihood 0.5, 50% already controlled, data 80% accurate. What is the risk?", "35", ["35"], "Base 50; −25 (50% controlled) + 10 (20% uncertainty) = 35.", "Risk determination"),
        ("Asset value 80, likelihood 0.5, 25% already controlled, data 90% accurate. What is the risk?", "34", ["34"], "Base 40; −10 (25%) + 4 (10%) = 34.", "Risk determination"),
    ],
    "match": [
        ("Match each quantitative term to its meaning.", "Quantitative", [
            ("SLE", "Loss expected from a single incident"),
            ("ARO", "Number of incidents expected per year"),
            ("ALE", "Expected loss for a year"),
            ("Safeguard value", "Cost of a control"),
        ]),
        ("Match each RA component or deliverable to its description.", "Components and results", [
            ("Scope", "Boundary of what the RA includes"),
            ("Critical areas", "Important parts the team must focus on"),
            ("Team", "Independent of those who fix deficiencies"),
            ("Ranked vulnerability risk worksheet", "Risk rating per uncontrolled asset–vulnerability pair"),
        ]),
    ],
    "short": [
        ("Compare quantitative and qualitative risk assessment, including one benefit and one limitation of each.",
         ["objective", "subjective", "dollar", "expert", "data", "quick"],
         "Quantitative RA is objective: it uses actual dollar values and formulas (SLE, ARO, ALE). Its results are accurate, verifiable, and automatable, but it needs large amounts of data that aren't always available. Qualitative RA is subjective: experts rate probability and impact with words or percentages. It is quick to complete but depends on expert opinion and is less precise.",
         "Methods"),
        ("A company loses about 6 USB drives a year, each costing $500 including data. Encryption software costing $1,200 a year would cut losses to 2 drives a year. Should they buy it? Show your working.",
         ["3000", "1000", "1200", "800", "sle", "ale"],
         "SLE = $500. ALE before = 500 × 6 = $3,000. ALE after = 500 × 2 = $1,000. Savings = 3,000 − 1,000 − 1,200 = $800. Savings are positive, so buying the encryption software is justified.",
         "Class activity"),
        ("Explain the three critical components of a risk assessment and why each matters.",
         ["scope", "boundary", "critical", "focus", "team", "conflict"],
         "Scope defines the boundary of the RA (what is and isn't included) and keeps it on track. Critical areas identify the important parts inside the scope, such as a web server's single point of failure, so the team focuses on what matters. The team should not be the people responsible for fixing deficiencies, avoiding a conflict of interest, although their input is valuable.",
         "Components"),
    ],
}
