"""CYS403 Chapter 6 content, built by scripts/build_cys403_study_tools.py."""
from cys403_study.blocks import defs, flow, h3, key, mnemonic, p, steps, table, tip, ul, vs

NUMBER = 6
TITLE = "Performing Risk Assessment"
SLUG = "performing-risk-assessment"
SUMMARY = "preparing for a risk assessment (defining the assessment, reviewing previous findings, identifying the management structure), the eight-step RA plan, replacement and recovery value, identifying threats, vulnerabilities and countermeasures, mitigating recommendations, POAM, and best practices."
HOOK = "From Plan to POAM:"
GRADIENT = "Performing a Risk Assessment"
SUB = "A detailed plan for running a real risk assessment: what to prepare, the eight steps to follow, how to value assets and find threats, vulnerabilities and controls, and how to present results to management."
CHIPS = ["Preparation", "Operational Characteristics", "Eight-Step Plan", "Replacement vs Recovery", "Vulnerability Assessment", "POAM"]

SECTIONS = [
    ("Preparation", "Prepare for the Risk Assessment", [
        p("Before progressing with the RA, you need to complete <strong>three preliminary actions</strong>:"),
        steps(("Define the assessment", "Decide what you are assessing and describe it as it is now."),
              ("Review previous findings", "Start from where others ended."),
              ("Identify the management structure", "Understand who owns and controls what.")),
        mnemonic("D-R-I", f"{key('Define, Review, Identify')}: define the system, review old reports, identify the owners."),
    ]),
    ("Define", "Define the Assessment", [
        ul("Will you assess a <strong>SYSTEM</strong> or a <strong>PROCESS</strong>?",
           "Because things always change, <strong>describe the system or process as its current situation</strong>.",
           "Focus on two primary areas:"),
        vs(("Operational characteristics", "Define <strong>how the system operates in your environment</strong>. Ask the relevant entities: <em>Do you have current diagrams that show all of the current systems? Do you have documentation of the current configuration?</em>", "a"),
           ("Mission of the system", "A <strong>short sentence describing what the system does</strong>, without much detail. Compared to operational characteristics, <strong>the mission is easy to define</strong>.", "c")),
        h3("Example: the email server", "b"),
        p("<strong>Operational characteristics</strong>: two email servers, an internal server and one in the DMZ, with their connections shown in a network diagram."),
        p("<strong>Mission</strong>: the e-mail server provides all e-mail services for the network, including:"),
        ul("Routing e-mail between internal clients", "Accepting e-mail from external servers and routing it to internal clients",
           "Accepting e-mail from internal clients and routing it to external servers", "Scanning all attachments and removing malware", "Scanning all e-mail for spam and stripping confirmed spam"),
    ]),
    ("Review", "Review Previous Findings", [
        p("<strong>Start from where the others ended.</strong> Earlier reports can contain a lot of valuable information that makes your job easier: <strong>assets, threats, vulnerabilities, recommendations, and controls</strong>."),
        table(["Pay attention to", "What it tells you"],
              ["<strong>Recommendations</strong>", "Previous recommendations give insight into several issues."],
              ["<strong>Current status of accepted recommendations</strong>", "Measure the <strong>effectiveness</strong> of recommendations in place; find the <strong>justification</strong> for those not in place."],
              ["<strong>Unapproved recommendations</strong>", "Insight into the business: the <strong>level of residual risk</strong> accepted and the organization's <strong>receptiveness to the control</strong>."]),
        tip("info", "Why unapproved matters", "If management rejected a control before, that tells you how much residual risk they tolerate and how likely a similar recommendation is to be approved."),
    ]),
    ("Structure", "Identify the Management Structure", [
        p("The management structure refers to <strong>how responsibilities are assigned</strong>. When you define the RA scope, it's helpful to <strong>keep the scope within the ownership of a single entity</strong>."),
        p("Ask: <strong>is IT controlled by one entity or by multiple entities?</strong> Responsibilities may be split across:"),
        ul("Network infrastructure", "User and computer management", "E-mail servers", "Web servers", "Database servers",
           "Configuration and change management (systematic and consistent, with proper documentation)"),
        tip("warn", "Don't cross management lines", "If the scope spans several owners, recommendations have no single decision maker. Match the RA to the management structure."),
    ]),
    ("Plan", "The Risk Assessment Plan: Eight Steps", [
        p("<strong>RA is not a one-day project</strong>; it is a continuous process that takes time and planning."),
        steps(("Identify assets and activities to address", ""), ("Identify and evaluate relevant threats", ""), ("Identify and evaluate relevant vulnerabilities", ""),
              ("Identify and evaluate relevant countermeasures", ""), ("Assess threats, vulnerabilities, and exploits", ""), ("Evaluate risks", ""),
              ("Develop recommendations to mitigate risks", ""), ("Present recommendations to management", "")),
        mnemonic("A-T-V-C then Assess, Evaluate, Recommend, Present", f"{key('Assets → Threats → Vulnerabilities → Countermeasures')}, then {key('Assess → Evaluate → Recommend → Present')}."),
    ]),
    ("Assets", "Step 1: Identify and Value Assets", [
        ul("<strong>Evaluate only assets within the boundary of the RA.</strong>",
           "<strong>Scope creep</strong> occurs when you start evaluating assets outside the scope, which <strong>wastes time and resources</strong>."),
        h3("Two perspectives on asset value", "b"),
        defs(("Replacement value", "The <strong>cost to purchase a new asset</strong> in its place. Example: a failed or stolen laptop costs <strong>$1,500</strong> to replace with similar hardware and software."),
             ("Recovery value", "The <strong>cost to get the asset operational after a failure</strong>. Example: replace a failed hard drive, reinstall the OS, and restore data. <strong>Include downtime</strong>: a 2-hour repair on a web server earning $10,000/hour adds <strong>$20,000</strong>.")),
        h3("Elements to consider when valuing assets", "c"),
        table(["Element", "What to consider"],
              ["System access and availability", "Available 24/7 or only during office hours"],
              ["System functions", "Automated, or requires interaction"],
              ["Hardware and software assets", "Their cost and role"],
              ["Personnel assets", "Stable organizations vs high turnover; <strong>high turnover brings more cybersecurity issues</strong>"],
              ["Data and information assets", "Data classification to know each item's protection level"],
              ["Facilities and supplies", "Insurance; redundancy with <strong>hot, warm, and cold sites</strong>"]),
        tip("exam", "Replacement vs recovery", "Replacement buys a <em>new</em> asset. Recovery <em>repairs</em> the existing one and must include lost revenue during downtime."),
    ]),
    ("Threats and Vulnerabilities", "Steps 2–3: Threats and Vulnerabilities", [
        h3("Identifying and evaluating relevant threats", "a"),
        vs(("Review historical data", "Past <strong>attacks, natural events, equipment failures, and accidents</strong>.", "a"),
           ("Threat modeling", "Structured methods such as STRIDE, attack trees, or OCTAVE (Chapter 3).", "c")),
        h3("Identifying and evaluating relevant vulnerabilities", "b"),
        p("A <strong>vulnerability assessment</strong> gathers and captures information:"),
        table(["Goal", "Technique"],
              ["Identify the IP addresses in use", "PING"],
              ["Identify domain names", "WHOIS"],
              ["Identify the running operating system", "Fingerprint attack"],
              ["Identify weak passwords", "Password cracking"],
              ["Identify open ports", "Port scan"],
              ["Capture data", "NMAP, NESSUS, SATAN, SAINT"]),
        p("An <strong>exploit assessment</strong> goes further and actually tests whether weaknesses can be exploited, through <strong>penetration testing</strong>."),
        tip("warn", "Vulnerability vs exploit assessment", "A vulnerability assessment <em>finds</em> weaknesses. An exploit assessment (penetration test) <em>proves</em> they can be exploited."),
    ]),
    ("Countermeasures", "Step 4: Identify and Evaluate Countermeasures", [
        defs(("In-place controls", "Controls <strong>currently installed</strong> in the operational system."),
             ("Planned controls", "Controls with a <strong>specified implementation date</strong>."),
             ("Control categories", "<strong>Administrative</strong>, <strong>technical</strong>, and <strong>physical</strong> controls.")),
        p("When reviewing all of the controls, <strong>consider their purpose</strong>: whether each is directive, preventive, detective, corrective, or recovery (Chapter 2)."),
        table(["Category", "Examples"],
              ["Administrative", "Policies, procedures, security awareness training, background checks"],
              ["Technical", "Firewalls, encryption, IDS, access control lists"],
              ["Physical", "Locks, guards, CCTV, fire suppression"]),
    ]),
    ("Recommendations", "Steps 7–8: Recommend and Present", [
        h3("Develop mitigating recommendations", "a"),
        ul("Based on <strong>threat/vulnerability pairs</strong>", "Include an <strong>estimate of cost and time to implement</strong>", "Include an <strong>estimate of operational impact</strong>", "Justify with a <strong>cost-benefit analysis</strong>"),
        h3("Present the risk assessment results", "b"),
        flow("Phase 1: ranked risk list to top management for approval", "Phase 2: POAM"),
        defs(("Phase one", "The <strong>list of ranked risks</strong> is submitted to <strong>top management for approval</strong>."),
             ("Phase two: POAM", "<strong>Plan Of Actions and Milestones</strong>: how to implement the approved items within the given <strong>budget and time</strong>.")),
    ]),
    ("Best Practices", "Best Practices for Performing Risk Assessments", [
        steps(("Ensure systems are fully described", ""), ("Review past audits", ""), ("Review past risk assessments", ""),
              ("Match the RA to the management structure", "Ownership and responsibilities; don't cross management lines."),
              ("Identify assets within the RA boundaries", ""), ("Identify and evaluate relevant threats", ""),
              ("Identify and evaluate relevant vulnerabilities", ""), ("Identify and evaluate countermeasures", ""),
              ("Track the results", "With a POAM.")),
    ]),
]

TIPS = [
    ("Three preliminary actions", "Define the assessment, review previous findings, identify the management structure."),
    ("Operational characteristics vs mission", "Characteristics = how the system operates (diagrams, configuration docs). Mission = one short sentence of what it does; easier to define."),
    ("Previous findings", "Look at recommendations, the status of accepted ones (effectiveness / justification), and unapproved ones (residual risk, receptiveness)."),
    ("Management structure", "Keep the scope within one owner; don't cross management lines."),
    ("Eight steps", "Assets, threats, vulnerabilities, countermeasures, assess, evaluate, recommend, present."),
    ("Asset value", "Replacement = buy new ($1,500 laptop). Recovery = repair + downtime (2 h × $10,000 = $20,000)."),
    ("Vulnerability tools", "PING (IPs), WHOIS (domains), fingerprinting (OS), password cracking, port scan; NMAP, NESSUS, SATAN, SAINT. Exploit assessment = penetration testing."),
    ("Presenting results", "Phase 1: ranked risks to top management. Phase 2: POAM (Plan Of Actions and Milestones)."),
]

QUICK = [
    ["Preliminary actions", "Define the assessment; review previous findings; identify the management structure."],
    ["System or process", "Decide which is assessed; describe it as it currently is."],
    ["Operational characteristics", "How the system operates; current diagrams and configuration documentation."],
    ["Mission", "Short sentence of what the system does."],
    ["Previous findings", "Recommendations; status of accepted ones; unapproved ones."],
    ["Management structure", "How responsibilities are assigned; keep scope within one entity."],
    ["RA plan", "8 steps from identifying assets to presenting recommendations."],
    ["Scope creep", "Evaluating assets outside the RA boundary; wastes time and resources."],
    ["Replacement value", "Cost to buy a new asset in its place."],
    ["Recovery value", "Cost to make an asset operational again, including downtime."],
    ["Valuation elements", "Access/availability, functions, hardware/software, personnel, data classification, facilities (insurance, hot/warm/cold sites)."],
    ["Threat identification", "Historical data or threat modeling."],
    ["Vulnerability assessment", "PING, WHOIS, fingerprinting, password cracking, port scan, NMAP/NESSUS/SATAN/SAINT."],
    ["Exploit assessment", "Penetration testing."],
    ["Countermeasures", "In-place, planned; administrative, technical, physical."],
    ["Recommendations", "T/V pairs, cost and time, operational impact, cost-benefit analysis."],
    ["POAM", "Plan Of Actions and Milestones: implementing approved items within budget and time."],
]

BRANCHES = [
    ("Preparation", "Three preliminary actions.", [
        ("Define the Assessment", "Step", "Decide whether you assess a system or a process, and describe it as it currently is."),
        ("Operational Characteristics", "Step", "How the system operates in your environment. Ask for current diagrams and configuration documentation."),
        ("System Mission", "Step", "A short sentence of what the system does, e.g. the email server routes internal and external mail and scans for malware and spam."),
        ("Review Previous Findings", "Step", "Start where others ended: recommendations, status of accepted ones, and unapproved ones (residual risk and receptiveness)."),
        ("Management Structure", "Step", "How responsibilities are assigned; keep the scope within a single owner (network, users, email, web, database, change management)."),
    ]),
    ("The Eight-Step Plan", "RA takes time and planning.", [
        ("Steps 1–4", "Process", "Identify assets and activities; identify and evaluate threats, vulnerabilities, and countermeasures."),
        ("Steps 5–8", "Process", "Assess threats, vulnerabilities, and exploits; evaluate risks; develop recommendations; present them to management."),
        ("Not a One-Day Project", "Key Idea", "Risk assessment is a continuous process that needs time and planning."),
    ]),
    ("Asset Valuation", "", [
        ("Stay in Scope", "Rule", "Evaluate only assets within the RA boundary. Scope creep wastes time and resources."),
        ("Replacement Value", "Value", "Cost to buy a new asset in its place, e.g. $1,500 for a laptop."),
        ("Recovery Value", "Value", "Cost to make the asset operational again, including downtime: 2 hours × $10,000/hour = $20,000."),
        ("Valuation Elements", "Checklist", "Access and availability, functions, hardware and software, personnel (turnover), data classification, facilities (insurance, hot/warm/cold sites)."),
    ]),
    ("Threats and Vulnerabilities", "", [
        ("Threat Identification", "Method", "Review historical data (attacks, natural events, equipment failure, accidents) or use threat modeling."),
        ("Vulnerability Assessment", "Method", "PING for IPs, WHOIS for domains, fingerprinting for OS, password cracking, port scans; tools NMAP, NESSUS, SATAN, SAINT."),
        ("Exploit Assessment", "Method", "Penetration testing proves whether weaknesses can be exploited."),
    ]),
    ("Countermeasures", "", [
        ("In-Place and Planned", "Control", "In-place controls are installed now; planned controls have a specified implementation date."),
        ("Control Categories", "Control", "Administrative, technical, and physical."),
        ("Consider the Purpose", "Key Idea", "Review whether each control is directive, preventive, detective, corrective, or recovery."),
    ]),
    ("Results and Best Practices", "", [
        ("Mitigating Recommendations", "Output", "Based on threat/vulnerability pairs, with cost and time estimates, operational impact, and cost-benefit analysis."),
        ("Phase 1: Ranked Risks", "Output", "Submit the ranked risk list to top management for approval."),
        ("Phase 2: POAM", "Output", "Plan Of Actions and Milestones to implement approved items within budget and time."),
        ("Best Practices", "Checklist", "Fully describe systems, review past audits and RAs, match the management structure, stay within boundaries, evaluate threats, vulnerabilities, and countermeasures, and track results with a POAM."),
    ]),
]

QUIZ = {
    "mcq": [
        ("Which is NOT one of the three preliminary actions before performing an RA?",
         ["Define the assessment", "Review previous findings", "Identify the management structure", "Purchase a vulnerability scanner"], 3,
         "The three preliminary actions are defining the assessment, reviewing previous findings, and identifying the management structure.", "Preparation"),
        ("A short sentence describing what a system does, without much detail, is the system's:",
         ["Operational characteristics", "Mission", "Scope", "Baseline"], 1, "The mission is a short, easy-to-define statement of what the system does.", "Define"),
        ("Asking 'Do you have documentation of the current configuration?' helps define the system's:",
         ["Mission", "Operational characteristics", "Replacement value", "POAM"], 1, "These questions gather operational characteristics: how the system operates in your environment.", "Define"),
        ("Unapproved recommendations from a previous RA give insight into:",
         ["The replacement value of assets", "The level of residual risk and the organization's receptiveness to the control", "The number of open ports", "The CVSS score"], 1,
         "Unapproved recommendations show the accepted residual risk and receptiveness to controls.", "Review"),
        ("Why should the RA scope be kept within the ownership of a single entity?",
         ["It lowers software licensing costs", "So recommendations have one clear decision maker and don't cross management lines", "Because PING only works on one network", "To avoid using threat modeling"], 1,
         "Matching the RA to the management structure avoids crossing management lines.", "Structure"),
        ("Evaluating assets outside the boundary of the RA is called:",
         ["Scope creep", "Privilege elevation", "Residual risk", "Exploit assessment"], 0, "Scope creep wastes time and resources.", "Assets"),
        ("A web server earning $10,000 per hour is down for 2 hours while its hard drive is replaced. The $20,000 of lost revenue belongs to its:",
         ["Replacement value", "Recovery value", "Safeguard value", "Mission"], 1, "Recovery value includes the cost of getting the asset operational, including downtime.", "Assets"),
        ("Which technique identifies the running operating system of a target?",
         ["WHOIS", "PING", "Fingerprint attack", "Password cracking"], 2, "Fingerprinting identifies the OS; WHOIS finds domain names; PING finds IP addresses.", "Vulnerabilities"),
        ("An exploit assessment is performed through:",
         ["Penetration testing", "Reviewing previous findings", "Weighted factor analysis", "Writing a mission statement"], 0, "Exploit assessment = penetration testing.", "Vulnerabilities"),
        ("Controls that have a specified implementation date are called:",
         ["In-place controls", "Planned controls", "Detective controls", "Baseline controls"], 1, "Planned controls have a specified implementation date.", "Countermeasures"),
        ("What happens in Phase TWO of presenting the risk assessment results?",
         ["The ranked risk list is submitted to top management", "A POAM is prepared to implement approved items within budget and time", "Threat modeling begins", "Assets are inventoried"], 1,
         "Phase one submits ranked risks for approval; phase two builds the POAM.", "Presenting results"),
        ("Which is the FIRST step of the eight-step RA plan?",
         ["Evaluate risks", "Identify assets and activities to address", "Present recommendations", "Identify countermeasures"], 1, "The plan begins by identifying assets and activities to address.", "RA plan"),
    ],
    "tf": [
        ("A risk assessment is a one-day project.", False, "RA is not a one-day project; it is a continuous process that takes time and planning.", "RA plan"),
        ("The mission of a system is harder to define than its operational characteristics.", False, "Compared to operational characteristics, the mission is easy to define.", "Define"),
        ("Organizations with high employee turnover tend to have more cybersecurity issues.", True, "The slides say high-turnover organizations have higher cybersecurity issues.", "Assets"),
        ("Hot, warm and cold sites are forms of redundancy considered when valuing facilities.", True, "Facilities and supplies include insurance and redundancy (hot, warm, cold sites).", "Assets"),
        ("NMAP, NESSUS, SATAN and SAINT are tools used to capture data in a vulnerability assessment.", True, "They are listed as data-capture tools.", "Vulnerabilities"),
        ("Controls fall into three primary categories: administrative, technical and physical.", True, "Those are the three control categories in the slides.", "Countermeasures"),
        ("Mitigating recommendations should include an estimate of operational impact.", True, "Recommendations include cost and time estimates, operational impact, and CBA.", "Recommendations"),
        ("Reviewing past audits is unnecessary if a new RA is being performed.", False, "Reviewing past audits and past RAs is a listed best practice.", "Best practices"),
    ],
    "fill": [
        ("POAM stands for Plan Of ________ and Milestones.", "Actions", ["action"], "POAM = Plan Of Actions and Milestones.", "Presenting results"),
        ("________ value is the cost to purchase a new asset in place of the old one.", "Replacement", ["replacement"], "Replacement value buys a new asset.", "Assets"),
        ("The ________ tool is used to identify domain names during information gathering.", "WHOIS", ["whois"], "WHOIS identifies domain names.", "Vulnerabilities"),
        ("Before assessing, decide whether you will assess a system or a ________.", "process", ["process"], "The assessment can target a system or a process.", "Define"),
        ("Threats can be identified by reviewing historical data or by threat ________.", "modeling", ["model"], "The two methods are historical data and threat modeling.", "Threats"),
    ],
    "calc": [
        ("A database server earns $5,000 per hour. A failure needs a $800 disk and 3 hours of downtime. What is the recovery value?", "15,800", ["15800", "15,800"], "Downtime 3 × 5,000 = 15,000 plus the 800 disk = 15,800.", "Recovery value"),
        ("A web server generating $10,000 per hour needs 2 hours to repair. How much lost revenue is included in the recovery value?", "20,000", ["20000", "20,000"], "2 × 10,000 = 20,000, as in the slide example.", "Recovery value"),
    ],
    "match": [
        ("Match each vulnerability assessment goal to its technique.", "Vulnerabilities", [
            ("Identify IP addresses in use", "PING"),
            ("Identify domain names", "WHOIS"),
            ("Identify the operating system", "Fingerprint attack"),
            ("Identify open ports", "Port scan"),
            ("Test whether weaknesses can be exploited", "Penetration testing"),
        ]),
        ("Match each item to what it means in the RA process.", "RA process", [
            ("Operational characteristics", "How the system operates in its environment"),
            ("Mission", "Short sentence of what the system does"),
            ("Recovery value", "Cost to restore an asset including downtime"),
            ("Phase one", "Ranked risks submitted to top management"),
            ("POAM", "Plan to implement approved items within budget and time"),
        ]),
    ],
    "short": [
        ("Describe the three preliminary actions before performing a risk assessment.",
         ["define", "system", "process", "previous", "recommendations", "management", "structure"],
         "1) Define the assessment: decide whether a system or process is assessed and describe it as it currently is, covering operational characteristics (how it operates, diagrams, configuration documents) and its mission (a short statement of what it does). 2) Review previous findings: use earlier reports' assets, threats, vulnerabilities, recommendations, the status of accepted recommendations, and unapproved ones. 3) Identify the management structure: how responsibilities are assigned, keeping the scope within a single owner.",
         "Preparation"),
        ("Explain the difference between replacement value and recovery value with an example of each.",
         ["replacement", "purchase", "new", "recovery", "operational", "downtime"],
         "Replacement value is the cost to purchase a new asset in place of the old one, e.g. $1,500 to buy a new laptop after one is stolen. Recovery value is the cost to get an existing asset operational after a failure, including repair and downtime, e.g. replacing a web server's hard drive, reinstalling the OS, restoring backups, and adding $20,000 of revenue lost during a 2-hour outage at $10,000 per hour.",
         "Assets"),
        ("Scenario: You finished a risk assessment of the company's web servers. Explain how you would present the results to management.",
         ["ranked", "top management", "approval", "poam", "budget", "milestones"],
         "Present results in two phases. Phase one: submit the list of ranked risks, with mitigating recommendations based on threat/vulnerability pairs, cost and time estimates, operational impact, and cost-benefit analysis, to top management for approval. Phase two: for the approved items, prepare a POAM (Plan Of Actions and Milestones) showing how and when they will be implemented within the given budget and time, and track results against it.",
         "Presenting results"),
    ],
}
