"""Cumulative CYS403 practice exams, built by scripts/build_cys403_study_tools.py.

Scopes follow the syllabus: Quiz 1 covers Chapters 1–2; the Major exam (week 8) covers
Chapters 1–6. Questions here are new, not copies of the chapter quizzes.
"""

QUIZ_1 = {
    "mcq": [
        ("Which pair of frameworks does Risk IT complement and extend?",
         ["ISO 27001 and NIST CSF", "COBIT and Val IT", "ITIL and Common Criteria", "OCTAVE and PASTA"], 1, "Risk IT complements and extends COBIT and Val IT.", "Ch1 · Frameworks"),
        ("A board of directors approves the organization's long-range security policy. This is which level of planning?",
         ["Operational", "Tactical", "Strategic", "Procedural"], 2, "Strategic planning is long term and high level, e.g. the overall security policy.", "Ch1 · Planning"),
        ("Which element turns functional policies into enforceable actions by specifying the minimum security configuration for a platform?",
         ["Guideline", "Baseline", "Security statement", "Blueprint"], 1, "Baselines ensure a minimum, platform-unique security configuration.", "Ch1 · Implementation"),
        ("Which requirement type is selected based on the risk management process and defines the security behavior of a control?",
         ["Assurance requirement", "Functional requirement", "Business requirement", "Legal requirement"], 1, "Functional requirements define security behavior and are chosen through risk management.", "Ch1 · Security solutions"),
        ("A disgruntled former employee who could harm the company, but has not yet acted, is best described as a:",
         ["Threat agent", "Attacker", "Residual risk", "Exposure"], 0, "A threat agent has the potential to cause a threat; an attacker is the actual cause of an attack.", "Ch2 · Terms"),
        ("Which risk management step uses the Risk Register to monitor, track and review risks?",
         ["Step 2", "Step 3", "Step 4", "Step 5"], 3, "Step 5, monitor and review, uses the Risk Register.", "Ch2 · Steps"),
        ("In the AS/NZS 4360 matrix, a 'rare' (E) likelihood with an 'insignificant' (1) consequence is:",
         ["Low", "Moderate", "High", "Extreme"], 0, "Row E, column 1 is L: routine acceptance.", "Ch2 · Qualitative"),
        ("A company stops offering an online service because its risk is too high. Which mitigation option is this?",
         ["Acceptance", "Reduction", "Transference", "Avoidance"], 3, "Stopping the activity that creates the risk is avoidance.", "Ch2 · Mitigation"),
        ("Restoring data from backup after a ransomware incident is an example of which control type?",
         ["Directive", "Detective", "Recovery", "Preventive"], 2, "Recovery controls restore systems to normal operation.", "Ch2 · Controls"),
        ("Which countermeasure selection principle requires that a safeguard can be tested and audited?",
         ["Sustainability", "Audit capability", "Universal application", "Vendor trustworthiness"], 1, "Audit capability means the safeguard can be tested and audited.", "Ch2 · Selection"),
    ],
    "tf": [
        ("Val IT provides an end-to-end view of all IT-related risks.", False, "That describes Risk IT. Val IT creates business value from IT investments.", "Ch1 · Frameworks"),
        ("Cybersecurity management includes governance and risk management.", True, "Both are listed as parts of cybersecurity management.", "Ch1 · Management"),
        ("Procedures are recommendations that employees may choose to follow.", False, "Procedures are step-by-step actions that must be followed; guidelines are recommendations.", "Ch1 · Implementation"),
        ("Risk management should identify potential risks before they occur and across the life of the project.", True, "That is the stated purpose of risk management.", "Ch2 · Purpose"),
        ("Qualitative risk analysis assigns absolute monetary values to all risk components.", False, "Qualitative analysis does not assign absolute numeric values; quantitative does.", "Ch2 · Qualitative"),
        ("Corrective controls react to a detected incident to reduce the chance of it recurring.", True, "That is the definition of corrective controls.", "Ch2 · Controls"),
    ],
    "fill": [
        ("The three properties protected by cybersecurity are confidentiality, integrity and ________.", "availability", ["availability"], "CIA triad.", "Ch1 · CIA"),
        ("Policies gain credibility through top ________ buy-in.", "management", ["management"], "Top management buy-in gives policies credibility.", "Ch1 · Policy"),
        ("Risk remaining after countermeasures are applied is ________ risk.", "residual", ["residual"], "Residual risk.", "Ch2 · Terms"),
        ("The Delphi technique and bow-tie analysis are ________ risk analysis techniques.", "qualitative", ["qualitative"], "Both are among the five top qualitative techniques.", "Ch2 · Qualitative"),
    ],
    "calc": [
        ("An asset worth $20,000 has an exposure factor of 25%. What is the SLE?", "5,000", ["5000", "5,000"], "SLE = 20,000 × 0.25 = 5,000.", "Ch2 · Quantitative"),
        ("SLE = $5,000 and the threat occurs 6 times a year. What is the ALE?", "30,000", ["30000", "30,000"], "ALE = 5,000 × 6 = 30,000.", "Ch2 · Quantitative"),
        ("ALE before = $30,000, ALE after = $10,000, annual control cost = $12,000. What is the value of the control?", "8,000", ["8000", "8,000"], "30,000 − 10,000 − 12,000 = 8,000, so the control is worth buying.", "Ch2 · Quantitative"),
    ],
    "match": [
        ("Match each term from Chapters 1–2 to its definition.", "Ch1–2 · Terms", [
            ("COBIT", "IT governance model for delivering value and managing IT risk"),
            ("Security blueprint", "Structure for organizing requirements and solutions"),
            ("Attack", "Any actual danger to information or systems"),
            ("Exposure", "Opportunity for a threat to cause loss"),
            ("Risk transference", "Passing risk to a third party"),
        ]),
    ],
    "short": [
        ("Explain the difference between standards, procedures, guidelines and baselines, with one example of each.",
         ["standard", "procedure", "guideline", "baseline", "minimum", "step"],
         "Standards adopt common hardware and software mechanisms enterprise-wide (e.g. one approved anti-virus). Procedures are step-by-step actions that must be followed (e.g. how to reset a password). Guidelines are recommendations for implementation and planning (e.g. ISO 17799, ITIL). Baselines are benchmarks setting a minimum, platform-unique security configuration (e.g. password rules, VPN setup).",
         "Ch1 · Implementation"),
        ("Scenario: A hospital's patient records server faces ransomware. Describe how the five types of security controls could each be applied.",
         ["directive", "preventive", "detective", "corrective", "recovery", "backup"],
         "Directive: an acceptable-use policy and awareness training telling staff not to open suspicious attachments. Preventive: email filtering, patching, and access controls. Detective: an IDS or anti-malware alerts that spot encryption activity. Corrective: isolating infected machines and removing the malware so it doesn't recur. Recovery: restoring patient records from clean backups to return to normal operations.",
         "Ch2 · Controls"),
    ],
}

MAJOR = {
    "mcq": [
        ("According to Chapter 1, cybersecurity governance must be fully integrated into:",
         ["The marketing plan", "Overall risk analysis and management", "The firewall configuration", "Vendor contracts only"], 1, "Governance is fully integrated into overall risk analysis/management.", "Ch1 · Governance"),
        ("Which is an example of a functional policy?",
         ["Remote access policy", "Firewall product standard", "VPN baseline", "ITIL guideline"], 0, "Remote access is one of the functional policies listed.", "Ch1 · Policy"),
        ("The formula 'Value of control = ALE(before) − ALE(after) − ACS' is used to:",
         ["Compute SLE", "Decide whether a control is cost-justified", "Rank DREAD scores", "Classify assets"], 1, "A positive value means the control saves more than it costs.", "Ch2 · Quantitative"),
        ("Which qualitative technique is known as a 'Structured What-If'?",
         ["Delphi", "SWIFT", "Bow-tie", "Decision tree"], 1, "SWIFT = Structured What-If Technique.", "Ch2 · Qualitative"),
        ("Using a stolen session ID cookie to access someone else's session is:",
         ["Session hijacking", "Hidden-field tampering", "Port scanning", "Privilege elevation"], 0, "Session hijacking uses a stolen session ID.", "Ch3 · Application threats"),
        ("Which threat modeling method combines attack trees, STRIDE and CVSS?",
         ["hTMM", "Quantitative TMM", "Trike", "OCTAVE"], 1, "Quantitative TMM applies attack trees, STRIDE, and CVSS in synergy.", "Ch3 · Threat modeling"),
        ("In LINDDUN, being able to identify the sender of an email within a group is:",
         ["Linkability", "Identifiability", "Detectability", "Unawareness"], 1, "Identifiability is identifying the subject within a set of subjects.", "Ch3 · LINDDUN"),
        ("Which Chapter 4 community of interest is responsible for building and maintaining secure systems?",
         ["Cyber security", "Information technology", "Management", "Users"], 1, "IT builds and maintains secure systems.", "Ch4 · Accountability"),
        ("A worksheet listing assets by priority on one axis and threats by priority on the other, recording vulnerabilities in the cells, is the:",
         ["Risk register", "POAM", "TVA worksheet", "Ranked risk worksheet"], 2, "The Threat–Vulnerability–Asset worksheet combines both prioritized lists.", "Ch4 · TVA"),
        ("Which asset attribute is tracked for procedures?",
         ["IP address", "Where it is stored for update purposes", "Security clearance", "Serial number"], 1, "Procedure attributes include description, purpose, related elements, and storage locations for reference and update.", "Ch4 · Inventory"),
        ("A qualitative risk assessment is described as:",
         ["Objective and data heavy", "Subjective and based on expert opinion", "Purely mathematical", "Impossible to complete quickly"], 1, "Qualitative RA is subjective and relies on experts; it is quick.", "Ch5 · Methods"),
        ("In the risk determination formula, if data is 70% accurate, the uncertainty used is:",
         ["70%", "30%", "7%", "0%"], 1, "Uncertainty = 1 − 0.7 = 30%.", "Ch5 · Risk determination"),
        ("A web server's critical area in the RA scope example was:",
         ["Inspection of all traffic", "Single point of failure and OS patch status", "Only data exchanged with the database", "Backup tapes"], 1,
         "Web server: SPOF and OS updates; database: exchanged data; firewall: traffic inspection.", "Ch5 · Components"),
        ("During RA preparation, which information comes from reviewing the current status of ACCEPTED recommendations?",
         ["The organization's receptiveness to rejected controls", "The effectiveness of recommendations in place and justification for those not in place", "The system mission", "IP addresses in use"], 1,
         "Accepted recommendations show effectiveness (in place) and justification (not in place).", "Ch6 · Review"),
        ("Which is the correct order of the last four steps of the RA plan?",
         ["Evaluate risks, assess exploits, present, recommend", "Assess threats/vulnerabilities/exploits, evaluate risks, develop recommendations, present to management",
          "Present, recommend, evaluate, assess", "Identify countermeasures, identify assets, present, evaluate"], 1,
         "Steps 5–8: assess, evaluate risks, develop recommendations, present recommendations.", "Ch6 · RA plan"),
        ("Port scanning and trace routing to detect network topology are threats against the:",
         ["Application", "Host", "Network", "Database"], 2, "They are information-gathering threats against the network.", "Ch3 · Network threats"),
    ],
    "tf": [
        ("Security blueprints are used to identify and design security requirements.", True, "That is one purpose of security blueprints.", "Ch1 · Governance"),
        ("Both quantitative and qualitative risk analysis are often required to get a full picture.", True, "Each has unique capabilities.", "Ch2 · Analysis"),
        ("OCTAVE addresses technological risks rather than organizational risks.", False, "OCTAVE focuses on organizational risks and does not address technological risks.", "Ch3 · OCTAVE"),
        ("In attack trees, special notation is needed to show AND relationships.", True, "Children are ORed by default; AND needs special notation.", "Ch3 · Attack trees"),
        ("Asset values are assigned during asset identification, before the inventory is complete.", False, "Assets are identified without pre-judging value; values come later.", "Ch4 · Inventory"),
        ("A likelihood value of zero is used for vulnerabilities that are very unlikely.", False, "Zero is not used; zero-likelihood vulnerabilities are removed.", "Ch5 · Likelihood"),
        ("Scope creep wastes time and resources by evaluating assets outside the RA boundary.", True, "That is the definition in Chapter 6.", "Ch6 · Assets"),
        ("The POAM is submitted in phase one for top management to approve the ranked risks.", False, "Phase one submits the ranked risk list; the POAM is phase two.", "Ch6 · Presenting results"),
    ],
    "fill": [
        ("________ IT is a governance framework used to create business value from IT investments.", "Val", ["val"], "Val IT.", "Ch1 · Frameworks"),
        ("The step of risk management that creates DRP, BCP and IRP plans is risk ________.", "control", ["control", "response"], "Step 4: risk control (risk response planning).", "Ch2 · Steps"),
        ("The D in STRIDE stands for denial of ________.", "service", ["service"], "STRIDE: Denial of service.", "Ch3 · STRIDE"),
        ("Asset classification categories must be comprehensive and mutually ________.", "exclusive", ["exclusive"], "Comprehensive and mutually exclusive.", "Ch4 · Classification"),
        ("The ________ risk worksheet is the final summary of the risk assessment.", "ranked", ["ranked"], "The ranked (vulnerability) risk worksheet.", "Ch5 · Results"),
        ("Penetration testing is used in an ________ assessment.", "exploit", ["exploit"], "Exploit assessment = penetration testing.", "Ch6 · Vulnerabilities"),
    ],
    "calc": [
        ("A laptop worth $1,800 is stolen twice a year. Locks costing $400 a year would reduce thefts to once a year. What are the annual savings with the locks?", "1,400", ["1400", "1,400"],
         "ALE before = 1,800 × 2 = 3,600; ALE after = 1,800; savings = 3,600 − 1,800 − 400 = 1,400.", "Ch5 · Quantitative"),
        ("Asset value 60, likelihood 0.5, 20% already controlled, data 90% accurate. Using the risk determination formula, what is the risk?", "27", ["27"],
         "Base = 30; − 20% (6) + 10% (3) = 27.", "Ch5 · Risk determination"),
        ("A threat scores Damage 2, Reproducibility 3, Exploitability 3, Affected users 2, Discoverability 1. What is the DREAD total?", "11", ["11"], "2 + 3 + 3 + 2 + 1 = 11.", "Ch3 · DREAD"),
        ("Weights: cost 20, revenue 50, public image 30. An asset scores 0.5, 0.6 and 0.9. What is its weighted score?", "67", ["67"], "10 + 30 + 27 = 67.", "Ch4 · Weighted analysis"),
        ("A payment server earns $4,000 per hour. Recovery needs a $1,000 part and 5 hours of downtime. What is the recovery value?", "21,000", ["21000", "21,000"], "5 × 4,000 = 20,000 + 1,000 = 21,000.", "Ch6 · Recovery value"),
    ],
    "match": [
        ("Match each concept to its chapter topic.", "Ch1–6 · Concepts", [
            ("Three levels of planning", "Strategic, tactical, operational"),
            ("Mitigation options", "Accept, reduce, transfer, avoid"),
            ("DREAD", "Scoring threats to prioritize them"),
            ("TVA worksheet", "Threats, vulnerabilities and assets combined"),
            ("POAM", "Plan Of Actions and Milestones"),
        ]),
        ("Match each quantitative or qualitative term to its meaning.", "Ch2 and Ch5 · Terms", [
            ("SLE", "Asset value multiplied by exposure factor"),
            ("ARO", "Expected incidents per year"),
            ("ALE", "SLE multiplied by ARO"),
            ("Impact", "Magnitude of loss if a risk occurs"),
            ("Likelihood", "Probability a vulnerability is successfully attacked"),
        ]),
    ],
    "short": [
        ("Trace a complete risk management effort from asset identification to presenting results, naming the key deliverable at each stage.",
         ["inventory", "tva", "assessment", "ranked", "recommendations", "poam"],
         "Identify assets (asset inventory) without pre-judging value, classify them (asset classification worksheet), and value and rank them (weighted criteria analysis worksheet). Identify threats and vulnerabilities per asset to build the threat–vulnerability matrix and the TVA worksheet. Perform a quantitative (SLE, ARO, ALE) or qualitative (probability × impact) risk assessment and summarize it in the ranked vulnerability risk worksheet. Develop mitigating recommendations with cost-benefit analysis, present the ranked risks to top management, and implement approved items through a POAM.",
         "Ch4–6 · Lifecycle"),
        ("Scenario: An online store's customer database is worth $200,000. A breach would expose 30% of its value and happens about once every two years. A database activity monitoring tool costs $12,000 a year and would cut the rate to once every ten years. Should the store buy it? Show SLE, ARO, ALE and savings.",
         ["60000", "0.5", "30000", "6000", "12000", "savings"],
         "SLE = 200,000 × 0.30 = $60,000. ARO before = 0.5, so ALE before = $30,000. ARO after = 0.1, so ALE after = $6,000. Savings = 30,000 − 6,000 − 12,000 = $12,000. The savings are positive, so the tool is cost-justified.",
         "Ch2 and Ch5 · Quantitative"),
        ("Using STRIDE, identify one threat in each category for an online banking login page and suggest a control for two of them.",
         ["spoofing", "tampering", "repudiation", "disclosure", "denial", "elevation"],
         "Spoofing: an attacker logs in with stolen credentials (control: multi-factor authentication). Tampering: changing transfer amounts in transit (control: TLS and integrity checks). Repudiation: a user denies making a transfer (audit logging). Information disclosure: error messages reveal account data. Denial of service: flooding the login page. Elevation of privilege: a normal user gains admin functions.",
         "Ch3 · STRIDE"),
        ("Explain why the risk assessment team should be independent, and how the scope should relate to the management structure.",
         ["conflict", "independent", "input", "scope", "single", "owner"],
         "The RA team should not be the people responsible for correcting deficiencies, to avoid a conflict of interest, although their input is important. The scope should be kept within the ownership of a single entity and not cross management lines, so every recommendation has one clear decision maker and the RA can be acted on.",
         "Ch5–6 · Team and scope"),
    ],
}

EXAMS = [
    {"slug": "quiz-1-practice-exam", "label": "Quiz 1 Practice Exam", "short": "Quiz 1", "scope": "Chapters 1–2",
     "heading": "Quiz 1 practice exam (Chapters 1–2)", "quiz": QUIZ_1},
    {"slug": "major-exam-practice", "label": "Major Exam Practice", "short": "Major Exam", "scope": "Chapters 1–6",
     "heading": "Major exam practice (Chapters 1–6)", "quiz": MAJOR},
]
