"""SE311 Chapter 1 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 1
TITLE = "Requirements Engineering Fundamentals"
AR_TITLE = "أساسيات هندسة المتطلبات"
SLUG = "requirements-engineering-fundamentals"
SUMMARY = "Interactive SE311 Chapter 1 mindmap: what requirements engineering is, the ten truths about requirements, project success factors, requirement types, and the RE process."

BRANCHES = [
    ("What Is Requirements Engineering?", "RE defines what a new or evolving system must do and why, before anyone decides how to build it.", [
        ("Definition", "Definition",
         "<strong>Requirements Engineering (RE)</strong> is the activity of development, elicitation, specification, analysis, and management of the stakeholder requirements that a new or evolving system must meet."),
        ("Purpose and Context", "Key Idea",
         "RE identifies the <strong>purpose</strong> of a software system and the <strong>contexts</strong> in which it will be used.",
         "A system is assessed by the extent to which it satisfies the purpose for which it was intended."),
        ("What Is a Requirement?", "Definition",
         "A <strong>requirement</strong> is a statement that translates or expresses a need together with its associated constraints and conditions."),
        ("Why It Matters", "Key Fact",
         "Errors in requirements account for <strong>40–50% of all defects</strong> in software products.",
         "If the requirements are wrong, it does not matter how well the rest of the project is executed."),
    ]),
    ("Ten Truths About Requirements", "Ten principles that frame how analysts should think about requirements work.", [
        ("#1–2: Right and Discovered", "Truths",
         "<strong>#1</strong> If you don't get the requirements right, it doesn't matter how well you execute the rest of the project.",
         "<strong>#2</strong> Requirements development is a <em>discovery and invention</em> process, not just a collection process."),
        ("#3–4: Change and Stakeholders", "Truths",
         "<strong>#3</strong> Change happens.",
         "<strong>#4</strong> The interests of all project stakeholders intersect in the requirements process."),
        ("#5–6: The Customer", "Truths",
         "<strong>#5</strong> Customer involvement is the most critical contributor to software quality.",
         "<strong>#6</strong> The customer is not always right, but the customer always has a point."),
        ("#7–8: Scope and Dialogue", "Truths",
         "<strong>#7</strong> The first question to ask about a proposed new requirement is: <em>“Is this requirement in scope?”</em>",
         "<strong>#8</strong> Even the best requirements document cannot, and should not, replace human dialogue."),
        ("#9–10: Never Perfect", "Truths",
         "<strong>#9</strong> The requirements might be vague, but the product will be specific.",
         "<strong>#10</strong> You're never going to have perfect requirements."),
    ]),
    ("Project Success and Failure", "The same requirements issues sit at the top of both lists.", [
        ("Top 10 Success Factors", "Success",
         "User involvement, executive management support, clear statement of requirements, proper planning, realistic expectations, smaller project milestones, competent staff, ownership, clear vision and objectives, and hard-working focused staff."),
        ("Top 10 Challenged Factors", "Failure",
         "Lack of user involvement, incomplete requirements and specifications, changing requirements and specifications, lack of executive support, technology incompetence, lack of resources, unrealistic expectations, unclear objectives, unrealistic timeframe, and new technology."),
        ("The Mirror Image", "Exam Tip",
         "<strong>User involvement</strong> is the #1 success factor, and its absence is the #1 cause of challenged projects.",
         "Two of the top three challenged factors are requirements problems: incomplete and changing requirements."),
    ]),
    ("Types of Requirements", "From why the system exists down to the conditions it must operate under.", [
        ("Business Requirements", "Type",
         "Answer <strong>why</strong> the system is being implemented.",
         "Example: “Airline wants to reduce airport counter staff costs by 25 percent.”"),
        ("User Requirements", "Type",
         "Describe goals or tasks the user must be able to perform with the product.",
         "Example: “User needs to be able to check in for a flight using the airline's website.”"),
        ("Functional Requirements", "Type",
         "Specify the <strong>behaviors</strong> the product will exhibit under specific conditions.",
         "Example: “If the passenger's profile does not indicate a seating preference, the reservation system shall assign a seat.”"),
        ("System Requirements", "Type",
         "Requirements for a product composed of multiple components or subsystems.",
         "Example: “The airport check-in kiosks need a barcode reader to scan a passport.”"),
        ("Non-Functional Requirements", [
            ("Quality Attributes", "NFR",
             "Product characteristics such as performance, safety, availability, and compatibility; they describe <strong>how well</strong> the product works.",
             "Example: “Flight search results should load within 5 seconds.”"),
            ("External Interfaces", "NFR",
             "Connections between the system and the outside world.",
             "Example: “A link to the Tawakkalna database to verify COVID-19 status.”"),
            ("Constraints", "NFR",
             "Restrictions on the developer's options during construction.",
             "Example: “System shall conform to MIL-STD-498.”"),
        ]),
        ("Application-Domain Requirements", "Type",
         "Derived from the application domain; they reflect domain characteristics and may add functional requirements, constrain existing ones, or define specific computations.",
         "If they are not satisfied the system may be <strong>unworkable</strong>. Example: “A patient's designated physician is the only entity allowed to retrieve a patient's medical reports.”"),
    ]),
    ("The RE Process", "Inception → Elicitation → Analysis → Specification → Validation, with Management running throughout.", [
        ("Inception", "Activity",
         "Starts the process from a business need, market opportunity, or great idea: business case, feasibility study, system scope, and risks."),
        ("Elicitation", "Activity",
         "Requirements are discovered through consultation with stakeholders."),
        ("Analysis and Negotiation", "Activity",
         "Requirements are analyzed and conflicts are resolved through negotiation."),
        ("Specification", "Activity",
         "A precise requirements document is produced."),
        ("Validation", "Activity",
         "The requirements document is checked for consistency and completeness."),
        ("Management", "Activity",
         "Runs throughout: needs and contexts evolve, and so do the requirements."),
    ]),
    ("Problems in the RE Process", "", [
        ("Lack of Expertise", "Problem",
         "Requirements engineers often lack domain expertise for the profession they are specifying."),
        ("Incomplete Initial Ideas", "Problem",
         "Stakeholders may not know exactly what they want, so early ideas are incomplete."),
        ("Complex Tools", "Problem",
         "Complex methods and tools for gathering requirements may negate their anticipated benefits."),
    ]),
    ("Exam Practice", "Questions from quizzes, the midterm, and Major 1.", [
        ("Managing Requirements", "Past Exam · Quiz 2",
         "<strong>Baseline</strong>: a formally reviewed, agreed, non-modifiable version of the requirements; the reference point for managing change.",
         "<strong>Synchronicity</strong>: all requirement artifacts stay consistent when one changes. <strong>Status tracking</strong>: each requirement is proposed, approved, implemented, verified, or deleted."),
        ("Not an RE Step", "Past Exam · Midterm",
         "Options: Elicitation, Design, Analysis, Documentation. Answer: <strong>Design</strong>.",
         "RE is about what to build; design is about how to build it."),
        ("Who Is a Stakeholder?", "Past Exam · Midterm",
         "“A stakeholder is anyone who will purchase the system.” <strong>False</strong>.",
         "A stakeholder is anyone with an interest in or affected by the project: users, developers, managers, domain experts, testers, and more."),
        ("Not in a Good SRS", "Past Exam · Midterm",
         "Answer: <strong>Algorithm for software implementation</strong>. An SRS states what the system does, not how it is implemented."),
        ("Collecting Quality Requirements", "Past Exam · Major 1",
         "Problems: we lack expertise in many professions; experienced engineers and domain experts are not always available; stakeholders are not always available.",
         "Some stakeholders see us as a threat to their job and won't cooperate; many important requirement areas are hard to specify clearly."),
    ]),
]
