"""SE311 Chapter 2 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 2
TITLE = "Requirements Inception"
AR_TITLE = "بدء المتطلبات"
SLUG = "requirements-inception"
SUMMARY = "Interactive SE311 Chapter 2 mindmap: requirements inception, the Vision and Scope document, scope representation techniques, stakeholders, and constraints."

BRANCHES = [
    ("What Is Inception?", "Inception = Vision + Scope + Business Case.", [
        ("Definition", "Definition",
         "The initial RE phase that establishes a <strong>shared understanding</strong> of the product's context: its underlying problem, proposed solution, boundaries, and benefits."),
        ("Larman's View", "Key Idea",
         "Do just enough investigation to form a rational, justifiable opinion of the overall purpose and feasibility of the new system, and decide whether deeper exploration is worth the investment."),
        ("The One-Sentence Summary", "Exam Tip",
         "Requirements inception = <strong>agree on a well-defined project's vision, scope, and business case</strong>."),
        ("Why It Matters", "Key Idea",
         "“A project without a clearly defined and well-communicated direction invites disaster.”",
         "Without inception: work on unaligned objectives, stakeholders disagreeing on requirements, missed deadlines and budget overruns, and incomplete or incorrect systems."),
    ]),
    ("1. Business Requirements", "The primary benefits the system gives its sponsors, buyers, and users.", [
        ("Business Opportunity", "V and S 1.1",
         "The situation driving the project. <strong>Corporate</strong>: the business problem and environment. <strong>Commercial</strong>: the market opportunity.",
         "Example: manual order processing causes delays (corporate); online retail grows 25% a year and competitors offer 24/7 shopping (commercial)."),
        ("Business Objectives", "V and S 1.2",
         "Business benefits stated in a <strong>quantitative, measurable</strong> way.",
         "Problems say what keeps the business from its goals; objectives define how achievement is measured. They are intertwined. Example: process at least 500 orders/day within 6 months, up from 100."),
        ("Success Metrics", "V and S 1.3",
         "Indicators that show whether the project is on track to meet its business objectives.",
         "Examples: 99.9% uptime, page load under 2 seconds, 50% fewer order-related service calls, 150% ROI in year one."),
        ("Vision Statement", "V and S 1.4",
         "Summarizes the long-term purpose of the project. It should be balanced across stakeholders, idealistic yet grounded in reality, and clear and inspiring."),
        ("Moore's Vision Template", "Template",
         "<strong>For</strong> [target customer] <strong>Who</strong> [need] <strong>The</strong> [product name] <strong>Is</strong> [category] <strong>That</strong> [key benefit] <strong>Unlike</strong> [competitive alternative] <strong>Our product</strong> [primary differentiation].",
         "Example: For small to medium online retailers who need to automate fulfillment, the SmartFulfill System is an integrated e-commerce platform that cuts processing time 80%…"),
        ("Risks, Assumptions, Dependencies", "V and S 1.5–1.6",
         "<strong>Business risks</strong>: factors that could threaten success. <strong>Assumptions and dependencies</strong>: what is assumed true and the external factors the project relies on.",
         "Sources of business requirements: funding sponsors, marketing managers, corporate executives, and product visionaries."),
    ]),
    ("2. Scope and Limitations", "What the solution will do, and what it will not.", [
        ("Vision vs Scope", "Comparison",
         "<strong>Product vision</strong>: the ultimate product, applies to the whole product, relatively static, long-term.",
         "<strong>Project scope</strong>: the portion the current project or iteration addresses, more dynamic, short-term deliverables. Vision encompasses the scope of every planned release."),
        ("Levels of Scope", "Key Idea",
         "Highest: which business objectives to target. Lower: features, use cases, or events to include. Lowest: functional requirements planned for a release.",
         "In-scope user requirements map to business objectives, and functional requirements map to in-scope user requirements: this is <strong>traceability</strong>."),
        ("Major Features and Initial Release", "V and S 2.1–2.2",
         "List major features without unnecessary detail. The initial release favors most value to stakeholders, acceptable cost, large community impact, and earliest feasible time frame."),
        ("Subsequent Releases", "V and S 2.3",
         "Build a release roadmap. The current release's scope is clear; later releases get fuzzier the farther out you look."),
        ("Limitations and Exclusions", "V and S 2.4",
         "Features stakeholders might expect but that are not planned: cut items, deferred functionality, and out-of-scope items needing explicit clarification."),
        ("New Requirements Mid-Project", "Key Idea",
         "Evaluate each new requirement against the defined scope. High-priority in-scope requirements can be added, but usually by deferring others or negotiating a new schedule."),
    ]),
    ("3. Business Context", "", [
        ("Stakeholder Profiles", "V and S 3.1",
         "Each profile states the major <strong>value</strong> the stakeholder expects, their expected <strong>attitude</strong> toward the product, and <strong>restrictions</strong> that must be built in.",
         "Example (customers): value is fast, easy shopping; attitude is enthusiastic but security-conscious; restrictions include mobile support and accessibility."),
        ("Project Priorities", "V and S 3.2",
         "Stakeholders must agree on project priorities. When changing a feature, check its priority first."),
        ("Deployment Considerations", "V and S 3.3",
         "Summarizes the information required when publishing the system."),
    ]),
    ("Scope Representation", "Visual techniques for communicating scope; follow a notation standard.", [
        ("Context Diagram", "Technique",
         "Shows the boundary between the system and everything else. No visibility into internal objects, processes, or data.",
         "Identifies external entities (terminators: user classes, organizations, other systems, hardware devices) and the data, control, and material flows between them and the system."),
        ("Ecosystem Map", "Technique",
         "Shows all systems related to the system and the interactions among them. Find them by asking which systems consume your data or supply it."),
        ("Context Diagram vs Ecosystem Map", "Comparison",
         "Context diagram: external entities that <strong>directly</strong> interface with the system; immediate connections only.",
         "Ecosystem map: systems related <strong>directly or indirectly</strong>; the broader picture."),
        ("Feature Tree", "Technique",
         "Groups features logically and subdivides each hierarchically, up to three levels (L1, L2, L3).",
         "A release's scope is a chosen set of features from the tree. Start broad at L1 and go deeper only for current-release features."),
        ("Event List", "Technique",
         "External events that trigger system behavior: <strong>user-triggered</strong> (submit order), <strong>time-triggered</strong> (end-of-day report), and <strong>signal</strong> events from external components (low-inventory alert).",
         "Responses are detailed in the SRS; a release's scope can be defined by which events it handles."),
    ]),
    ("Stakeholders and Constraints", "", [
        ("Finding Stakeholders", "Checklist",
         "Who uses the system? Who is the customer? Who is affected by outputs? Who evaluates or approves it? Other internal or external users? Who maintains it? Anyone else who cares, such as legal or regulatory bodies?"),
        ("Riyadh Season Stakeholders", "Past Exam",
         "Event organizers, traditional ticket agencies, customers and attendees, Secure Payment Inc., the website/IT team, terminal operators, venue vendors, security personnel, and government regulators."),
        ("What a Constraint Is", "Definition",
         "A restriction on the solution space that limits the ability to deliver the solution as envisioned; usually a non-functional requirement imposing major restrictions."),
        ("Six Sources of Constraints", "Checklist",
         "<strong>Economics</strong> (budget ≤ $500,000), <strong>politics</strong>, <strong>technology</strong> (must integrate with Oracle), <strong>systems</strong> (legacy compatibility), <strong>environment</strong> (GDPR), and <strong>schedule and resources</strong> (launch by Oct 1)."),
    ]),
    ("Tips and Pitfalls", "", [
        ("Why Before What", "Tip",
         "Understand the business problem before jumping to solutions, and make objectives SMART: Specific, Measurable, Achievable, Relevant, Time-bound."),
        ("Out of Scope Is Scope", "Tip",
         "Define what is out of scope as clearly as what is in; it manages expectations and prevents scope creep.",
         "Get sign-off on the Vision and Scope document before detailed requirements work."),
        ("Skipping Inception", "Pitfall",
         "“Everyone knows what we need” leads to misaligned expectations and rework."),
        ("Confusing Vision and Scope", "Pitfall",
         "Vision is long-term and stable; scope is specific to a release. A vision that is too vague or too detailed also misses the sweet spot."),
        ("Everything Equally Important", "Pitfall",
         "Treating all requirements as equal makes scope and releases unmanageable; prioritize."),
    ]),
    ("Exam Practice", "", [
        ("Library Vision Statement", "Practice",
         "For university students and faculty who need library resources without visiting physically, the Digital Library Portal is an online library system that enables 24/7 search, reservation, and digital borrowing.",
         "Unlike physical visits, our product gives instant catalog access and extends borrowing automatically based on availability."),
        ("Riyadh Objectives and Metrics", "Practice",
         "Increase ticket sales 40% in the first season through online purchasing; measure online vs traditional sales.",
         "Cut entrance wait time 60% with self-check-in terminals; measure arrival-to-entry time from 15 to 6 minutes or less."),
        ("Riyadh FRs vs NFRs", "Practice",
         "<strong>Functional</strong>: buy tickets online by card or wallet; issue electronic bracelets at self-check-in terminals.",
         "<strong>Non-functional</strong>: payments comply with PCI DSS; check-in completes within 30 seconds per customer."),
    ]),
]
