"""SE311 Chapter 3 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 3
TITLE = "Requirements Elicitation"
AR_TITLE = "استنباط المتطلبات"
SLUG = "requirements-elicitation"
SUMMARY = "Interactive SE311 Chapter 3 mindmap: the elicitation process, sources of requirements, facilitated and independent techniques, use cases, misuse cases, and prototyping."

BRANCHES = [
    ("What Is Elicitation?", "Identifying the needs and constraints of the stakeholders.", [
        ("Definition", "Definition",
         "<strong>Elicitation</strong> is the process of identifying the needs and constraints of the various stakeholders for a software system."),
        ("More Than Gathering", "Key Idea",
         "A collaborative and analytical process to collect, discover, extract, and define requirements; not just transcribing what users say.",
         "It discovers business, user, functional, and non-functional requirements, and is perhaps the most challenging, error-prone, communication-intensive part of development."),
        ("ELICIT", "Memory Hook",
         "<strong>E</strong>xtract, <strong>L</strong>isten, <strong>I</strong>nvestigate, <strong>C</strong>ollaborate, <strong>I</strong>nterpret, <strong>T</strong>ransform."),
        ("Elicitation Goals", "Key Idea",
         "Determine information sources and select techniques; elicit information on the domain, problem, needs, and constraints.",
         "Produce a first document of mainly user requirements and notes. It may be incomplete, disorganized, and inconsistent, but you must start somewhere."),
        ("Iterative by Nature", "Key Idea",
         "Elicit, study what you learned, write requirements, find gaps and conflicts, return to elicitation, and repeat."),
    ]),
    ("Sources of Requirements", "", [
        ("Client / Customer", "Stakeholder",
         "Pays for development; contributes business objectives, budget, and final decisions."),
        ("Users", "Stakeholder",
         "Current or future users; contribute user requirements, usability needs, and workflow."),
        ("Domain Experts", "Stakeholder",
         "Familiar with the problem and environment; contribute domain knowledge, business rules, and constraints."),
        ("Developers and Others", "Stakeholder",
         "Developers give technical feasibility and design constraints; project managers and testers add testing requirements and project constraints."),
        ("Other Sources", "Source",
         "Existing systems (not necessarily software), existing documentation, competing systems, documentation of interfacing systems, and standards, policies, agreements, and legislation."),
    ]),
    ("The Elicitation Process", "Plan → Prepare → Perform → Follow Up.", [
        ("1. Plan", "Step",
         "Define objectives, strategy and techniques (which stakeholders, which techniques), schedule and resources, expected products (use cases, SRS, quality attributes), and risks.",
         "Start with independent elicitation of documents and systems before talking to people."),
        ("2. Prepare", "Step",
         "Decide the scope (topics, process flows, use cases), create an agenda, prepare resources, learn stakeholders' cultural and language preferences, prepare questions, and draft straw-man models."),
        ("Good Question Starters", "Tip",
         "Imagine learning the user's job: What else could…? What happens when…? Would you ever need to…? Where do you get…? Why do you (or don't you)…? Does anyone ever…?"),
        ("3. Perform", "Step",
         "Run the session and take good notes: attendees, decisions made, actions and who owns them, outstanding issues, and key points."),
        ("4. Follow Up", "Step",
         "Review and update notes right after the session, consolidate sources, edit carefully, keep originals, and review with stakeholders.",
         "Document open issues: items to explore further and gaps to close."),
        ("When Are We Done?", "Exam Tip",
         "Users can't think of more use cases; new scenarios yield no new functional requirements; issues repeat; new requests are out of scope or low priority; reviewers have few questions.",
         "You are never completely done, but these signs mark a good stopping point for the iteration."),
    ]),
    ("Classifying Customer Input", "Not everything a stakeholder says is a requirement.", [
        ("Business vs User Requirement", "Classify",
         "Business requirement: “Save SAR X per year on electricity.” User requirement: “I need to print a mailing label.”"),
        ("Business Rule", "Classify",
         "“Time-off approvals must comply with the HR vacation policy.”"),
        ("Functional vs Quality Attribute", "Classify",
         "Functional: “The user must be able to sort the project list alphabetically.” Quality attribute: “The mobile software must respond quickly to touch commands.”"),
        ("External Interface", "Classify",
         "“Files submitted electronically cannot exceed 10 MB.”"),
        ("Solution Idea and Data Definition", "Classify",
         "Solution idea: “Select state from a drop-down list.” Data definition: “ZIP code has 5 digits plus an optional 4 digits.”"),
    ]),
    ("Elicitation Challenges", "Each source of challenge has a matching mitigation.", [
        ("Scope", "Challenge",
         "Scope inadequately or incorrectly defined, and hard to keep focus.",
         "Mitigate: re-check scope before delving in and label items in-scope or out-of-scope."),
        ("Requirements", "Challenge",
         "Assumed, implied, and missing requirements.",
         "Mitigate: ask “What are we assuming here?” and analyze requirements systematically."),
        ("Business Analyst", "Challenge",
         "Lack of expertise or domain knowledge. Mitigate: research the domain and consult others."),
        ("Stakeholders", "Challenge",
         "Uncertainty, limited technical knowledge, availability, cooperation problems, and conflicts.",
         "Mitigate with the BA's interpersonal and communication skills and interviewing techniques."),
    ]),
    ("Facilitated Techniques", "Interactive: work directly with stakeholders to discover user and business requirements.", [
        ("Interviews", "Technique",
         "One-on-one or small group sessions. Strengths: learn the domain quickly, interviewees share more freely than in workshops, easy to build involvement, suits busy executives."),
        ("Interview Tips", "Tip",
         "Acquire background knowledge, prepare questions, establish rapport, stay in scope, suggest ideas, and listen actively by paraphrasing.",
         "User: “My elevators are too slow!” Bad: “No, you have a throughput problem.” Good: “I see. Tell me why you feel they are too slow.” Never contradict directly."),
        ("Workshops", "Technique",
         "Facilitated, structured meetings with many stakeholders at once. Strengths: resolves disagreements, suits tight schedules, gathers many viewpoints.",
         "Tips: ground rules, fill roles (facilitator, scribe), agenda, parking lot, timeboxing, small team, and watch for dominators."),
        ("Focus Groups", "Technique",
         "A representative group of users giving input on functional and quality requirements; valuable for commercial products.",
         "Keep on topic without influencing opinions; participants usually lack decision authority, so feedback is subjective."),
        ("Observation", "Technique",
         "Shadow users doing their work “in the wild”, silently or interactively. Useful for important or high-risk tasks, helps validation, and suggests interview topics; time-consuming."),
        ("Questionnaires", "Technique",
         "Survey large groups: inexpensive, scales to large populations, works across geography.",
         "Tips: cover all responses, mutually exclusive choices, no suggestive questions, consistent scales, closed questions for statistics, test first, avoid fatigue."),
    ]),
    ("Independent Techniques", "Work on your own to find functionality users may not be aware of.", [
        ("System Interface Analysis", "Technique",
         "Examine the systems yours connects to, using context diagrams and ecosystem maps, to reveal requirements for exchanging data and services."),
        ("User Interface Analysis", "Technique",
         "Study existing systems to discover user and functional requirements; suited to building a new version and spotting improvements.",
         "Don't assume the next implementation must keep every existing UI feature."),
        ("Document Analysis", "Technique",
         "Examine manuals, guides, memos, and change histories. A fast way to learn a system or domain, but documents may be out of date."),
        ("Comparing Techniques", "Comparison",
         "Questionnaires reach many cheaply but depend on design. Interviews explore issues but take time. Focus groups show consensus and conflict.",
         "Observation gives unique context insight but huge data. Document analysis needs no user time, but documented and real procedures differ."),
        ("Choosing: N-T-A-E", "Memory Hook",
         "<strong>N</strong>ature of the information (conscious, unconscious, subconscious), <strong>T</strong>ime and budget, <strong>A</strong>vailability of stakeholders, <strong>E</strong>xperience of the BA."),
        ("Three Methods for Riyadh Season", "Past Exam · Major 1",
         "<strong>Analyze existing systems</strong>: other cities built similar systems; suited to organizers. <strong>Interviews</strong>: all stakeholders' input is essential.",
         "<strong>Prototyping</strong>: reveals requirements stakeholders can't state; suited to organizers and customers, who try it while you watch reactions."),
    ]),
    ("Use Cases and Misuse Cases", "", [
        ("Use Case", "Definition",
         "A sequence of interactions between a system and an external actor that lets the actor achieve an <strong>outcome of value</strong>.",
         "It shifts from “what should the system do?” to the user-centric “what do you need to accomplish?”"),
        ("Scenario vs Use Case", "Comparison",
         "A <strong>scenario</strong> is one instance of usage: a specific actor, time, and data. A <strong>use case</strong> is a collection of related scenarios.",
         "“Request a Chemical” has scenarios for requesting from the stockroom and from a vendor."),
        ("Diagram Elements", "Notation",
         "Actor (stick figure), use case (oval), association (line), &lt;&lt;include&gt;&gt; (base requires the included case), and &lt;&lt;extend&gt;&gt; (base optionally extended)."),
        ("Use Case Practice", "Tip",
         "Name use cases verb + object (“Buy Ticket”), name actors by role not person, and pick the right abstraction level.",
         "Strengths: clearer user expectations, less unneeded functionality, feeds OO design. Risks: too many or overly complex use cases."),
        ("Misuse Case", "Definition",
         "A negative scenario whose goal is undesirable to the organization but desirable to a hostile agent (not necessarily human). Proposed by Sindre and Opdahl (2000) for security and risk analysis."),
        ("Finding Misuse Cases", "Process",
         "1. Identify misactors for the use case diagram. 2. Identify misuse cases and link them with &lt;&lt;threaten&gt;&gt;. 3. Mitigate with new use cases linked by &lt;&lt;mitigate&gt;&gt;.",
         "Example: a crook steals a password, mitigated by encrypting messages; a competitor floods the system, mitigated by blocking repeated registrations."),
        ("Misuse Benefits and Risks", "Comparison",
         "Benefits: early security and safety requirements, threats, test cases, and documented rationale.",
         "Risks: premature design during mitigation, and misactors missed in a partial view."),
    ]),
    ("Prototyping", "A partial, possible, or preliminary implementation of the product.", [
        ("Three Purposes", "Key Idea",
         "Clarify and validate requirements (requirements tool), explore design alternatives (design tool), or grow into the product (construction tool). State the purpose from the start."),
        ("Prototype Attributes", "Classification",
         "<strong>Scope</strong>: mock-up (interface) or proof-of-concept (key functionality). <strong>Future use</strong>: throwaway or evolutionary. <strong>Form</strong>: paper or electronic."),
        ("Low vs High Fidelity", "Comparison",
         "Low fidelity is static: easy, quick, cheap, great for interfaces, but not interactive.",
         "High fidelity is fully functional: deeper understanding and precise decisions, but costly and hard to change."),
        ("Strengths and Risks", "Comparison",
         "Strengths: more user involvement, closes expectation gaps, resolves uncertainty early.",
         "Risks: pressure to release the prototype, distraction by detail, unrealistic performance expectations, excessive effort."),
        ("Success Factors", "Tip",
         "Plan for prototyping, state its purpose, plan several, make throwaways fast and cheap, don't prototype well-understood requirements, and never let a prototype replace written requirements."),
    ]),
]
