"""SE311 Chapter 4 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 4
TITLE = "Problem Analysis"
AR_TITLE = "تحليل المشكلة"
SLUG = "problem-analysis"
SUMMARY = "Interactive SE311 Chapter 4 mindmap: the five steps of problem analysis, root causes, vision and scope, constraints, scope representation, and the Vision and Scope document."

BRANCHES = [
    ("What Is Problem Analysis?", "Understanding before building.", [
        ("Definition", "Definition",
         "<strong>Problem analysis</strong> is gaining a better understanding of the problem being solved before development begins. Goal: understand the problem deeply before jumping to solutions."),
        ("Key Activities", "Key Idea",
         "Identify the root cause of the problem, the stakeholders and their needs, and the solution boundary."),
        ("Input and Output", "Key Idea",
         "<strong>Input</strong>: business requirements obtained from stakeholders. <strong>Output</strong>: the product vision and the project scope."),
        ("5W Framing", "Memory Hook",
         "<strong>Why</strong> we're building it (business opportunity), <strong>what</strong> problem we're solving (root cause), <strong>who</strong> it's for (stakeholders), <strong>where</strong> the boundaries are (scope)."),
    ]),
    ("Five Steps (A-R-S-V-C)", "Agreement, Root causes, Stakeholders, Vision and boundary, Constraints.", [
        ("1. Agree on the Problem", "Step",
         "Document the problem and seek stakeholder agreement, ideally with problem statements in an agreed format.",
         "A problem statement covers: what the problem is, who is affected, the impact, any proposed solution, and the key benefits."),
        ("2. Understand Root Causes", "Step",
         "There is often a <strong>problem behind the problem</strong>. Root cause analysis finds underlying causes that are not immediately apparent by recursively asking what contributes to the problem."),
        ("The 5 Whys", "Example",
         "Low sales → users abandon carts → checkout is confusing → too many steps → account required first → legacy system limitation.",
         "Root cause: the legacy architecture, not just “low sales”."),
        ("3. Identify Stakeholders", "Step",
         "Ask who uses, buys, approves, maintains, or is affected by the system, and who else cares (legal, regulatory).",
         "A stakeholder profile lists the value they receive, likely attitude, features of interest, and constraints to accommodate."),
        ("4. Define Vision and Scope", "Step",
         "<strong>Product vision</strong>: what the product is and could become; aligns stakeholders; long-term.",
         "<strong>Project scope</strong>: the portion of that vision the current project or release addresses; a subset of the vision."),
        ("5. Identify Constraints", "Step",
         "Restrictions on the solution space, usually non-functional. <strong>E-P-T-S-E-S</strong>: Economics, Politics, Technology, Systems, Environment, Schedule and resources.",
         "Examples: SAR 500,000 budget; preferred vendor; must use Java; integrate with legacy SAP; comply with GDPR; launch before a competitor in Q3."),
    ]),
    ("Business Case", "", [
        ("Business Opportunity", "Key Idea",
         "Describes the market opportunity, the competing market, and the business problem being solved or improved.",
         "Example: “Exploit the poor security record of a competing product.”"),
        ("Business Objectives", "Key Idea",
         "Must be quantitative and measurable. Examples: “Capture 80% market share by being recognized as the most secure product” and “Achieve positive cash flow within 6 months.”"),
        ("SMART Objectives", "Memory Hook",
         "Specific, Measurable, Achievable, Relevant, Time-bound."),
        ("Vision Template (Moore)", "Template",
         "<strong>For</strong> target customer · <strong>Who</strong> need · <strong>The</strong> product name · <strong>Is</strong> category · <strong>That</strong> key benefit · <strong>Unlike</strong> alternative · <strong>Our product</strong> differentiation.",
         "Focus “That” on benefits rather than features, and be specific about the advantage in “Our product”."),
        ("Vision Example: QuickBite", "Example",
         "For busy professionals and students who need quality meals without leaving, the QuickBite App is a mobile food delivery platform that delivers in under 30 minutes with real-time tracking.",
         "Unlike services taking 60+ minutes, our product uses route optimization and local kitchens to guarantee fast delivery."),
    ]),
    ("Scope", "", [
        ("What Scope Defines", "Definition",
         "The solution system's boundaries: what the system will and will not do. It establishes realistic stakeholder expectations."),
        ("New Requirements", "Key Idea",
         "Evaluate new requirements against scope. In-scope ones enter if high priority relative to the baseline, usually by deferring others or renegotiating the schedule; out-of-scope ones go to a later release."),
        ("Scope Creep", "Pitfall",
         "Without a clear scope, projects go over budget, schedules slip, the team is overwhelmed, and quality suffers. Always ask “Is this in scope?”"),
    ]),
    ("Scope Representation (C-E-F-E)", "Context diagram, Ecosystem map, Feature tree, Event list.", [
        ("Context Diagram", "Technique",
         "The system as a single box, the external entities that directly interface with it, and the flows between them. Seen from outside only: no internal features."),
        ("Ecosystem Map", "Technique",
         "All systems related to yours and their interactions, including systems with no direct connection. A broader view than the context diagram."),
        ("Feature Tree", "Technique",
         "A hierarchical breakdown of features, e.g. User Management → Registration (email verification, profile creation) and Authentication (login, password reset)."),
        ("Event List", "Technique",
         "External events that trigger behavior: user-triggered (click “Submit Order”), time-triggered (end-of-day report), system-triggered (inventory below threshold)."),
    ]),
    ("Vision and Scope Document", "", [
        ("Five Sections", "Structure",
         "1. Business requirements (opportunity, objectives, success criteria). 2. Vision of the solution (statement, major features, dependencies). 3. Scope and limitations.",
         "4. Business context (stakeholder profiles, priorities, operating environment). 5. Risks (technical, business, resource)."),
        ("Why It Matters", "Key Idea",
         "It establishes stakeholder agreement, gives the project direction, supports in-or-out scope decisions, prevents scope creep, and is the foundation for elicitation."),
    ]),
    ("Common Mistakes", "", [
        ("Jumping to Solutions", "Pitfall",
         "Designing before understanding the problem. Fix: complete all five steps of problem analysis first."),
        ("Problems at Face Value", "Pitfall",
         "Not digging for root causes: “elevators are too slow” may really be perception or boredom. Fix: ask “Why?” repeatedly."),
        ("Unclear Boundaries", "Pitfall",
         "Vague scope causes scope creep, overruns, and missed deadlines. Fix: state inclusions and exclusions explicitly."),
        ("Vision Too Narrow or Broad", "Pitfall",
         "Balance ambition with feasibility and align the vision with business objectives."),
        ("Ignoring Constraints", "Pitfall",
         "Planning without real-world limits yields infeasible designs and wasted effort. Identify E-P-T-S-E-S constraints early."),
    ]),
    ("Exam Practice", "", [
        ("Riyadh Stakeholders and Goal", "Past Exam · Major 1",
         "Stakeholders: organizers, Secure Payment Inc., customers (also agencies, venue vendors, technical staff).",
         "Goal: completely modernize ticket selling and introduce short queues and low waiting times. Goals are business benefits, not technical features."),
        ("Course Registration Vision", "Practice",
         "For university students who register each semester, the SmartReg System is an online registration platform that shows courses, checks prerequisites, and registers in real time.",
         "Unlike manual in-person registration, our product offers 24/7 access, instant confirmation, and course recommendations based on degree requirements."),
        ("Answering Strategy", "Exam Tip",
         "Underline key scenario details, find the pain points, ask “why?” for root causes, think broadly about stakeholder types (including indirect ones), and be specific."),
    ]),
]
