"""SE311 Chapter 5 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 5
TITLE = "Requirements Analysis and Domain Modeling"
AR_TITLE = "تحليل المتطلبات ونمذجة المجال"
SLUG = "requirements-analysis-and-domain-modeling"
SUMMARY = "Interactive SE311 Chapter 5 mindmap: requirements analysis, the SRS, identifying and evaluating domain model classes, associations and attributes, the Movie Shop case study, and common modeling errors."

BRANCHES = [
    ("Requirements Analysis", "Understand the domain, capture the requirements, and validate them.", [
        ("Definition", "Definition",
         "The process of understanding the application domain, identifying user needs, capturing system requirements, and validating them."),
        ("Main Goals", "Key Idea",
         "Understand the domain and user needs; collect data on requirements and constraints; define development scope and design goals; determine risks; capture and validate the requirements."),
        ("Five Risk Types", "Checklist",
         "Economic, technical, operational, organizational, and legal risks."),
        ("Where Requirements Go", "Key Idea",
         "Data requirements → <strong>domain model</strong>. Functional requirements → <strong>use-case model</strong>. Non-functional requirements → <strong>supplementary text</strong>."),
        ("Four Activities", "Process",
         "1. Capture data requirements (domain modeling). 2. Capture functional requirements (use-case modeling). 3. Capture non-functional requirements (supplementary specifications). 4. Validate the system requirements."),
    ]),
    ("System Requirements Specification", "", [
        ("What an SRS Is", "Definition",
         "The official statement of what is required of the system, including both user requirements and a specification of system requirements."),
        ("WHAT, Not HOW", "Key Idea",
         "An SRS is <strong>not a design document</strong>: it states what the system should do, never how."),
        ("The Agile View", "Comparison",
         "Many agile methods argue a formal SRS wastes time because requirements change quickly, though some documentation still helps communication and traceability."),
        ("Natural and Structured Language", "Writing Style",
         "<strong>Natural language</strong>: easy and universally understood, but ambiguous and imprecise.",
         "<strong>Structured natural language</strong>: a fixed template makes it consistent and less ambiguous, but rigid."),
        ("Graphical, DDL, Mathematical", "Writing Style",
         "<strong>Graphical (UML) plus text</strong>: visual and standard, but needs training. <strong>Design description languages</strong>: precise but technical.",
         "<strong>Mathematical specifications</strong>: unambiguous and provable, but hard to understand and slow."),
    ]),
    ("Domain Modeling Basics", "", [
        ("Definition", "Definition",
         "Captures the most important <strong>classes and associations for which data must be stored</strong>: things that exist or events that occur. Drawn as a class diagram; also gives a glossary of terms."),
        ("Sources", "Key Idea",
         "Requirements statements, domain experts (users), and application documentation."),
        ("Class Categories", "Classification",
         "<strong>Business objects</strong>: orders, accounts, invoices. <strong>Real-world objects</strong>: suppliers, customers, products. <strong>Events</strong>: arrivals, sales, reservations, rentals."),
        ("Persistent, Not Transient", "Key Rule",
         "A class represents <strong>persistent</strong> data that is stored (Customer, Movie, Order), not transient runtime data (SearchResults, ValidationStatus). Only essential, lasting classes give a stable system."),
        ("No Single Correct Model", "Key Idea",
         "Decomposition into classes and associations depends on judgment, experience, and the problem; there is usually no one correct answer."),
    ]),
    ("Identifying Elements", "", [
        ("Classes Are Nouns", "Technique",
         "Look for naturally occurring things or concepts: classes appear as nouns or noun phrases."),
        ("Associations Are Verbs", "Technique",
         "Verbs connecting nouns (“customer rents movie”) suggest associations, which must describe persistent structural relationships, not transient events."),
        ("Attributes Are Possessives", "Technique",
         "Nouns with possessive phrases (“student's address”) suggest attributes; adjectives often signal enumerated values (“Fall term”).",
         "Most attributes are not in the requirements and must come from domain experts or documentation."),
        ("Naming Conventions", "Tip",
         "Use singular names (Movie, not Movies) and active voice for associations."),
        ("Worked Example", "Example",
         "“Record which movies are sold and rented and by whom” → classes Movie and Customer; associations Customer Purchases Movie and Customer Rents Movie."),
    ]),
    ("Evaluating the Model", "Filter candidates with checklists before drawing.", [
        ("Class Checklist", "Checklist",
         "Eliminate irrelevant classes, operations, and implementation constructs; make vague classes specific; keep the most descriptive of redundant classes.",
         "Ask whether a class should really be an attribute, and be careful with names that describe roles."),
        ("Association Checklist", "Checklist",
         "Eliminate irrelevant associations, those describing operations, derived associations, and implementation constructs; decompose ternary associations into binary ones."),
        ("Derived Associations", "Key Rule",
         "If A–X–B and B–Y–C exist, a direct A–Z–C association is derived and redundant; it can be computed by following X then Y, so remove it."),
        ("Attribute Checklist", "Checklist",
         "Is each attribute closely related to its class? Should it be a class (independent, with several attributes of its own)? Does it belong in an association class, like quantity sold on Purchases?"),
        ("No Object Identifiers", "Key Rule",
         "Don't put IDs such as movieID in Customer to link classes. Relationships are shown with associations; IDs are implementation details."),
    ]),
    ("Specifying Details", "", [
        ("Classes and Attributes", "Specification",
         "For each class give its attributes; get and set operations are assumed. For each attribute give a unique name, a type, and multiplicity if greater than 1, e.g. leadingActor[0..*]."),
        ("Associations", "Specification",
         "Give a name that says what (not how or why), role names if needed, multiplicity if known (use “?” if not), and an association class if needed."),
        ("Finding Multiplicities", "Key Idea",
         "From explicit requirements, from real-world domain knowledge, or mark as unknown (“?”) when they cannot be inferred."),
        ("Movie vs Physical Copy", "Key Idea",
         "A Movie instance is a <strong>description</strong> of a movie, not a physical copy, so one Movie can relate to many rental copies, rentals, and purchases."),
    ]),
    ("Movie Shop Case Study", "A web system for selling and renting physical and digital movies.", [
        ("Classes", "Solution",
         "Customer, Member, Movie, RentalCopy, and Review.",
         "Movie has isPhysical and isDigital flags because one movie can be both."),
        ("Associations", "Solution",
         "Customer Purchases Movie, Customer Rents Movie, Movie HasPhysical RentalCopy, Customer RentsPhysical RentalCopy, Customer Provides Review, Review IsFor Movie, Member Reserves RentalCopy."),
        ("Generalization and Association Class", "Solution",
         "Customer generalizes Member (member number, password). Purchases is an association class holding quantity. RentalCopy holds copyNumber and returnDate."),
        ("Constraints", "Solution",
         "max-card(Member, Reserves) = 5 and max-card(Customer, RentsPhysical) = *.",
         "Real-world multiplicities: a RentalCopy is of exactly one Movie and is reserved or rented by at most one person at a time."),
        ("Requirements With No Model Impact", "Exam Tip",
         "Generating reports, selling and renting at the counter, and looking up customers are <strong>functional</strong> requirements: things users do, not data to store."),
        ("Three Modeling Options", "Comparison",
         "1. Direct associations: simple, but no repeat purchases or history. 2. Purchase and Rental transaction classes (preferred): track history and dates.",
         "3. A generalized Transaction class with Purchase and Rental subclasses: most extensible, but may be over-engineered."),
    ]),
    ("Common Modeling Errors", "Ask of every element: does this need to be stored in a database?", [
        ("IDs as Links", "Error",
         "Using customerID or movieID attributes to relate classes instead of associations."),
        ("Modeling the Shop", "Error",
         "The Shop is the organization running the system, not data the system stores."),
        ("Wrong Generalization", "Error",
         "Adding Person (too general), Nonmember (just a Customer), or PhysicalMovie and DigitalMovie subclasses when a movie can be both. Use Customer → Member and boolean attributes."),
        ("Wrong Aggregation", "Error",
         "Movie ◇ RentalCopy, Movie ◇ Review, and Customer ◇ Member are not part-whole relationships; Member is a specialization."),
        ("Misplaced Association Class", "Error",
         "Putting returnDate on Customer Rents Movie; it belongs to a specific copy, so use RentsPhysical RentalCopy."),
        ("Wrong Constraints", "Error",
         "{XOR} physical or digital is wrong because a movie can be both."),
        ("Operations, Reports, Roles", "Error",
         "Classes like Generates or Browses are actions; SalesReport is generated output; SalesClerk and Manager are user roles. None are persistent data."),
        ("Implementation Aspects", "Error",
         "System, Web, and Telephone are implementation constructs or access methods; the domain model is implementation-independent."),
    ]),
    ("Exam Strategy", "", [
        ("Step-by-Step Approach", "Process",
         "Read carefully → nouns as classes → verbs as associations → possessives as attributes → apply evaluation criteria → multiplicities → generalizations → association classes → draw → review against common errors."),
        ("Time Split", "Exam Tip",
         "Analysis 40%, evaluation 20%, drawing the diagram 30%, review 10%."),
        ("Question Types", "Exam Tip",
         "Build a complete domain model with multiplicities; list specific elements and justify each; or find and explain errors in a given model."),
        ("Avoid ROID", "Memory Hook",
         "Keep out <strong>R</strong>oles (SalesClerk), <strong>O</strong>perations (Generate), <strong>I</strong>mplementation (System, Web), and <strong>D</strong>erived associations."),
    ]),
]
