"""SE311 Chapter 7 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 7
TITLE = "Requirements Specification"
AR_TITLE = "توصيف المتطلبات"
SLUG = "requirements-specification"
SUMMARY = "Interactive SE311 Chapter 7 mindmap: the SRS and its audiences, labeling methods, handling TBDs, user interfaces in the SRS, specification best practices, and the Volere shell."

BRANCHES = [
    ("Specification in RE", "The 4th step of requirements development.", [
        ("Where It Fits", "Process",
         "Inception → Elicitation → Analysis → <strong>Specification</strong> → Validation → Management.",
         "The result of requirements development is a documented agreement among stakeholders about the product to be built."),
        ("Three Key Documents", "Key Idea",
         "<strong>Vision and Scope</strong>: business requirements, for executives and sponsors. <strong>Use cases / user stories</strong>: user requirements, for developers and users.",
         "<strong>SRS</strong>: functional and non-functional requirements, for all stakeholders."),
        ("Three Representations", "Key Idea",
         "<strong>Natural language</strong>: most common and accessible, but prone to ambiguity. <strong>Visual models</strong>: UML diagrams that complement text.",
         "<strong>Formal specifications</strong>: mathematically precise, but few developers and fewer customers know them, so rarely used."),
    ]),
    ("The SRS", "Says WHAT the system should do, never HOW.", [
        ("Many Names", "Definition",
         "Also called the Business Requirements Document (BRD), functional specification, product specification, system specification, or requirements document."),
        ("What It Contains", "Checklist",
         "Functions and capabilities, characteristics and constraints, behaviors under various conditions, desired qualities (performance, security, usability), and known design and implementation constraints."),
        ("What It Excludes", "Checklist",
         "Design decisions, construction or implementation details, testing procedures or scripts, and project management details."),
        ("A Foundation", "Key Idea",
         "The basis for project planning, design, and coding, and the foundation for system testing and user documentation."),
    ]),
    ("SRS Audiences", "Eight types of readers.", [
        ("The Critical Rule", "Key Rule",
         "If a capability or quality doesn't appear somewhere in the requirements agreement, no one should expect it in the product. <strong>If it's not written, it won't be built.</strong>"),
        ("Developers and Project Managers", "Audience",
         "Developers need to know what to build; project managers use it for schedule and resource estimates."),
        ("Customers, Marketing, Testers", "Audience",
         "Customers, marketing, and sales learn what will be delivered; testers derive requirements-based tests and test plans."),
        ("Maintenance, Writers, Trainers", "Audience",
         "Maintenance and support staff learn what each part does; documentation writers and trainers build manuals and training material."),
        ("Legal Staff and Subcontractors", "Audience",
         "Legal staff check compliance with laws and regulations; subcontractors base their work on, and can be legally held to, the specified requirements."),
        ("Why Multiple Models", "Key Idea",
         "One deliverable can't serve every audience: some need only objectives, others the big picture or every detail. Hence use cases, class diagrams, and more alongside the SRS."),
    ]),
    ("Labeling Requirements", "Every requirement needs a unique, persistent identifier.", [
        ("Why Unique Labels", "Key Idea",
         "They let you cite requirements in change requests and history, reuse them across projects, collaborate, and build a traceability matrix. A deleted requirement's number is never reused."),
        ("1. Sequence Number", "Method",
         "FR-26, UC-9: the prefix gives the type. Pros: easy to keep unique when moving, supported by RM tools.",
         "Cons: no grouping of related requirements, and the number says nothing about intent."),
        ("2. Hierarchical Numbering", "Method",
         "3.2.4.3 is a child of 3.2.4 in section 3.2. Pros: compact, familiar, auto-numbered.",
         "Cons: labels grow long and carry no meaning."),
        ("The Word Processor Trap", "Pitfall",
         "Insert, move, merge, or delete a requirement and the automatic labels change.",
         "Mitigation: number sections hierarchically, but use a short text code and sequence within each section, e.g. Section 3.5 Editor Functions → ED-1, ED-2."),
        ("3. Hierarchical Textual Tags", "Method",
         "Parent.Child tags like Product.Cart.Discount. Pros: meaningful and unaffected by inserting, deleting, or moving others.",
         "Cons: longer and harder to keep unique. Mitigate by combining with a sequence: Product.Cart.01."),
        ("S-H-T", "Memory Hook",
         "<strong>S</strong>equence (FR-26) → <strong>H</strong>ierarchical number (3.2.4) → <strong>T</strong>extual tag (Product.Cart.01). Each adds meaning but also maintenance cost."),
    ]),
    ("Handling TBDs", "No requirements document is complete on the first draft.", [
        ("Four TBD Rules", "Key Rule",
         "Flag missing information with TBD; resolve all TBDs before implementing; if you must proceed, defer unresolved requirements or design those parts to be easily modified; record TBDs in an issues list."),
        ("Track to Closure", "Memory Hook",
         "Treat each TBD like an <strong>open bug</strong>: number it, assign an owner and a due date, review it at checkpoints, and track it to closure. A TBD with no owner never gets resolved."),
    ]),
    ("User Interfaces and the SRS", "Including UI designs is a double-edged sword.", [
        ("Benefits", "Comparison",
         "Prototypes, wireframes, and mock-ups make requirements tangible, set accurate look-and-feel expectations, and help non-technical stakeholders validate."),
        ("Drawbacks", "Comparison",
         "Screen images bloat the SRS, waiting for UI design delays baselining, and the UI can start driving requirements, leaving functional gaps."),
        ("Golden Rule", "Key Rule",
         "Screen layouts <strong>never replace functional requirements</strong>. If specific UI controls are required, state that explicitly as a written requirement."),
        ("Readability Tips", "Tip",
         "Use a template, consistent labels and styles, a table of contents, numbered and captioned figures, cross-references instead of page numbers, and hyperlinks.",
         "Use emphasis consistently, remembering that color may be invisible to colorblind readers or in grayscale print."),
    ]),
    ("Best Practices (AILRS)", "", [
        ("The Five Practices", "Memory Hook",
         "<strong>A</strong>dopt requirement document templates · <strong>I</strong>dentify requirement origins · <strong>L</strong>abel each requirement uniquely · <strong>R</strong>ecord business rules · <strong>S</strong>pecify non-functional requirements."),
    ]),
    ("The Volere Shell", "A structured template, a “business card” for one requirement.", [
        ("Identity Fields", "Field",
         "<strong>Requirement #</strong> (unique ID), <strong>requirement type</strong>, <strong>event / use case #</strong>, and a one-sentence <strong>description</strong> of intent."),
        ("Rationale, Source, Fit Criterion", "Field",
         "<strong>Rationale</strong> justifies why it is needed; <strong>source</strong> says who raised it.",
         "<strong>Fit criterion</strong> is a measurement that makes it possible to test whether the solution meets the requirement, which makes it verifiable."),
        ("Satisfaction Scores", "Field",
         "<strong>Customer satisfaction</strong>: happiness if implemented, 1 (uninterested) to 5 (extremely pleased).",
         "<strong>Customer dissatisfaction</strong>: unhappiness if not implemented, 1 (hardly matters) to 5 (extremely displeased)."),
        ("Dependencies, Conflicts, History", "Field",
         "Requirements that depend on this one, requirements that can't be implemented if it is, pointers to supporting materials, and the creation and change history."),
        ("Prioritizing Requirement #75", "Past Exam · Quiz 2",
         "Use the satisfaction and dissatisfaction scores: 5 and 5 means highest priority. Check dependencies for requirements that block it, and weigh the source (executive vs user)."),
        ("Closest Technique", "Past Exam · Quiz 2",
         "<strong>Prioritization based on value, cost, and risk</strong>: it uses measurable 1–5 scores rather than subjective groupings like MoSCoW or a three-level scale."),
    ]),
]
