"""SE311 Chapter 8 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 8
TITLE = "The SRS Template"
AR_TITLE = "قالب وثيقة مواصفات المتطلبات"
SLUG = "the-srs-template"
SUMMARY = "Interactive SE311 Chapter 8 mindmap: every section of the SRS template, from introduction and overall description to data, interfaces, quality attributes, internationalization, and appendices."

BRANCHES = [
    ("SRS Overview", "The official record of WHAT the system should do.", [
        ("Where It Fits", "Process",
         "Specification follows Inception → Elicitation → Analysis: it formally documents what was discovered and analyzed, before Validation and Management."),
        ("WHAT, Not HOW", "Key Rule",
         "The SRS documents user and system requirements. It is <strong>not a design document</strong>: no implementation details or architecture."),
        ("Writing Styles", "Key Idea",
         "Natural language, structured natural language, graphical models with text (most common in SE311), design description languages, and mathematical specifications."),
        ("Template Mnemonic", "Memory Hook",
         "“<strong>I O</strong>nly <strong>S</strong>ee <strong>D</strong>ata – <strong>E</strong>very <strong>Q</strong>uality <strong>I</strong>s <strong>O</strong>rganized <strong>A</strong>lphabetically”: Introduction, Overall description, System features, Data, External interfaces, Quality attributes, I18n, Other, Appendices."),
    ]),
    ("1. Introduction", "How the SRS is organized and how to use it.", [
        ("1.1 Purpose", "Section",
         "Identify the product, application, or subsystem and its release or version, and describe the intended reader audiences."),
        ("1.2 Document Conventions", "Section",
         "Typographical standards and the meaning of styles and notations, e.g. italics for new terms, bold fixed-width for SQL examples, ALL CAPS for SQL keywords; plus the labeling standard."),
        ("1.3 Project Scope", "Section",
         "A short description of the software and its purpose, related to business objectives, with a summary of major features. Refer to the Vision and Scope document if one exists."),
        ("1.4 References", "Section",
         "Contracts, standards, and other specifications the SRS relies on, with enough information (title, author, hyperlink) for readers to find them."),
    ]),
    ("2. Overall Description", "The product, its environment, users, and known constraints.", [
        ("2.1 Product Perspective", "Section",
         "Context and origin: next in a product line, new version, replacement, or entirely new? For a subsystem, how it relates to the whole. Consider an ecosystem map or context diagram."),
        ("2.2 User Classes", "Section",
         "Anticipated user classes, their characteristics, and the favored class. User classes are a <strong>subset of the stakeholders</strong> from the Vision and Scope document.",
         "Movie Shop: Customer, Member, Sales Clerk, Manager."),
        ("2.3 Operating Environment", "Section",
         "Hardware platform, OS version, locations of users, servers, and databases, hosting organizations, and other software the system must coexist with."),
        ("2.4 Design and Implementation Constraints", "Section",
         "Programming language or library restrictions and other factors that constrain developers, each with its rationale. Don't over-specify with unnecessary design constraints."),
        ("2.5 Assumptions and Dependencies", "Section",
         "Assumptions about functionality (business assumptions belong in Vision and Scope) and dependencies on external components.",
         "Document them: a developer may assume custom code, the BA reuse, and the PM a purchased library."),
    ]),
    ("3. System Features", "Functional requirements, organized one feature at a time.", [
        ("Organizing Features", "Key Idea",
         "By system feature is one option; also by functional area, process flow, use case, user class, or a combination. Pick what helps readers understand the capabilities."),
        ("3.x.1 Description", "Section",
         "A short description of the feature and its priority. Priorities often change, so manage them."),
        ("3.x.2 Functional Requirements", "Section",
         "An itemized list of capabilities, including responses to error conditions, each with a unique label.",
         "Past exam (Major 2, municipality system): “Submit Permit Application” becomes a feature with requirements for national-ID login, PDF uploads, and electronic fee payment."),
        ("Naming Features", "Tip",
         "Use a few words in verb-noun form (“Buy Movie”, “Reserve Movie”), neither too broad nor too granular."),
    ]),
    ("4. Data Requirements", "The data the system consumes, processes, or creates.", [
        ("4.1 Logical Data Model", "Section",
         "A visual model of data objects and relationships as an ER diagram or UML class diagram, e.g. the Chapter 5 Movie Shop domain model."),
        ("4.2 Data Dictionary", "Section",
         "Composition of data structures and each element's meaning, type, length, format, and allowed values. Can be kept as a separate, reusable artifact.",
         "Shared dictionary benefits: consistent definitions and better communication across the team."),
        ("ERD vs Data Dictionary", "Past Exam · Major 2",
         "The ERD gives the high-level view of entities and relationships; the dictionary gives precise attribute details (types, constraints, valid values). Together they make data requirements clear and complete."),
        ("4.3 Reports", "Section",
         "Reports to generate and any layouts they must follow; defer detailed layout to design."),
        ("4.4 Acquisition, Integrity, Retention", "Section",
         "How data is acquired and maintained, integrity techniques such as backups and checkpointing, and policies for retaining or disposing of data."),
    ]),
    ("5. External Interfaces", "Agreeing on interfaces is an industry best practice.", [
        ("5.1 User Interfaces", "Section",
         "UI standards and style guides, fonts, icons, labels, color schemes, tabbing order, screen constraints, standard buttons, shortcut keys, message conventions, validation, and accessibility."),
        ("5.2 Software Interfaces", "Section",
         "Connections to other software (name and version), message formats, data exchanged and mapped, and services needed.",
         "Riyadh Season: the payment API protocol and transaction format for Secure Payment Inc."),
        ("5.3 Hardware Interfaces", "Section",
         "Device types, protocols, inputs and outputs with formats, valid ranges, and timing.",
         "Riyadh Season: the self-check-in terminal and the bracelet chip reader."),
        ("5.4 Communications Interfaces", "Section",
         "Email, browsers, network protocols, and electronic forms; message formats; security, encryption, and transfer rates; and constraints such as allowed attachment types."),
    ]),
    ("6. Quality Attributes", "Non-functional requirements other than constraints (2.4) and UI (5.1).", [
        ("Must Be Verifiable", "Key Rule",
         "Quality requirements must be specific, quantitative, and verifiable. “The page shall load within 3 seconds on standard broadband” is good.",
         "Past exam (Major 2): “The interface shall load quickly” violates <strong>verifiability</strong>."),
        ("6.1 Usability", "Section",
         "Ease of learning and use, error avoidance and recovery, efficiency of interaction, and accessibility."),
        ("6.2 Performance", "Section",
         "Performance needs for specific operations, e.g. “The server shall send welcome emails within 10 minutes of registration.”"),
        ("6.3 Security", "Section",
         "Restrictions on access and use, often from business rules.",
         "“The online payment service shall be secure” is still too vague; name the standard, e.g. TLS 1.3."),
        ("6.4 Safety", "Section",
         "Possible loss, damage, or harm from using the product; required safeguards; dangerous actions to prevent."),
        ("6.x Other Attributes", "Section",
         "Availability, modifiability, portability, reliability, reusability, robustness.",
         "Past exam: portability is the degree to which software on one platform can easily be converted to run on another. Maintainability, portability, and robustness are all NFRs."),
    ]),
    ("7–8 and Appendices", "", [
        ("7. Internationalization", "Section",
         "Suitability for other nations and cultures: currency, date and number formats, language and Arabic RTL layout, spelling, name order, time zones, units, and legal or cultural issues.",
         "These requirements are often reusable across projects."),
        ("8. Other Requirements", "Section",
         "Legal, regulatory, or financial compliance; installation, configuration, startup, and shutdown; logging, monitoring, and audit trails."),
        ("Appendix A: Glossary", "Section",
         "Specialized terms, acronyms, and abbreviations; consider an enterprise-level glossary. Data definitions belong in the data dictionary, not here."),
        ("Appendix B: Analysis Models", "Section",
         "Optional DFDs, feature trees, state-transition diagrams, or ER diagrams; often better inline in the relevant sections."),
        ("Final Tips", "Tip",
         "Don't duplicate information; cross-reference instead. Use version control with a revision history, and actively manage changing priorities."),
    ]),
    ("What Goes Where", "Quick placement guide.", [
        ("Features and Data", "Exam Tip",
         "Member discount rule → 3 System Features. ER diagram → 4.1. Data type and length of memberNumber → 4.2. Member vs Customer definition → Appendix A."),
        ("Constraints and Interfaces", "Exam Tip",
         "Programming language → 2.4. Screen resolution → 5.1. Payment API integration → 5.2."),
        ("Quality, Legal, I18n", "Exam Tip",
         "Page load time → 6.2 Performance. Legal compliance → 8 Other. Arabic RTL support → 7 Internationalization."),
    ]),
    ("Past Exam Questions", "", [
        ("A Good SRS Avoids", "Past Exam · Major 2",
         "Answer: <strong>mixing design decisions with requirements</strong>."),
        ("One Interpretation", "Past Exam · Major 2",
         "An SRS where every requirement has only one interpretation is <strong>unambiguous</strong>."),
        ("Data-Quality Constraint", "Past Exam · Major 2",
         "“Each employee record shall contain a valid, unique national-ID number” constrains specific data content."),
        ("Two Directions of Traceability", "Past Exam · Major 2",
         "<strong>Backward</strong> to the source (stakeholder or business goal) to show each requirement is necessary; <strong>forward</strong> to design, code, and tests to show it is implemented and verified."),
        ("Ambiguity Types", "Past Exam · Major 2",
         "“Up to 5 days… 5 to 10 days” is boundary ambiguity (overlapping ranges). “Search using a name and/or email” is and/or ambiguity."),
        ("Prioritization Challenges", "Past Exam · Major 2",
         "Conflicting stakeholder interests, limited resources, unclear or ambiguous requirements, and changing requirements."),
    ]),
]
