"""SE311 Chapter 9 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 9
TITLE = "Nonfunctional Requirements"
AR_TITLE = "المتطلبات غير الوظيفية"
SLUG = "nonfunctional-requirements"
SUMMARY = "Interactive SE311 Chapter 9 mindmap: external and internal quality attributes, exploring and specifying them, trade-offs, constraints, and easily confused pairs."

BRANCHES = [
    ("Quality Attributes", "NFR = Quality Attributes + External Interfaces + Constraints.", [
        ("Definition", "Definition",
         "User and developer expectations about <strong>how well</strong> the system performs its tasks; also called quality factors, quality of service requirements, or the “-ilities”."),
        ("A Subset of NFRs", "Key Idea",
         "Quality attributes are not synonymous with NFRs. NFRs cover <strong>quality attributes</strong> (the -ilities), <strong>external interfaces</strong> (connections to the outside world), and <strong>constraints</strong> (developer restrictions)."),
        ("The Heating System Story", "Example",
         "A heating system met every stated requirement, but no one specified noise, and the training room was unusable because the fan was too loud.",
         "Quality attributes must be explicitly elicited; always ask what is unstated."),
    ]),
    ("Why They Matter", "", [
        ("Distinguish Products", "Key Idea",
         "They separate a product that merely works from one that delights; excellent products balance competing characteristics."),
        ("Cost of Late Discovery", "Key Idea",
         "Re-architecting a finished system for quality goals costs far more than designing for them at the outset, as with retroactive security patches."),
        ("They Drive Design", "Key Idea",
         "Quality attributes are the origin of many functional requirements and architectural decisions."),
        ("Why Collecting Them Is Hard", "Past Exam · Midterm",
         "Engineers lack domain expertise; expectations are implicit; “secure” isn't verifiable without criteria; quality requirements conflict; stakeholders are unavailable; some, like reliability, only appear in operation."),
    ]),
    ("External Attributes", "Visible to users.", [
        ("Availability and Installability", "External",
         "<strong>Availability</strong>: services are available when and where needed. <strong>Installability</strong>: easy to install, uninstall, and reinstall."),
        ("Integrity and Interoperability", "External",
         "<strong>Integrity</strong>: protects against data inaccuracy and loss. <strong>Interoperability</strong>: exchanges data easily with other systems."),
        ("Performance and Reliability", "External",
         "<strong>Performance</strong>: responds quickly and predictably. <strong>Reliability</strong>: runs a long time before failing."),
        ("Robustness and Safety", "External",
         "<strong>Robustness</strong>: responds well to unexpected conditions. <strong>Safety</strong>: protects against injury or property damage."),
        ("Security and Usability", "External",
         "<strong>Security</strong>: blocks unauthorized access to data and functions. <strong>Usability</strong>: easy to learn, remember, and use."),
    ]),
    ("Internal Attributes", "Visible to developers and maintainers.", [
        ("Efficiency and Modifiability", "Internal",
         "<strong>Efficiency</strong>: uses computer resources well. <strong>Modifiability</strong>: easy to maintain, change, enhance, and restructure."),
        ("Portability and Reusability", "Internal",
         "<strong>Portability</strong>: works in other operating environments. <strong>Reusability</strong>: components can be used in other systems."),
        ("Scalability and Verifiability", "Internal",
         "<strong>Scalability</strong>: grows to handle more users, data, and transactions. <strong>Verifiability</strong>: developers and testers can confirm correct implementation."),
        ("External vs Internal", "Memory Hook",
         "External = what you <strong>feel</strong> using the app. Internal = what engineers <strong>worry</strong> about building it."),
    ]),
    ("Exploring Quality Attributes", "Five steps.", [
        ("1. Broad Taxonomy", "Step",
         "Start from a full list of attributes so no important dimension is overlooked."),
        ("2. Reduce With Stakeholders", "Step",
         "Work with a cross-section of stakeholders to find which attributes matter. An airport kiosk needs usability (infrequent users) and security (payments)."),
        ("3. Prioritize Pairwise", "Step",
         "Ask “If I could have only one of these, which would I take?” and build a comparison matrix. If security scores 7 and performance 4, resolve their conflicts toward security."),
        ("4. Elicit Specific Expectations", "Step",
         "Users can't answer “What are your reliability requirements?” but can answer “What would be an unacceptable failure?”"),
        ("5. Specify With SMART", "Step",
         "Specific, Measurable, Attainable, Relevant, Time-sensitive.",
         "“User-friendly” is unmeasurable, and “available 24×7” is rarely realistic or measurable. Ask: can a tester verify this objectively?"),
    ]),
    ("Specifying Key Attributes", "Textbook example requirements.", [
        ("Availability", "Attribute",
         "Planned uptime when services are fully operational. Define what “available” means, maintenance windows, and notifications.",
         "AVL-1: at least 95% available on weekdays 6:00 AM–midnight. Avoid 100%: a “five 9s” requirement caused about 25% of one system's cost."),
        ("Integrity", "Attribute",
         "Preventing information loss and preserving data correctness, with no tolerance for error.",
         "INT-1: after a backup, verify the copy and report discrepancies. INT-2: protect against unauthorized addition, deletion, or modification of data."),
        ("Performance", "Attribute",
         "Response time, throughput, capacity, predictability, latency, and degraded behavior.",
         "PER-1: ATM withdrawal authorization in no more than 2.0 seconds. PER-3: 98% of the time, update trade status within 1 second."),
        ("Reliability", "Attribute",
         "Probability of executing without failure for a period; a <strong>lagging indicator</strong>.",
         "REL-2: mean time between failures of the card reader at least 90 days."),
        ("Robustness", "Attribute",
         "Keeps functioning with invalid inputs, defective components, attacks, or unexpected conditions: fault tolerance, survivability, recoverability.",
         "ROB-1: recover unsaved text to within one minute of a crash. Don't specify the mechanism (autosave)."),
        ("Safety", "Attribute",
         "Preventing injury to people or damage to property, mainly for software-controlled hardware.",
         "SAF-2: the radiation machine shall irradiate only if the proper filter is in place."),
        ("Security", "Attribute",
         "Blocking unauthorized access, with no tolerance for error; often from business rules.",
         "SEC-1: lock an account after 3 failed logons within 5 minutes. SEC-4: only Auditors may view transaction histories."),
        ("Usability", "Attribute",
         "Ease of learning, memorability, error handling, efficiency, accessibility, and ergonomics, balanced across all users.",
         "USE-1: a trained user submits a chemical request in 3 minutes on average, and within 5 minutes 95% of the time."),
        ("Modifiability and Portability", "Attribute",
         "MOD-1: modify reports for new regulations in 10 hours or less.",
         "POR-1: porting the iOS app to Android changes no more than 10% of the source code."),
        ("Scalability", "Attribute",
         "Growth in users, data, servers, or traffic without losing performance.",
         "SCA-1: emergency line capacity increases from 500 to 2,500 calls per day within 12 hours."),
    ]),
    ("Trade-offs", "Prioritization tells you how to resolve conflicts.", [
        ("Security vs Performance", "Trade-off",
         "More security slows performance (authentication) and adds usability friction, but improves reliability through fewer breaches."),
        ("Portability, Reliability, Modifiability", "Trade-off",
         "Portability and modifiability add abstraction layers that cost performance; reliability adds redundancy overhead."),
        ("Resolving Conflicts", "Key Idea",
         "Bias each conflict toward the higher-ranked attribute, and know why it ranks higher in that domain. The airport kiosk favors security over performance."),
    ]),
    ("Constraints", "Restrictions on design or implementation choices.", [
        ("Definition", "Definition",
         "Imposed by external stakeholders, interacting systems, existing agreements, management decisions, or technical decisions."),
        ("Four Sources", "Classification",
         "<strong>Technology</strong> (tools, languages, versions), <strong>regulatory</strong> (laws, standards, business rules), <strong>physical</strong> (memory, size, weight), <strong>interface</strong> (existing systems, formats, protocols)."),
        ("Examples", "Example",
         "CON-2: only GNU GPL open source may be used. CON-3: must use .NET 4.5. CON-4: ATMs contain only $20 bills. CON-5: payments only via PayPal. CON-6: textual data stored as XML."),
        ("Hidden Solution Ideas", "Pitfall",
         "Users often present solution ideas as requirements. For “results shall appear in a dropdown”, ask why, write the need about search behavior, and list the dropdown as a constraint only if it is truly required."),
    ]),
    ("Easily Confused Pairs", "", [
        ("Reliability vs Availability", "Comparison",
         "Reliability: probability of <strong>not failing</strong> (MTBF). Availability: percentage of time <strong>up</strong>, including repair time, MTBF / (MTBF + MTTR). A system can fail often but restart quickly."),
        ("Safety vs Security", "Comparison",
         "Safety protects people and property <strong>from the system</strong>. Security protects the system <strong>from unauthorized people</strong>."),
        ("Integrity vs Security", "Comparison",
         "Integrity is data correctness and protection from loss. Security is sometimes considered a <strong>subset of integrity</strong> (True/False past exam: True)."),
        ("Robustness vs Reliability", "Comparison",
         "Reliability: won't fail. Robustness: handles failure gracefully. A non-robust system crashes ungracefully; an unreliable one crashes often."),
        ("Portability vs Scalability", "Comparison",
         "Portability: running on different platforms. Scalability: handling more load on the same or an expanded platform."),
    ]),
    ("Past Exam Questions", "", [
        ("Riyadh Season FRs and NFRs", "Past Exam · Quiz",
         "Functional: self-check-in using a ticket; issue a bracelet with an electronic chip.",
         "Non-functional: the online payment service shall be secure (security); a bracelet payment completes in under 3 seconds (performance)."),
        ("Which Is an NFR?", "Past Exam · MCQ",
         "“The system shall process payments within 2 seconds.” It says how fast, not what the system does."),
        ("Improving “24×7”", "Past Exam · Discussion",
         "It is unmeasurable, rarely realistic, and expensive.",
         "Better: “at least 99.5% available on weekdays 6:00 AM–midnight Riyadh Time, with maintenance allowed 2:00–5:00 AM Sunday.”"),
    ]),
]
