"""SE311 Chapter 10 mindmap content, built by scripts/build_se311_mindmaps.py."""

NUMBER = 10
TITLE = "Requirements Prioritization"
AR_TITLE = "ترتيب أولويات المتطلبات"
SLUG = "requirements-prioritization"
SUMMARY = "Interactive SE311 Chapter 10 mindmap: why requirements are prioritized, triage and the 80-20 rule, prioritization scales, Wiegers' method, Kano surveys, and the three-level scale."

BRANCHES = [
    ("Why Prioritize?", "Resources are always limited; you can rarely implement everything.", [
        ("Structural Difficulties", "Difficulty",
         "Too many requirements from too many sources, limited budget, time, and people; developers don't know business value and clients don't know complexity.",
         "Companies often lack data and metrics, so prioritization is manual, informal, and ad hoc."),
        ("Human and Political Difficulties", "Difficulty",
         "Stakeholders have conflicting goals, some carry more weight, and priorities are hard to communicate.",
         "“We can do everything!” lasts until the deadline, and then requirements get cut chaotically instead of strategically."),
        ("What It Must Achieve", "Key Idea",
         "Acceptable trade-offs among value, cost, and time-to-market; resources allocated by importance; the right time for each requirement; the right product at the right time."),
        ("The 80-20 Rule", "Key Idea",
         "Pareto principle: <strong>20% of functionality provides 80% of the value</strong> (or revenue). The same shape shows up elsewhere: 20% of drivers cause 80% of accidents."),
        ("The 80% Trap", "Pitfall",
         "The other 80% of functionality gives a lower return while adding delay, development, and maintenance cost. Think of how few Word features you use; find and protect the impactful 20%."),
    ]),
    ("Requirements Triage", "A medical term for sorting by urgency.", [
        ("Triage Defined", "Definition",
         "Deciding which requirements really matter and which should be implemented in the current release."),
        ("The Process Must Be", "Checklist",
         "Simple and fast enough for industry, accurate and reliable, maximize value to stakeholders, minimize cost and time to market, and agree on requirement granularity first (use cases, features, or detailed FRs)."),
        ("High Value, Low Cost", "Key Rule",
         "Top priority goes to requirements that provide the largest fraction of product value at the smallest fraction of cost: the high-value, low-cost quadrant."),
        ("Volvo Example", "Example",
         "Volvo mapped components by customer value against cost complexity: high-value, low-cost components were prioritized, and low-value, high-cost ones were flagged to avoid."),
    ]),
    ("1. Prioritization Scales", "Define criteria and a scale, then rate every requirement.", [
        ("Urgency Scale", "Scale",
         "<strong>High</strong>: mission critical, required for the next release. <strong>Medium</strong>: supports necessary operations, needed eventually. <strong>Low</strong>: an enhancement, nice to have if resources permit."),
        ("Importance Scale", "Scale",
         "<strong>Essential</strong>: product unacceptable without it. <strong>Conditional</strong>: enhances the product, but it's acceptable without. <strong>Optional</strong>: may or may not be worthwhile."),
        ("Small vs Large Projects", "Key Idea",
         "Small projects can agree informally. Large or contentious ones need structured methods to remove emotion, politics, and guesswork."),
    ]),
    ("2. Wiegers' Method", "Semi-quantitative, based on value, cost, and risk.", [
        ("Four Dimensions", "Technique",
         "Each scored 0–9 relative to the others: <strong>benefit</strong> of having it, <strong>penalty</strong> of not having it, <strong>cost</strong> to implement, and <strong>risk</strong>."),
        ("Priority Formula", "Formula",
         "Priority = Value% ÷ (Cost% × cost weight + Risk% × risk weight), where Value = benefit × benefit weight + penalty × penalty weight.",
         "Typical weights: benefit 2, penalty 1, cost 1, risk 0.5. High value with low cost and risk rises to the top."),
        ("Chemical Tracking Example", "Example",
         "“Query vendor order status” ranks first (1.345) despite moderate benefit because its cost and risk are very low.",
         "“Import from drawing tools” ranks last (0.365) because both cost and risk are high."),
        ("Strengths", "Comparison",
         "Systematic and analytical, removes some emotion and politics, considers several dimensions, gives comparable rankings, and weights can be adapted per project."),
        ("Limitations", "Comparison",
         "Only as good as the estimates; interdependent requirements are hard to score separately; stakeholder estimates are inconsistent; needs calibration per project."),
        ("Volere Prioritization Spreadsheet", "Technique",
         "Four weighted factors totaling 100%: value to customer 40%, value to business 20%, minimize implementation cost 10%, ease of implementation 30%. Priority = sum of score × weight."),
    ]),
    ("3. Kano Model", "Groups requirements by customer perception to maximize satisfaction.", [
        ("Basic", "Kano Category",
         "Taken for granted: absence causes extreme dissatisfaction, presence adds nothing. A car must have brakes."),
        ("Performance", "Kano Category",
         "Explicitly asked for: the more, the better. Better fuel economy means a happier customer."),
        ("Excitement", "Kano Category",
         "Neither requested nor expected: delight when present, no dissatisfaction when absent."),
        ("Indifferent and Reverse", "Kano Category",
         "<strong>Indifferent</strong>: customers don't care either way. <strong>Reverse</strong>: customers actively dislike it, so avoid it."),
        ("Survey Questions", "Technique",
         "For each requirement ask a <strong>functional</strong> question (reaction if it IS included) and a <strong>dysfunctional</strong> question (reaction if it is NOT).",
         "Answers: I like it, I expect it, I am neutral, I can tolerate it, I dislike it."),
        ("Reading the Matrix", "Technique",
         "Like if present and dislike if absent → Performance. Like if present, neutral or tolerant if absent → Excitement. Expect, neutral, or tolerate if present but dislike if absent → Basic.",
         "Dislike if present → Reverse. Contradictory answers → Questionable. Otherwise → Indifferent."),
        ("Priority Order (BPEIR)", "Memory Hook",
         "Basic > Performance > Excitement > Indifferent > Reverse. “<strong>B</strong>e <strong>P</strong>erfectly <strong>E</strong>xcited, <strong>I</strong>gnore <strong>R</strong>everse.”"),
    ]),
    ("4. Three-Level Scale", "High, Medium, Low from Importance × Urgency.", [
        ("The Matrix", "Technique",
         "Important and urgent → <strong>High</strong>. Important, not urgent → <strong>Medium</strong>. Neither → <strong>Low</strong>.",
         "It is subjective and imprecise, so stakeholders must agree on what each level means first."),
        ("High Priority", "Key Rule",
         "Must be in the next release or that release is not shippable; contractual or compliance obligations may dictate it."),
        ("Urgent but Not Important", "Pitfall",
         "Seems urgent to some stakeholders but doesn't achieve business objectives. Don't waste time on these: set them Low or scrub them."),
        ("Too Many Highs", "Technique",
         "Record each priority in the SRS and prioritize iteratively. If the High group is too big, re-rank it into Highest, Higher, and High.",
         "“Highest” becomes the new top priority; “Higher” and “High” merge with the original Medium requirements."),
    ]),
    ("Other Criteria", "Cost and benefit alone are sometimes not enough.", [
        ("Financial", "Criteria",
         "Cost of implementation, value to the customer, and value to the company."),
        ("Time and Technical", "Criteria",
         "Time to implement, ease of implementation at the technical level, and at the organizational level (business process changes)."),
        ("Legal and Strategic", "Criteria",
         "Obligations to external authorities (laws, standards, patents, compliance) and strategic competitive advantage."),
        ("Risk (ISO 31000)", "Definition",
         "“The effect of uncertainty on objectives”: risk covers both negative threats and positive opportunities, not just probability of loss.",
         "Identify it, characterize the uncertainty, assess susceptibility, estimate damage or gain × probability, and find ways to reduce negative risks."),
    ]),
    ("Optional Techniques", "Listed for self-study.", [
        ("In or Out, Pairwise", "Technique",
         "<strong>In or Out</strong>: a binary in-scope decision per requirement. <strong>Pairwise comparison and rank ordering</strong>: compare every requirement pair by pair."),
        ("MoSCoW and $100", "Technique",
         "<strong>MoSCoW</strong>: Must, Should, Could, Won't. <strong>$100 method</strong>: stakeholders distribute $100 across requirements."),
        ("AHP and Focal Point", "Technique",
         "<strong>AHP</strong> (Analytic Hierarchy Process): a mathematical multi-criteria method.",
         "<strong>TeamBLUE Focal Point</strong>: a commercial decision tool with dynamic pairwise comparisons, web questionnaires, inconsistency detection, and IBM DOORS integration."),
    ]),
    ("Comparing Techniques", "", [
        ("Scales vs Three-Level", "Comparison",
         "Both are subjective. Scales suit small teams and quick early decisions. The three-level scale suits most projects and is easy to communicate, but its High bucket bloats without iterative refinement."),
        ("Wiegers vs Kano", "Comparison",
         "Wiegers is semi-quantitative, for large projects needing formula-based ranking, but depends on estimates.",
         "Kano is survey-based, for customer-facing products and satisfaction drivers, but surveys are slow and need a representative sample."),
    ]),
]
