#!/usr/bin/env python3
"""Build SE322 Ethics-style mindmaps and comprehensive chapter exams."""
from pathlib import Path
import re
import build_se401_study_tools as core

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "docs/academics/software-engineering/se322"

CHAPTERS = [
 ("introduction-to-software-design-and-architecture", "Introduction to Software Design and Architecture", [
  ("Software Engineering Foundations", "IEEE defines software engineering as a systematic, disciplined, and quantifiable approach to software development, operation, and maintenance.", ["The SDLC connects requirements, design, implementation, testing, deployment, and maintenance.", "Engineering problem solving identifies the initial state, goal state, constraints, candidate solutions, evaluation, and implementation.", "Design is studied because defects and costly decisions are easier to address before construction.", "Cost of change grows roughly by an order of magnitude per phase, so a requirement misread in analysis is cheap to fix on paper and expensive to fix in production.", "Systematic means repeatable and reviewable; quantifiable means the result can be measured against stated targets rather than judged by taste."], [
   ("Cost of a late fix", "A payment system stores money as a floating-point number. Caught in design review it is a one-line type decision; caught after launch it means a schema migration, a data-repair script, reconciliation with the bank, and a customer refund process."),
   ("Problem-solving frame", "Initial state: a monolithic student portal that takes 40 minutes to deploy. Goal state: deploys under 5 minutes. Constraints: same Oracle database, no new servers this year. Candidates: modularize the build, split services, add a deploy cache — each evaluated against the constraints before one is implemented."),
  ]),
  ("Design vs Architecture", "Architecture captures system-wide structures and high-impact decisions; detailed design refines components and collaborations.", ["Architecture addresses elements, externally visible properties, and relationships.", "Detailed design turns architectural responsibilities into classes, interfaces, algorithms, and data structures.", "Both manage complexity through abstraction, decomposition, and separation of concerns.", "A useful test: if the decision is expensive to reverse and affects many teams or qualities, it is architectural; if it is local and cheaply replaced, it is detailed design.", "Externally visible properties are what other elements can depend on — provided services, performance characteristics, resource use — not internal implementation."], [
   ("Architectural decision", "Choosing to split an e-commerce system into separate catalog, cart, and payment services communicating over HTTP. It fixes deployment boundaries, failure modes, and team ownership for years."),
   ("Detailed-design decision", "Inside the cart service, choosing a HashMap keyed by SKU to hold line items and a Strategy class per discount rule. Swapping either one is an afternoon of work and no other service notices."),
  ]),
  ("Stakeholders & Concerns", "Architectural decisions serve multiple stakeholders whose concerns can conflict.", ["Users emphasize usability and reliability; developers emphasize modifiability; operators emphasize deployability and observability.", "A viewpoint frames particular concerns; a view is the resulting representation.", "Trade-offs must be explicit and justified.", "Business stakeholders add time-to-market, cost, and market position; maintainers add testability and comprehensibility.", "Unstated concerns become surprise requirements late in the project, which is why stakeholder identification is an architectural activity, not a formality."], [
   ("Conflicting concerns", "In a hospital records system the physician wants one-click access to a chart, the compliance officer wants re-authentication every five minutes, and the operator wants full audit logging. The architecture resolves this with a short-lived session token plus a break-glass emergency-access path that logs loudly."),
   ("Viewpoint vs view", "The deployment viewpoint says: show nodes, artifacts, and networks for the operations team. The deployment view is the actual diagram showing two web nodes behind a load balancer with a replicated database."),
  ]),
  ("Architectural Drivers", "Business goals, functional requirements, quality attributes, and constraints shape the architecture.", ["Drivers are the small set of requirements with major architectural influence.", "Constraints restrict choice, such as mandated technology, regulation, budget, or legacy integration.", "Architecturally significant requirements should be measurable and prioritized.", "Most functional requirements are not architectural; the few that are usually involve scale, distribution, security boundaries, or integration.", "A driver is worth recording only if you can name the structure it forces or the alternative it eliminates."], [
   ("Quality-attribute driver", "\"Checkout must complete in under 2 seconds at 10,000 concurrent users on Black Friday\" forces caching, read replicas, and asynchronous order processing — it shapes structure far more than \"the user can apply a coupon\"."),
   ("Constraint", "A university mandates the existing Oracle database and Saudi data-residency rules. That removes managed cloud databases in other regions from the option set before design starts."),
  ]),
  ("Design Process", "Move iteratively from requirements and context to structures, responsibilities, interfaces, and evaluation.", ["Decompose around responsibilities and change boundaries.", "Record decisions, rationale, assumptions, and rejected alternatives.", "Validate early with scenarios, prototypes, reviews, and risk analysis.", "Attribute-Driven Design iterates: choose an element to decompose, pick the driving requirement, select tactics and patterns, allocate responsibilities and interfaces, then verify before the next round.", "Design is iterative because analysis reveals new drivers; a single top-down pass rarely survives the first prototype."], [
   ("Decomposing by change boundary", "Tax rules change every fiscal year while the invoice layout is stable, so tax calculation becomes its own module with a versioned rule table rather than being scattered through invoice code."),
   ("Early validation", "Before committing to a message broker, the team builds a two-day spike that pushes 50,000 synthetic events through it and measures end-to-end latency; the prototype, not the vendor's slide deck, decides."),
  ]),
  ("Good Design", "Good design balances correctness, simplicity, cohesion, low coupling, information hiding, and evolvability.", ["There is rarely one universally best architecture.", "Premature detail and accidental complexity make change harder.", "Design quality is demonstrated against stakeholder scenarios, not aesthetic preference alone.", "Essential complexity comes from the problem itself; accidental complexity comes from our chosen solution and is the part we can design away.", "Simplicity is not fewer features but fewer things a reader must hold in mind to change one behavior safely."], [
   ("Accidental complexity", "A team adds a plugin framework, a rules engine, and a message bus to a CRUD admin tool used by six staff members. None of the flexibility is ever exercised, but every bug fix now crosses three layers."),
   ("Fit for context", "A layered monolith is the better architecture for a 3-person startup that must ship in two months; the same design would be the wrong answer for a 200-engineer platform needing independent deploys."),
  ]),
  ("Design Challenges", "Architects must manage volatile requirements, inconsistent processes, rapidly changing technology, design influences, and professional obligations.", ["AI and machine-learning technologies add fast-moving constraints and uncertainty.", "Quality goals frequently conflict and require explicit trade-offs.", "Ethical and professional practices remain design constraints, not optional extras.", "Architects work with incomplete information under deadline; deferring a decision until evidence exists is itself a legitimate design move.", "Team structure influences architecture (Conway's law), so organizational boundaries should be designed alongside technical ones."], [
   ("Conflicting qualities", "Encrypting every field in a medical database raises confidentiality but breaks indexed search and adds latency. The team encrypts identifiers and free-text notes, keeps coded diagnoses searchable, and records the residual risk."),
   ("Conway's law in practice", "Three teams in three time zones each own a layer of one monolith, so every feature needs three coordinated releases. Reorganizing into feature teams that own vertical slices changes both the org chart and the architecture."),
  ])]),
 ("software-architecture", "Software Architecture", [
  ("Structures", "An architecture comprises multiple complementary structures rather than one diagram.", ["Module structures show implementation units and dependencies.", "Component-and-connector structures show runtime elements and interactions.", "Allocation structures map software to hardware, teams, files, or deployment environments.", "Module views answer \"what can a developer change and what breaks?\"; C&C views answer \"what is running and how does it talk?\"; allocation views answer \"where does it live and who owns it?\".", "One module can map to many runtime components and one component can span many modules, so the structures cannot be collapsed into a single picture."], [
   ("Three views of one system", "A `PaymentValidator` class sits in the payments module (module view), runs as three replicated instances behind a queue (C&C view), and is deployed to two availability zones and owned by the Payments team (allocation view)."),
   ("Uses structure", "The reporting module uses the ledger module but not vice versa. That one-way dependency is what allows reporting to be rebuilt or replaced without touching the ledger."),
  ]),
  ("Views & Viewpoints", "Views communicate architecture for defined stakeholder concerns.", ["A viewpoint defines conventions, stakeholders, concerns, and modeling rules.", "Logical, process, development, physical, and scenario views answer different questions.", "Consistency across views matters because they describe one system.", "Choose views by asking which stakeholder question would go unanswered without them, rather than producing a fixed set out of habit.", "A view without a key and defined element semantics is decoration; boxes and lines alone carry no agreed meaning."], [
   ("Concern-driven selection", "A regulator asks where personal data crosses a network boundary. Neither the class diagram nor the sequence diagram answers it — a deployment view annotated with trust zones does."),
   ("Cross-view consistency", "The process view shows an async event from Order to Shipping, but the module view shows Shipping calling Order directly. One of them is wrong, and the mismatch is a real architectural defect, not a drawing error."),
  ]),
  ("Requirements Engineering", "Elicitation, analysis, specification, validation, and management provide the architectural test basis.", ["Elicitation uses interviews, facilitated meetings, observation, and scenarios.", "Analysis includes classification, prioritization, negotiation, and conceptual modeling.", "Requirements may be imposed or derived and product- or process-oriented.", "Good requirements are specific, consistent, correct, attainable, complete, and verifiable.", "Quality attribute scenarios make nonfunctional requirements testable.", "Traceability connects drivers to decisions and verification evidence.", "Imposed requirements come from outside (law, standards, corporate policy); derived requirements are consequences the team infers from them."], [
   ("Unverifiable vs verifiable", "\"The system shall be fast\" cannot be tested. \"95% of catalog searches return within 300 ms with 500 concurrent users\" can be measured and can fail a build."),
   ("Traceability chain", "Business goal \"expand to the EU\" → requirement \"support GDPR erasure requests\" → decision \"user data isolated behind a single deletion API\" → evidence \"integration test deletes a user across all seven stores\"."),
  ]),
  ("Kruchten 4+1 Views", "The 4+1 model combines logical, process, development, physical, and scenario views.", ["Logical views commonly use class, collaboration, and sequence diagrams.", "Process views use activity models; development views use component or package diagrams.", "Physical views use deployment diagrams, while scenarios connect the other four with use cases or textual flows.", "The logical view serves end users, the process view serves integrators, the development view serves programmers, and the physical view serves system engineers.", "Scenarios are the \"+1\" because they validate the other four: a use case must be traceable through all of them."], [
   ("One scenario, four views", "\"Student registers for a course\": logical view shows Student, Section, and Registration classes; process view shows the seat-reservation transaction and its locking; development view shows the registration package depending on the billing package; physical view shows the app server, the SIS database, and the payment gateway."),
   ("Physical view value", "The deployment diagram is what reveals that the reporting job and the live registration service share one database node — the source of every peak-week slowdown."),
  ]),
  ("Architectural Decisions", "Important decisions constrain structures and future options and therefore require rationale.", ["Document context, decision, alternatives, consequences, and status in an ADR.", "Irreversible or expensive decisions deserve early evidence.", "Technical debt is a deliberate or accidental future obligation.", "Recording the rejected alternatives is what stops the same debate from reopening every six months when the original context is forgotten.", "An ADR status moves through proposed, accepted, deprecated, and superseded, so the record stays honest as the system evolves."], [
   ("ADR shape", "ADR-014 — Context: reporting queries slow the transactional database. Decision: add a read replica and route all reports to it. Alternatives: materialized views (rejected, staleness unacceptable); separate warehouse (rejected, too costly now). Consequences: eventual-consistency lag up to 5 s must be shown in report headers. Status: accepted."),
   ("Deliberate technical debt", "The team ships a hard-coded currency conversion table to hit a launch date, records it as debt with a review date, and replaces it with a rates service in the next quarter — debt taken knowingly, not accidentally."),
  ]),
  ("Interfaces & Contracts", "Interfaces define provided and required services plus behavioral assumptions.", ["Contracts cover syntax, semantics, protocols, errors, timing, and versioning.", "Stable interfaces reduce coupling but cannot hide every quality concern.", "Integration failures often arise from mismatched assumptions rather than syntax alone.", "An interface has two sides: what the element provides and what it requires from others; documenting only the provided half hides half the coupling.", "Preconditions, postconditions, and invariants make the semantic half of a contract checkable rather than conversational."], [
   ("Semantic mismatch", "Two services both agree on `{\"amount\": 1050}`. One means 1050 halalas, the other 1050 riyals. The JSON schema validates perfectly and the money is wrong by a factor of 100."),
   ("Versioning contract", "A payments API adds an optional `installments` field and keeps old clients working; removing the deprecated `card_token` field waits for a v2 endpoint so no client breaks mid-release."),
  ]),
  ("Architecture Lifecycle", "Architecture evolves through analysis, synthesis, documentation, implementation, evaluation, and governance.", ["Architecture is not a one-time phase artifact.", "Conformance checks detect drift between intended and implemented structures.", "Governance should enable consistent decisions without unnecessary bureaucracy.", "Architectural erosion happens when code violates intended structure; architectural drift happens when the design evolves without the documentation following.", "Fitness functions — automated checks in the build — turn architectural rules into something CI can enforce."], [
   ("Conformance check in CI", "An ArchUnit test asserts that no class in `domain` imports anything from `infrastructure`. The build fails the first time a developer takes the shortcut, before the layering quietly dissolves."),
   ("Drift", "The documented architecture still shows a single deployable, but the team split off two services last quarter. New joiners follow the diagram and wire dependencies the wrong way."),
  ])]),
 ("quality-attributes", "Quality Attributes", [
  ("Quality Scenarios", "Specify source, stimulus, environment, artifact, response, and response measure.", ["A measurable response turns a vague quality wish into an analyzable requirement.", "General scenarios are reusable; concrete scenarios are system-specific.", "Quality attributes interact and often conflict.", "The six parts are: who or what triggers it, what arrives, under what system state, which part is hit, what the system does, and how the response is measured.", "Environment matters because the acceptable response under normal load differs from the response under degraded or overload conditions."], [
   ("Six-part availability scenario", "Source: a database node. Stimulus: the node crashes. Environment: normal operation at peak hours. Artifact: the order service's data store. Response: the standby is promoted and in-flight transactions are replayed. Measure: service restored within 30 seconds with no committed order lost."),
   ("Performance scenario", "Source: 5,000 concurrent users. Stimulus: submit search queries. Environment: exam-week peak. Artifact: catalog search. Response: results returned. Measure: 95th-percentile latency under 500 ms, no request over 2 s."),
  ]),
  ("Design Decisions", "Quality is shaped by seven recurring architectural decisions: responsibilities, coordination, data, resources, element mapping, binding time, and technology.", ["Allocation of responsibilities determines where behavior and knowledge live.", "Coordination and resource-management choices shape runtime qualities.", "Binding-time and technology choices trade flexibility against complexity and cost.", "Data-model decisions cover what is stored, where, how it is partitioned, and how consistently it must be replicated.", "Mapping elements to runtime and deployment structures decides what can scale, fail, or be released independently."], [
   ("Binding time", "A discount rate hard-coded at compile time is fast but needs a release to change; the same rate in a config file binds at startup; in a rules table it binds at run time and marketing can change it without a deploy — each step buys flexibility and adds a failure mode."),
   ("Resource management", "A thread pool capped at 200 with a bounded queue protects the service under a traffic spike; an unbounded pool answers more requests briefly, then dies from memory exhaustion."),
  ]),
  ("Performance", "Performance concerns latency, throughput, capacity, deadlines, and resource use.", ["Demand can be controlled through sampling, admission, or prioritization.", "Resources can be increased, scheduled, replicated, or made more efficient.", "Measure percentile latency and behavior under representative load.", "Averages hide the users who suffer; p95 and p99 are what customers actually experience during a spike.", "Queueing effects mean latency rises sharply as utilization approaches capacity, so headroom is a design parameter, not waste."], [
   ("Control demand", "A public API applies rate limiting of 100 requests/minute per key and drops low-priority analytics events first when the queue exceeds 80% — the checkout path keeps its capacity."),
   ("Manage resources", "Adding a Redis cache in front of the product catalog turns a 120 ms database join into a 3 ms lookup for 90% of reads, and the cache TTL becomes the new staleness trade-off."),
  ]),
  ("Availability", "Availability is readiness for correct service despite faults.", ["Detect faults with ping/echo, heartbeat, exceptions, or voting.", "Recovery preparation includes active or passive redundancy and spares.", "Reintroduction tactics include shadow state, resynchronization, and rollback.", "Prevention includes removal from service, transactions, and process monitoring.", "MTBF and MTTR influence achieved availability.", "Availability = MTBF / (MTBF + MTTR), so halving repair time improves availability as much as doubling time between failures.", "A fault becomes a failure only when it reaches the user; masking a fault fast enough is a valid availability strategy."], [
   ("Detect and recover", "Kubernetes sends a liveness probe every 5 seconds; three misses and the pod is killed and rescheduled while the load balancer stops routing to it — detection by heartbeat, recovery by spare."),
   ("Nines arithmetic", "99.9% availability allows about 8.8 hours of downtime a year; 99.99% allows about 53 minutes. Moving between those two tiers is usually the difference between one region and two."),
   ("Reintroduction", "A repaired replica replays the write-ahead log to catch up (resynchronization) and serves shadow traffic for ten minutes before it is trusted with real users."),
  ]),
  ("Security", "Security protects confidentiality, integrity, availability, authenticity, accountability, and non-repudiation.", ["Authenticate subjects, authorize actions, limit exposure, encrypt data, and audit activity.", "Defense in depth avoids a single control becoming a single point of failure.", "Threat modeling links assets, threats, vulnerabilities, and mitigations.", "Tactics group into detect attacks, resist attacks, react to attacks, and recover from attacks.", "Least privilege and limited exposure shrink the blast radius of any single compromised component."], [
   ("Defense in depth", "A stolen API key still fails because the request also needs a valid mTLS client certificate, comes from an unexpected IP range, and exceeds the per-key rate limit — three independent controls, no single point of failure."),
   ("STRIDE threat modeling", "For a grade-entry feature: Spoofing (a student impersonates faculty), Tampering (grade altered in transit), Repudiation (instructor denies the change) — mitigated by SSO, TLS with signed payloads, and an append-only audit log."),
  ]),
  ("Modifiability & Testability", "Design to localize change and make behavior controllable and observable.", ["High cohesion, low coupling, abstraction, and indirection contain ripple effects.", "Dependency injection and stable interfaces improve substitution and testing.", "Testability requires controllability, observability, isolation, and repeatability.", "Modifiability tactics reduce the size of a module, increase cohesion, reduce coupling, and defer binding time.", "Modifiability is measured in cost: how many modules must change, and how much effort and calendar time the change takes."], [
   ("Localizing change", "Adding a new payment provider touches one class implementing `PaymentGateway` plus one configuration entry, because every caller depends on the interface rather than on Stripe's SDK."),
   ("Controllability", "The billing service takes a `Clock` dependency, so a test can set the date to 29 February and to a month boundary instead of waiting for the calendar."),
  ]),
  ("Usability & Interoperability", "Usability supports effective user action; interoperability supports meaningful exchange across systems.", ["Separate UI from domain logic and support cancel, undo, feedback, and error recovery.", "Interoperability requires shared syntax, semantics, protocols, and identity assumptions.", "Standards help but do not guarantee compatible meaning.", "Usability tactics split into supporting the user initiative (cancel, undo, pause, aggregate) and supporting system initiative (maintaining models of the user, task, and system).", "Interoperability tactics include discovering services and orchestrating or tailoring the interface between mismatched parties."], [
   ("Support user initiative", "A long report export shows progress, stays cancellable, and leaves no partial file behind — which requires the export to run outside the UI thread and to write atomically."),
   ("Semantic interoperability", "Two hospitals both speak HL7 FHIR, but one records blood pressure as a single string and the other as separate systolic and diastolic values. Syntax matches, meaning does not, so a translation layer is still required."),
  ])]),
 ("architecture-patterns", "Architecture Patterns", [
  ("Pattern Foundations", "Architectural styles name families of organization; patterns capture reusable solutions in context, influenced by Christopher Alexander and adopted by software engineering in the 1990s.", ["Data-centered styles include repository and blackboard.", "Data-flow styles include pipes and filters; distributed styles include client-server and broker.", "Interactive styles include MVC, while hierarchical styles include layered architecture.", "A pattern is documented as a problem in a context with a solution and its consequences — the consequences are what make it a design tool rather than a template.", "A style is a vocabulary of element and connector types plus constraints on how they may be combined."], [
   ("Alexander's influence", "Alexander described building patterns such as \"light on two sides of every room\": a recurring problem, a context, and a solution with trade-offs. Gamma and colleagues carried that form into software in 1994."),
   ("Style as constraint", "The layered style's constraint — a layer may only call the layer below — is what delivers its benefits. A system that draws layers but calls freely across them gets the diagram without the portability."),
  ]),
  ("Layered", "Organize responsibilities into abstraction layers with controlled dependencies.", ["Benefits include portability, replaceability, and separation of concerns.", "Costs include latency, duplicated transformations, and layer bypass pressure.", "Closed layers restrict calls to adjacent layers; open layers permit skipping.", "The sinkhole anti-pattern appears when most requests pass through layers that add no logic, paying the cost of the structure without the benefit.", "Layering is the default for business applications because it maps cleanly onto team skills and is easy to reason about."], [
   ("Classic four layers", "Presentation (React screens) → Business (order rules, pricing) → Persistence (repositories) → Database (PostgreSQL). Swapping the UI for a mobile client touches only the top layer."),
   ("Sinkhole", "A read-only \"list countries\" request passes through a controller, a service that only forwards, a repository that only forwards, and the database. Marking the persistence layer open for pure lookups avoids two useless hops."),
  ]),
  ("Model–View–Controller", "Separate domain state, presentation, and input coordination.", ["The controller interprets input and updates the model; the model notifies observing views of change.", "Multiple views can share one model.", "Poor responsibility allocation can create fat controllers or anemic models.", "MVC improves UI change isolation but adds interaction complexity.", "The model must not know about specific views; it publishes change notifications and observers react — that is the Observer pattern doing the work inside MVC.", "MVP and MVVM are variants that move more coordination out of the view for easier testing."], [
   ("Shared model, many views", "A spreadsheet holds one set of numbers. A bar chart, a pie chart, and the cell grid all observe it; typing in one cell updates all three without any view knowing the others exist."),
   ("Fat controller smell", "A `CheckoutController` that computes tax, applies loyalty rules, and calls the payment gateway has absorbed the model's job — the same logic then cannot be reused by the mobile API."),
  ]),
  ("Pipes and Filters", "Independent filters transform streams connected by pipes.", ["Filters can be reused, reordered, and executed concurrently.", "Shared state and interactive workflows fit poorly.", "Define data formats, error propagation, backpressure, and termination.", "Each filter should be independent and stateless with respect to its neighbours, knowing only its input and output format.", "Throughput is limited by the slowest filter, and a single shared data format is what keeps filters recombinable."], [
   ("Unix pipeline", "`cat access.log | grep 500 | cut -d' ' -f7 | sort | uniq -c | sort -rn` — five reusable filters composed into a report, each ignorant of the others."),
   ("Compiler and CI", "Lexer → parser → semantic analyzer → optimizer → code generator is the textbook pipeline; a CI stage of lint → build → unit test → package → scan is the same style applied to delivery."),
   ("Poor fit", "An interactive form wizard that lets the user go back and edit step 2 after step 4 fits pipes and filters badly, because the style assumes a one-way stream."),
  ]),
  ("Client–Server & Broker", "Clients request services; servers provide them; brokers mediate location and communication.", ["Broker improves distribution transparency and loose coupling.", "Networks introduce partial failure, latency, retries, and versioning.", "Avoid assuming remote calls behave like local calls.", "A broker registers servers, locates them for clients, forwards requests, and returns results or exceptions.", "Idempotent operations make retries safe; without them a retry after a timeout can charge a customer twice."], [
   ("Broker in practice", "A service registry plus API gateway: the mobile client calls `api.shop.com/orders` and the gateway resolves which of the twelve order-service instances handles it, hiding location entirely."),
   ("Fallacy of transparency", "Code written as `order.getCustomer().getAddress().getCity()` is fine locally and catastrophic remotely — three network round-trips per order, each able to time out on its own."),
  ]),
  ("Repository & Blackboard", "Components coordinate through shared data; blackboard systems iteratively contribute partial solutions.", ["A blackboard architecture separates shared blackboard data, specialist knowledge-source agents, and a controller.", "Agents inspect and contribute partial solutions while the controller selects what acts next.", "Repository centralizes data consistency but can become a bottleneck and coupling point.", "Blackboard suits problems with no deterministic solution sequence.", "In the repository style the data is passive and the clients drive control; in the blackboard style changes to the data drive which agent runs next."], [
   ("Repository", "An IDE where the parser, the debugger, the refactoring tool, and the version-control plugin all read and write one shared project model — and all stall when that model locks."),
   ("Blackboard", "Speech recognition posts a raw waveform; acoustic, phonetic, lexical, and grammar agents each add partial hypotheses; the controller repeatedly picks whichever agent can most improve the current best interpretation."),
  ]),
  ("Event-Driven", "Producers publish events and consumers react asynchronously.", ["It improves decoupling and scalability but complicates ordering and debugging.", "Design for idempotency, duplicate delivery, eventual consistency, and failure handling.", "Events should represent meaningful facts with stable schemas.", "A mediator topology routes an event through an orchestrator for multi-step workflows; a broker topology chains consumers directly for simpler flows.", "Debugging is harder because no single call stack shows the whole transaction — correlation IDs and tracing replace the stack."], [
   ("Fan-out", "`OrderPlaced` is published once and independently consumed by inventory, email, analytics, and fraud detection. Adding a loyalty-points consumer requires no change to the order service."),
   ("Duplicate delivery", "At-least-once delivery means the email consumer may see `OrderPlaced` twice. Keying sent mail on the event ID makes the second delivery a no-op instead of a second receipt in the customer's inbox."),
  ])]),
 ("principles-of-detailed-design", "Principles of Detailed Design", [
  ("Detailed-Design Workflow", "Detailed design sits between architecture and construction and refines components into implementable structures and behavior.", ["Tasks include understanding architecture and requirements, internal and external interface design, GUI design, component structure and behavior, data and database design, evaluation, documentation, and implementation management.", "Documentation includes interface control documents, data dictionaries, and version-controlled design records.", "Reverse engineering recovers design knowledge from an existing implementation.", "Detailed design must respect architectural decisions; a component that quietly opens its own database connection breaks the architecture from below.", "The output is specific enough that a competent developer can implement it without re-deciding structure."], [
   ("Data dictionary entry", "`enrollment.status` — enumeration {PENDING, CONFIRMED, WAITLISTED, DROPPED}; set by RegistrationService only; PENDING expires after 30 minutes; never null."),
   ("Reverse engineering", "Facing an undocumented legacy payroll module, the team generates class and sequence diagrams from the code, then annotates them with observed behavior before attempting any change."),
  ]),
  ("Object-Oriented Modeling", "Classes, interfaces, inheritance, polymorphism, generalization, and realization express detailed object-oriented structure and behavior.", ["Abstract classes or methods defer some implementation; concrete classes can be instantiated.", "Generalization models an is-a relationship; realization connects a classifier to an implemented interface.", "Internal behavior models should preserve requirements while allocating responsibilities clearly.", "Association, aggregation, and composition differ in lifetime coupling: composition means the part dies with the whole.", "Polymorphism lets a caller hold an abstract reference and get behavior chosen by the concrete type at run time — the mechanism behind most design patterns."], [
   ("Aggregation vs composition", "A `Department` aggregates `Professor` objects — delete the department and the professors still exist. An `Invoice` composes `InvoiceLine` objects — delete the invoice and the lines are meaningless and go with it."),
   ("Polymorphism", "`Shape.area()` is abstract; `Circle`, `Rectangle`, and `Triangle` each implement it. A billing report sums `shapes.stream().mapToDouble(Shape::area)` without a single type check."),
  ]),
  ("Abstraction & Encapsulation", "Expose essential behavior while hiding volatile representation and implementation choices.", ["Program to contracts, not concrete details.", "Information hiding localizes likely change.", "Encapsulation includes behavioral invariants, not only private fields.", "Parnas's criterion: modularize around the decisions most likely to change, and hide each one inside a module.", "A getter that returns the internal mutable collection breaks encapsulation as surely as a public field."], [
   ("Leaky encapsulation", "`getItems()` returning the internal `List` lets any caller do `cart.getItems().clear()` and bypass the recalculation of totals. Returning an unmodifiable copy restores the invariant."),
   ("Hiding a decision", "The choice of Redis for session storage lives behind a `SessionStore` interface, so moving to a database-backed store later changes one class instead of forty call sites."),
  ]),
  ("Cohesion & Coupling", "Place closely related responsibilities together and minimize unnecessary dependencies.", ["Functional cohesion is stronger than coincidental grouping.", "Content and common coupling are especially harmful.", "Interfaces, events, and dependency inversion can reduce coupling when used deliberately.", "Cohesion runs from coincidental, logical, temporal, procedural, communicational, and sequential up to functional.", "Coupling runs from content and common through control and stamp down to data coupling, which is the weakest and preferred form."], [
   ("Coincidental cohesion", "A `Utils` class holding date formatting, password hashing, and CSV parsing — grouped only because nothing else claimed them. Every team touches it and every change risks an unrelated feature."),
   ("Control coupling", "`generateReport(type, isPdf, includeCharts)` makes the caller steer the callee's internal branching. Separate `PdfReport` and `CsvReport` implementations remove the flags and the coupling."),
  ]),
  ("SRP & OCP", "A module should have one reason to change and be open to extension without repeated modification.", ["SRP is about alignment with an actor or change source, not doing only one tiny task.", "OCP often uses polymorphism, composition, configuration, or plugins.", "Do not introduce extension mechanisms without a credible variation point.", "A class serving two actors — say finance and operations — has two reasons to change and will eventually break one while serving the other.", "OCP pays off where variation is real and recurring; speculative extension points are accidental complexity."], [
   ("SRP by actor", "`Employee` with `calculatePay()` (finance), `reportHours()` (operations), and `save()` (DBA) answers to three actors. Splitting into `PayCalculator`, `HourReporter`, and `EmployeeRepository` gives each change one home."),
   ("OCP", "A growing `switch` over shipping carriers is replaced by a `ShippingCarrier` interface with `Aramex`, `SMSA`, and `DHL` implementations registered at startup — a new carrier is a new class, not an edit to tested code."),
  ]),
  ("LSP & ISP", "Subtypes must preserve client expectations; interfaces should be focused around client needs.", ["LSP forbids stronger preconditions and weaker postconditions.", "Behavioral incompatibility cannot be repaired by matching method signatures.", "ISP prevents clients depending on operations they do not use.", "A subtype that throws `UnsupportedOperationException` for an inherited method is announcing an LSP violation at run time.", "Fat interfaces force recompilation and re-stubbing on clients that never call the added methods."], [
   ("LSP violation", "`Square extends Rectangle` overriding `setWidth` to also set the height. Client code that sets width 5 and height 4 and expects area 20 gets 16 — the signature matched, the behavior did not."),
   ("ISP fix", "A `Printer` interface with `print`, `scan`, `fax`, and `staple` forces a basic printer to stub three methods. Splitting it into `Printer`, `Scanner`, and `FaxMachine` lets each device implement only what it does."),
  ]),
  ("Dependency Inversion", "High-level policy and low-level detail should depend on abstractions.", ["Dependency injection supplies collaborators from outside.", "DIP reverses source-code dependency; it does not mean every class needs an interface.", "Stable abstractions protect policy from volatile infrastructure.", "The abstraction should be owned by the high-level module, so the detail conforms to policy rather than policy conforming to the detail.", "Dependency injection is a mechanism; dependency inversion is the design goal, and one can be used without achieving the other."], [
   ("Inverting the dependency", "`OrderService` (policy) declares the `NotificationSender` interface it needs; `SmtpSender` and `SmsSender` (details) implement it. The arrow at compile time now points from infrastructure to the domain, not the reverse."),
   ("Injection in a test", "The constructor takes a `PaymentGateway`, so the unit test passes a fake that returns DECLINED and asserts the retry path — no network, no sandbox account, runs in milliseconds."),
  ]),
  ("Composition & Refactoring", "Prefer assembling focused objects and continuously improve structure without changing behavior.", ["Composition is often more flexible than inheritance.", "Code smells indicate design pressure, not automatic rewrite commands.", "Automated tests make safe incremental refactoring possible.", "Inheritance binds subclass to superclass implementation at compile time; composition can be reconfigured at run time and avoids the fragile base class problem.", "Refactoring is behavior-preserving by definition — changing behavior at the same time is what turns a refactor into an outage."], [
   ("Composition over inheritance", "Instead of `LoggingCachingRetryingRepository` deep in an inheritance chain, wrap a plain repository with a logging decorator, a caching decorator, and a retry decorator, composed differently per environment."),
   ("Named smells", "Long method, large class, long parameter list, shotgun surgery, feature envy, and duplicated code — each points at a specific refactoring (extract method, extract class, introduce parameter object, move method)."),
  ])]),
 ("creational-design-patterns", "Creational Design Patterns", [
  ("Pattern Classification", "Design patterns are classified by purpose and by class-level or object-level scope and should be documented with intent, applicability, structure, participants, consequences, and examples.", ["Creational patterns separate clients from concrete construction decisions.", "Class patterns rely mainly on inheritance; object patterns rely mainly on composition.", "The five covered creational patterns are Abstract Factory, Factory Method, Builder, Prototype, and Singleton.", "The three purposes are creational, structural, and behavioral; the two scopes are class and object.", "Factory Method is the one class-scoped creational pattern; the other four are object-scoped."], [
   ("Reading a pattern entry", "Intent: \"ensure a class has one instance\". Applicability: \"there must be exactly one and clients need a well-known access point\". Consequences: \"controlled access, but global state and harder testing\" — the consequences decide whether you should use it."),
   ("Purpose vs scope", "Factory Method varies the product through subclassing (class scope, inheritance); Abstract Factory varies it by swapping a factory object at run time (object scope, composition)."),
  ]),
  ("Factory Method", "Define a creation operation while allowing subclasses or collaborators to choose the concrete product.", ["It removes direct construction from client policy.", "Use when product type varies through extension.", "Costs include extra classes and indirection.", "The creator class contains the logic that uses the product but delegates the `new` to a factory method its subclasses override.", "It is the pattern behind most framework hook points: the framework calls, your subclass decides what gets created."], [
   ("Document framework", "`Application.createDocument()` is abstract; `DrawingApplication` returns a `DrawingDocument` and `TextApplication` returns a `TextDocument`. `Application.openDocument()` works unchanged for both."),
   ("Everyday form", "`DialogFactory.createButton()` returns a `WindowsButton` or an `HtmlButton` depending on the concrete dialog subclass, while the dialog's render-and-click logic is written once."),
  ]),
  ("Abstract Factory", "Create families of related products without exposing concrete classes.", ["It enforces compatibility within a product family.", "Adding a new family is easy; adding a new product kind changes every factory.", "Clients depend on abstract product and factory interfaces.", "It is often implemented as a single object whose creation methods are each a Factory Method.", "Use it when a system must be configured with one of several families and you must prevent mixing members of different families."], [
   ("UI toolkit", "`MacFactory` produces `MacButton`, `MacCheckbox`, and `MacScrollbar`; `WindowsFactory` produces the Windows trio. Client code holds a `WidgetFactory` and can never accidentally place a Mac button in a Windows dialog."),
   ("The rigidity cost", "Adding a new product type — say `Slider` — means editing the abstract factory interface and every one of its implementations; adding a new platform means adding one class."),
  ]),
  ("Builder", "Construct a complex object step by step while separating construction from representation.", ["Useful for optional parameters, validation, and multiple representations.", "A director can encode reusable construction sequences.", "Builder avoids telescoping constructors but adds ceremony.", "The same construction process can produce different representations because the director drives the steps and the concrete builder decides what each step produces.", "Validation belongs in `build()`, which is the one point where the object is known to be complete."], [
   ("Fluent builder", "`new Pizza.Builder().size(30).crust(THIN).topping(\"cheese\").topping(\"olives\").build()` replaces a constructor with nine nullable parameters, and `build()` rejects a pizza with no size."),
   ("Director with two builders", "One `HouseDirector.buildMinimal()` sequence drives either a `HouseBuilder` producing a real house object or a `HouseBlueprintBuilder` producing a printable plan — same steps, different representations."),
  ]),
  ("Prototype", "Create new objects by copying a configured prototype.", ["Useful when construction is expensive or runtime types vary.", "Deep versus shallow copying must be deliberate.", "Identity, shared references, and mutable state are common hazards.", "The prototype instance carries its configuration with it, so cloning avoids re-running expensive setup or re-reading configuration.", "A prototype registry lets clients ask for a copy by key without knowing any concrete class."], [
   ("Shallow vs deep", "Cloning an `Order` shallowly copies the reference to its `List<OrderLine>`, so editing the copy's lines silently edits the original's. A deep clone copies the list and each line."),
   ("Registry", "A diagram editor keeps prototype shapes — a styled rectangle, a labelled node — and the toolbar clones the selected prototype on each drop, preserving colors, fonts, and default sizes."),
  ]),
  ("Singleton", "Ensure one accessible instance, but recognize global-state and testability costs.", ["Concurrency, lifecycle, serialization, and class loaders complicate uniqueness.", "Dependency injection often provides controlled single-instance lifetime more cleanly.", "Use only when singularity is a real invariant.", "A naive lazy `getInstance()` is not thread-safe; double-checked locking, an eager static field, or an enum are the usual fixes.", "Singletons hide dependencies — a class that calls `Config.getInstance()` has a dependency its constructor never declares."], [
   ("Broken lazy init", "Two threads both see `instance == null` and both run the constructor, producing two connection pools. `private static final Pool INSTANCE = new Pool();` or an enum makes the JVM guarantee uniqueness."),
   ("Testability cost", "Tests that share a singleton cache pass alone and fail when run together, because state leaks between them. Injecting one instance through the container keeps single-instance lifetime without the global."),
  ]),
  ("Pattern Selection", "Choose by variation in what, how, and when objects are created.", ["Factories choose types; Builder controls assembly; Prototype copies configured state.", "Patterns can work together and should solve a demonstrated design problem.", "Prefer the simplest mechanism that preserves required flexibility.", "Abstract Factory, Builder, and Prototype are often interchangeable candidates for the same problem, and the deciding question is what varies.", "Start with a plain constructor; introduce a creational pattern when the construction decision itself starts changing."], [
   ("Choosing", "Many kinds of one product → Factory Method. Families that must stay consistent → Abstract Factory. One product with many optional parts → Builder. Expensive or run-time-configured setup → Prototype."),
   ("Patterns together", "An Abstract Factory is frequently implemented as a Singleton and its creation methods as Factory Methods — three creational patterns in one collaboration."),
  ])]),
 ("structural-design-patterns", "Structural Design Patterns", [
  ("Adapter", "Translate one interface into another expected by a client.", ["Object adapters use composition; class adapters use inheritance where supported.", "Adapter changes interface, not core responsibility.", "It is common at legacy and third-party boundaries.", "Adapter is applied after the fact to make unrelated code work together; Bridge is designed in up front.", "A two-way adapter implements both interfaces so either side can use the object."], [
   ("Third-party adapter", "The app expects `PaymentGateway.charge(Money)`. The vendor SDK offers `StripeClient.createCharge(long amountInCents, String currency)`. A `StripeAdapter` implements the interface and translates the call."),
   ("Legacy boundary", "A new reporting module expects JSON; the 20-year-old mainframe returns fixed-width records. The adapter parses columns into objects, and neither side is modified."),
  ]),
  ("Bridge", "Separate an abstraction from its implementation so both can vary independently.", ["Bridge prevents multiplying subclasses across two variation dimensions.", "The abstraction delegates implementation-specific work.", "Identify the two axes of change before applying it.", "Without Bridge, m abstractions × n implementations produce m×n classes; with it, m+n.", "Refined abstractions extend the abstraction side without touching any implementation."], [
   ("Class explosion avoided", "Shapes {Circle, Square, Triangle} × renderers {SVG, Canvas, PDF} would need nine classes. With a `Shape` abstraction holding a `Renderer`, it is six — and a fourth renderer adds one class, not three."),
   ("Real-world Bridge", "JDBC: your code writes to the `Connection`/`Statement` abstraction while Oracle, MySQL, and PostgreSQL drivers supply the implementation side."),
  ]),
  ("Composite", "Represent part–whole hierarchies so clients treat leaves and composites uniformly.", ["Recursive operations make tree processing simple.", "A transparent interface is easy to use but may expose meaningless operations on leaves.", "Ownership, cycles, and traversal policy need care.", "In the transparent variant, child-management methods live on the component; in the safe variant they live only on the composite, trading uniformity for type safety.", "The pattern's power is that client code contains no conditional distinguishing a leaf from a branch."], [
   ("File system", "`getSize()` on a file returns its bytes; on a folder it sums its children recursively. A backup tool calls `getSize()` on the root and never checks which kind it holds."),
   ("Safe vs transparent", "Calling `add(child)` on a `File` in the transparent variant must throw at run time; the safe variant simply does not offer `add` on leaves, at the cost of client type checks."),
  ]),
  ("Decorator", "Attach responsibilities dynamically by wrapping an object with the same interface.", ["Decorators compose features without subclass explosion.", "Order can affect behavior.", "Many small wrappers may complicate identity and debugging.", "The decorator holds a reference to the wrapped component and forwards calls, adding behavior before, after, or instead of forwarding.", "Because the wrapper shares the component's interface, clients cannot tell a decorated object from a plain one."], [
   ("Java I/O", "`new BufferedReader(new InputStreamReader(new FileInputStream(f)))` — buffering and character decoding added by wrapping, not by subclassing a `BufferedDecodingFileReader`."),
   ("Order matters", "Compress-then-encrypt produces a small ciphertext; encrypt-then-compress produces near-random bytes that barely compress. Same two decorators, very different results."),
  ]),
  ("Facade", "Provide a simpler entry point to a complex subsystem.", ["Facade reduces client coupling but does not forbid advanced subsystem access.", "It can coordinate workflows and shield clients from change.", "Avoid turning it into an all-knowing god object.", "Facade simplifies an existing interface without adding functionality, which is what separates it from Adapter and Mediator.", "It is often the natural entry point of a layer, giving the layer above one thing to depend on."], [
   ("Booking facade", "`TripFacade.bookTrip(request)` internally calls the flight, hotel, car, payment, and email subsystems in order and rolls back on failure. The web controller calls one method."),
   ("Escape hatch", "A power user of the video library still calls the codec API directly for frame-level control; the facade covers the common 90% without locking the other 10% out."),
  ]),
  ("Proxy", "Control access to another object through the same interface.", ["Remote, virtual, protection, and caching proxies serve different purposes.", "Proxy preserves interface while adding access behavior.", "Latency and failure semantics must not be hidden misleadingly.", "Proxy and Decorator share a structure; the difference is intent — Proxy controls access, Decorator adds responsibilities.", "A smart-reference proxy can add reference counting, lazy loading, or locking around the real subject."], [
   ("Virtual proxy", "A document holds `ImageProxy` objects that render a placeholder and only load the 8 MP image from disk when it scrolls into view — the document opens instantly."),
   ("Protection proxy", "`AdminServiceProxy` checks the caller's role before forwarding to the real service, so authorization lives in one wrapper instead of at the top of every method."),
  ])]),
 ("architecture-evaluation", "Architecture Evaluation", [
  ("Evaluation Purpose", "Assess whether architectural decisions satisfy business goals and quality requirements before failures become expensive.", ["Evaluation exposes risks, sensitivity points, trade-off points, and missing information.", "Evaluate early and repeat when drivers or architecture change.", "The goal is informed decisions, not a pass/fail beauty contest.", "The cheapest possible fix for an architectural mistake is the one made while the architecture is still a document.", "A side benefit is forced clarity: teams often discover their documented architecture and their real intent differ during the first evaluation session."], [
   ("Early beats late", "A two-day review finds that the reporting service and the transaction service share one database — a design change at that point. Found after launch, it is a migration, a data backfill, and a maintenance window."),
   ("Stakeholder alignment", "During evaluation the operations lead learns for the first time that the design assumes a nightly two-hour batch window that the business promised customers would not exist."),
  ]),
  ("Evaluation Methods", "ATAM, SAAM, and ARID evaluate architecture from complementary perspectives.", ["SAAM emphasizes scenario-based modifiability analysis.", "ARID is an active review of an intermediate design.", "Method choice depends on maturity, questions, participants, and available evidence.", "SAAM came first and focuses on modifiability and functionality; ATAM generalized it to all quality attributes and their interactions.", "ARID combines ATAM's scenario technique with active design reviews to evaluate a partial design before it is finished."], [
   ("Picking a method", "A finished architecture with competing performance and security goals → ATAM. A question purely about how costly three planned changes will be → SAAM. A half-designed shared component that other teams must use → ARID."),
   ("ARID session", "The designer presents a draft caching component, then the reviewers who will have to use it must write pseudocode against its interface — usability gaps surface immediately."),
  ]),
  ("ATAM", "The Architecture Tradeoff Analysis Method evaluates quality trade-offs through structured stakeholder scenarios.", ["Its nine steps cover presenting the method, business drivers, and architecture; identifying approaches; building a utility tree; analyzing approaches; brainstorming and prioritizing scenarios; reanalyzing; and presenting results.", "ATAM uses evaluation-team roles plus decision makers and stakeholders across preparation, evaluation, and follow-up phases.", "Sensitivity points affect one quality; trade-off points affect multiple qualities.", "A lightweight ATAM retains scenario-and-tradeoff reasoning with less ceremony.", "Phase 1 works with the core team, phase 2 widens to the broader stakeholder group, and phase 3 delivers the report and follow-up.", "Outputs include the utility tree, approaches, scenarios, risks, non-risks, sensitivity points, and trade-off points."], [
   ("Sensitivity point", "The number of web-server replicas is a sensitivity point for availability: change it from two to one and availability drops sharply while nothing else moves."),
   ("Trade-off point", "The encryption level on the message bus is a trade-off point: raising it improves confidentiality and worsens latency, so it sits at the intersection of two drivers and needs an explicit decision."),
   ("Risk vs non-risk", "Risk: \"the failover procedure has never been tested under load\". Non-risk: \"the read replica handles reporting, which is acceptable because reports tolerate 5 s staleness\" — both are recorded outputs."),
  ]),
  ("Scenarios & Utility Tree", "Prioritize concrete quality scenarios by business importance and architectural difficulty.", ["Scenarios use stimulus, environment, artifact, response, and measure.", "High-priority scenarios drive deeper analysis.", "A utility tree organizes quality goals and exposes stakeholder priorities.", "The tree runs Utility → quality attribute → refinement → concrete scenario, with each leaf given an (importance, difficulty) rating such as (H,H).", "(H,H) leaves are analyzed first because they carry the most business value and the most architectural uncertainty."], [
   ("Utility tree branch", "Utility → Performance → Transaction response time → \"500 users submit grades at semester end; all confirmations under 3 s\" rated (H, M)."),
   ("Prioritization in the room", "Twelve scenarios are brainstormed, stakeholders vote with a fixed number of votes each, and only the top four (H,H) scenarios get detailed analysis in the time available."),
  ]),
  ("Tactics & Reasoning", "Explain how structures and tactics produce the required response measures.", ["Trace each scenario through runtime and development structures.", "Prototype or measure where reasoning alone is weak.", "Assumptions and evidence strength should be visible.", "Each analyzed approach is recorded with the architectural decisions it embodies and the questions the evaluators asked about it.", "\"We believe it will be fast enough\" is an assumption; a load-test result is evidence, and the report should not blur the two."], [
   ("Walking a scenario", "The failover scenario is traced: heartbeat detects in 5 s, the load balancer drains in 3 s, the standby promotes in 10 s, clients retry with backoff — 18 s total against a 30 s requirement, with the promotion step untested."),
   ("Evidence gap", "The team claims the cache gives 90% hit rate. No measurement exists, so the evaluation records it as an assumption and recommends a one-week production measurement."),
  ]),
  ("Review Outcomes", "Capture risks, themes, decisions, open questions, and recommended experiments.", ["A risk theme groups related architectural weaknesses.", "Evaluation findings need owners and follow-up actions.", "Re-evaluation checks whether mitigation changed the risk profile.", "Risk themes are mapped back to the business drivers they endanger, which is what makes the findings actionable for management.", "Non-risks are worth recording too: they document decisions that were checked and found sound."], [
   ("Risk theme", "Four separate risks — no failover test, no runbook, single on-call engineer, no alerting on the queue — group into the theme \"operational readiness is unaddressed\", which threatens the availability driver."),
   ("Follow-up", "Each finding leaves the review with an owner and a date: \"run a failover drill in staging — Ops lead — before 15 October\", and the next review checks it."),
  ])]),
 ("architecture-documentation", "Architecture Documentation", [
  ("Documentation Principles", "Write for stakeholders, organize around views, avoid unnecessary repetition, and keep information current.", ["Document what readers need to reason, build, operate, and change the system.", "State conventions and provide a roadmap.", "Use a single source of truth for repeated facts where possible.", "Write from the reader's point of view, avoid unnecessary repetition, avoid ambiguity, and record rationale — documentation nobody can act on is not documentation.", "Review documentation for fitness with its intended readers before declaring it done."], [
   ("Reader-driven", "New developers need the module view and the build instructions; the operations team needs deployment, monitoring, and failure modes. Shipping one 90-page document to both serves neither."),
   ("Avoiding repetition", "The retry policy is specified once in a cross-cutting concepts section and referenced from each view, so a change to it cannot leave three views disagreeing."),
  ]),
  ("View Documentation", "Each view includes a primary presentation, element catalog, context, variability, and rationale.", ["The primary presentation is usually a diagram plus key annotations.", "The element catalog defines responsibilities, interfaces, and relationships.", "Context shows the view boundary and external dependencies.", "Variability guides record where the architecture allows options — configurable, build-time, or run-time choices — and their permitted values.", "Rationale explains why this view looks the way it does and which alternatives were rejected."], [
   ("Element catalog entry", "`NotificationService` — responsibility: deliver user-facing messages; provides `send(Notification)`; requires `TemplateStore` and an SMTP relay; may not be called synchronously from the checkout path."),
   ("Variability guide", "The identity provider is a build-time choice among {internal LDAP, Azure AD, Okta}; the session timeout is a run-time setting between 5 and 60 minutes."),
  ]),
  ("Documentation Approaches", "Established view approaches include 4+1, Siemens Four-Views, Herzum and Sims, Software Cost Reduction, RUP, and SEI guidance.", ["Choose views from stakeholder concerns rather than documenting every possible model.", "Each selected approach organizes complementary evidence about one architecture.", "Consistency and mappings across views prevent contradictory documentation.", "Siemens Four-Views separates conceptual, module, execution, and code architecture views.", "The C4 model is a widely used modern variant that nests context, container, component, and code levels."], [
   ("Choosing an approach", "A team already using RUP and UML adopts 4+1 with little friction; a microservices team communicating with mixed audiences often finds C4's context-and-container levels a faster fit."),
   ("Mapping between views", "A table stating that the `billing` module (module view) is deployed as the `billing-api` container on two nodes (deployment view) is what keeps the two from drifting apart."),
  ]),
  ("Beyond Views", "Record cross-cutting concepts, decisions, constraints, mappings, and glossary terms.", ["A complete package can include a documentation roadmap, view documents, system overview, rationale, directory, glossary, and acronym list.", "Interfaces, data, security, error handling, deployment, and build concerns often cross views.", "ADRs preserve decision context and consequences.", "The documentation roadmap tells a reader which part to read for which question — it is the entry point that makes a large package usable.", "A glossary prevents the same word meaning three things to three teams."], [
   ("Cross-cutting concept", "\"All service-to-service errors return RFC 7807 problem details, and all retries use exponential backoff with jitter\" — one rule that belongs to no single view but constrains all of them."),
   ("Glossary need", "In one university system \"student\" meant an applicant to admissions, an enrolled learner to registration, and a debtor to finance. The glossary entry ended a month of circular meetings."),
  ]),
  ("Diagram Quality", "Diagrams need a key, defined notation, readable scope, and meaningful relationships.", ["Boxes and lines are ambiguous without semantics.", "Show only information relevant to the view and audience.", "Automated diagrams help freshness but still require curation.", "Every diagram needs a key defining what each box shape, line style, and color means, even when the notation feels obvious to its author.", "One diagram should answer one question; a diagram that answers five answers none of them well."], [
   ("Ambiguous arrow", "An arrow from A to B may mean \"A calls B\", \"data flows from A to B\", \"A depends on B\", or \"A sends B a message\". Without a key, four readers form four architectures."),
   ("Scoped diagram", "Instead of one diagram with 60 services, the team ships a context diagram with 6 boxes and six focused container diagrams — each readable on one screen."),
  ]),
  ("Living Documentation", "Integrate documentation updates with development and architecture governance.", ["Version documentation with code where appropriate.", "Review for drift and link decisions to implementation evidence.", "Useful documentation is concise enough to maintain and detailed enough to act on.", "Documentation that is not part of the definition of done goes stale within a release or two.", "Generated artifacts — API references, dependency graphs, deployment topologies — stay fresh for free and should carry the facts that change most often."], [
   ("Docs as code", "Markdown architecture docs and PlantUML sources live in the repository, are reviewed in the same pull request as the change, and are published by CI — so an undocumented structural change fails review."),
   ("Generated vs curated", "The service dependency graph is generated nightly from real traffic; the rationale for why payments must not call reporting is written by hand, because no tool can infer intent."),
  ])]),
]

def main():
    core.BASE = BASE
    core.MAPS = BASE / "extra-resources/mindmaps"
    core.EXAMS = BASE / "exams"
    core.CHAPTERS = CHAPTERS
    core.main()
    summary_dir = BASE / "extra-resources/summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    summary_template = (ROOT / "docs/academics/software-engineering/se401/extra-resources/summary/index.html").read_text()
    summary_page = summary_template.replace("SE401", "SE322").replace("se401", "se322")
    summary_page = re.sub(
        r'<iframe\s+src="[^"]*summary\.pdf"[^>]*></iframe>',
        '<iframe class="embed-frame" src="../summary.pdf" title="SE322 Course Summary PDF"></iframe>',
        summary_page,
        count=1,
    )
    summary_page = re.sub(
        r'(<a class="btn btn-primary" href=")[^"]*summary\.pdf("[^>]*>)',
        r'\1../summary.pdf\2',
        summary_page,
        count=1,
    )
    summary_page = core.sitegen.replace_academic_sidebar(summary_page, "SE322", "Study Material", "Summary")
    summary_page = summary_page.replace(
        "/academics/software-engineering/se322/extra-resources/01-summary/",
        "/academics/software-engineering/se322/extra-resources/summary/",
    )
    summary_dir.joinpath("index.html").write_text(re.sub(r'[ \t]+\n', '\n', summary_page))
    targets = [BASE / "extra-resources/index.html", BASE / "extra-resources/summary/index.html", BASE / "exams/index.html"]
    targets += list((BASE / "extra-resources/mindmaps").rglob("*.html"))
    targets += list((BASE / "exams").glob("*/*.html"))
    for path in targets:
        text = path.read_text().replace("SE401", "SE322").replace("se401", "se322")
        text = re.sub(r'/Academics/courses/se322/', '/academics/software-engineering/se322/', text)
        text = re.sub(r'<li class="tree-item"><a class="tree-file" href="/academics/software-engineering/se322/">SE322</a></li>', '', text, count=1)
        text = re.sub(r'(<div class="dir-title">Chapter \d+: [^<]*?) Mindmap</div>', r'\1</div>', text)
        text = re.sub(r'(>Chapter \d+: [^<]*?) Mindmap</a>', r'\1</a>', text)
        path.write_text(re.sub(r'[ \t]+\n', '\n', text))
    extra = BASE / "extra-resources/index.html"
    text = extra.read_text()
    icon = '<svg class="dir-folder-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="square" aria-hidden="true"><path d="M3 7a1 1 0 0 1 1-1h5l2 2h9a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7z"/></svg>'
    rows = f'''<div class="directory-container"><div class="dir-header"><span>SEQ</span><span>DESCRIPTOR</span><span>SYS_STATE</span><span></span></div><a class="dir-row" href="/academics/software-engineering/se322/extra-resources/mindmaps/"><div class="dir-num">1</div><div class="dir-title"><span class="dir-title-text">Mindmaps</span>{icon}</div><div class="dir-status"><span class="status-tag available">AVAILABLE</span></div><div class="dir-arrow">-&gt;</div></a><a class="dir-row" href="/academics/software-engineering/se322/extra-resources/summary/"><div class="dir-num">2</div><div class="dir-title"><span class="dir-title-text">Course Summary</span></div><div class="dir-status"><span class="status-tag available">AVAILABLE</span></div><div class="dir-arrow">-&gt;</div></a></div>'''
    text = re.sub(r'<div class="coming-soon-container".*?</div>\s*</div>', rows, text, count=1, flags=re.S)
    if '.dir-folder-icon {' not in text:
        text = text.replace('</style>', '.dir-title:has(.dir-folder-icon){display:flex;align-items:center;gap:10px}.dir-folder-icon{width:20px;height:20px;flex:0 0 auto;color:var(--text-tertiary);transition:.2s}.dir-row:hover .dir-folder-icon{color:var(--brand-purple);transform:translateY(-1px)}</style>', 1)
    extra.write_text(re.sub(r'[ \t]+\n', '\n', text))
    print(f"Built {len(CHAPTERS)} SE322 mindmaps and exams")
    from fix_mindmap_sidebar_state import apply_course
    # Sidebar and hub rows name the chapter itself; the surrounding section is
    # already called MINDMAPS, so repeating "Mindmap" on every row is noise.
    chapter_labels = {f"{i:02d}-{slug}": f"Chapter {i}: {title}" for i, (slug, title, _b) in enumerate(CHAPTERS, 1)}
    apply_course("se322", BASE, chapter_labels)
    from fix_academic_sidebar_links import fix_page
    for page in [core.MAPS / "index.html", core.EXAMS / "index.html", summary_dir / "index.html", *core.MAPS.glob("*/index.html"), *core.EXAMS.glob("*/index.html")]:
        fix_page(page)

if __name__ == "__main__": main()
