#!/usr/bin/env python3
"""Build SE322 Ethics-style mindmaps and comprehensive chapter exams."""
from pathlib import Path
import re
import build_se401_study_tools as core

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "docs/academics/software-engineering/se322"

CHAPTERS = [
 ("introduction-to-software-design-and-architecture", "Introduction to Software Design and Architecture", [
  ("Software Engineering Foundations", "IEEE defines software engineering as a systematic, disciplined, and quantifiable approach to software development, operation, and maintenance.", ["The SDLC connects requirements, design, implementation, testing, deployment, and maintenance.", "Engineering problem solving identifies the initial state, goal state, constraints, candidate solutions, evaluation, and implementation.", "Design is studied because defects and costly decisions are easier to address before construction."]),
  ("Design vs Architecture", "Architecture captures system-wide structures and high-impact decisions; detailed design refines components and collaborations.", ["Architecture addresses elements, externally visible properties, and relationships.", "Detailed design turns architectural responsibilities into classes, interfaces, algorithms, and data structures.", "Both manage complexity through abstraction, decomposition, and separation of concerns."]),
  ("Stakeholders & Concerns", "Architectural decisions serve multiple stakeholders whose concerns can conflict.", ["Users emphasize usability and reliability; developers emphasize modifiability; operators emphasize deployability and observability.", "A viewpoint frames particular concerns; a view is the resulting representation.", "Trade-offs must be explicit and justified."]),
  ("Architectural Drivers", "Business goals, functional requirements, quality attributes, and constraints shape the architecture.", ["Drivers are the small set of requirements with major architectural influence.", "Constraints restrict choice, such as mandated technology, regulation, budget, or legacy integration.", "Architecturally significant requirements should be measurable and prioritized."]),
  ("Design Process", "Move iteratively from requirements and context to structures, responsibilities, interfaces, and evaluation.", ["Decompose around responsibilities and change boundaries.", "Record decisions, rationale, assumptions, and rejected alternatives.", "Validate early with scenarios, prototypes, reviews, and risk analysis."]),
  ("Good Design", "Good design balances correctness, simplicity, cohesion, low coupling, information hiding, and evolvability.", ["There is rarely one universally best architecture.", "Premature detail and accidental complexity make change harder.", "Design quality is demonstrated against stakeholder scenarios, not aesthetic preference alone."]),
  ("Design Challenges", "Architects must manage volatile requirements, inconsistent processes, rapidly changing technology, design influences, and professional obligations.", ["AI and machine-learning technologies add fast-moving constraints and uncertainty.", "Quality goals frequently conflict and require explicit trade-offs.", "Ethical and professional practices remain design constraints, not optional extras."])]),
 ("software-architecture", "Software Architecture", [
  ("Structures", "An architecture comprises multiple complementary structures rather than one diagram.", ["Module structures show implementation units and dependencies.", "Component-and-connector structures show runtime elements and interactions.", "Allocation structures map software to hardware, teams, files, or deployment environments."]),
  ("Views & Viewpoints", "Views communicate architecture for defined stakeholder concerns.", ["A viewpoint defines conventions, stakeholders, concerns, and modeling rules.", "Logical, process, development, physical, and scenario views answer different questions.", "Consistency across views matters because they describe one system."]),
  ("Requirements Engineering", "Elicitation, analysis, specification, validation, and management provide the architectural test basis.", ["Elicitation uses interviews, facilitated meetings, observation, and scenarios.", "Analysis includes classification, prioritization, negotiation, and conceptual modeling.", "Requirements may be imposed or derived and product- or process-oriented.", "Good requirements are specific, consistent, correct, attainable, complete, and verifiable.", "Quality attribute scenarios make nonfunctional requirements testable.", "Traceability connects drivers to decisions and verification evidence."]),
  ("Kruchten 4+1 Views", "The 4+1 model combines logical, process, development, physical, and scenario views.", ["Logical views commonly use class, collaboration, and sequence diagrams.", "Process views use activity models; development views use component or package diagrams.", "Physical views use deployment diagrams, while scenarios connect the other four with use cases or textual flows."]),
  ("Architectural Decisions", "Important decisions constrain structures and future options and therefore require rationale.", ["Document context, decision, alternatives, consequences, and status in an ADR.", "Irreversible or expensive decisions deserve early evidence.", "Technical debt is a deliberate or accidental future obligation."]),
  ("Interfaces & Contracts", "Interfaces define provided and required services plus behavioral assumptions.", ["Contracts cover syntax, semantics, protocols, errors, timing, and versioning.", "Stable interfaces reduce coupling but cannot hide every quality concern.", "Integration failures often arise from mismatched assumptions rather than syntax alone."]),
  ("Architecture Lifecycle", "Architecture evolves through analysis, synthesis, documentation, implementation, evaluation, and governance.", ["Architecture is not a one-time phase artifact.", "Conformance checks detect drift between intended and implemented structures.", "Governance should enable consistent decisions without unnecessary bureaucracy."])]),
 ("quality-attributes", "Quality Attributes", [
 ("Quality Scenarios", "Specify source, stimulus, environment, artifact, response, and response measure.", ["A measurable response turns a vague quality wish into an analyzable requirement.", "General scenarios are reusable; concrete scenarios are system-specific.", "Quality attributes interact and often conflict."]),
  ("Design Decisions", "Quality is shaped by seven recurring architectural decisions: responsibilities, coordination, data, resources, element mapping, binding time, and technology.", ["Allocation of responsibilities determines where behavior and knowledge live.", "Coordination and resource-management choices shape runtime qualities.", "Binding-time and technology choices trade flexibility against complexity and cost."]),
  ("Performance", "Performance concerns latency, throughput, capacity, deadlines, and resource use.", ["Demand can be controlled through sampling, admission, or prioritization.", "Resources can be increased, scheduled, replicated, or made more efficient.", "Measure percentile latency and behavior under representative load."]),
  ("Availability", "Availability is readiness for correct service despite faults.", ["Detect faults with ping/echo, heartbeat, exceptions, or voting.", "Recovery preparation includes active or passive redundancy and spares.", "Reintroduction tactics include shadow state, resynchronization, and rollback.", "Prevention includes removal from service, transactions, and process monitoring.", "MTBF and MTTR influence achieved availability."]),
  ("Security", "Security protects confidentiality, integrity, availability, authenticity, accountability, and non-repudiation.", ["Authenticate subjects, authorize actions, limit exposure, encrypt data, and audit activity.", "Defense in depth avoids a single control becoming a single point of failure.", "Threat modeling links assets, threats, vulnerabilities, and mitigations."]),
  ("Modifiability & Testability", "Design to localize change and make behavior controllable and observable.", ["High cohesion, low coupling, abstraction, and indirection contain ripple effects.", "Dependency injection and stable interfaces improve substitution and testing.", "Testability requires controllability, observability, isolation, and repeatability."]),
  ("Usability & Interoperability", "Usability supports effective user action; interoperability supports meaningful exchange across systems.", ["Separate UI from domain logic and support cancel, undo, feedback, and error recovery.", "Interoperability requires shared syntax, semantics, protocols, and identity assumptions.", "Standards help but do not guarantee compatible meaning."])]),
 ("architecture-patterns", "Architecture Patterns", [
  ("Pattern Foundations", "Architectural styles name families of organization; patterns capture reusable solutions in context, influenced by Christopher Alexander and adopted by software engineering in the 1990s.", ["Data-centered styles include repository and blackboard.", "Data-flow styles include pipes and filters; distributed styles include client-server and broker.", "Interactive styles include MVC, while hierarchical styles include layered architecture."]),
  ("Layered", "Organize responsibilities into abstraction layers with controlled dependencies.", ["Benefits include portability, replaceability, and separation of concerns.", "Costs include latency, duplicated transformations, and layer bypass pressure.", "Closed layers restrict calls to adjacent layers; open layers permit skipping."]),
  ("Model–View–Controller", "Separate domain state, presentation, and input coordination.", ["The controller interprets input and updates the model; the model notifies observing views of change.", "Multiple views can share one model.", "Poor responsibility allocation can create fat controllers or anemic models.", "MVC improves UI change isolation but adds interaction complexity."]),
  ("Pipes and Filters", "Independent filters transform streams connected by pipes.", ["Filters can be reused, reordered, and executed concurrently.", "Shared state and interactive workflows fit poorly.", "Define data formats, error propagation, backpressure, and termination."]),
  ("Client–Server & Broker", "Clients request services; servers provide them; brokers mediate location and communication.", ["Broker improves distribution transparency and loose coupling.", "Networks introduce partial failure, latency, retries, and versioning.", "Avoid assuming remote calls behave like local calls."]),
  ("Repository & Blackboard", "Components coordinate through shared data; blackboard systems iteratively contribute partial solutions.", ["A blackboard architecture separates shared blackboard data, specialist knowledge-source agents, and a controller.", "Agents inspect and contribute partial solutions while the controller selects what acts next.", "Repository centralizes data consistency but can become a bottleneck and coupling point.", "Blackboard suits problems with no deterministic solution sequence."]),
  ("Event-Driven", "Producers publish events and consumers react asynchronously.", ["It improves decoupling and scalability but complicates ordering and debugging.", "Design for idempotency, duplicate delivery, eventual consistency, and failure handling.", "Events should represent meaningful facts with stable schemas."])]),
 ("principles-of-detailed-design", "Principles of Detailed Design", [
  ("Detailed-Design Workflow", "Detailed design sits between architecture and construction and refines components into implementable structures and behavior.", ["Tasks include understanding architecture and requirements, internal and external interface design, GUI design, component structure and behavior, data and database design, evaluation, documentation, and implementation management.", "Documentation includes interface control documents, data dictionaries, and version-controlled design records.", "Reverse engineering recovers design knowledge from an existing implementation."]),
  ("Object-Oriented Modeling", "Classes, interfaces, inheritance, polymorphism, generalization, and realization express detailed object-oriented structure and behavior.", ["Abstract classes or methods defer some implementation; concrete classes can be instantiated.", "Generalization models an is-a relationship; realization connects a classifier to an implemented interface.", "Internal behavior models should preserve requirements while allocating responsibilities clearly."]),
  ("Abstraction & Encapsulation", "Expose essential behavior while hiding volatile representation and implementation choices.", ["Program to contracts, not concrete details.", "Information hiding localizes likely change.", "Encapsulation includes behavioral invariants, not only private fields."]),
  ("Cohesion & Coupling", "Place closely related responsibilities together and minimize unnecessary dependencies.", ["Functional cohesion is stronger than coincidental grouping.", "Content and common coupling are especially harmful.", "Interfaces, events, and dependency inversion can reduce coupling when used deliberately."]),
  ("SRP & OCP", "A module should have one reason to change and be open to extension without repeated modification.", ["SRP is about alignment with an actor or change source, not doing only one tiny task.", "OCP often uses polymorphism, composition, configuration, or plugins.", "Do not introduce extension mechanisms without a credible variation point."]),
  ("LSP & ISP", "Subtypes must preserve client expectations; interfaces should be focused around client needs.", ["LSP forbids stronger preconditions and weaker postconditions.", "Behavioral incompatibility cannot be repaired by matching method signatures.", "ISP prevents clients depending on operations they do not use."]),
  ("Dependency Inversion", "High-level policy and low-level detail should depend on abstractions.", ["Dependency injection supplies collaborators from outside.", "DIP reverses source-code dependency; it does not mean every class needs an interface.", "Stable abstractions protect policy from volatile infrastructure."]),
  ("Composition & Refactoring", "Prefer assembling focused objects and continuously improve structure without changing behavior.", ["Composition is often more flexible than inheritance.", "Code smells indicate design pressure, not automatic rewrite commands.", "Automated tests make safe incremental refactoring possible."])]),
 ("creational-design-patterns", "Creational Design Patterns", [
  ("Pattern Classification", "Design patterns are classified by purpose and by class-level or object-level scope and should be documented with intent, applicability, structure, participants, consequences, and examples.", ["Creational patterns separate clients from concrete construction decisions.", "Class patterns rely mainly on inheritance; object patterns rely mainly on composition.", "The five covered creational patterns are Abstract Factory, Factory Method, Builder, Prototype, and Singleton."]),
  ("Factory Method", "Define a creation operation while allowing subclasses or collaborators to choose the concrete product.", ["It removes direct construction from client policy.", "Use when product type varies through extension.", "Costs include extra classes and indirection."]),
  ("Abstract Factory", "Create families of related products without exposing concrete classes.", ["It enforces compatibility within a product family.", "Adding a new family is easy; adding a new product kind changes every factory.", "Clients depend on abstract product and factory interfaces."]),
  ("Builder", "Construct a complex object step by step while separating construction from representation.", ["Useful for optional parameters, validation, and multiple representations.", "A director can encode reusable construction sequences.", "Builder avoids telescoping constructors but adds ceremony."]),
  ("Prototype", "Create new objects by copying a configured prototype.", ["Useful when construction is expensive or runtime types vary.", "Deep versus shallow copying must be deliberate.", "Identity, shared references, and mutable state are common hazards."]),
  ("Singleton", "Ensure one accessible instance, but recognize global-state and testability costs.", ["Concurrency, lifecycle, serialization, and class loaders complicate uniqueness.", "Dependency injection often provides controlled single-instance lifetime more cleanly.", "Use only when singularity is a real invariant."]),
  ("Pattern Selection", "Choose by variation in what, how, and when objects are created.", ["Factories choose types; Builder controls assembly; Prototype copies configured state.", "Patterns can work together and should solve a demonstrated design problem.", "Prefer the simplest mechanism that preserves required flexibility."])]),
 ("structural-design-patterns", "Structural Design Patterns", [
  ("Adapter", "Translate one interface into another expected by a client.", ["Object adapters use composition; class adapters use inheritance where supported.", "Adapter changes interface, not core responsibility.", "It is common at legacy and third-party boundaries."]),
  ("Bridge", "Separate an abstraction from its implementation so both can vary independently.", ["Bridge prevents multiplying subclasses across two variation dimensions.", "The abstraction delegates implementation-specific work.", "Identify the two axes of change before applying it."]),
  ("Composite", "Represent part–whole hierarchies so clients treat leaves and composites uniformly.", ["Recursive operations make tree processing simple.", "A transparent interface is easy to use but may expose meaningless operations on leaves.", "Ownership, cycles, and traversal policy need care."]),
  ("Decorator", "Attach responsibilities dynamically by wrapping an object with the same interface.", ["Decorators compose features without subclass explosion.", "Order can affect behavior.", "Many small wrappers may complicate identity and debugging."]),
  ("Facade", "Provide a simpler entry point to a complex subsystem.", ["Facade reduces client coupling but does not forbid advanced subsystem access.", "It can coordinate workflows and shield clients from change.", "Avoid turning it into an all-knowing god object."]),
  ("Proxy", "Control access to another object through the same interface.", ["Remote, virtual, protection, and caching proxies serve different purposes.", "Proxy preserves interface while adding access behavior.", "Latency and failure semantics must not be hidden misleadingly."])]),
 ("architecture-evaluation", "Architecture Evaluation", [
  ("Evaluation Purpose", "Assess whether architectural decisions satisfy business goals and quality requirements before failures become expensive.", ["Evaluation exposes risks, sensitivity points, trade-off points, and missing information.", "Evaluate early and repeat when drivers or architecture change.", "The goal is informed decisions, not a pass/fail beauty contest."]),
  ("Evaluation Methods", "ATAM, SAAM, and ARID evaluate architecture from complementary perspectives.", ["SAAM emphasizes scenario-based modifiability analysis.", "ARID is an active review of an intermediate design.", "Method choice depends on maturity, questions, participants, and available evidence."]),
  ("ATAM", "The Architecture Tradeoff Analysis Method evaluates quality trade-offs through structured stakeholder scenarios.", ["Its nine steps cover presenting the method, business drivers, and architecture; identifying approaches; building a utility tree; analyzing approaches; brainstorming and prioritizing scenarios; reanalyzing; and presenting results.", "ATAM uses evaluation-team roles plus decision makers and stakeholders across preparation, evaluation, and follow-up phases.", "Sensitivity points affect one quality; trade-off points affect multiple qualities.", "A lightweight ATAM retains scenario-and-tradeoff reasoning with less ceremony."]),
  ("Scenarios & Utility Tree", "Prioritize concrete quality scenarios by business importance and architectural difficulty.", ["Scenarios use stimulus, environment, artifact, response, and measure.", "High-priority scenarios drive deeper analysis.", "A utility tree organizes quality goals and exposes stakeholder priorities."]),
  ("Tactics & Reasoning", "Explain how structures and tactics produce the required response measures.", ["Trace each scenario through runtime and development structures.", "Prototype or measure where reasoning alone is weak.", "Assumptions and evidence strength should be visible."]),
  ("Review Outcomes", "Capture risks, themes, decisions, open questions, and recommended experiments.", ["A risk theme groups related architectural weaknesses.", "Evaluation findings need owners and follow-up actions.", "Re-evaluation checks whether mitigation changed the risk profile."])]),
 ("architecture-documentation", "Architecture Documentation", [
  ("Documentation Principles", "Write for stakeholders, organize around views, avoid unnecessary repetition, and keep information current.", ["Document what readers need to reason, build, operate, and change the system.", "State conventions and provide a roadmap.", "Use a single source of truth for repeated facts where possible."]),
  ("View Documentation", "Each view includes a primary presentation, element catalog, context, variability, and rationale.", ["The primary presentation is usually a diagram plus key annotations.", "The element catalog defines responsibilities, interfaces, and relationships.", "Context shows the view boundary and external dependencies."]),
  ("Documentation Approaches", "Established view approaches include 4+1, Siemens Four-Views, Herzum and Sims, Software Cost Reduction, RUP, and SEI guidance.", ["Choose views from stakeholder concerns rather than documenting every possible model.", "Each selected approach organizes complementary evidence about one architecture.", "Consistency and mappings across views prevent contradictory documentation."]),
  ("Beyond Views", "Record cross-cutting concepts, decisions, constraints, mappings, and glossary terms.", ["A complete package can include a documentation roadmap, view documents, system overview, rationale, directory, glossary, and acronym list.", "Interfaces, data, security, error handling, deployment, and build concerns often cross views.", "ADRs preserve decision context and consequences."]),
  ("Diagram Quality", "Diagrams need a key, defined notation, readable scope, and meaningful relationships.", ["Boxes and lines are ambiguous without semantics.", "Show only information relevant to the view and audience.", "Automated diagrams help freshness but still require curation."]),
  ("Living Documentation", "Integrate documentation updates with development and architecture governance.", ["Version documentation with code where appropriate.", "Review for drift and link decisions to implementation evidence.", "Useful documentation is concise enough to maintain and detailed enough to act on."])]),
]

def main():
    core.BASE = BASE
    core.MAPS = BASE / "extra-resources/mindmaps"
    core.EXAMS = BASE / "exams"
    core.CHAPTERS = CHAPTERS
    core.main()
    summary_dir = BASE / "extra-resources/summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    summary_template = (ROOT / "docs/academics/software-engineering/se401/extra-resources/summary/index.html").read_text()
    summary_page = summary_template.replace("SE401", "SE322").replace("se401", "se322")
    summary_page = re.sub(
        r'<iframe\s+src="[^"]*summary\.pdf"[^>]*></iframe>',
        '<iframe class="embed-frame" src="../summary.pdf" title="SE322 Course Summary PDF"></iframe>',
        summary_page,
        count=1,
    )
    summary_page = re.sub(
        r'(<a class="btn btn-primary" href=")[^"]*summary\.pdf("[^>]*>)',
        r'\1../summary.pdf\2',
        summary_page,
        count=1,
    )
    summary_page = core.sitegen.replace_academic_sidebar(summary_page, "SE322", "Study Material", "Summary")
    summary_page = summary_page.replace(
        "/academics/software-engineering/se322/extra-resources/01-summary/",
        "/academics/software-engineering/se322/extra-resources/summary/",
    )
    summary_dir.joinpath("index.html").write_text(re.sub(r'[ \t]+\n', '\n', summary_page))
    targets = [BASE / "extra-resources/index.html", BASE / "extra-resources/summary/index.html", BASE / "exams/index.html"]
    targets += list((BASE / "extra-resources/mindmaps").rglob("*.html"))
    targets += list((BASE / "exams").glob("*/*.html"))
    for path in targets:
        text = path.read_text().replace("SE401", "SE322").replace("se401", "se322")
        text = re.sub(r'/Academics/courses/se322/', '/academics/software-engineering/se322/', text)
        text = re.sub(r'<li class="tree-item"><a class="tree-file" href="/academics/software-engineering/se322/">SE322</a></li>', '', text, count=1)
        path.write_text(re.sub(r'[ \t]+\n', '\n', text))
    extra = BASE / "extra-resources/index.html"
    text = extra.read_text()
    icon = '<svg class="dir-folder-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="square" aria-hidden="true"><path d="M3 7a1 1 0 0 1 1-1h5l2 2h9a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7z"/></svg>'
    rows = f'''<div class="directory-container"><div class="dir-header"><span>SEQ</span><span>DESCRIPTOR</span><span>SYS_STATE</span><span></span></div><a class="dir-row" href="/academics/software-engineering/se322/extra-resources/mindmaps/"><div class="dir-num">1</div><div class="dir-title"><span class="dir-title-text">Mindmaps</span>{icon}</div><div class="dir-status"><span class="status-tag available">AVAILABLE</span></div><div class="dir-arrow">-&gt;</div></a><a class="dir-row" href="/academics/software-engineering/se322/extra-resources/summary/"><div class="dir-num">2</div><div class="dir-title"><span class="dir-title-text">Course Summary</span></div><div class="dir-status"><span class="status-tag available">AVAILABLE</span></div><div class="dir-arrow">-&gt;</div></a></div>'''
    text = re.sub(r'<div class="coming-soon-container".*?</div>\s*</div>', rows, text, count=1, flags=re.S)
    if '.dir-folder-icon {' not in text:
        text = text.replace('</style>', '.dir-title:has(.dir-folder-icon){display:flex;align-items:center;gap:10px}.dir-folder-icon{width:20px;height:20px;flex:0 0 auto;color:var(--text-tertiary);transition:.2s}.dir-row:hover .dir-folder-icon{color:var(--brand-purple);transform:translateY(-1px)}</style>', 1)
    extra.write_text(re.sub(r'[ \t]+\n', '\n', text))
    print(f"Built {len(CHAPTERS)} SE322 mindmaps and exams")
    from fix_mindmap_sidebar_state import apply_course
    apply_course("se322", BASE)
    from fix_academic_sidebar_links import fix_page
    for page in [core.MAPS / "index.html", core.EXAMS / "index.html", summary_dir / "index.html", *core.MAPS.glob("*/index.html"), *core.EXAMS.glob("*/index.html")]:
        fix_page(page)

if __name__ == "__main__": main()
