#!/usr/bin/env bash
# Run this whenever you add or remove pages from a course.
# Usage: bash scripts/generate-manifest.sh

DOCS="$(cd "$(dirname "$0")/.." && pwd)/docs/academics"
OUT="$(cd "$(dirname "$0")/.." && pwd)/docs/javascripts/course-manifest.js"

echo "// Auto-generated by scripts/generate-manifest.sh — do not edit by hand." > "$OUT"
echo "// Run that script whenever you add or remove pages from a course." >> "$OUT"
echo "var COURSE_MANIFEST = {" >> "$OUT"

# NF>=5 = actual content pages only (excludes course home + section index pages).
# Path structure: subject/course/section/page/index.html → 5 parts minimum.
find "$DOCS" -name "index.html" \
  | sed "s|$DOCS/||" \
  | awk -F'/' 'NF>=5 {print $2}' \
  | sort | uniq -c \
  | sort -k2 \
  | awk '{printf "  \"%-12s %s,\n", $2"\":", $1}' >> "$OUT"

echo "};" >> "$OUT"

echo "✓ course-manifest.js updated:"
grep -v "^//" "$OUT"
